### ISSUE TITLE
Different slideshow presentation option

### ISSUE THREAD

**Issue by mkpelletier** [gjb2048/moodle-theme_essential#103]
I think a worthwhile enhancement to the slider would be the option to allow the user to select whether the slideshow:
1. slides (vertical/horizontal)
2. fades/crossfade
3. kenburns
4. slices

Thoughts?  I would be happy to do this... when I have some spare time (whatever that is).

**Comment by richardschwarz** [comment]
Any thoughts on looking at porting the UIKit slideshow across? It does actually look awesome. I love the slideshow that you've put together... and am more than happy with it... but am willing to play with porting UIKit.

**Comment by gjb2048** [comment]
Thoughts:

1. Can't be bothered unless paid to implement / review / test.
2. Should be in the child theme to avoid 'complaints'.
3. As with '2', Essential is already complex and should not be made any more complex to a greater extent.

**Comment by richardschwarz** [comment]
Fair call. I agree.Child theme idea is good... hadn't even thought that far.

On Sat, Jun 13, 2015 at 11:34 PM, Gareth J Barnard <notifications@github.com
