### ISSUE TITLE
Rework branches - docs

### ISSUE THREAD

**Issue by DBezemer** [gjb2048/moodle-theme_essential#12]
master branch - bleeding edge development
MOODLE_25 - supported but semi-abandoned Moodle 2.5 version
MOODLE_26 - stable branch for Moodle 2.6 and Moodle 2.7
MOODLE_27 - stable branch for Moodle 2.7

Custom branches can be created for major rewrites/reworks. For a release please follow these steps:
- bump version number in version.php (in master)
- sync to branch from master
- update README.txt with new version + changelog
- tag release with version number + 1 (github tag)
- release on moodle.org

any further suggestions / improvements are welcome!

**Comment by gjb2048** [comment]
Info out of date.  Only me working things.  Closing.
