### ISSUE TITLE
User picture error

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_essential#179]
Marcelo Schmitt has commented on a plugin you're contributing to :

Someusers got the following error. I could not identify exactly what provokes.

[19-Aug-2014 14:15:34 America/Sao_Paulo] Default exception handler: Erro de
codificação detectado e deve ser corrigido por um programador: PHP catchable
fatal error Debug: Argument 1 passed to user_picture::__construct() must be an
instance of stdClass, boolean given, called in
[dirroot]/theme/essential/renderers/core_renderer.php on line 343 and defined
Error code: codingerror
* line 393 of /lib/setuplib.php: coding_exception thrown
* line 183 of /lib/outputcomponents.php: call to default_error_handler()
* line 343 of /theme/essential/renderers/core_renderer.php: call to
user_picture->__construct()
* line 153 of /theme/essential/layout/includes/header.php: call to
theme_essential_core_renderer->custom_menu_messages()
* line 27 of /theme/essential/layout/frontpage.php: call to require_once()
* line 877 of /lib/outputrenderers.php: call to include()
* line 807 of /lib/outputrenderers.php: call to
core_renderer->render_page_layout()
* line 101 of /index.php: call to core_renderer->header()

**Comment by mkpelletier** [comment]
Hello all,
I think we have a regression on this in Essential 2.7.9.4.3 on Moodle 2.7.3:
Debug info: Argument 1 passed to user_picture::__construct() must be an instance of stdClass, boolean given, called in [dirroot]/theme/essential/renderers/core_renderer.php on line 394 and defined
Error code: codingerror
Stack trace:
	•	line 393 of /lib/setuplib.php: coding_exception thrown
	•	line 183 of /lib/outputcomponents.php: call to default_error_handler()
	•	line 394 of /theme/essential/renderers/core_renderer.php: call to user_picture->__construct()
	•	line 139 of /theme/essential/layout/includes/header.php: call to theme_essential_core_renderer->custom_menu_messages()
	•	line 27 of /theme/essential/layout/frontpage.php: call to require_once()
	•	line 877 of /lib/outputrenderers.php: call to include()
	•	line 807 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
	•	line 101 of /index.php: call to core_renderer->header()

**Comment by whymiss** [comment]
Hi,
We are on Essential 2.7.7 Build(2014090303) and Moodle 2.7.2+ and this is a problem for us too even though this bug was fixed in Essential 2.7.7.

**Comment by gjb2048** [comment]
I don't know why https://github.com/gjb2048/moodle-theme_essential/commit/e21671df9327437b2daf668b1670da7d9b3c1a91 has disappeared from 2.7.9.4.3

**Comment by gjb2048** [comment]
Protection code still there: latest; https://github.com/gjb2048/moodle-theme_essential/blob/MOODLE_27/renderers/core_renderer.php#L466-L469

But not in:

2.7.9.4.3: https://github.com/gjb2048/moodle-theme_essential/blob/V2.7.9.4.3/renderers/core_renderer.php#L394

As fixed in #422.

**Comment by gjb2048** [comment]
Broken in #225 ??? log says something different: https://github.com/gjb2048/moodle-theme_essential/commit/b144f9d7d974268c7fca7f064da60e741eb4bb47#diff-492783807c33850a258efa189c59b5b2
