### ISSUE TITLE
Update to Bootstrap 3

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_essential#24]
Issue for the milestone

**Comment by jk3us** [comment]
Is this still on the table?  BS3 has been released for a while now.

**Comment by gjb2048** [comment]
Yes it is.

But before it happens, the M2.9 version needs to happen.  Before that the bugs in M2.8 need to happen.  Before that I'm involved here: https://moodle.org/mod/forum/discuss.php?d=313548 and here: https://tracker.moodle.org/browse/MDL-50241 and gaining skills required here: https://moodle.org/mod/forum/discuss.php?d=313747.  And need to work out how to migrate BS3 to Essential's unique optimised serving for both LTR and RTL that benefit all users regardless of device.

**Comment by gjb2048** [comment]
Decided to follow what core does with Bootstrap support.
