### ISSUE TITLE
Conflict with Turnitin plugin's navbar

### ISSUE THREAD

**Issue by akababs** [gjb2048/moodle-theme_essential#289]
Turnitin's Moodle Direct 2 (turnitintooltwo) use <div class="top navbar"> for a set of controls displayed in the center of the main content area.  When a course uses the Essential theme, the Turnitin navbar, Essential appears to insert an additional class "affix" causing the Turnitin navbar to be positioned at the top of the page on top of Essential's navbar.  

Screenshots of Turnitin page with Essential and Clean themes.
![tii-navbar-essential-theme](https://cloud.githubusercontent.com/assets/5932708/4376986/983e26d0-434a-11e4-9c39-9675b12b644a.png)
![tii-navbar-clean-theme](https://cloud.githubusercontent.com/assets/5932708/4376989/9c9f23fa-434a-11e4-99df-6ddbf62c29ab.png)

Moodle 2.6.5 (Build: 20140908)
Turnitin Direct 2 (2014012407)

Here's the contents of our  version.php

<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see http://www.gnu.org/licenses/.

/**
- This is built using the bootstrapbase template to allow for new theme's using
- Moodle's new Bootstrap theme engine
  *
- @package     theme_essential
- @copyright   2013 Julian Ridden
- @copyright   2014 Gareth J Barnard, David Bezemer
- @license     http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
  */

defined('MOODLE_INTERNAL') || die;

$plugin->version = 2014090302; // YYYYMMDDVV.
$plugin->maturity = MATURITY_STABLE; // this version's maturity level.
$plugin->release = '2.6.10 (Build: 2014090302)';
$plugin->requires = 2013111800; // Requires Moodle 2.6
$plugin->component = 'theme_essential';
$plugin->dependencies = array();

**Comment by harry-1** [comment]
Dear Barbara,

**Thank you very much for this solution.** I've just tried it on our sandpit and it works perfectly.

I really appreciate you letting us know since we won't be able to update to 2.7 soon.

Thanks again,
Harry
