### ISSUE TITLE
Group editing icons do not update on click to reflect new group status

### ISSUE THREAD

**Issue by tonyjbutler** [gjb2048/moodle-theme_essential#320]
Using Essential 2.7.7 with Moodle 2.7.2.
![image](https://cloud.githubusercontent.com/assets/1395170/4541379/2974b39e-4e13-11e4-9b8c-8b4cbbe30582.png)
The group editing icon should update when clicked, reflecting the new group status.

Looking at the code, the image added by course_get_cm_edit_actions() in course/lib.php (hidden by the Essential theme) does update, but the class added by Essential to display the equivalent FontAwesome icon in its place does not.

In replace_moodle_icon() (in theme/essential/renderers/core_renderer.php) all group statuses are mapped against the same FontAwesome icon, but even mapping them against different icons only results in the class being updated when the page is reloaded.

Thanks.

**Comment by gjb2048** [comment]
Fixed in #535

**Comment by gjb2048** [comment]
Mistakenly closed this.  Still an issue.

**Comment by gjb2048** [comment]
Oooo, there is a parent class that is changed in M3.1 (test 3.0) e.g. editing_groupsvisible so there is a chance of a fix!

**Comment by gjb2048** [comment]
Classes go back as far as M2.9 version so a possible!

**Comment by nadavkav** [comment]
Bless you! just now got a user complaining about this, and was so happy to find out it was not something I broke on a child theme :smile:
