### ISSUE TITLE
Footer doesn't stay at bottom

### ISSUE THREAD

**Issue by emanuelis** [gjb2048/moodle-theme_essential#351]
Hi, if there are not much content on a page, the footer doesn't stay at bottom

![bad](https://cloud.githubusercontent.com/assets/329596/4814643/4062da1c-5ed1-11e4-9a30-0fdc9246f572.png)

**Comment by saeed3234** [comment]
I don't know if that is the best solution but I stick the footer to the bottom as follows:
For the login page, I wrap the php tag of

<?php require_once(dirname(__FILE__) . '/includes/footer.php'); ?>
inside divs of class="navbar-fixed-bottom"

**Comment by saeed3234** [comment]
like this

![sticky footer](https://cloud.githubusercontent.com/assets/6469688/6103633/a6466df4-b05b-11e4-8ee6-13021761aada.jpg)

**Comment by lazydaisy** [comment]
If there is no content you could add CSS to that effect that keeps the page open just for the view. It can only happen in My Home page (mydashboard). So how about...
<pre>
body.pagelayut-mydashboard {
    height: 100%;
    min-height: 700px;
}
</pre>

**Comment by richardschwarz** [comment]
In the layout files, I added a <div id="pageWrapper"> around most of the page (including the footer), and then targeted a few things in css. It's based on: http://cssreset.com/how-to-keep-footer-at-bottom-of-page-with-css/ and only uses css. Of course... you do need to set a height for the footer (I'm happy to do so, but others may not be) and the padding-bottom in the #page needs to be at least the height of the footer.

Making a pull (new to github/git... so not sure of the terminology yet) request now.  
CSS below:

html, body {
height:100%;
}

#pageWrapper {
position:relative;
min-height:100%;
}

#page {
padding-bottom: 300px;
}

#page-footer {
position:absolute;
bottom:0;
height:250px;
min-height:200px;
}

**Comment by gjb2048** [comment]
Adding class 'navbar-fixed-bottom' sort of works but then overlays content if there is sufficient content.

**Comment by gjb2048** [comment]
Possibly: https://css-tricks.com/snippets/css/sticky-footer/ - but height of footer needs to be known.

**Comment by richardschwarz** [comment]
My fix causes some issues in the administration section (back-end only). Thinking about only putting the divs in renderers that are 'likely' to be short... eg. login page. I'll give feedback when I've seen what it does.

**Comment by EricPoitras** [comment]
Any updates on this thread? I have the same issue on my courses and login page, where the main content is much shorter. However, I have tried copy/pasting your fix richard in the CSS textbox in the General options, and still having some issues, even on the home page where the bar appears in the middle above all the page content. 

Hoping you've made some progress and would like to elaborate further.

**Comment by gjb2048** [comment]
No progress at this time.

**Comment by gjb2048** [comment]
Slight fix in: https://github.com/gjb2048/moodle-theme_essential/commit/3b8cd5408c09ab86ea2470993a763a7b98cbfdf4
