### ISSUE TITLE
Category count on front page

### ISSUE THREAD

**Issue by gibbysimswilson** [gjb2048/moodle-theme_essential#421]
When I select display categories I see this, I assume the (0) should be the total number of courses in the category, am I wrong? 
Why does it say (0) when I have 6 courses?
Have I done something wrong?
Thanks
![zero in cat](https://cloud.githubusercontent.com/assets/10324307/5591540/470385a8-91a1-11e4-8ef3-f8b97f6fccd0.jpg)

**Comment by gjb2048** [comment]
That's the number of courses in that category.  The courses will be in another category.  Check that the category is different to the category the courses are in.

**Comment by gjb2048** [comment]
Tested on 2.8.1.1 and the code is operating correctly to display the number of courses in the category shown.
