### ISSUE TITLE
Users do not have edit profile in preferences menu

### ISSUE THREAD

**Issue by mkpelletier** [gjb2048/moodle-theme_essential#424]
Can anyone confirm this on your own installations.  Our installation has some arcane role definitions, so the problem may be there.  I have checked the role capabilities for specific users to ensure they have editownprofile,  However, even if a user has explicit permission allow, the link does not show up in the user preferences menu.

**Comment by gjb2048** [comment]
Hi Mathieu,

I doubt anybody else but me will read this, so I suggest posting on the theme's forum.

Cheers,

Gareth
