### ISSUE TITLE
Copyright date localization

### ISSUE THREAD

**Issue by h-taleghani** [gjb2048/moodle-theme_essential#425]
As of introducing calendar systems, it's better to use userdate() instead of php date()
in [footer.php](https://github.com/gjb2048/moodle-theme_essential/blob/master/layout/includes/footer.php#L53):
date("Y") -> userdate(time(), '%Y')

**Comment by gjb2048** [comment]
What version of Essential please?

**Comment by h-taleghani** [comment]
I'm using 2.7.9.2 but I think this is common in all versions.
In hijri calendar we are in 1436 and in jalali calendar we are in 1393. But date("Y") shows 2015 (which is  only correct for gregorian calendar).

**Comment by gjb2048** [comment]
Clearly I am unable to test this, so I need justifiable qualified sources that clearly demonstrate this sort of change is credible.

**Comment by h-taleghani** [comment]
Why you are unable to test this? You can install calendar types from [moodle plugins directory](https://moodle.org/plugins/browse.php?list=category&id=51) and check whether this code works or not. 
And If you are not sure which year is this on that calendar system, you can google it.
So, where is the problem?

**Comment by gjb2048** [comment]
I did not know about the different calendar types on: https://moodle.org/plugins/browse.php?list=category&id=51.

**Comment by h-taleghani** [comment]
Jalali calendar is official calendar in Iran (and Afghanistan) and it's meaningless to say 2015.
I don't know these will help or not
http://en.wikipedia.org/wiki/Islamic_calendar
http://en.wikipedia.org/wiki/Jalali_calendar
http://en.wikipedia.org/wiki/Solar_Hijri_calendar

**Comment by gjb2048** [comment]
I see that with the Jalali calendar it would be meaningless to say 2015 - well duh!

I'll fix this when I can find a free hour to implement and test in M2.7 / M2.8 branches.

**Comment by h-taleghani** [comment]
Thanks!
