### ISSUE TITLE
Front page content area set to "Show before login only" still paritally displays

### ISSUE THREAD

**Issue by cwaffles** [gjb2048/moodle-theme_essential#429]
Hi,

I'm running Essential version 2.7.9.4.3 on Moodle 2.7.1. I noticed under the "Enable front page content area" option, when you set it to "Show before login only", a border appears when students are logged in:
http://imgur.com/FI7pSQY
The box is missing when set to "Never show":
http://imgur.com/8frO49O

Hopefully you can reproduce this issue.

**Comment by gjb2048** [comment]
Thanks for the report, I will look at it when I get time, probably the weekend.
