### ISSUE TITLE
Header above Custom Menu

### ISSUE THREAD

**Issue by JamieHibbard** [gjb2048/moodle-theme_essential#431]
Love the theme, how can I move the header section above the custom menu as you have it in your video? or is this a bug

Live site http://moodle.langstone-jun.portsmouth.sch.uk/

Jamie

**Comment by mkpelletier** [comment]
Hello Jamie,

It’s great isn’t it?  I think you want Site Administration > Appearance > Themes > Essential > General > “Use the old nabber position”.

In the future it is usually best to ask these questions on the Theme forum here: https://moodle.org/plugins/view.php?plugin=theme_essential <https://moodle.org/plugins/view.php?plugin=theme_essential>

Best Regards,

Mathieu

**Comment by JamieHibbard** [comment]
Thanks you, can I suggest a change then. Add in the description "Enable this option to use the old navbar position. Placing the header on top"

**Comment by mkpelletier** [comment]
I have added a pull-request for this.  We’ll have to wait for Gareth to approve it.
