### ISSUE TITLE
Add a 'This Course' dropdown menu (Code attached)

### ISSUE THREAD

**Issue by ActionJONA** [gjb2048/moodle-theme_essential#433]
I've added a 'This Course' dropdown menu to our version of the theme.
This has been poached from the great BCU theme - https://moodle.org/plugins/view.php?plugin=theme_bcu

I was just hoping to put it into consideration for a future update, however without asking you to do too much work! :)

(I think this is all that needs to be added - Except for .less and the extra .css files... You'll see what I mean)

File | Code
------------ | -------------
header.php | https://github.com/ActionJONA/moodle-theme_essential/commit/b88378a8556c24376166e553f2fd0d34d4ead720
lib.php | https://github.com/ActionJONA/moodle-theme_essential/commit/074fbcc6e34f94099eabd4285d2725254ffae53c
core_renderer.php | https://github.com/ActionJONA/moodle-theme_essential/commit/911dc8d01ba362f9c59ef9707d658f7c7e796fde
essential.css | https://github.com/ActionJONA/moodle-theme_essential/commit/ad8b876169aa50e0e7a17c899ea5823e524ccdb8

Apologies if anything doesn't make sense, this is my first time using GitHub when it comes to coding.
[I'm very aware I haven't added everything in relating to other .css / .less, etc files, - this was just enough to get it working for me.]

Hope this helps if it's something you'd consider adding!

Many thanks for your continued efforts in maintaining such a great theme!

**Comment by gjb2048** [comment]
Thanks, do you have the LESS rather than CSS changes?

In my opinion, the BCU theme is not as good as it could be having being created using an older theme methodology.  It does have flaws.  But I will when I get a moment, have a look at this component and consider its suitability for Essential.

**Comment by gjb2048** [comment]
For instance, https://github.com/ActionJONA/moodle-theme_essential/commit/074fbcc6e34f94099eabd4285d2725254ffae53c could be in core_renderer.php and refactored to use existing member variables.

**Comment by ActionJONA** [comment]
Well now you're just going above my head! :) 
Unfortunately I'm not that amazing with coding, I know just enough to get by.

I've never even looked at any LESS so I've only managed the CSS. Apologies.

**Comment by gjb2048** [comment]
Ok, no problem, ok, to put it another way, how did you create: https://github.com/ActionJONA/moodle-theme_essential/commit/ad8b876169aa50e0e7a17c899ea5823e524ccdb8 ?

**Comment by ActionJONA** [comment]
... This may not be the answer you're looking for (as I'm not sure I fully understand what you're asking), but I simply added those changes (using dreamweaver) into the actual essential.css file in my theme folder, and then copied and pasted my changes into a forked version of the theme on here....

Hopefully this answers your question...
[As I said - 'just enough to get by']

:)

**Comment by gjb2048** [comment]
Thanks for the answers :) - to be honest, I'm now a tad scared! ;)

I'll figure out the LESS.

**Comment by ActionJONA** [comment]
Scared? Don't be scared! just because I've been of no help.... haha

![screen shot 2015-01-15 at 15 43 45](https://cloud.githubusercontent.com/assets/10047439/5760549/68ca4e38-9ccd-11e4-9abf-ddd9b47e96ed.png)

Look! it does work! See....

**Comment by gjb2048** [comment]
Oh, I'm not scared of you.  It's just Dreamweaver and hacking with it!

**Comment by ActionJONA** [comment]
Ahh no, that's the fun part! ;)

Hopefully it won't be too much work! 
(Sorry for giving you yet another thing)

**Comment by gjb2048** [comment]
No problem, it will get done when it gets done.

**Comment by gjb2048** [comment]
Thinking about it, would need to be optional and only shown on the 'course' layout.

**Comment by ActionJONA** [comment]
This is true about being optional.... However it does already only show on course pages.

**Comment by gjb2048** [comment]
Ok, looking at: https://github.com/ActionJONA/moodle-theme_essential/commit/911dc8d01ba362f9c59ef9707d658f7c7e796fde - the guard code could use '$this->page->pagelayout' instead.  Plus, there are some strings hard coded in English, so more work to change them.

**Comment by gjb2048** [comment]
Hi ActionJONA,

I have decided to implement the enhancement as you can see in: https://github.com/gjb2048/moodle-theme_essential/commit/ba6fb02f0f2a8877a99e4d47eb90802137d2a97b - because:

1. You supplied the code, which then just needed a few tweaks.
2. It is in my opinion a good thing for Essential.
3. You asked nicely and treated me like a person rather than a dogsbody developer.

Kind regards,

Gareth

**Comment by ActionJONA** [comment]
Hi Gareth, 

You are a very good man! Swift work sir.

Thank you very much for this.
