### ISSUE TITLE
Bug with rear submit area - fitem_actionbuttons fitem_fsubmit

### ISSUE THREAD

**Issue by mjugariu** [gjb2048/moodle-theme_essential#435]
The wrapper around the "save changes" appears everywhere (when it shouldn't) and you can't get rid of it. Using Moodle 2.6.1 with the latest Essential theme for 2.6

Screenshot: https://www.dropbox.com/s/yijur4134y376dw/Untitled.png?dl=0

Thanks,
Marius

**Comment by gjb2048** [comment]
Ok,

Fair point, but version 2.6.11 was the 'last' for M2.6 as stated on: https://moodle.org/plugins/view.php?plugin=theme_essential - I'm sorry, but I cannot go on supporting old versions.  So have to draw the line somewhere, thus follow Moodle's support policy.  Currently for M2.6 that is security updates only.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Ok, I'd thought I had already fixed this, and indeed I have in the M2.7 version: https://github.com/gjb2048/moodle-theme_essential/issues/372 - please upgrade.

**Comment by mjugariu** [comment]
Thanks and sorry, looked around and didn't realise it was duplicate. I can't upgrade to M2.7 just now for a number of reasons. Will try and see if I can get rid of it as it is in 2.6

Cheers,

M
