### ISSUE TITLE
Add a Page Progress / Loading bar

### ISSUE THREAD

**Issue by ActionJONA** [gjb2048/moodle-theme_essential#437]
Hi Gareth, 
I'll try not to make this a regular occurrence... Promise.

I've added a loading bar to the top of my version of the theme and just thought i'd throw it your way for consideration. If you think it doesn't fit - no problems, If you think it does - I can send you over the code that got it working nicely for me!

Here's mine working on a short and long page load:
![loading-bar](https://cloud.githubusercontent.com/assets/10047439/5816645/6497a812-a09a-11e4-9428-54377528b7ce.gif)

:)

**Comment by gjb2048** [comment]
Hi ActionJONA,

I saw this when Julian first added it to Elegance and enquired at the time to see it was linked to the page loading process, which it was not, just a meaningless animation, so sorry, but thought it was 'tacky'.  Therefore not something I subscribe to.

Thanks anyway,

Gareth
