### ISSUE TITLE
Messages Screen when on mobile ( - 767px ) - background not filling area (region-main)

### ISSUE THREAD

**Issue by ActionJONA** [gjb2048/moodle-theme_essential#441]
Hi Gareth, 

I've been playing with the look of the messages screen and came across a bug when on smaller screen sizes. The background doesn't fill behind the content:
![screen shot 2015-02-04 at 10 10 32](https://cloud.githubusercontent.com/assets/10047439/6038575/22c1dd82-ac56-11e4-99de-8f4ce1c519c7.png)

Should look like:
![screen shot 2015-02-04 at 10 10 51](https://cloud.githubusercontent.com/assets/10047439/6038585/364b32a4-ac56-11e4-811f-e37b0731ded3.png)

I've found that this is the 'float: none' as here:

@media (max-width: 767px)
.row-fluid .span8.pull-right, .row-fluid .span9.pull-right {
 float: none; 
}

Fixed when:
@media (max-width: 767px)
.row-fluid .span8.pull-right, .row-fluid .span9.pull-right {
/* float: none; */
}

(I know this isn't a proper fix...)
Also though to I've found the message box then overflows slightly...

(My temp fix):
.message .messagearea .messagesend .messagesendbox {
width: 98%;
}

Rather than:
.message .messagearea .messagesend .messagesendbox {
width: 100%;
}

Hopefully this makes it easy to track down and fix.
(Ignore the styling of the messages, I know this isn't the standard styling - I was just playing and preferred this mobile-like look for messaging).

**Comment by ActionJONA** [comment]
Just some more pics to help track down the lines:...
 
![screen shot 2015-02-04 at 09 56 39](https://cloud.githubusercontent.com/assets/10047439/6038501/86a5dd7c-ac55-11e4-8322-118fcdd9facf.png)

![screen shot 2015-02-04 at 09 56 14](https://cloud.githubusercontent.com/assets/10047439/6038502/89f2d8fe-ac55-11e4-9846-b8a64b9a02c5.png)

**Comment by gjb2048** [comment]
I've seen this before in my other themes.  Need to look up what the solution was there.

**Comment by gjb2048** [comment]
Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/261b2888b4b12d5bb9fc130827f830e54823c2c4

**Comment by ActionJONA** [comment]
Hi Gareth, 
Just noticed that this Fix didn't quite work...
It's now overflowing into the first block below and getting confused.

I've had a look and I believe that the 'float' code - left vs right - is the wrong way round.
https://github.com/gjb2048/moodle-theme_essential/commit/261b2888b4b12d5bb9fc130827f830e54823c2c4#diff-63c3dec7a5e8f15a6ea6db6998fdccf8R106

That highlighted one should be:
+    #page-message-index {
+        #region-main {
+            float: right;

Not
+    #page-message-index {
+        #region-main {
+            float: left;

This (I'm guessing) will then swap them around in the Essential.css & Essential-rtl.css etc.

**Comment by ActionJONA** [comment]
... As you can probably tell I'm on a re-branding mission today!
Apologies for re-opening something.

:)

**Comment by gjb2048** [comment]
Screen shot evidence please.  Seemed ok in testing.

**Comment by gjb2048** [comment]
If its a fix of a closed fix then raise another issue.
