### ISSUE TITLE
slide show height is fixed.

### ISSUE THREAD

**Issue by kordan** [gjb2048/moodle-theme_essential#442]
I wonder why the height of the slide show is fixed.
I know that essential is a responsive theme but I don't think this implies the height of the slide show to be static.
With small icons the look of the theme is really bad.

**Comment by gjb2048** [comment]
Thanks for the observations.

What small icons?

With the slide show, please if you can do any better then kindly submit changes as a patch for review.

**Comment by kordan** [comment]
In the frame of the development of the patch to use a custom slide show heigh, I found that [[setting:themeiconcolor]] is not replaced into essential/style/essential.css
May I ask you to confirm my suspect?

**Comment by gjb2048** [comment]
You are wrong, that is now in settings.css.

**Comment by kordan** [comment]
ok, you are right!
One more question: are sure about subfolder essential inside theme folder esential?

**Comment by kordan** [comment]
I have a working draft.
Where can I post it?

**Comment by gjb2048** [comment]
With 'essentials' in 'essential' - please read the readme!

With the working draft please submit a pull request from your branch on GitHub.

**Comment by gjb2048** [comment]
Deferred to pull request.
