### ISSUE TITLE
Font specific to an RTL language in a multilingual Moodle website

### ISSUE THREAD

**Issue by saeed3234** [gjb2048/moodle-theme_essential#443]
Hi

A really good enhancement in future releases, in my opinion, would be to add the capability of letting those who run a multilingual Moodle website, especially those with an RTL language among others to choose a specific font for a particular language. In my case, font Tahoma is the best for the RTL language but I prefer Verdana for the English language. I think most Moodle administrators dealing with an RTL language would appreciate such an improvement.

Regards

**Comment by gjb2048** [comment]
Good idea, do you have the patch for this please?

**Comment by saeed3234** [comment]
Not yet really. Just mentioned it here to see if any one is interested to help. I will add the code, in case I come up with any.
