### ISSUE TITLE
Messages Page CSS update

### ISSUE THREAD

**Issue by ActionJONA** [gjb2048/moodle-theme_essential#446]
Hi Gareth

Regarding: https://moodle.org/mod/forum/discuss.php?d=279942&parent=1203767

I've added all the bits and bobs for an updated look on the messages screen, along with colour options in settings.
(This time I've also changed the relevant .less file = message.less) - (I watched your ShoeHorn - Grunt - Screen cast and understand .less a little more now).

:)

Here's my changes = https://github.com/ActionJONA/moodle-theme_essential/compare/Message-Bubble-Colours (Slowly getting to grips with this whole Github thing too)

Hopefully this covers everything you need and that you'll consider it for a coming update.

**Comment by gjb2048** [comment]
Thanks Daniele, no time ATM but will look when I get a moment.

**Comment by gjb2048** [comment]
essential-settings.css is a generated file so this: https://github.com/ActionJONA/moodle-theme_essential/compare/Message-Bubble-Colours#diff-6b4e6f5edddd26a017da528ac86daa04R930 does need to be in the LESS.

**Comment by gjb2048** [comment]
Almost certainly a new LESS file here: https://github.com/gjb2048/moodle-theme_essential/tree/master/less/essential/settings and added here: https://github.com/gjb2048/moodle-theme_essential/blob/master/less/essential-settings.less with the tilda wrapper, e.g: https://github.com/gjb2048/moodle-theme_essential/blob/master/less/essential/settings/categories.less#L19

**Comment by ActionJONA** [comment]
Daniele?
Wrong person.

However, more like this? - https://github.com/ActionJONA/moodle-theme_essential/compare/Message-Bubble-Colours#diff-1e68e82f10698a3c0d909b3fc2f2b14cR22

**Comment by gjb2048** [comment]
Yes.

**Comment by ActionJONA** [comment]
...Just realised, I deleted the repo that I'm linking to above...
I've just brought it back! :)

https://github.com/gjb2048/moodle-theme_essential/compare/master...ActionJONA:Message-Bubbles-V2

**Comment by gjb2048** [comment]
Thanks for the enhancement branch Jona.  It still needs work to tidy things up.

With the continued lack of funding, I'm considering charging for code integration and reviews.  As this is an enhancement for which I would need to check, test, release and maintain.

Kind regards,

Gareth

**Comment by ActionJONA** [comment]
Hi Gareth, I completely understand.
As this one is just a small styling enhancement, in which i've already added to my version, I wouldn't be able to fund this unfortunately.

(I just thought it a nice potential enhancement for others)

However I may well have some proper work coming your way in the near future.
I shall keep you posted.

All the best.

**Comment by gjb2048** [comment]
Thanks for letting me know Jona.
