### ISSUE TITLE
Allow further customisation of category icons

### ISSUE THREAD

**Issue by mkpelletier** [gjb2048/moodle-theme_essential#448]
Hello Gareth,

What do you think about allowing users to select their own category icons in lieu of font-awesome?  I have begun to add this feature to my fork, but I wanted to get your take on it.

Our use case is that we are running different programmes, and in the marketing trademark pictures have been used.  Allowing users to upload their own custom icons helps with brand recognition.

Thoughts?

**Comment by gjb2048** [comment]
Fine idea.

I've thought about making this available at some point too: http://typicons.com/
