### ISSUE TITLE
Hidden categories not aligning correctly

### ISSUE THREAD

**Issue by ActionJONA** [gjb2048/moodle-theme_essential#451]
Hi Gareth, 

Not sure if this is an Essential or a Grid Format issue, (I think it's an Essential one), however when inside a topic on a course, if the next or previous section / topic is hidden, it doesn't align correctly within the box. (See images for example).

Image 1 - Next section is hidden
![screen shot 2015-02-16 at 09 13 46](https://cloud.githubusercontent.com/assets/10047439/6209370/3001e74c-b5bd-11e4-8bbc-406afee9209d.png)
Image 2 - Neither section is hidden
![screen shot 2015-02-16 at 09 13 58](https://cloud.githubusercontent.com/assets/10047439/6209371/320812d2-b5bd-11e4-8bc3-b5932913f449.png)

This was happening in Moodle 2.7 on the latest of both Grid and Essential, however after updating to Moodle 2.8.3+, and each of the plugins to their latest (see below), it still happens.
Not sure if this is intentional, but it certainly looks strange.

format_grid
Additional	2014122100	2.8.2

theme_essential
Additional	2015021100	2.8.1.1-RC3 (Build: 2015021100)

**Comment by gjb2048** [comment]
Ok,

1. What happens in the Clean theme?
2. What do you think the fix is?

**Comment by ActionJONA** [comment]
It is fine in the Clean theme, (which I should have realised before as essential styles the next and previous options), and I'm not sure how to fix this... 
I have an idea in mind of how it could look, and I know roughly where in the code I might be able to make it work, however I'm still not that fantastic with writing new code.

Here is how I would say it could look:
![screen shot 2015-02-16 at 09 53 08](https://cloud.githubusercontent.com/assets/10047439/6209869/ff0c9d6c-b5c1-11e4-9297-e55cc14047b0.png)
(Stealing the idea from inside the 'My Courses' drop-down with hidden courses.

**Comment by gjb2048** [comment]
Ta,

I'll have time on Saturday to look at it.

**Comment by gjb2048** [comment]
Hi Jona,

I had a spare moment, so fixed it.

I had a look at Brockenhurst College's VLE and its starting to look good.  As Essential depends on donations would they consider supporting the theme?

Kind regards,

Gareth
