### ISSUE TITLE
Messages Screen when on mobile still not quite correct - Ref #441

### ISSUE THREAD

**Issue by ActionJONA** [gjb2048/moodle-theme_essential#452]
See Issue https://github.com/gjb2048/moodle-theme_essential/issues/441 for reference...

Screenshot evidence as requested:

@media (min-width: 768px) and (max-width: 979px)
![screen shot 2015-02-16 at 13 13 23](https://cloud.githubusercontent.com/assets/10047439/6212501/f394e400-b5dd-11e4-986d-6f5f7d0fccaa.png)

@media (max-width: 767px)
![screen shot 2015-02-16 at 13 13 44](https://cloud.githubusercontent.com/assets/10047439/6212515/07bc8ea6-b5de-11e4-9fe3-078aa1c01c32.png)

**Comment by ActionJONA** [comment]
...Also, at full size the message nav dropdown overflows into the content area:
![screen shot 2015-02-16 at 13 18 48](https://cloud.githubusercontent.com/assets/10047439/6212552/86d58e72-b5de-11e4-8e5b-0d9ecc9fc9c1.png)

This seems to be fixed by adding ' width:100% ' to the .singleselect on that page.
![screen shot 2015-02-16 at 13 19 17](https://cloud.githubusercontent.com/assets/10047439/6212554/8f5713c2-b5de-11e4-97f6-e245e6895cd6.png)

**Comment by gjb2048** [comment]
Seems or does?

**Comment by ActionJONA** [comment]
Well, does....
![screen shot 2015-02-16 at 13 27 43](https://cloud.githubusercontent.com/assets/10047439/6212648/9f0d4a56-b5df-11e4-9066-8ea6ecd0d597.png)

**Comment by gjb2048** [comment]
Extremely busy with paid work ATM.  Will need to leave until Saturday.

**Comment by ActionJONA** [comment]
No problems, thanks very much for supporting this theme anyways! 
It is much appreciated!

**Comment by gjb2048** [comment]
Ok, watch: https://moodle.org/mod/forum/discuss.php?d=279485 - applies to Essential as well as Shoehorn.  Work out the correct changes to the LESS files in the right places.  Then submit a pull request.

**Comment by gjb2048** [comment]
Fixed do to potential paid work.
