### ISSUE TITLE
Turn on edit button not theming 

### ISSUE THREAD

**Issue by danbuntu** [gjb2048/moodle-theme_essential#453]
I'm upgrading to essential tot he latest version for moodle 2.7

I've set my theme colours but for some reason when in a course the turn editing on /off button is white instead of picking up the theme colours or showing as red/ green.

I've cleared all my caches

Please see the attached image
![moodle-button](https://cloud.githubusercontent.com/assets/688626/6247302/c290a6e4-b76a-11e4-8559-beb36a53b3c3.PNG)
 

any ideas on what's happening here please please?

**Comment by gjb2048** [comment]
What exact version of Essential and Moodle please?

How did you change the theme colours?  What settings did you set?

I do not see any red or green colours in the screen shot, only a variation of purple.

**Comment by gjb2048** [comment]
Ok, double checked and code has the background as red or green.  There is no code to change this unless you have changed the LESS.

**Comment by danbuntu** [comment]
it's moodle 2.7.5+
and essential 2014111007

I set the colours via the back end 

I was expecting to see red and green as that what my older verison of essential shows and I noted that the buttons are using the boostrap btn-danger and btn-success

**Comment by gjb2048** [comment]
When you say 'back end' you mean 'not via the user interface'?

My version (2014111008) shows 'red' / 'green'.  And I've not changed that area.  And the buttons are 'btn-danger' and 'btn-success'

Any Custom CSS in the setting box for it?

**Comment by ActionJONA** [comment]
danbuntu, a real shot in the dark here, but do you have any plugin's installed that aren't from moodle.org?
Maybe even specifically - GradeTracker?
It's only because I had this same issue when I installed a recent version of Grade Tracker.

Just worth a mention!?

**Comment by danbuntu** [comment]
I do have grade tracker installed actually so a good shot in the dark!

**Comment by ActionJONA** [comment]
Ahhh, hopefully that's it then....

In which case, you need to comment out their button CSS.
Depending on the version, I had to do this (in the most recent version (7.4 I think), in:
moodle/ blocks/ bcgt/ styles.css
You're looking for line 2244 = /* line 10, bootstrap/_buttons.scss */

Comment out the whole: .btn part.
Lines = 2244 - 2332

Hopefully that should fix it.

**Comment by gjb2048** [comment]
Please could you upload the plugin here so I can check it.

**Comment by gjb2048** [comment]
Or is this it? -> https://github.com/jagobrown/bcgt

**Comment by gjb2048** [comment]
Also, this https://github.com/jagobrown/bcgt/blob/master/bclib.php#L2-L9 is in violation of the GPLv3 license.

**Comment by danbuntu** [comment]
I've been in contact with them today. I'll give them a ping now to let them know about this thread
