### ISSUE TITLE
Error in maintenance.php 

### ISSUE THREAD

**Issue by ppv1979** [gjb2048/moodle-theme_essential#456]
Moodle 2.7.5+ (Build: 20150205)
Essential 2.7.9.5 (Build: 2014111008) — latest version from Github (MOODLE_27 branch)

When trying to update plugins there is an error: 

Fatal error: Call to undefined method theme_essential_core_renderer_maintenance::get_csswww() in /var/www/edususu/main/theme/essential/layout/maintenance.php on line 45

**Comment by gjb2048** [comment]
Is this on a test server?

**Comment by gjb2048** [comment]
All code in the branches that has not been formally released on https://moodle.org/plugins/view.php?plugin=theme_essential is in development and subject to code faults as development progresses.
