### ISSUE TITLE
Header logo pushing social icons off header - smaller sized screens

### ISSUE THREAD

**Issue by ActionJONA** [gjb2048/moodle-theme_essential#458]
Hi Gareth, 

Apologies I haven't mentioned this one sooner, (especially as you've just done a new release today)
(I noticed whilst updating today that I'd fixed this one previously in my code and forgot to raise a new issue for it).

Anyway - 
`<div class="ecol8 pull-left">` pushes the social app icons off of the header (and partially under the navbar) when at smaller screen sizes (I tested down to 768px (wide) before it changes to mobile). - Screenshots at 768px wide.

![screen shot 2015-02-23 at 16 07 20](https://cloud.githubusercontent.com/assets/10047439/6331487/57a10b88-bb77-11e4-8338-1959323412aa.png)

If changed to: `<div class="ecol7 pull-left">` or even `<div class="ecol6 pull-left">` - this fixes it.

![screen shot 2015-02-23 at 16 08 21](https://cloud.githubusercontent.com/assets/10047439/6331508/7558cb84-bb77-11e4-998b-000d59c04602.png)
![screen shot 2015-02-23 at 16 08 04](https://cloud.githubusercontent.com/assets/10047439/6331504/704d91a6-bb77-11e4-8a02-8f7a356a8061.png)

See: https://github.com/ActionJONA/moodle-theme_essential/commit/9ea89f8fe24014a4a588045bae63b5512f83661f for my fix.

**Comment by gjb2048** [comment]
Hi Jona,

Thanks for the information.

With no donations coming in I have now reached the end of what I can do for a while and regrettably will need to take a break.

Gareth

**Comment by gjb2048** [comment]
If one day I get paid to to customise the theme for a client, then I'll try and put in any bug fixes that have arisen.  But currently the planet is gaining from all of my hard work and I'm not getting a penny in support to keep things going.  It does say in the Readme, that the theme 'relies' on donations, well, that's it, no donations, no theme.  Today's releases were just to clear the decks of what has built up.

**Comment by gjb2048** [comment]
Ok, well maybe not 'relies', but so many corporations and institutions are using it and have not bothered to support the theme with even a minimal donation.

**Comment by ActionJONA** [comment]
Hi Gareth, 
I completely understand.

I am in the process of seeing if there's any donation we can make to such a great Moodle Developer!

**Comment by gjb2048** [comment]
Hi Jona,

Thank you :).

There is a bug I need to fix this morning so will incorporate this fix as would be so silly not to.  I cannot let the other bug go out of professional pride.

Kind regards,

Gareth

**Comment by ActionJONA** [comment]
Please say that's #457!?   :P

**Comment by gjb2048** [comment]
No it is not :(

**Comment by ActionJONA** [comment]
...I know you don't want to hear this, (and yes I'll create a new one for this - I'm so sorry), but the #452 fix has made all dropdowns 100% wide as it / I wasn't specific enough. - Just trying to work out how to be more specific to the messages screen dropdown only and I'll add it to the tracker.

I feel bad for this one.... :(

**Comment by gjb2048** [comment]
I've had enough.

**Comment by gjb2048** [comment]
I will fix this and this alone when I sort the switching theme issue.

**Comment by ActionJONA** [comment]
No problems Gareth, I wasn't pushing for an instant fix at all! (I've already fixed it in my instance) It was more that it was an issue to report for others to benefit from.
Apologies for mentioning it here.

Hope you have a decent break!
