### ISSUE TITLE
Messages Screen - Ref #441 #452

### ISSUE THREAD

**Issue by ActionJONA** [gjb2048/moodle-theme_essential#459]
Just as a final push to fix the small bits in the messages screen:
Ref #441 & #452 

I believe that the 'float' code - left vs right - is the wrong way round.
https://github.com/gjb2048/moodle-theme_essential/commit/261b2888b4b12d5bb9fc130827f830e54823c2c4#diff-63c3dec7a5e8f15a6ea6db6998fdccf8R106

That highlighted one should be:

#page-message-index {
#region-main {
float: right;
Not

#page-message-index {
#region-main {
float: left;
_______________________

Also to fix the contacts dropdown: - the closing fix should be:
https://github.com/gjb2048/moodle-theme_essential/commit/e7719d9abe08eb1c48ee4f3320c6a21b122e0e47

.message .contactselector .singleselect {
width: 100%;
}

Not:
.singleselect {
    form, select {
        width: 100%;
    }
}

**Comment by ActionJONA** [comment]
I'm aware this one will get fixed when Gareth returns from a decent break! :)

**Comment by gjb2048** [comment]
Changing https://github.com/gjb2048/moodle-theme_essential/commit/261b2888b4b12d5bb9fc130827f830e54823c2c4#diff-63c3dec7a5e8f15a6ea6db6998fdccf8R106 to right makes 'didley squat' difference.

**Comment by ActionJONA** [comment]
Ahh really?
I can't currently test as to why, as my Dev server is down, however the reasoning was that when the messages screen is down between 768px and 979px, the blocks on the left were pushed to the right of the main content - also meaning their margins were all out and it was all a bit ugly. (As seen on the first screenshot #452).

When I'm back up and running, I shall try to sort the fix! :)

**Comment by gjb2048** [comment]
Cannot replicate that between 768 and 979px.

**Comment by ActionJONA** [comment]
Ahh ok, leave it with me, once I'm up and running again (hopefully by Monday as this weekend is apparently a no-go) I shall see what the problem is my end and report back.

**Comment by gjb2048** [comment]
Adjusted and closed.

**Comment by gjb2048** [comment]
To run you own local Moodle, see this: http://www.slideshare.net/gb2048/my-own-moodle and this: https://drive.google.com/folderview?id=0B17B0rYH2zERU21sQnVweUZCUFk&usp=sharing
