### ISSUE TITLE
Upgrade now site is blank

### ISSUE THREAD

**Issue by gibbysimswilson** [gjb2048/moodle-theme_essential#461]
Sorry for poor english

moodle 2.8.1
Just upgraded essential through moodle admin and now my site is completely blank

**Comment by gjb2048** [comment]
Please look at: https://moodle.org/mod/forum/discuss.php?d=282598 - and provide more information, thanks.

**Comment by gjb2048** [comment]
Is the site online?

**Comment by gjb2048** [comment]
Bingo! -> https://moodle.org/mod/forum/discuss.php?d=282598#p1210237 and below.

**Comment by gjb2048** [comment]
Fixed in 2.8.1.3
