### ISSUE TITLE
Coding error when trying to access Single View for tasks and students in Grade Report

### ISSUE THREAD

**Issue by rjapayne** [gjb2048/moodle-theme_essential#462]
This seems to be happening to Essential Theme only, I've switched to Clean Theme and this problem goes away.

When opening Single View, for either a student or task, in the Grade Report a coding error is experienced.

![error](https://cloud.githubusercontent.com/assets/8947966/6404111/7f57f1a2-be68-11e4-8709-2e1e91e7bc22.PNG)

Also made a post on the Moodle bug Tracker: https://tracker.moodle.org/browse/CONTRIB-5612

**Comment by gjb2048** [comment]
What version of Essential are you using please?

**Comment by rjapayne** [comment]
The very latest. 
Release 2.7.9.5.1 (Build: 2014111009)

**Comment by gjb2048** [comment]
You can't be as the stack trace line numbers do not match: https://github.com/gjb2048/moodle-theme_essential/blob/24527097fb80d93f03fa20f343c81a057529555b/renderers/core_renderer.php#L1109

**Comment by rjapayne** [comment]
Oops, thought I had downloaded and tested out the latest version but I just checked out the plugin overview and it says 2.7.9.1 (Build: 2014111001). Sorry about that.

**Comment by gjb2048** [comment]
A 'lot' has happened in that time: https://github.com/gjb2048/moodle-theme_essential/blob/MOODLE_27/README.txt#L166-L246

**Comment by gjb2048** [comment]
I'm likely to publish a 2.8.1.3 soon to fix a few things.  Bugs tend to get reported just after a release despite the RC phase.
