### ISSUE TITLE
When 'layout' set then message screen is between 768px and 979px is broken.

### ISSUE THREAD

**Issue by ActionJONA** [gjb2048/moodle-theme_essential#464]
Hi Gareth, regarding the messages screen at smaller sized screens - this is the difference I get - 

![screen shot 2015-02-27 at 14 50 46](https://cloud.githubusercontent.com/assets/10047439/6414550/3789c6de-be90-11e4-9e3d-0becdc20b2d8.png)
![screen shot 2015-02-27 at 14 50 57](https://cloud.githubusercontent.com/assets/10047439/6414551/3889b558-be90-11e4-8370-1a9e52970ce9.png)

- These screenshots are taken down at 926px.

I've highlighted in the CSS the change from left to right I've made that fixes the strange layout issue.

**Comment by gjb2048** [comment]
What is the setting of 'oldboringlayout' thing?

**Comment by gjb2048** [comment]
'layout' setting.

**Comment by gjb2048** [comment]
Ok, issue only happens if 'layout' is set.
