### ISSUE TITLE
Forum overflow

### ISSUE THREAD

**Issue by mwcao** [gjb2048/moodle-theme_essential#466]
Hi We recently adopted Essential after upgrading Moodle to 2.7. 
The theme is wonderful. 
But we notice some forums of our old courses were cut off as seen in the screenshot.
![50b7456b-7ca1-430f-bf39-7b816052dd7f](https://cloud.githubusercontent.com/assets/5649728/6516410/45acff62-c357-11e4-8e2a-d637199bc968.png)

If I change the theme page width to normal, it's fine. But we prefer to use narrow. 

Another weird thing is it only happens to some old courses, the others are fine. 

Please help. 

Thanks.

**Comment by gjb2048** [comment]
What version of Essential are you using now?
What does it look like in the Clean theme?
What do you notice that is special about the old courses where it happens?
Is there a scroll bar at the bottom of the forum where the problem occurs?

**Comment by mwcao** [comment]
Thank you for replying so quickly! 
Our site is journalismcourses.org

From the readme.txt, The essential version is 2.7.9.4.3

The forum looks fine with Clean theme. 
![clean](https://cloud.githubusercontent.com/assets/5649728/6517180/28cbc278-c35e-11e4-9101-760796ca347d.png)

The old courses that are having issues is in Spanish. But we have other course in Spanish which look fine. 
There is no scroll bar the the bottom of the forum. 
![screen shot 2015-03-05 at 5 43 28 pm](https://cloud.githubusercontent.com/assets/5649728/6517299/3557fc4a-c35f-11e4-860a-95ee068247f0.png)

**Comment by gjb2048** [comment]
Thanks.  2.7.9.4.3 is now old.  2.7.9.5.1 is the current and has changes that may already have addressed the issue, please upgrade.

But I repeat....

BTW 2.7.9.5.1 is the last version for M2.7. Due to lack of funding, only the M2.8 version has a hope, therefore, does it have the problem?

**Comment by gjb2048** [comment]
Issue is long user names not overflowing.

**Comment by mwcao** [comment]
Thank you so much! 
I upgraded it to 2.7.9.5.1 but the problem still exists. 
I noticed you fixed in the 2.8 version. 

Is it possible to give us a fix for 2.7 version? 

Thanks!

**Comment by gjb2048** [comment]
Version 2.7.9.5.1 was the last version for M2.7 because due to lack of funding I've stopped doing back-ports.
