### ISSUE TITLE
Add an option to change position of marketing spots

### ISSUE THREAD

**Issue by cwaffles** [gjb2048/moodle-theme_essential#467]
Hi Gareth,

I just wanted to suggest an option to have an option for the marketing spots to be above or below the  page-content section.

Thanks a bunch for the great theme :+1:

**Comment by gjb2048** [comment]
Hi cwaffles,

Thank you for the suggestion.

The approximate fixed cost for this enhancement into the M2.8 version is 60 GBP.

Kind regards,

Gareth
