### ISSUE TITLE
Top menu bar message Update notifications messages blank

### ISSUE THREAD

**Issue by gibbysimswilson** [gjb2048/moodle-theme_essential#469]
I hoover over the envelope and see
A big "i" and Update notification
I click and I see in my message centre
Recent Notifications
Update notifications
    HERE IS BLANK

Should there be something to read here ?

**Comment by gjb2048** [comment]
What:

Version of Moodle?
Version of Essential?

And screen shot evidence please.

**Comment by gibbysimswilson** [comment]
Moodle 2.8
Theme 2.8.1.3 (Build: 2015022700)
Thanks
![not](https://cloud.githubusercontent.com/assets/10324307/6618934/b00880d4-c901-11e4-9da0-94e4a4047662.jpg)

**Comment by gjb2048** [comment]
Thanks, I'll look at this when I can.

**Comment by zahrah-** [comment]
Hello,

With:
Moodle 2.8.5+ (Build: 20150313)
Essential 2.8.1.3 (Build: 2015022700)

The same screen (as in the screenshot above) is displayed but I believe that this may be the norm as it is also obtained with the Clean and Archaius themes when tested.

With Clean theme:
![notif-1](https://cloud.githubusercontent.com/assets/8460383/6709958/ba0f997c-cd53-11e4-9ec5-89d67a78355b.png)

**Comment by gjb2048** [comment]
Thanks for the information, I still need to replicate the issue.

**Comment by gjb2048** [comment]
I'm going to have to wait until there is a notification before I can test.

**Comment by gjb2048** [comment]
NTS: message_get_messages
