### ISSUE TITLE
Footer included in forum description

### ISSUE THREAD

**Issue by gibbysimswilson** [gjb2048/moodle-theme_essential#470]
Moodle 2.8
Theme 2.8.1.3 (Build: 2015022700) 
In the course Click - This course - Forums
And the footer is included in the last forum post
![footerinforum](https://cloud.githubusercontent.com/assets/10324307/6621529/12af77d2-c912-11e4-8843-832348b54910.jpg)

Thanks

**Comment by gibbysimswilson** [comment]
The problem is when I add my add server code to the forum description. When I remove the add server code it works fine

**Comment by gjb2048** [comment]
Why is this bad?

**Comment by gjb2048** [comment]
RE: "The problem is when I add my add server code to the forum description. When I remove the add server code it works fine" ???  What code?  And please note I do NOT support issues where customisations have taken place.

**Comment by gibbysimswilson** [comment]
I am adding revive add server code in the html editor for the forum description and it displays fine on the course page.
However when I select the forum link in the top menu (This Course) the list of furums do not show the add and the last forum discription contains the footer, as in the picture attached...

**Comment by gjb2048** [comment]
Sorry, what do you mean by "revive add server code in the html editor for the forum description" I don't understand your English.

**Comment by gjb2048** [comment]
Test server has "Display description on course page" ticked and followed instructions to replicate and cannot.

**Comment by gibbysimswilson** [comment]
Sorry - I am pasting the invocation code from my Adserver (revive) into the forum description box using the EDIT HTML SOURCE. After doing this I have my advert displayed with the forum description on the course page, this works fine. When I click - This course - Forums
I get the footer included in the last forum description.

**Comment by gjb2048** [comment]
Sorry, then must be a fault in the markup of the Adserver causing the structure of the page to break.  Not my problem.

**Comment by gibbysimswilson** [comment]
it's ok thanks for helping I will just not display them there, great theme and support
