### ISSUE TITLE
Descriptions on profile page truncated

### ISSUE THREAD

**Issue by zahrah-** [gjb2048/moodle-theme_essential#471]
Hello

This applies to:
Moodle 2.8.5+ (Build: 20150313) Essential 2.8.1.3 (Build: 2015022700)
as well as:
Moodle 2.7.3+ (Build: 20141211) Essential 2.7.9.5.1 (Build: 2014111009)

The descriptions on the profile pages (summary and full profile) appear to have been truncated and there is a larger gap between the descriptions on the left and details on the right.

![profile1](https://cloud.githubusercontent.com/assets/8460383/6713804/1928e2f8-cd6b-11e4-9af4-93afbed286e3.png)

This is what it looks like in Clean theme:

![profile2](https://cloud.githubusercontent.com/assets/8460383/6713813/25b73dee-cd6b-11e4-8748-26cb5af83294.png)

(Please note that I needed to erase some of the descriptions as it's based on a production site).

Many thanks.

**Comment by gjb2048** [comment]
What browser and version?

**Comment by zahrah-** [comment]
Hello,

Firefox 36.0.1
Chrome 41.0.2272.89 m
IE 11

(running on Win 8.1)

**Comment by gjb2048** [comment]
Thanks, I'll look into this when I need to.

**Comment by zahrah-** [comment]
Thank you. 
The theme is really a pleasure to use and gets better with every new version.
Your work is very much appreciated.
