### ISSUE TITLE
Custom Menu (Does it actually exist?)

### ISSUE THREAD

**Issue by mmclain** [gjb2048/moodle-theme_essential#472]
Is it possible to get the top menu (Where you see courses) to have other menu items and sub menu items added or add a menu to the header section? I'm not a heavy PHP person or I'd be able to work around it most likely. Maybe I'm missing something and if this was something that was available and then discontinued, I'm not seeing a reason why...

Thanks

**Comment by gjb2048** [comment]
Hi,

This is already in place when you use the custom menu items in the standard theme settings for Moodle (not the Essential settings).

Cheers,

Gareth

**Comment by gjb2048** [comment]
Hi Marc,

I see this has been resolved here: https://moodle.org/mod/forum/discuss.php?d=310766

Gareth
