### ISSUE TITLE
Cloze answer fields overflow to the right on mobiles

### ISSUE THREAD

**Issue by sympo** [gjb2048/moodle-theme_essential#473]
Hi,
I have noticed that the cloze answer fields overflow to the right on mobiles is the cloze answer is long. The solution I used is adding this to custom css:

/* quiz cloze */
.formulation input[type="text"], .formulation select {
    max-width: 100% !important;
}

**Comment by gjb2048** [comment]
What version of Essential and Moodle please?

Thanks for the suggested fix.  Where is the line it overrides so that 'important' is not used?  Are there any side effects if the fix when not used on mobiles as the CSS is not mobile specific?

**Comment by sympo** [comment]
Moodle 2.8.5, Essential 2.8.1.3 (Build: 2015022700)

This is most likely a wrong practice, but I've been using important out of convenience. 
I have not noticed any side-effects on desktop version of the website during my testing. The users also have not notified us of any errors. This change has been implemented in the past 48h though, so there may be changes that have gone unnoticed.

**Comment by gjb2048** [comment]
Thanks.  Avoid important'

**Comment by gjb2048** [comment]
Thanks.  Avoid 'important' at all costs as this can cause major problems.

I'll look at this when I can depending on a few factors.  Probably mid June.
