### ISSUE TITLE
highlight active module

### ISSUE THREAD

**Issue by mwcao** [gjb2048/moodle-theme_essential#474]
Hi, we use module systems in our moodle. 
We want to highlight the week we are on. Moodle used to have a highlight section option. I could not find it with essential theme. 

But for some reason, the blue highlight is there. How to change it?
![image](https://cloud.githubusercontent.com/assets/5649728/6929318/69e904ee-d7bf-11e4-80cd-2da692ead370.png)

Thanks!

**Comment by gjb2048** [comment]
Hi,

This is a installation specific / use of generic Moodle question as the functionality does exist.  Therefore I'd be willing to spend the time investigating the correct answer for a small consultancy fee.

Kind regards,

Gareth

**Comment by mwcao** [comment]
Hi Gareth, 

The feature is there. We see it in some course - the lighting bulb controls it. 
But it does not show up here. 

![screen shot 2015-03-31 at 4 37 04 pm](https://cloud.githubusercontent.com/assets/5649728/6929916/5b69bca6-d7c4-11e4-93cb-912b95b3c54e.png)
![screen shot 2015-03-31 at 4 37 17 pm](https://cloud.githubusercontent.com/assets/5649728/6929917/5b6ab296-d7c4-11e4-8f9c-849f01d969db.png)

I am wondering if you have a quick answer for it. Otherwise, I can investigate on it more. 

Thanks!

**Comment by gjb2048** [comment]
Hi,

I have a hunch, but would need to fire up a Moodle installation to check and give the correct response.  As this is not a bug, but rather a 'how to use Moodle' / possibly bespoke installation specific change of Essential, therefore time is money.

Kind regards,

Gareth

**Comment by mwcao** [comment]
I figured it out! 
It works on topic format not weekly format. 

Thanks.
