### ISSUE TITLE
"This Course" menu only displays on course home page.

### ISSUE THREAD

**Issue by robinleung** [gjb2048/moodle-theme_essential#479]

**Comment by gjb2048** [comment]
As opposed to what please?

**Comment by robinleung** [comment]
On the BCU theme, the "This Course" menu displays on all course pages. 
The "This Course" menu only displays on only the course home page. Once clicked into an activity, it disappears.

**Comment by gjb2048** [comment]
What do you think the solution is?

**Comment by robinleung** [comment]
Working at it. BCU and Essential has it coded differently.

**Comment by robinleung** [comment]
You might only be missing "global $PAGE, $COURSE, $OUTPUT, $CFG;" in your renderer. Got it to show on my customized theme. 
Thanks.

**Comment by gjb2048** [comment]
??? What line please?

In the core_renderer.php, $this and $OUTPUT are one and the same thing.

**Comment by gjb2048** [comment]
Not sure if this is a 'bug' or an 'enhancement'.

**Comment by mike-grant** [comment]
Hi Gareth,

You check if the page layout is a course, which it isn't. So I would qualify this as a bug, it works in the BCU theme and I'm assuming this is meant to replicate that functionality?

**Comment by gjb2048** [comment]
Hi Mike,

Thanks for your input.  As far as I can tell, the BCU theme will display the menu anywhere that is not the site course: https://bitbucket.org/jezh/moodle-theme_bcu/src/218b217b7e580605d6fcc5883b8514ca1cc45866/renderers.php?at=master#cl-354 - subject to the constraints implied by: https://bitbucket.org/jezh/moodle-theme_bcu/src/218b217b7e580605d6fcc5883b8514ca1cc45866/config.php?at=master#cl-47 via: https://bitbucket.org/jezh/moodle-theme_bcu/src/218b217b7e580605d6fcc5883b8514ca1cc45866/layout/includes/header.php?at=master#cl-170 and loaded as appropriate by: https://bitbucket.org/jezh/moodle-theme_bcu/src/218b217b7e580605d6fcc5883b8514ca1cc45866/layout/columns2.php?at=master#cl-27 etc.

But as the functionality was implemented differently in Essential, then consideration needs to be made upon which the correct classification of such entity can be decided and acted upon appropriately.

Kind regards,

Gareth

**Comment by JeryH** [comment]
Hi Gareth,

The test we used for this is quite simple, something along the lines of "if course ID is set and != 1 display the menu".

!= 1 prevents it showing on the front page or site pages.
It will not show on "my home" or any admin pages as they do not have a course id.

Then wherever you are in any other course the menu will display which allows you to move around that course more easily. For example you can jump directly from a forum thread discussing assignments to your list of assignments within that course.

**Comment by gjb2048** [comment]
Thanks for the idea, but I have another solution for which I will do when circumstances allow.

**Comment by gjb2048** [comment]
Or I may use your idea instead, needs to be thought, implemented and tested.  All of which takes time.
