### ISSUE TITLE
Save Changes/Cancel button area

### ISSUE THREAD

**Issue by mgerszew** [gjb2048/moodle-theme_essential#484]
I really like the floating save/cancel box when working with the admin side and settings, but some of our teachers and students have voiced frustrations that on many of their highly used areas (glossaries, text submissions, etc.) the floating box covers up the text entry areas and requires extra scrolling in order to type in information.

I have found a way to disable this feature in the CSS, but I'm wondering if there is a better design option that can somehow show that save/cancel floating box below any text input areas or if there is some other option for display.

Here's an example in the glossary editing area:
![image](https://cloud.githubusercontent.com/assets/3145912/7327100/1628a5c4-ea90-11e4-8057-98fb8e9b6284.png)

**Comment by gjb2048** [comment]
For crying out loud!  Its Friday @ 20:51!  Give me a break.

**Comment by gjb2048** [comment]
Ok, the only solution to have best of both worlds is to identify one by one the problem pages and exclude them from having the floating area.

**Comment by pccde** [comment]
mgerszew:
Could you share your CSS "fix" so we can apply it till the enhancement can be made?

Thanks,

**Comment by gjb2048** [comment]
What fix?

**Comment by pccde** [comment]
User mgerszew mentioned some CSS code they used to get rid of the large
Save/Cancel button that floats at the bottom when in edit mode.  I wanted
to see if I could get a copy of that code.


Mike Clendenen, A.A.S., IC3
Director of Distance Learning and Instructional Technology
Pitt Community College-VEW 20
P O Drawer 7007
Greenville, NC 27835-7007
Phone: 252-493-7608
Email: mwclendenen091@my.pittcc.edu

On Wed, Aug 26, 2015 at 11:42 AM, Gareth J Barnard <notifications@github.com
> wrote:

> What fix?
>
> Sent from my iPod in deep space...
>

**Comment by gjb2048** [comment]
Dear Mike,

Ok.

All enhancements now need to be funded.  If you would like to fund this setting, I can work out the cost soon.

Kind regards,

Gareth

**Comment by mgerszew** [comment]
Add this to the Custom CSS in the general settings for the theme:

/* fix for floating save box, move back to bottom of page */
body.desktopdevice #region-main form #fgroup_id_buttonar, body.desktopdevice #region-main form .form-buttons{
  position: inherit;
}

/* needed for the 2.9 version and forum posts, quiz report page*/
body.desktopdevice #region-main form #fitem_id_submitbutton{
  position: inherit;
  margin: 0 25%;
}

**Comment by cdipe** [comment]
We lifted the button up a bit and made the background transparent instead, works quite good I think:
It's the last value in 
background-color: rgba(103,104,110,0.3)

/* Better "save changes" button */
body.desktopdevice #region-main form #fgroup_id_buttonar,body.desktopdevice #region-main form #fitem_id_submitbutton,body.desktopdevice #region-main form .form-buttons,body.desktopdevice #region-main form .fp-content-center form+div,body.desktopdevice #region-main form .path-admin .buttons,body.desktopdevice #region-main form div.backup-section+form,body.desktopdevice #region-main form table#form td.submit{
position:fixed;left:30%;bottom: 20px
}

#page form .form-buttons,
#region-main form .form-buttons,
#page form #fgroup_id_buttonar,
#region-main form
#fgroup_id_buttonar {
   background-color: rgba(103,104,110,0.3);
    border-top: 0px solid #67686e
}

#page form .form-buttons #fgroup_id_buttonar,
#page form table#form td.submit #fgroup_id_buttonar,
#page form .form-buttons #fgroup_id_buttonar,
#page form .path-admin .buttons #fgroup_id_buttonar,
#page form #fitem_id_submitbutton #fgroup_id_buttonar,
#page form .fp-content-center form + div #fgroup_id_buttonar,
#page form div.backup-section + form #fgroup_id_buttonar,
#page form #fgroup_id_buttonar #fgroup_id_buttonar,
#page form fieldset:last-of-type.hidden
#fgroup_id_buttonar {
    background-color: rgba(103,104,110,0.3);
    border-top: 0px solid #67686e
}

#page form
#fitem_id_submitbutton {
   background-color: rgba(103,104,110,0.3);
    border-top: 0px solid #67686e
}

#page form .form-buttons,
#region-main form .form-buttons,
#page form #fgroup_id_buttonar,
#region-main form
#fgroup_id_buttonar {
    background-color: rgba(103,104,110,0.3);
    border-top: 0px solid #67686e
}

**Comment by gjb2048** [comment]
In 2.8.1.10 and 2.9.0.9 I have reduced the size of the button area.

**Comment by relecand** [comment]
Is it possible to implement a setting?

Floating button area (yes/no)

**Comment by gjb2048** [comment]
Possible = yes.  Cost = ?

**Comment by relecand** [comment]
Hi Gareth, please send me an offer: christian dot niemczik at googlemail dot com

**Comment by gjb2048** [comment]
I think about one hour to add setting and test.

**Comment by gjb2048** [comment]
Implemented in https://github.com/gjb2048/moodle-theme_essential/commit/a37bd6a07fe2afc68739e4148352c31062292fc3
