### ISSUE TITLE
Can't overwrite files in FTP

### ISSUE THREAD

**Issue by koroshiya1** [gjb2048/moodle-theme_essential#489]
Hi,

Since updating to 2.8.1.4 I am no longer able to write to the "essential" folder to update any files. I have tried changing the file and folder permissions to allow writing to them but this fails every time.
I'm attempting to update some css files since upgrading and it's very frustrating that I'm no longer able to do this. I'm am using Filezilla to upload/download files, and am able to write to other theme folders using this.

**Comment by gjb2048** [comment]
I'm sorry, but this is really nothing to do with the theme code or anything I can do to prevent it from happening.  This is definitely something with your permissions.  Please use your IT support or post on the themes forum with a screen shot of the theme folder in FileZilla showing the permissions.

**Comment by koroshiya1** [comment]
Thank you for responding. It is worth mentioning that I haven't experienced this issue with any other 3rd party themes, nor does the issue occur with version 2.7.9.5.1 of this theme, yet 3 installs of 2.8.1.4 have resulted in the same issue each time. If there is no way the problem is with the theme itself, then I will have to stick with 2.7.9.5.1 for the time being.

Many thanks.

**Comment by gjb2048** [comment]
Hi,

In all the installs I have done with this version, I have never ever encountered the issue.  If it has happened three times then there must be a fault in the process or the permissions somewhere.

The zip file on Moodle.org has no permissions.  The GitHub version has no permissions.  The install via the Moodle UI has had permission issues in the past but that was resolved and was to do with the Grid Format.

Apart from you posting screen shots on the themes forum, I'm not sure what I can really do to solve this.

Were all three installs on the same server?  How did you install the theme?  What instructions did you follow?  What was the state / permissions of the theme folder before the install.  What is the error that happens in FileZilla?  Does the FTP account you use have write permissions?  Is it in the same user / group as the directory '.' being 'theme'?.... Etc.

**Comment by gjb2048** [comment]
If no response in 24 hours, I will close.

**Comment by koroshiya1** [comment]
Feel free to close.
