### ISSUE TITLE
Availability date selection dropdowns

### ISSUE THREAD

**Issue by pccde** [gjb2048/moodle-theme_essential#490]
Is there an option or can one be added to allow switching back to the Moodle default?  The dropdowns currently in Essentials take up way too much screen real estate (see attached images):

![image](https://cloud.githubusercontent.com/assets/12518238/7712171/9e2df1ac-fe3d-11e4-875e-96147ab72c29.png)

![image](https://cloud.githubusercontent.com/assets/12518238/7712177/aac1c902-fe3d-11e4-828e-69d062357448.png)

**Comment by gjb2048** [comment]
What version of Moodle and Essential please?

**Comment by pccde** [comment]
Moodle 2.8.5 (Build: 20150310) and Essential theme 2.8.1.4 (Build:
2015040900).

Thanks for replying back so quickly.  Love the theme!


Mike Clendenen, A.A.S., IC3
 Director of Distance Learning and Instructional Technology
Pitt Community College-VEW 20
P O Drawer 7007
Greenville, NC 27835-7007
Phone: 252-493-7608
 Email: mwclendenen091@my.pittcc.edu

**Comment by gjb2048** [comment]
Thanks Mike, its now added to the list of things to fix.  Probably sometime between July and September.

**Comment by pccde** [comment]
Noticed something else (not really a bug, but it does confuse our
faculty).  If you have a lot of gradebook items all visible, the link to go
to the next page of the gradebook listing may not be easy to find.  In some
cases, the user has to scroll far to the right to see the next page option,
as well as other gradebook "tabs".

Is it possible to have those options default to be left aligned?

We also noticed that if the browser window is not wide enough, you do not
see all of the breadcrumb trail?  Is that by design?  I have seen other
themes where the breadcrumb trail will wrap around onto the next line so
you can see the entire trail.

I appreciate any assistance you can provide.

Thanks,


Mike Clendenen, A.A.S., IC3
 Director of Distance Learning and Instructional Technology
Pitt Community College-VEW 20
P O Drawer 7007
Greenville, NC 27835-7007
Phone: 252-493-7608
 Email: mwclendenen091@my.pittcc.edu

**Comment by gjb2048** [comment]
Hi Mike,

I'm doing iMoot at the moment so will need to get back to you sometime next week.  Please could you be so kind as to keep different issues separate.

Thanks,

Gareth

**Comment by pccde** [comment]
Will do.


Mike Clendenen, A.A.S., IC3
 Director of Distance Learning and Instructional Technology
Pitt Community College-VEW 20
P O Drawer 7007
Greenville, NC 27835-7007
Phone: 252-493-7608
 Email: mwclendenen091@my.pittcc.edu

**Comment by FromOz** [comment]
The following custom CSS seems to be an interim fix for the initial issue: 

fieldset .form-item .form-description, fieldset input[size], fieldset select, fieldset textarea[cols] {width: auto;}

**Comment by gjb2048** [comment]
Thanks FromOz,

Does this override any existing selector?  If so, which one and what LESS file is it located in please?  As I'm trying to reduce the number of selectors not increase them.

Do you have screen shot evidence of the fix?  Have you checked other forms to see that they have not been harmed?

**Comment by pccde** [comment]
Thanks.  I will try it out.


Mike Clendenen, A.A.S., IC3
 Director of Distance Learning and Instructional Technology
Pitt Community College-VEW 20
P O Drawer 7007
Greenville, NC 27835-7007
Phone: 252-493-7608
 Email: mwclendenen091@my.pittcc.edu

**Comment by FromOz** [comment]
G'day Gareth

I only know enough to be dangerous I'm afraid, just tweaking things as and when stumbled over. I'll point my colleague to this issue thread when he gets to work as he is more likely to give you a "proper" answer than I re LESS etc. (Once we get a break we'll try and figure out the right way to do pull requests for the tweaks we've made and pass them through.)

As far as I can tell that custom CSS hasn't had a detrimental affect on anything else (been a few weeks).

This is how it looks when applied:

![editing assignment](https://cloud.githubusercontent.com/assets/3842633/7948491/ab046d3a-09c7-11e5-8def-3792fe260a78.png)

**Comment by gjb2048** [comment]
Ta :)

**Comment by sim3083** [comment]
G'day Gareth, I am FromOz' colleague.

I added the code into the Custom CSS, and didn't touch any less files so cant help you there.

It does override 

fieldset .form-item .form-description, fieldset input[size], fieldset select, fieldset textarea[cols] {
  width: 65.95744681%;
}
from essential.css: line-17, if that helps, but we haven't noticed any detrimental affects yet.

Difference is as below

![test home edit profile](https://cloud.githubusercontent.com/assets/5117357/7977962/7555cc44-0ad3-11e5-84ff-6c9bdb9e0664.jpeg)
![edit profile2](https://cloud.githubusercontent.com/assets/5117357/7977963/755b8aa8-0ad3-11e5-81d3-868a6540735e.jpeg)

**Comment by gjb2048** [comment]
G'day FromOz colleague,

Thanks for the information, will come in handy :)

Hoping not to chuck another selector on the barby ;)

Many thanks,

Gareth

**Comment by gjb2048** [comment]
Possible contradiction with #417.

**Comment by gjb2048** [comment]
In Moodle its always more complex than it should be: https://github.com/gjb2048/moodle-theme_essential/commit/e9222afea27ba99d8914913c72a3374d383b0085

**Comment by pccde** [comment]
To all:
I have applied the following code and will let you know of any ill effects:

fieldset .form-item .form-description, fieldset input[size], fieldset select, fieldset textarea[cols] {width: auto;}

Thank you.

**Comment by gjb2048** [comment]
'fieldset select' will break issue #417 - see above!

**Comment by pccde** [comment]
If that is the only page it messes up, I'm good with that till a more
permanent fix comes along.


Mike Clendenen, A.A.S., IC3
 Director of Distance Learning and Instructional Technology
Pitt Community College-VEW 20
P O Drawer 7007
Greenville, NC 27835-7007
Phone: 252-493-7608
 Email: mwclendenen091@my.pittcc.edu

**Comment by gjb2048** [comment]
https://github.com/gjb2048/moodle-theme_essential/commit/e9222afea27ba99d8914913c72a3374d383b0085 is the permanent fix, hence the improved LESS and the fact I've closed the issue.

**Comment by sim3083** [comment]
Thanks Gareth, works great

**Comment by pccde** [comment]
Gareth:

Do I download a new version of the theme to get the fix?


Mike Clendenen, A.A.S., IC3
 Director of Distance Learning and Instructional Technology
Pitt Community College-VEW 20
P O Drawer 7007
Greenville, NC 27835-7007
Phone: 252-493-7608
 Email: mwclendenen091@my.pittcc.edu

**Comment by gjb2048** [comment]
Hi Mike,

Ok, currently the repository is in 'development mode' and needs to be changed to 'production', using the same technique illustrated here: https://www.youtube.com/watch?v=8uwYn2im008.  This can be done locally for you after either using the 'Download ZIP' button on the main page: https://github.com/gjb2048/moodle-theme_essential - or you can use a similar technique of using Git for Administrators: https://docs.moodle.org/29/en/Git_for_Administrators

Or you can wait for me to make a release.  This is a 30 min admin job for me so clearly I only do it when I consider that it is warranted.

Kind regards,

Gareth
