### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by angelsimon** [gjb2048/moodle-theme_essential#492]
I have installed the Essential Theme 2.6.11. My Moodle version is 2.6.2. After I installed the theme and tried to "select" it, I got this error and the whole system crashed.
I don't know if there is something wrong in my configuration but it couldn't be so severe to turn down the whole system.
I attach a screenshot.

Thanks in advance! It seems to be a great theme!.
[captura de pantalla de 2015-05-26 14 27 27](https://cloud.githubusercontent.com/assets/627054/7818807/499908bc-03b4-11e5-8f4a-31e17adb4e5e.png)

**Comment by gjb2048** [comment]
Do you have this folder and its contents in '/theme/essential/jquery'?

**Comment by gjb2048** [comment]
V2.6.2 is very old version!

**Comment by angelsimon** [comment]
Yes, i have that folder in theme/essential/jquery. Files in this folder are: four js files and a php file named plugins.php

What could it be ?

**Comment by gjb2048** [comment]
I don't know, is the site public?

**Comment by angelsimon** [comment]
No, it's a development site. It's only intranet.

**Comment by gjb2048** [comment]
Is it a complete clean of install of Moodle?

**Comment by angelsimon** [comment]
No, it's an upgrade from a 2.5 version.

**Comment by gjb2048** [comment]
Have you made any code changes or installed other plugins?

**Comment by gjb2048** [comment]
How did you upgrade / change the core files?

**Comment by angelsimon** [comment]
No changes where made in the source code.

**Comment by gjb2048** [comment]
Plugins?  And why are you using 2.6.2 in development when 2.6.11 is the latest?

**Comment by gjb2048** [comment]
What's the URL when you inspect the issue / error in the 'console'?

**Comment by angelsimon** [comment]
I thought 2.6.11 was the theme version that will work with any 2.6.x Moodle version. Development site is the same we have in production but for testing.

**Comment by gjb2048** [comment]
2.6.11 is the theme version but there is now a 2.6.11 of core too.  It should do, but I'm trying to determine what might be the issue, so works / don't work binary chop.

**Comment by gjb2048** [comment]
Ok, given that line 833 is a core API call: https://github.com/gjb2048/moodle-theme_essential/blob/MOODLE_26/lib.php#L833 - then there is a problem with your core files and not the theme files.

**Comment by angelsimon** [comment]
OK, thanks for your help. You have been more than helpful. If I can fix the problem I'll let you know. I'm going to ask in the Moodle Forums too, perhaps somebody has faced this problem before.

**Comment by gjb2048** [comment]
Ok, but TBH from that line number it's not an Essential issue but rather how your Core files / installation are set-up.

**Comment by gjb2048** [comment]
If you find Essential useful, please consider donating :)

**Comment by angelsimon** [comment]
Sure

**Comment by gjb2048** [comment]
Ok, I'll close if not resolved or understood.

**Comment by angelsimon** [comment]
Hi, I will leave this message if someone is having a problem like the one I had:

While debugging each line I noticed that the problem started when PHP tried to parse some urls. If you have Moodle 2.6.2+ and your url address contains a port number. Be careful with url address that contain backslashes.

For example:
<pre>$url = 'http://someaddress:someport\themedir\anotherdir\filename.ext';
parse_url($url); // Error and later an exception</pre>

But
<pre>$url = 'http://someaddress:someport/themedir/anotherdir/filename.ext';
parse_url($url); // Everything's fine :)</pre>

Thanks for the help! Hope this helps too.

**Comment by gjb2048** [comment]
Was the use of backslashes in URL's in your or my code?
