### ISSUE TITLE
How to adjust marketing box in CSS

### ISSUE THREAD

**Issue by e24etf** [gjb2048/moodle-theme_essential#493]
Hi,
This is first question. I'm using essential theme for moodle 2.8 but i don't know how to adjust marketing box in CSS. i try .marketing.content { height: 250px; } but not working please tell me about solve it.

Thank you.

**Comment by gjb2048** [comment]
This is a question pertaining to your customisation of the theme, please ask on Moodle.org themes forum.

**Comment by gjb2048** [comment]
Or I'd be happy to solve this as a contractor for 50 GBP payable by PayPal in advance.

**Comment by gjb2048** [comment]
No reply in several months, closing.
