### ISSUE TITLE
Site Administration menu collapse

### ISSUE THREAD

**Issue by dschwa** [gjb2048/moodle-theme_essential#494]
There must be a simple CSS fix 

When I'm deep into something like site administration/themes/essential/header
and use the browser back arrow, the menu collapses back to default.

I would love the menu to stay open as I work.

This may also be why the breadcrumbs while in admin, are not links for most levels

**Comment by gjb2048** [comment]
This is in the administration block?

**Comment by dschwa** [comment]
Yes, the admin block

**Comment by gjb2048** [comment]
Hi,

Oh, that's not CSS for the functionality but the core Navigation API which may or may not be override-able in a theme.  I'd be happy to produce a feasibility report for 210 GBP with 50% deposit payable by PayPal.

Kind regards,

Gareth
