### ISSUE TITLE
Embedded videos do not adhere to set width & height restrictions

### ISSUE THREAD

**Issue by kimboking** [gjb2048/moodle-theme_essential#497]
Embedding a video using youTube embed code with width & height restrictions ignores restrictions and expands video to 100% width of content area in Essential Theme.  

To test:
1. Copy embed code from youTube video 
2. Paste to label or page content area using Moodle HTML editor (HTML button on atto toolbar)
3. Save and display

The attached screenshots display an embedded youTube video with frame restrictions set to 560 X 315 pixels.  The video displays correctly in Clean Theme but is "enormously expanded" in Essential theme.

![clean theme embedded video](https://cloud.githubusercontent.com/assets/6333407/7969696/af8b2c6a-0a06-11e5-8839-bce1c52ae33b.png)
![essential theme embedded video](https://cloud.githubusercontent.com/assets/6333407/7969697/af8b8fc0-0a06-11e5-9c6e-168ea4afca9b.png)

**Comment by gjb2048** [comment]
Please read info about FitVids in the Readme.txt file.

**Comment by gjb2048** [comment]
https://github.com/gjb2048/moodle-theme_essential/blob/master/README.txt#L157-L160
