### ISSUE TITLE
IE9 Carousel positioning support

### ISSUE THREAD

**Issue by Lumnock** [gjb2048/moodle-theme_essential#498]
I'm not sure what version of Essential theme that we're using where I am, but I've found that the carousel doesn't position properly in Internet Explorer 9.  The reason is because 'position:initial' is being used on a number of the CSS elements within Essentials.  You'll find however that position:initial isn't supported by any versions of IE.  I haven't tested it on other versions other than 9, but I suspect that this may well be the root cause of a number of problems users are having with Internet Explorer on the moodle forums.

Regards,
Robbie Coombs

**Comment by gjb2048** [comment]
Ok, the version for Moodle 2.8 supports IE9 and works.  Without the Essential and Moodle version, how can I replicate the issue and help you?

**Comment by gjb2048** [comment]
P.s. Umm, Robbie, what specific issues on the forums?  I look at the themes forum at least once a day and have not seen anything like this.  I also look at other forums like the general one.  Please back up your words with evidence.

**Comment by Lumnock** [comment]
"Ok, the version for Moodle 2.8 supports IE9 and works".  That could well be because Moodle core doesn't have position:initial within it (that I've come across anyway).  It's being called by the Essential theme (which I believe is 2.7).  If you're using out the box Essential theme then it doesn't raise its' head, but if you start to tinker with it, (such as the positioning of the slideshow in my case), then it becomes an issue.

As you'll see here - https://developer.mozilla.org/en-US/docs/Web/CSS/initial, the initial css property isn't supported on any IE versions.  By using it, Internet Explorer drops it and it instead inherits.

As an example, see #essentialCarousel.carousel .carousel-inner.below .carousel-caption.

Again I say that out of the box essentials, you may not notice it.  The point is that it's there in the CSS, yet doesn't actually get assigned to the element in IE, which I suspect is the cause of a number of peoples' problems on the Moodle forums.  Instead it's inheriting position:absolute in a lot of cases

As for evidence on the forums, I closed the tabs a while ago as they didn't have any answers to what was causing my problems.  Sorry I can't be more help in narrowing down whom else this may also be of benefit to.

Regards,
Robbie Coombs

**Comment by gjb2048** [comment]
Hi Robbie,

If you had open tabs a while ago then the URLs would still be in the history.
What tinkering have you done so that I can see the effect and thus have just cause to possibly spend my time and do something about it?

Gareth

**Comment by Lumnock** [comment]
I've already searched quickly, but I've been going through loads of moodle threads today (on various issues) and can't come across them readily.  There were only 2 that stuck out at me at the time, as they had screenshots that looked reminiscent of what was occurring for me.

I wish I could share with you the tinkering, but it's in a classified environment and a lot of the code is embedded with classified messages and notifications.  I know I'm not being much help here, but it's the reality.

Regardless, I'm not interested in trying to make a case for you to allocate any of your time if you don't want to.  I've identified a problem with Essentials, and already fixed it on my end.  As custodian of the Essential theme it's entirely up to you to decide if you want to improve the code or not.  To me it's a no brainer, but do whatever you like.

http://stackoverflow.com/questions/15343487/is-position-initial-cross-browser-css
https://developer.mozilla.org/en-US/docs/Web/CSS/initial
https://msdn.microsoft.com/en-us/library/ms531140(v=vs.85).aspx
https://developer.mozilla.org/en-US/docs/Web/CSS/position
http://www.sitepoint.com/web-foundations/position-css-property/

**Comment by gjb2048** [comment]
Thanks for reporting the issue Robbie.

**Comment by gjb2048** [comment]
Hi Robbie,

Ok, I have investigated both the LESS and the CSS in the M2.7 and M2.8 versions of Essential and can find no trace of 'position: initial' pertaining to the 'below' functionality of the carousel.  When implementing it I do not remember in the past having added such attribute.  In fact there appears to be no use of 'position: initial' anywhere in either the LESS or CSS or indeed injected by the JS.

Therefore I can only assume that it must be some other anomaly outside of my control.

Gareth

**Comment by Lumnock** [comment]
Hi Gareth,

I just downloaded 2.7.7 - https://moodle.org/plugins/download.php/6816/theme_essential_moodle27_2014090303.zip and have found the position: initial in the following locations:

essential/less/essential/blocks.less:
   40    }
   41    li.item_with_icon > p img {
   42:     position: initial !important;
   43    }
   44  }

essential/less/essential/carousel.less:
   34      &.below {
   35        .carousel-caption {
   36:         position: initial;
   37          height: 65px;
   38        }

/essential/less/moodle/course.less:
  127      }
  128      div.activityinstance {
  129:       padding-right: initial;
  130  
  131        input {
  132:         margin-bottom: initial;
  133:         padding-top: initial;
  134:         padding-bottom: initial;
  135          vertical-align: text-bottom;
  136        }
  ...
  151         * absolute positioned move icon.
  152         */
  153:       padding-left: initial;
  154        padding-right: 32px;
  155      }
  ...
  164      .activityinstance {
  165        padding-left: 4px;
  166:       padding-right: initial;
  167      }
  168    }
  ...
  179      &.editor_displayed {
  180        div.activityinstance {
  181:         padding-left: initial;
  182        }
  183      }
  ...
 1063      margin-right: 1em;
 1064      display: inline-block;
 1065:     display: initial;
 1066      img {
 1067        margin: 0 4px;

/essential/less/moodle/core.less:
 1648  }
 1649  
 1650: .initialbar {
 1651    a, strong {
 1652      padding-left: 3px;
 ....
 2437      .moodle-actionmenu[data-enhance] {
 2438        .toggle-display.textmenu {
 2439:         margin-left: initial;
 2440          margin-right: 4px;
 2441  
 2442          .caret {
 2443:           margin-left: initial;
 2444            margin-right: 2px;
 2445          }

/essential/less/essential/navigation.less:
  228                .notification-text {
  229                  width: 185px;
  230:                 white-space: initial;
  231                  float: right;
  232                  font-size: 12px;

Then there's a large chunk of the minimised code which contains it as well.  For the most part, setting values

**Comment by gjb2048** [comment]
Hi Robbie,

Ok, version 2.7.7 is 'seven' versions out of date and in the past.  The current version 2.7.9.5.1 does not have 'position: initial'.  There is nothing for me to do!

Gareth

**Comment by gjb2048** [comment]
However, there are usages of 'initial' in other places.  Essential follows 'core' and thus mirrors it: https://github.com/moodle/moodle/blob/MOODLE_27_STABLE/theme/bootstrapbase/less/moodle/course.less#L119-L128 and https://github.com/moodle/moodle/blob/master/theme/bootstrapbase/less/moodle/course.less#L119-L128 etc.  Changes to that code require a report and justification in the Moodle tracker: tracker.moodle.org

**Comment by gjb2048** [comment]
'white-space' is not supported by IE: http://caniuse.com/#search=white-space so no problem there.

**Comment by gjb2048** [comment]
essential/blocks.less no longer has the issue: https://github.com/gjb2048/moodle-theme_essential/blob/master/less/essential/blocks.less#L32

**Comment by gjb2048** [comment]
essential/carousel.less no longer has the issue: https://github.com/gjb2048/moodle-theme_essential/blob/master/less/essential/carousel.less#L41

**Comment by gjb2048** [comment]
moodle/course.less and moodle/core.less whilst in my control as said above need to 'mirror' core code, faulty or otherwise.  It might be the case that those values are required for the browsers that support them but not for IE and thus the code is actually 'correct' despite being apparently wrong for IE.  Thus if there is a justified bug with evidence then if needs fixing, but if 'its not broken, don't fix it'!!!

**Comment by gjb2048** [comment]
Better white-space reference: http://www.w3schools.com/cssref/pr_text_white-space.asp - despite IE8 support but no-initial - the other browser argument still holds water.

**Comment by gjb2048** [comment]
P.S. The minimised CSS is generated from the LESS.

**Comment by Lumnock** [comment]
Quite right about the LESS > CSS.  Put that down to early in Canberra with no coffee.

As for other versions being fixed, glad that it won't be a problem for other users who are going forward.  Something to keep in your hat for any queries from Legacy users.

All the best,
Robbie Coombs
