### ISSUE TITLE
Mixing Google Fonts with Normal Fonts breaks rendering of Google Fonts

### ISSUE THREAD

**Issue by richardschwarz** [gjb2048/moodle-theme_essential#500]
Moodle 2.8.6+ (Build: 20150514)., Latest Stable Essential from Plugins Directory

Heading Font: Questrial
Text Font: Verdana

Just recently (last couple of days) I noticed that our Headings were suddenly not rendering in our chosen Google Font (Questrial). With code inspector, it looked like the fonts were being called properly from the font repository, it just wasn't displaying.

I looked at the code: looks fine. 
Noticed, though, that it was trying to pull Verdana from Google Fonts as well. It can't as it's not hosted on Google Fonts, so it wasn't pulling the Heading font either.
The fix: Use only Google Fonts, not a mix.
I've attached before and afters to show the difference.

The weird thing is that it was working only just last week.

New thought - is there a way to separate the fonts? Google Font for heading, Normal font for text?

Thanks!
Richard
Before:
![font_selection_before](https://cloud.githubusercontent.com/assets/145715/7999408/d69a6d24-0b8d-11e5-947d-19d083ab46a1.png)
After:
![font_selection_after](https://cloud.githubusercontent.com/assets/145715/7999418/dea590b6-0b8d-11e5-8d59-823236df8846.png)

**Comment by gjb2048** [comment]
Hi Richard,

Almost probable to split.  Would take about of half a day to get it right and thus the cost is 122.50 GBP.  Actual time might be less but would only know when completed, but not less than two hours so 80 GBP.

Would you like to fund it?

Kind regards,

Gareth

**Comment by richardschwarz** [comment]
Hi Gareth. I've switched from Verdana to Roboto and that's fixed it up. Just thought it was a bit weird because it was working then stopped. 

I appreciate the work that would go into doing this, but am not looking for a fix at this point. It's not a big problem, just thought you'd like to know.

**Comment by gjb2048** [comment]
Thanks for letting me know Richard.
