### ISSUE TITLE
Different settings for different courses / categories / users

### ISSUE THREAD

**Issue by jamaur** [gjb2048/moodle-theme_essential#501]
Moodle allows us to have different themes for different users / courses / course categories. I was wondering if there is anything in place to allow for that same type of functionality but with the essential theme. That is, to have different essential theme settings for different courses / categories / users.

For example, course XYZ might have a spaceship logo with blue and orange colours while course 123 has a different logo with purple and yellow colours.

**Comment by gjb2048** [comment]
No there is not and 'yes' it would be a complex enhancement.
