### ISSUE TITLE
Use Alternate Name in user menu as the main name

### ISSUE THREAD

**Issue by MarkWhitington** [gjb2048/moodle-theme_essential#503]
Hi all,

I have a few users who want to have their "Alternate Name" displayed if they complete the field in their profile.

I have set the user permissions to use alternatename in the Alternate Name field.

I am using Essentials theme 2.7.9.5.1 (we have just updated to Moodle 2.8... have yet to update plugins)

Originally raised: https://moodle.org/mod/forum/discuss.php?d=314766#p1260801

I have had partial success... the person's firstname is appearing at the top with the Alternate name lower. 

Is it possible to have the Alternate name display where the firstname currently does - but only if they complete the Alternate name field in their profile
![alternate name](https://cloud.githubusercontent.com/assets/7004621/8019715/1410cb4e-0c9c-11e5-812e-2f2a6d2f0397.png)
? 

This only affects a few users so we don't want to inconvenience the many for the sake of a few. Clearly we would not want to show a "blank" if the Alternate Field was blank.

I hope this can be done.

Thanks 
Mark

menu image

**Comment by gjb2048** [comment]
Hi Mark,

Firstly thanks for posting on here.  I do suspect that it can be done, however it would not be a five minute implementation, especially if there would need to be a setting such as "Use alternate name if available" as others may not wish it at all.

Thus as what I am about to type I cannot really say on the forums.  As I suspect that it would take around a hour's time to investigate, solve, implement and test, would you be willing to fund the enhancement please?

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Note: Need to check if the alternated name is a core switch on setting: https://docs.moodle.org/29/en/Additional_name_fields and if there are any 'capabilities' associated with it.

**Comment by MarkWhitington** [comment]
Hi Gareth,
Thanks for your reply.
It seems completely reasonable to pay you for this service.
I will need to take this back to my managers, and get back to you.
Approx how much is the hourly $ rate?
Thanks Mark

**Comment by gjb2048** [comment]
Hi Mark,

Thank you for getting back to me.  I estimate that this should take about one hour of time, so 40 GBP.

Kind regards,

Gareth

**Comment by MarkWhitington** [comment]
Hi Gareth,
Thank you for your patience. We would like to proceed.
We have organised that our website host will pay for this enhancement and bill us as part of his service to us.
Host: Richard Wallace - email:  Richard@wwdad.com
As usual please CC us in on you discussions with Richard. (nice chap who serves us well)

I have had more thought about being less confusing...
I think I am asking to replace the firstname (as in the image above) with the alternate name.
These are my current settings:
![alternatename-user-policy-settings](https://cloud.githubusercontent.com/assets/7004621/8098840/6f72ce06-1034-11e5-875f-b59a38d67e11.png)
These settings result in...
![alternatename-user-policy-settings](https://cloud.githubusercontent.com/assets/7004621/8098868/b50faed4-1034-11e5-94bd-e0b5ab84f36a.png)
This is desirable as it has the user's full name with alternate name in brackets... this format flows through to the browse users screens and to our certificates.

Hence I hope only to change the name level with the envelope to the alternate name if it exists.

If you go ahead with this enhancement will it just be for us or will you be able to include it for all who want it?
Cheers
Mark

**Comment by MarkWhitington** [comment]
OOPS...
These settings result in...
![alternatename-user-menu](https://cloud.githubusercontent.com/assets/7004621/8098944/75f79d0a-1035-11e5-9ba5-5f8d3a383427.png)

**Comment by gjb2048** [comment]
Thanks Mark,

The settings you show are something different to what was asked.  I'll have to look into if they have an impact as I've not encountered them before.  The change will be for everybody.  If it was just for you then it would be a child theme special and cost more.

But I just thought this issue was if the alternate name was there, then use it.  Nothing mentioned before about format.  Also in those settings the description pertains to how other users view the name for the alternate setting (not name), so I don't think they apply here.

Cheers,

Gareth

**Comment by gjb2048** [comment]
P.s.  The code as it stands has the first name only as the menu title and then the 'full name' in the menu which I believe is governed by the settings you said.  Therefore I understood the issue as replacing the menu name where it only has the alternate name not the name in the menu which will contain the alternate name already as core provides that via those settings already.

**Comment by MarkWhitington** [comment]
I am hoping this is not difficult... what I have provided indicated the flow-on effect of including the alternatename. (If used alone - alternatename - had a dramatic effect on both user browsing and certificate naming)
The image below will show what is in the "Adam Nurse" profile... I hope it is a simple switch of field name for the menu heading.
![alternatename-roger](https://cloud.githubusercontent.com/assets/7004621/8101576/98202e0c-1057-11e5-84c2-dd4675d7e27b.png)
ing.
I suspect you are on the right track! 
I am probably checking stuff that does not need to be checked.
Cheers
Mark

**Comment by MarkWhitington** [comment]
Sorry when I edited the post above the text changed... not sure how ... but I am not yelling at you.

**Comment by gjb2048** [comment]
Hi Mark,

Ok, I think I need to prototype this, screen shot and get back to you later.

Cheers,

Gareth

**Comment by gjb2048** [comment]
Ok....

Given:

![2015-06-11 11_42_49-moo28_ administration_ users_ permissions_ user policies](https://cloud.githubusercontent.com/assets/1058419/8105376/aca2b06a-1030-11e5-8396-d88d4eca438c.jpg)

which currently gives:

![2015-06-11 11_43_27-moodle 28](https://cloud.githubusercontent.com/assets/1058419/8105388/c2c62bec-1030-11e5-8dc3-b1521a92a3fe.jpg)

Then with:

![2015-06-11 11_53_03-moodle 28](https://cloud.githubusercontent.com/assets/1058419/8105402/ccb6ed6c-1030-11e5-83b8-522669465e0d.jpg)

It would be possible to use the alternate name (if it exists) at position 'a' but with position 'b' it is far more complex as can clearly be seen the function that generates the string takes into account the 'login as' status but what setting to use as the template for the string, so here as the original user has the capability they see the '&' one rather than the '-' one.

**Comment by gjb2048** [comment]
Where the alternate name for the 'Admin' is 'Administrator' and for 'A Teacher' it is 'The'.

**Comment by gjb2048** [comment]
So....

![2015-06-11 12_15_25-moodle 28](https://cloud.githubusercontent.com/assets/1058419/8105724/a3550000-1033-11e5-9b7d-7b0103acec85.jpg)

**Comment by MarkWhitington** [comment]
Yes... I noticed that it was the "alternate full name format" that was passed through to various screens if used. 
I believe what you have demonstrated above is what we want. 
I hope that is still OK for you to do.
Cheers
Mark

**Comment by gjb2048** [comment]
Hi Mark,

In that case I can have it such that the alternate name is used as the menu name if it exists.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Hi Mark,

Would you like to proceed for the price of 40 GBP quoted above?

Kind regards,

Gareth

**Comment by MarkWhitington** [comment]
Yes thank you.... will you be able to invoice Richard Wallace ... above.
Cheers
Mark

**Comment by gjb2048** [comment]
Hi Mark,

I've completed the work and put it into the V2.8.1.5 version (to be released soon).  Do you have a test server to check and sign it off please?  So using the 'Download ZIP' button here: https://github.com/gjb2048/moodle-theme_essential/tree/master

Cheers,

Gareth

**Comment by MarkWhitington** [comment]
Hi Gareth
I have installed on my localhost ... all looks great!
Thanks... we really appreciate your effort with this request.
Please send invoice to Richard Wallace.
Should you have any trouble I will assist.
Cheers
Mark

**Comment by gjb2048** [comment]
Hi Mark,

I've sent Richard an invoice, but I could not CC you as I don't have your eMail address.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Hi Mark,

Payment received, thank you.

Essential V2.8.1.5 released, please update ASAP as contains a very small security fix.

Kind regards,

Gareth

**Comment by MarkWhitington** [comment]
Thanks Gareth,
Richard has updated us just now.
The alternate name looks great, for those who will use it.
I think the Essentials is fantastic for our worksite as it allows great flexibility for us “non-programmers”.

Karen, Richard will pass on Gareth’s fee on his next invoice.
Cheers
Mark

Mark Whitington
Education Facilitator
Centre for Nursing & Midwifery Education & Research
Flinders Medical Centre
Southern Adelaide Local Health Network
SA Health
Flinders Drive Bedford Park SA 5042
• Tel: (08) 8204 6321 |  • Mobile: 0407497981 | • Fax: (08) 8204 5907 |
• Email: mark.whitington@health.sa.gov.au<mailto:mark.whitington@health.sa.gov.au>
This email may contain confidential information, which also may be legally privileged.  Only the intended recipient(s) may access, use, distribute or copy this email. If this email is received in error, please inform the sender by return email and delete the original.  If there are doubts about the validity of this message, please contact the sender by telephone.  It is the recipient's responsibility to check the email and attached files for viruses.
