### ISSUE TITLE
Essentials child theme will not inherit parent settings

### ISSUE THREAD

**Issue by hcpss-banderson** [gjb2048/moodle-theme_essential#504]
To reproduce:

1. Install moodle 2.8 and the Essential theme.
2. Enable Essential theme and add a header image.
3. copy theme/essential/essentials to theme/essentials
4. Set Essentials theme to inherit setting from Essential:
    1. Remove $THEME->parents_exclude_sheets from theme/essentials/config.php
    2. Set $usingessentialsettings to true in function theme_essentials_process_css
5. Switch theme to Essentials

Expected result: The header image I set for Essential should now display for theme Essentials.

Actual result: No header image is displayed.

This seems to be due to the fact that, though we are calling theme_essential_process_css on line 32 of theme/essential/essentials/lib.php, we are passing it a $theme object that does not contain the settings for Essential, but instead contains settings for the theme Essentials (of which there are none).

**Comment by hcpss-banderson** [comment]
Submitted pull request #505 to load the Essential theme to pass to theme_essential_process_css.

**Comment by gjb2048** [comment]
Pulled #505 - ta.
