### ISSUE TITLE
Essential Summary error

### ISSUE THREAD

**Issue by jvickers2001** [gjb2048/moodle-theme_essential#506]
Whenever I try to view a summary, I get an error. The error is different in each browser. I have attached images for Safari, Chrome, Explorer and Firefox.

![chrome_summary_error](https://cloud.githubusercontent.com/assets/2656374/8085240/19209c0e-0f5d-11e5-9046-884160ef16b8.PNG)
![explorer_summary_error](https://cloud.githubusercontent.com/assets/2656374/8085242/1921b3a0-0f5d-11e5-8349-f64b4617db0e.PNG)
![firefox_summary_error](https://cloud.githubusercontent.com/assets/2656374/8085241/192125e8-0f5d-11e5-98ad-0bc0854176ba.PNG)
![safari_summary_error](https://cloud.githubusercontent.com/assets/2656374/8085243/1922aa6c-0f5d-11e5-8434-260fc2c3098f.PNG)

**Comment by gjb2048** [comment]
V2.8.1.3 of Essential?  What version of Moodle please?  Clicking on the 'i' icon?

**Comment by jvickers2001** [comment]
Sorry - version 2.8 of Moodle. Yes, when clicking on the "i" icon, the errors appear.

**Comment by gjb2048** [comment]
Ok, can replicate in 2.8.1.4 but don't know what's wrong yet.  Mark-up looks the same.

**Comment by gjb2048** [comment]
I have an idea of what might be happening but need time to think and check.

**Comment by jvickers2001** [comment]
Thanks for working on this Gareth. I really appreciate your efforts and ingenuity with the theme.

**Comment by gjb2048** [comment]
NP :)

NTS: YUI panel collapse conflict with full jQuery now in Essential?  Shoehorn fine, so can adapt from the renderer there.  Plus double check overridden course renderer against bootstrapbase overridden one.
