### ISSUE TITLE
tiny icon in grading window for collapsed columns in Chrome

### ISSUE THREAD

**Issue by whymiss** [gjb2048/moodle-theme_essential#510]
When in the grading page of a moodle assignment we often collapse columns such as the Email address and User picture to get make viewing other columns easier. In Chrome V43 (and maybe other versions) the +icon for the collapsed columns is so tiny it looks like a dot instead of a plus. Can this be fixed please? It behaves OK in other themes and behaves OK in Essential if using IE11 so maybe its just a Chrome issues with Essential theme.
![essential](https://cloud.githubusercontent.com/assets/4484052/8245159/7e1c8eec-167e-11e5-9c9f-188a9d284614.JPG)

**Comment by gjb2048** [comment]
What version of Essential and Moodle please?

If I do fix it then it will still be a while until the next release as releases take time.

**Comment by gjb2048** [comment]
Cannot replicate:

![2015-06-19 16_16_48-assignment](https://cloud.githubusercontent.com/assets/1058419/8256406/d1deaab8-169e-11e5-8aef-02621b80b3e8.jpg)
