### ISSUE TITLE
Google Web Fonts do not load in quiz

### ISSUE THREAD

**Issue by sim3083** [gjb2048/moodle-theme_essential#511]
When using Google Web Fonts, evrything works well until you attempt or review an quiz.

Settings 
![test home administration appearance themes essential font](https://cloud.githubusercontent.com/assets/5117357/8299086/8909f444-19b6-11e5-9482-6138d4c911dd.jpeg)

What I want to see
![test assessment-good](https://cloud.githubusercontent.com/assets/5117357/8299072/542acb9a-19b6-11e5-98f0-29022295e61c.jpeg)

What I see
![test assessment](https://cloud.githubusercontent.com/assets/5117357/8299062/2c502638-19b6-11e5-85e4-e7eb3efa370c.jpeg)

I can only think there are some security setting in the quiz module that wont allow access the Google Fonts.
I have it working by using custom fonts and uploading the .ttf

I have tried it in Clean theme by adding the link in AdditionalHTML and the style in Custom CSS and it seems to carry over.

Anyway a bug nonetheless (l think!)

**Comment by gjb2048** [comment]
Ok,

A) will not be a security setting.
B) both screen shots are identical using the theme bar the font, so how did you make the first screen shot?

**Comment by gjb2048** [comment]
Scrub B - too early.

**Comment by gjb2048** [comment]
Plus, do the other pages work?

**Comment by gjb2048** [comment]
Cannot replicate:

![2015-06-23 12_27_28-moo28_ administration_ appearance_ themes_ essential_ font](https://cloud.githubusercontent.com/assets/1058419/8305098/a049dcea-19a3-11e5-90fb-0fa97587ae96.jpg)
![2015-06-23 12_28_57-a quiz](https://cloud.githubusercontent.com/assets/1058419/8305096/a040cede-19a3-11e5-9272-42ee8db11678.jpg)
![2015-06-23 12_27_48-a quiz](https://cloud.githubusercontent.com/assets/1058419/8305097/a0427748-19a3-11e5-8404-a9d23b30a03d.jpg)

**Comment by gjb2048** [comment]
Humm, perhaps a '+' symbol thing.....

![2015-06-23 12_34_02-a quiz](https://cloud.githubusercontent.com/assets/1058419/8305195/9c4886a4-19a4-11e5-985a-5f1b63908679.jpg)
![2015-06-23 12_31_25-a quiz](https://cloud.githubusercontent.com/assets/1058419/8305194/9c485bac-19a4-11e5-9d0b-64745ef4fe5a.jpg)
![2015-06-23 12_36_09-google fonts](https://cloud.githubusercontent.com/assets/1058419/8305196/9c4b6e50-19a4-11e5-84e4-54f1dfe5b3b7.jpg)

**Comment by gjb2048** [comment]
No 'Open Sans' being loaded on the network tab.....

**Comment by gjb2048** [comment]
Ok, everything in place, so not a bug:

![2015-06-23 12_40_10-a quiz](https://cloud.githubusercontent.com/assets/1058419/8305271/4ede3700-19a5-11e5-9b31-2936627a64a4.jpg)
![2015-06-23 12_41_09-fonts googleapis com_css_family oswald_open sans subset latin latin-ext](https://cloud.githubusercontent.com/assets/1058419/8305270/4ed18938-19a5-11e5-9843-21a9bad361d0.jpg)

**Comment by gjb2048** [comment]
![2015-06-23 12_44_11-fonts](https://cloud.githubusercontent.com/assets/1058419/8305313/b31a5ac8-19a5-11e5-96e6-da3d0d16b46c.jpg)

**Comment by sim3083** [comment]
Hi Gareth

Thanks for looking into this... sorry for the late reply as we are on opposite ends of the earth (Australia).

I haven't noticed any issues in any other plugin/module 

The developer tab does not show any errors or missing links to fonts, and the css files load correctly as you have shown above and the rule is setting Oswald and Open Sans, but for some reason the fonts do not load.

If it cannot be replicated then so be it but I thought i would share in case it was a bug.

Regards

**Comment by gjb2048** [comment]
Hi Simon,

I'm sorry but if I cannot replicate the problem or see fault in the code, there is nothing I can do about it.  Unless, are you running on https?

Gareth

**Comment by gjb2048** [comment]
Nope, won't be that: https://github.com/gjb2048/moodle-theme_essential/blob/master/layout/includes/fonts.php#L28

**Comment by gjb2048** [comment]
Are there any 404 errors on the Network tab?

**Comment by sim3083** [comment]
Hey Gareth

No network Errors but it isnt importing the fonts in question, not even an attempt it seems

**Comment by gjb2048** [comment]
In that case, I have no idea.

**Comment by sim3083** [comment]
Ok no problem... 

Thanks for looking into it anyway

S

**Comment by richardschwarz** [comment]
Something I noticed in other parts was that if one was a google font and
the other was looking for a font that's not on the google repository (ie a
websafe,local font) then it won't load the google font.

**Comment by gjb2048** [comment]
Thanks for that Richard, but if you see the sequence of screen shots above, that statement is false.

**Comment by gjb2048** [comment]
P.s. Tested with fonts specified which are both on Google Fonts.

**Comment by richardschwarz** [comment]
No, that's cool. Checked on google fonts too. They are definitely both
there. Interesting. I'm using Google fonts on mine and not getting that
issue.
