### ISSUE TITLE
Essential user menu should use $CFG->customusermenuitems config (like standard themes)

### ISSUE THREAD

**Issue by tonyjbutler** [gjb2048/moodle-theme_essential#512]
In Moodle 2.9 there is a new user preferences editing page, /user/preferences.php, which contains links to /user/edit.php, /message/edit.php plus a bunch of other useful pages, including new ones like /user/language.php, /user/editor.php, /user/forum.php which now contain a lot of the settings that previously cluttered up the old profile editing page.

Currently this new user preferences page cannot be accessed via the Essential user menu.

There is also a new admin config setting called customusermenuitems, which can be configured by the site admin with links to populate the user menu (by default it contains links to the profile page, the grade book, the messaging preferences page and the new main user preferences page). It currently works with the Clean and More themes and any other themes using bootstrapbase as a parent theme, but not Essential. It seems fairly obvious that Essential should support this too.

**Comment by gjb2048** [comment]
What version of Essential are you testing with?

**Comment by tonyjbutler** [comment]
The latest stable 2.8 release and the latest dev version on master, both of which contain the same set of items in the user menu.

**Comment by gjb2048** [comment]
Thanks Tony, would you consider donating to fund this enhancement please?

**Comment by tonyjbutler** [comment]
I might be able to donate some time to look into it ;-)

**Comment by gjb2048** [comment]
Thanks Tony, a fully tested, commented and complete patch that passes through code checker would be nice :).

**Comment by tonyjbutler** [comment]
That's the only way I know :-)

**Comment by gjb2048** [comment]
Ok, '/user/preferences.php' implemented in: https://github.com/gjb2048/moodle-theme_essential/commit/ff1feced7d568c76dc334260e45b10cb7359732d - see: https://moodle.org/mod/forum/discuss.php?d=316279.

**Comment by gjb2048** [comment]
Ok, that now just leaves 'customusermenuitems'.  I'd need to research the changes, but initial estimate with testing is 3.5 hours.

**Comment by gjb2048** [comment]
Is this still wanted?

**Comment by tonyjbutler** [comment]
We don't need it anymore.
