### ISSUE TITLE
Upgrade to FontAwesome 4.4

### ISSUE THREAD

**Issue by mruasar** [gjb2048/moodle-theme_essential#519]
Not an issue, but FontAwesome 4.4 just released with 66 new icons.

**Comment by gjb2048** [comment]
Ok.

**Comment by gjb2048** [comment]
It is an 'issue' as it is an enhancement which means work for me.  It will get done when it does.

**Comment by gjb2048** [comment]
Implemented in https://github.com/gjb2048/moodle-theme_essential/commit/7fe2610d43a52f1d393064525cf19dd1fda8d232
