### ISSUE TITLE
Equation editor square root symbol.

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_essential#522]
The equation editor in quiz does not have a square root symbol?

**Comment by geoffrowland** [comment]
You can add the square root symbol to the Moodle configuration (though should probably be part of the default configuration):

Site administration > Plugins > Text editors > Atto HTML editor > Equation editor settings

However an 'empty' (i.e. without argument) LaTeX/MathJax square root symbol does not display correctly in the equation editor tool bar:
i.e. \sqrt  does NOT render correctly

You CAN use something like:
\sqrt{x}
\sqrt{\alpha}

or for a cube root:
\sqrt[3]{x}

You can also use the surd symbol
\surd

**Comment by gjb2048** [comment]
Thank you so much Geoff, really helpful :)
