### ISSUE TITLE
modal.fade

### ISSUE THREAD

**Issue by seyduna** [gjb2048/moodle-theme_essential#531]
In this line ".modal.fade{-webkit-transition:opacity .3s linear,top .3s ease-out;-moz-transition:opacity .3s linear,top .3s ease-out;-o-transition:opacity .3s linear,top .3s ease-out;transition:opacity .3s linear,top .3s ease-out;top:-25%}", .3s ease-out;top:-25% should be .3s ease-out;top:-100%. Because bootsraps elements deny headering button such as theme colours, this course button.

**Comment by gjb2048** [comment]
??????

**Comment by gjb2048** [comment]
It's original Bootstrap LESS: https://github.com/twbs/bootstrap/blob/v2.3.2/less/modals.less#L42 - so what do you want me to do about it?

**Comment by seyduna** [comment]
you can change top:-25% to top:-100%. When i use bootstap element which is a module of Moodle,  headering button such as theme colours, this course button is not working

**Comment by seyduna** [comment]
you can look at this mod : https://moodle.org/plugins/view/mod_bootstrapelements

**Comment by gjb2048** [comment]
BS 3.3.5 is the same: https://github.com/twbs/bootstrap/blob/v3.3.5/less/modals.less#L33

**Comment by gjb2048** [comment]
Who's to say that Essential code is wrong and https://moodle.org/plugins/view/mod_bootstrapelements is right?

**Comment by seyduna** [comment]
After i changed the code, it is working now

**Comment by gjb2048** [comment]
That means that core is 'wrong' too: https://github.com/moodle/moodle/blob/MOODLE_29_STABLE/theme/bootstrapbase/less/bootstrap/modals.less#L41-L44 - so therefore, raise in general here: https://moodle.org/mod/forum/view.php?id=46 and get enough positive responses to convince me to spend any time on this.

**Comment by seyduna** [comment]
Yes, you are right. It should be changed. 
Thank you very much for spending time.

**Comment by gjb2048** [comment]
Screen shots of 'headering button such as theme colours, this course button is not working' please as with respect I don't quite understand the English.

**Comment by gjb2048** [comment]
And, also with respect, I'm not spending time or fixing it until I'm convinced.

**Comment by gjb2048** [comment]
Ok, looked at https://moodle.org/mod/forum/discuss.php?d=319007 and there are no elements in the menu that have the 'modal' or 'fade' classes.

**Comment by gjb2048** [comment]
Replied on theme's forum.  Not convinced.  Need more information and evidence.  I am 'loathed' to change the BS LESS as it appears to be a Bootstrap Elements issue.

**Comment by gjb2048** [comment]
Replied again, still not convinced.  Please provide detailed steps to replicate.

**Comment by gjb2048** [comment]
Cannot replicate as a 'display: block' / 'display: none' is in operation, such as:

<div id="bootstrapelements1" class="modal fade in" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: block;">

when shown and:

<div id="bootstrapelements1" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">

when not shown.  Therefore the JavaScript is broken on your site and preventing the normal operation of the modal.  Therefore the 'top' fix is NOT a solution.

**Comment by gjb2048** [comment]
Humm.

**Comment by gjb2048** [comment]
I'll do this at some point at check M2.9 at the same time.

**Comment by seyduna** [comment]
thank you very much for your helping and time

**Comment by gjb2048** [comment]
BS3.5.5 has this fix: https://github.com/twbs/bootstrap/blob/v3.3.5/less/modals.less#L17 - BS2.3.2 does  not: https://github.com/twbs/bootstrap/blob/v2.3.2/less/modals.less#L24-L46.

**Comment by gjb2048** [comment]
Note to self:  Need to implement in Shoelace and Campus.

**Comment by seyduna** [comment]
Ok you are right. But i did not try Shoelace and Campus, yet.

**Comment by gjb2048** [comment]
Shoelace and Campus will have the issue as I wrote the code!

**Comment by seyduna** [comment]
ok, thank you very much!

**Comment by gjb2048** [comment]
Further investigation reveals that Bootstrap Elements is not using the 'hide' class with modals: https://moodle.org/mod/forum/discuss.php?d=319007#p1279691 - therefore a bug with it as first suspected.

**Comment by gjb2048** [comment]
Note:

Went to raise an issue on Moodle core, looked for an example: http://getbootstrap.com/2.3.2/javascript.html#modals - discovered that the modal has the extra class 'hide' which does a 'display: none'.  Therefore as previously suspected Bootstrap Elements is WRONG as not 'read the fine manual' and implemented the code correctly, thus in lib.php line 245:

```
'class' => 'modal fade',
```

should be:

```
'class' => 'modal hide fade',
```
