### ISSUE TITLE
PIWIK Analytics and IP addresses

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_essential#533]
Ref: https://moodle.org/mod/forum/discuss.php?d=319644

https://github.com/gjb2048/moodle-theme_essential/blob/MOODLE_28/layout/includes/piwik.php#L90
https://developer.piwik.org/guides/tracking-javascript-guide: _paq.push(['setUserId', 'USER_ID_HERE']);, to be easily added when there is a logged in user.

**Comment by scara** [comment]
TNX Gareth for having pinned this improvement from the Community!
Besides https://developer.piwik.org/guides/tracking-javascript-guide#user-id, the relevant doc to understand how the tracking, on the Piwik side, will change is: http://piwik.org/docs/user-id/.

**Comment by gjb2048** [comment]
Implemented in https://github.com/gjb2048/moodle-theme_essential/commit/e007821a1d0d614f7b2561c9fc405276355687bd
