### ISSUE TITLE
[[setting:abc]] variables are not processed when they are in customcss settings - fix attached

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#534]
[[setting:abc]] variables are not processed when they are in customcss settings.

**Fix**

In: lib.php lines 328-330 

```
// Set custom CSS.
$customcss = \theme_essential\toolbox::get_setting('customcss');
$css = theme_essential_set_customcss($css, $customcss);
```

move to: lib.php lines 222-224 

I don't know the reason for not processing the customcss, but if it is ok I would create a pull request.

**Comment by gjb2048** [comment]
The font settings are in the custom.css file: https://github.com/gjb2048/moodle-theme_essential/blob/master/style/custom.css#L7-L9 and they are correctly processed here: https://github.com/gjb2048/moodle-theme_essential/blob/master/lib.php#L369-L429.

**Comment by relecand** [comment]
"... or any other theme": BCU Theme ( https://moodle.org/plugins/view/theme_bcu ) does process [[setting:abc]] variables from the 'Custom CSS' box of the user interface. 

The advantage is: If you are a moodle admin without access to the server then you define your css in the Custom CSS box. "[[setting:abc]]" usage in Custom CSS box makes it more dynamic: when you change the setting "abc" you don't have to do this in the custom css again.

**Comment by gjb2048** [comment]
But... "[[setting:abc]]" still needs to be transformed by some other PHP elsewhere into something meaningful from a setting that has been created in settings.php.  Thus broken pencil territory.

**Comment by relecand** [comment]
Of course "[[setting:abc]]" is just an example. 

It could be [[setting:themeurlcolor]], [[setting:themecolor]], [[setting: textcolor]] etc. 

The transformation takes place here: https://github.com/gjb2048/moodle-theme_essential/blob/master/lib.php#L222-L326

If we put this: https://github.com/gjb2048/moodle-theme_essential/blob/master/lib.php#L328-L330 before the transformation https://github.com/gjb2048/moodle-theme_essential/blob/master/lib.php#L222-L326 it's done.

**Comment by relecand** [comment]
Example from a custom css in the "Custom CSS box" in BCU theme

```
.yui3-skin-sam .yui3-tab-selected .yui3-tab-label:hover
{
border-color: [[setting:maincolor]] !important;
background-color: [[setting:maincolor]] !important;
}
```
If I'm changing the maincolor of the theme on the moodle theme settings page, I don't have to change it in the custom css.

**Comment by gjb2048** [comment]
Ok, so in your example, what changes [[setting:maincolor]] into something meaningful?

**Comment by gjb2048** [comment]
Oh, ok, I get it.  Therefore this is an enhancement rather than a bug as nothing needs fixing.  The code is not wrong, it just does not support a given bit of functionality.

**Comment by relecand** [comment]
maincolor is a setting in BCU theme. In essential theme it's themecolor. So essential theme example:

```
.yui3-skin-sam .yui3-tab-selected .yui3-tab-label:hover
{
border-color: [[setting:***themecolor***]] !important;
background-color: [[setting:***themecolor***]] !important;
}
```
The transformation takes place here: https://github.com/gjb2048/moodle-theme_essential/blob/master/lib.php#L224

**Comment by relecand** [comment]
Yes - great :) I would call it also an enhancement - it's not a bug.

**Comment by relecand** [comment]
Should I submit a pull request?

**Comment by gjb2048** [comment]
Up to you.  It will go on the long list of enhancements for consideration after the M2.9 stable release.

**Comment by gjb2048** [comment]
To make this work 'theme_essential_process_css' needs to be refactored to be called by the set_custom_css from itself to process any 'known' setting values in the Custom CSS.  However this would only work on Essential settings and not pix:theme etc.  Thus more complex and needs investigating.

Cost estimate with research, development and testing: 3.5 hours+.  Fixed cost possible after research.

**Comment by gjb2048** [comment]
Is this still wanted?

**Comment by gjb2048** [comment]
No reply, closing.
