### ISSUE TITLE
Problem in core_renderer when outputs the messages menu containing HTML special chars

### ISSUE THREAD

**Issue by PatLemaire** [gjb2048/moodle-theme_essential#538]
Hello,
We encounter an issue on our customised 2.7.9.5.1 version of Essential theme.
Some of our users send HTML chars through messages during PHP courses and when they are connected the rendered pages come in a very bad shape.
To solve this problem I added a few modifications in core_rederer.php
L:462 => $messagecontent .= html_writer::span(htmlspecialchars($message->text), 'notification-text');
L:480 => $messagecontent .= html_writer::span(htmlspecialchars($message->text), 'msg-text');
I first thought the strings were filtered by the Moodle code, but... no :o( 
This is surely not the only change needed.
Regards
Patrick

**Comment by gjb2048** [comment]
Hi Patrick,

How can I replicate this situation as despite the bespoke code there seems to be an issue with support of such thing?

Cheers,

Gareth

**Comment by gjb2048** [comment]
Searched for info and only found this: https://moodle.org/mod/forum/discuss.php?d=32756

**Comment by PatLemaire** [comment]
Hi Gareth,

Two users have exchanged direct messages that contained "?>" and "<?php"  . Then everytime they were connected the page was blank. 

Cheers,
Patrick

**Comment by gjb2048** [comment]
Hi Patrick,

That sounds extremely dangerous! So you are saying that the code executed?

G

**Comment by PatLemaire** [comment]
I'm not sure but it gives a very bad result. I don't know how much this can be dangerous, but it bothers a lot !

P

**Comment by gjb2048** [comment]
Thanks for the info, need to think.

G

**Comment by PatLemaire** [comment]
I will follow your thoughts. I don't know if my modifications are safe but for now it saves my MOODLE ;o)

**Comment by gjb2048** [comment]
I think they are safe given: http://php.net/manual/en/function.htmlspecialchars.php

**Comment by gjb2048** [comment]
Looking at the spec and other core code, I think that 'htmlspecialchars($message->text, ENT_COMPAT | ENT_HTML401, 'UTF-8')' would be better.

**Comment by PatLemaire** [comment]
It seems better to me too. I'll change.

**Comment by gjb2048** [comment]
This is the fix in M2.9 branch: https://github.com/gjb2048/moodle-theme_essential/commit/ecda36682e9cd9bee6ca9a967066784543c25b5b - I may or not back port all the way to M2.7 because of the security risk.  At the moment I have no intention of progressing the M2.7 version any further.

**Comment by PatLemaire** [comment]
I will inform users of MOODLE that I know around me that use a version 2.7.
Thank you for this amazing theme! ;o)

Cheers,
Patrick

**Comment by gjb2048** [comment]
M2.8: https://github.com/gjb2048/moodle-theme_essential/commit/c6b5ea80ae9094b859a4084c8c1866dc3d1adfe6
