### ISSUE TITLE
Incorrect path found in thirdpartylibs

### ISSUE THREAD

**Issue by ewallah** [gjb2048/moodle-theme_essential#539]
When I run codechecker for other plugins, I receive 2 warnings:

Processing theme/essential/thirdpartylibs.xml for exclussions, incorrect /theme/essential/jquery/html5shiv_3_7_2.js path found. Please fix it
line 216 of /local/codechecker/locallib.php: call to debugging()
line 71 of /local/codechecker/index.php: call to local_codesniffer_get_ignores()

Processing theme/essential/thirdpartylibs.xml for exclussions, incorrect /theme/essential/jquery/fitvids_1_1.js path found. Please fix it
line 216 of /local/codechecker/locallib.php: call to debugging()
line 71 of /local/codechecker/index.php: call to local_codesniffer_get_ignores()

Moodle Version 2.9.2

**Comment by gjb2048** [comment]
:(

**Comment by gjb2048** [comment]
Why do people always report issues on a Tuesday and last thing on a Friday before the weekend?

**Comment by gjb2048** [comment]
Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/6359bb1456e953d34a5996231ca4e09d9057d6c1
