### ISSUE TITLE
"Save and continue editing" when creating quiz not floating

### ISSUE THREAD

**Issue by cdipe** [gjb2048/moodle-theme_essential#540]
When adding or editing a question in the question bank, the "Save Changes" and "Cancel" buttons float with the theme but the "Save changes and continue editing" button is still on the bottom of page. 
Using Moodle 2.8.7 and Essential 2.8.1.8 (Build: 2015061902)
![save question](https://cloud.githubusercontent.com/assets/14754240/10015922/82d29766-6123-11e5-8a68-614cc9d7a610.png)

**Comment by gjb2048** [comment]
Thanks for the information, does this happen in 2.8.1.10?

**Comment by gjb2048** [comment]
Hang on, I believe this is intentional from a previous 'issue'.

**Comment by gjb2048** [comment]
Ok, in the Clean theme, the buttons are in two separate areas:

![2015-09-22 11_35_52-editing a true_false question](https://cloud.githubusercontent.com/assets/1058419/10016347/369204e0-611e-11e5-8297-0a49371bdf77.jpg)

Therefore the core code that renders this is wrong as Essential only styles what is given to it.  Making the other area with that button floating too would lead to horrible issues.  Therefore, please raise a core Moodle tracker issue stating that the buttons should all be together on that page if one does not exist already.

**Comment by cdipe** [comment]
OK, thank you!
