### ISSUE TITLE
Issue with embedded mp3 player display

### ISSUE THREAD

**Issue by jonwitts** [gjb2048/moodle-theme_essential#542]
Hi there,

Using the beta 2.9 version of Essential here (version 2015062406) and I have noticed an issue with the display of the mp3 player when embedded into a page. I have tested the same page in both Clean and More themes and can confirm that the issue is not present there.

It appears as if Essential is adding an extra DIV element around the mp3 player object with an in-line style of "padding-top: 100%". This causing a large gap to created between the mp3 player object and the next item on the page. Disabling this style (using Firebug in Firefox 40.0.3 on Win 7 64bit) confirms that it removes this large space.

Please see screen grabs from all 3 themes to illustrate my point.

Jon
![mp3-player-clean-theme](https://cloud.githubusercontent.com/assets/8962587/10050759/d8ebfabe-6215-11e5-8473-ee058d0a3f24.png)
![mp3-player-essential-theme](https://cloud.githubusercontent.com/assets/8962587/10050760/d9007746-6215-11e5-93d4-6004b90c7869.png)
![mp3-player-more-theme](https://cloud.githubusercontent.com/assets/8962587/10050761/d91f5db4-6215-11e5-8edf-705330862064.png)

**Comment by gjb2048** [comment]
What specific version of the theme please Jon?

**Comment by gjb2048** [comment]
Ok, in 2.9.0.9 and above this will not happen because FitVids will no longer operate on mp3 files, see: #536.

**Comment by gjb2048** [comment]
V2.9.0.9 was version 2015062408, so please update.  But it does have one issue which is fixed here but not released: #541.
