### ISSUE TITLE
Alternative colors: box borders remain in standard color

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#543]
In color picker:

![screenshot 2015-09-23 18 15 04](https://cloud.githubusercontent.com/assets/5286499/10050979/51db68a2-621f-11e5-8a3b-092542394f0a.png)

Same here:

![screenshot 2015-09-23 18 08 12](https://cloud.githubusercontent.com/assets/5286499/10050992/6709a694-621f-11e5-94fc-a507d88d60c9.png)

**Comment by gjb2048** [comment]
What specific version of Essential please?

**Comment by relecand** [comment]
master branch from today: 2.9.0.10

**Comment by relecand** [comment]
The box borders are using the color that is defined in the themecolor setting. Just black for all alternative colors would also be ok.

**Comment by relecand** [comment]
Thank you for your work!

**Comment by gjb2048** [comment]
Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/57d9c770a6c5575a2820c3b78133ded28dc36aca
