### ISSUE TITLE
Alternative colors: background hover always black in standard color scheme

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#544]
Using the standard color scheme: the background of the color switcher is always black:

![screenshot 2015-09-23 18 21 04](https://cloud.githubusercontent.com/assets/5286499/10051073/f882d19a-621f-11e5-8f00-81ffd40ace7d.png)

Using the alternative color schemes: the background of the color switcher is ok:

![screenshot 2015-09-23 18 09 15](https://cloud.githubusercontent.com/assets/5286499/10051019/a32d2204-621f-11e5-9ade-acc89d9dd04d.png)

**Comment by gjb2048** [comment]
This is as currently intended.  I'm still thinking about which one is the correct one.

**Comment by gjb2048** [comment]
What specific version of Essential please?

**Comment by relecand** [comment]
master branch from today

**Comment by gjb2048** [comment]
Cannot replicate:

![2015-09-23 17_48_52-dashboard](https://cloud.githubusercontent.com/assets/1058419/10051840/819540a8-621b-11e5-8867-ba8de225c8fd.png)

Please ensure you have 'Purged all caches' before reporting.

**Comment by gjb2048** [comment]
![2015-09-23 17_50_43-dashboard](https://cloud.githubusercontent.com/assets/1058419/10051868/ac1465ca-621b-11e5-90b2-0f8a3b5e4aba.png)

**Comment by relecand** [comment]
Ok, please switch to Alternative color 1. Does the background change?

**Comment by gjb2048** [comment]
Yes:

![2015-09-23 18_03_26-dashboard](https://cloud.githubusercontent.com/assets/1058419/10052181/757d88f0-621d-11e5-9141-e566caf864b1.png)
![2015-09-23 18_02_59-dashboard](https://cloud.githubusercontent.com/assets/1058419/10052183/75a55f2e-621d-11e5-82fc-5f6eb16f902c.png)

**Comment by relecand** [comment]
Ok, this is the bug I reported. 

![screenshot 2015-09-23 19 10 43](https://cloud.githubusercontent.com/assets/5286499/10052394/f151610a-6226-11e5-99d0-479c23276539.png)

**Comment by relecand** [comment]
It is "always black" in my installation. The bug is more correctly: the different background colors of the color switcher in the standard color scheme.

**Comment by relecand** [comment]
Thank you!
