### ISSUE TITLE
course icons of  „my courses“ menu disappear

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#545]
![screenshot 2015-09-23 18 23 48](https://cloud.githubusercontent.com/assets/5286499/10051185/a7181648-6220-11e5-97a7-db8098e99bbe.png)

**Comment by relecand** [comment]
They disappear on the Dashboard / mymoodle site. They don't disappear in the menu in the course view.

**Comment by gjb2048** [comment]
What specific version of Essential please?

**Comment by gjb2048** [comment]
Are you using the standard colours or alternatives?  Have you changed the settings from the defaults?

**Comment by relecand** [comment]
master branch from today: 2.9.0.10

**Comment by relecand** [comment]
It does not work in both: standard colours and alternatives (on the mymoodle site).

**Comment by gjb2048** [comment]
Mymoodle site?

**Comment by gjb2048** [comment]
Cannot reproduce:

![2015-09-23 17_52_19-dashboard](https://cloud.githubusercontent.com/assets/1058419/10051949/0926e03a-621c-11e5-91e5-b520cef0de4a.png)
![2015-09-23 17_52_49-dashboard](https://cloud.githubusercontent.com/assets/1058419/10051950/0928a136-621c-11e5-8580-903fc538dee6.png)

Was a known issue during past development, please ensure you do a 'Purge all caches' before reporting.

**Comment by gjb2048** [comment]
![2015-09-23 17_55_31-dashboard](https://cloud.githubusercontent.com/assets/1058419/10052012/71b1aa86-621c-11e5-9d66-76b43dc77578.png)

**Comment by relecand** [comment]
Of course I did 'Purge all caches' before. Hm - will try to fix it.
