### ISSUE TITLE
Alternative colors: scroll bar color does not change (in Chrome and Safari)

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#546]
In Firefox the scrollbar is grey in all color schemes. In Chrome the color of the scrollbar is the one of the standard scheme (in all alternative color schemes).

![screenshot 2015-09-23 20 03 59](https://cloud.githubusercontent.com/assets/5286499/10053911/d441b68e-622e-11e5-813e-e39e78e85152.png)

![screenshot 2015-09-23 20 04 19](https://cloud.githubusercontent.com/assets/5286499/10053925/dfb20924-622e-11e5-9789-025ac891e25b.png)

**Comment by relecand** [comment]
If it is grey like in Firefox it would be ok.

**Comment by relecand** [comment]
Same in Safari

**Comment by gjb2048** [comment]
Looked at this whilst doing #543 and #544 - due to the CSS used to style the scroll bars and the body class used to select the alternative colours, this is impossible.

**Comment by relecand** [comment]
Is it possible to have the same color (e.g. grey) for the scrollbar in all alternative color schemes?

**Comment by gjb2048** [comment]
Yes, but you can do that on your own installation by removing the settings/custom.less and recompiling the CSS.

**Comment by gjb2048** [comment]
In re-reading that Jon, then you can either remove it completely or set the colour you want in that file.

**Comment by relecand** [comment]
Ok, thank you!

**Comment by relecand** [comment]
This is a fix that I added into the custom css box of the essential theme:

::-webkit-scrollbar {
  background-color: transparent;
}
::-webkit-scrollbar-track {
  background-color: transparent;
}
::-webkit-scrollbar-track-piece {
  background-color: transparent;
}
::-webkit-scrollbar-thumb {
  background-color: grey;
  border: 0px;
}
::-webkit-scrollbar-corner {
  background-color: transparent;
}

**Comment by relecand** [comment]
![screenshot 2015-09-23 22 48 50](https://cloud.githubusercontent.com/assets/5286499/10058348/4d0f94da-6245-11e5-886a-0d2cf79a9a6e.png)
