### ISSUE TITLE
Alternative colors: background hover on the frontpage

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#547]
In standard theme it works (white in my case). In the alternative colors the themecolor of the alternative color scheme is used: alternativethemecolor1, alternativethemecolor2 etc

This is my workaround:

.course_category_tree .category[data-categoryid]:hover {
 background-color: #ffffff !important;
}

![screenshot 2015-09-24 10 50 18](https://cloud.githubusercontent.com/assets/5286499/10069157/8235cc0a-62aa-11e5-9299-381509eec783.png)

![screenshot 2015-09-24 10 49 47](https://cloud.githubusercontent.com/assets/5286499/10069163/89ba4744-62aa-11e5-82de-845ab3a89ec9.png)

**Comment by gjb2048** [comment]
Ok, are you on a mission and working to a deadline?

**Comment by relecand** [comment]
Yes - intensive testing.

**Comment by gjb2048** [comment]
Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/9bf6e3021216abafba34b6026ab49b0952936c1b
