### ISSUE TITLE
Slideshow: slidebuttoncolor does not have an effect

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#548]
The color that is defined in slidebuttoncolor is not set in the standard color scheme.

![screenshot 2015-09-24 11 17 07](https://cloud.githubusercontent.com/assets/5286499/10069729/576a6a04-62ae-11e5-89fa-fa0f70404157.png)

![screenshot 2015-09-24 11 17 16](https://cloud.githubusercontent.com/assets/5286499/10069732/5ef42774-62ae-11e5-9507-0f30c160bd44.png)

**Comment by gjb2048** [comment]
Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/9bf6e3021216abafba34b6026ab49b0952936c1b
