### ISSUE TITLE
Mobile layout: Layer fills the whole page

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#549]
This seems to be a quite new bug (in the last updates in the master branch, I think).

![mobile_err_1](https://cloud.githubusercontent.com/assets/5286499/10096219/08315962-6370-11e5-9a25-9b5d98559587.png)

![mobile_err_2](https://cloud.githubusercontent.com/assets/5286499/10096225/0ca5aea8-6370-11e5-8572-71a68bb87421.png)

**Comment by gjb2048** [comment]
Ok, this is a workaround for #530 - I have literately spent days and days trying to work out why the second time you click on the button the changing of the 'overflow' attribute kills the 'onclick' event attached to that element.

Refs:
https://moodle.org/mod/forum/discuss.php?d=318870
https://tracker.moodle.org/browse/MDL-51201
