### ISSUE TITLE
Breadcrumb menu "eaten away" when tighter window

### ISSUE THREAD

**Issue by cdipe** [gjb2048/moodle-theme_essential#550]
Is this a known problem: When using other breadcrumb styles than "Simple", the breadcrumb menu disappears gradually when the window is tightened. In my iPhone tha means most of the menu is gone all the time. I have made a video showing the problem.
https://play.lnu.se/media/t/0_0oqxm1ep
Using Moodle 2.8.7 and Essential 2.8.1.10 (Build: 2015061903)

**Comment by gjb2048** [comment]
Thin is easy to fix, fancy has no solution yet, any ideas?

**Comment by gjb2048** [comment]
Going to make fixes in M2.9 version and back-port at some point as other fixes there already and need to save admin-faff.

**Comment by cdipe** [comment]
Sorry, no ideas. I'd ask our tech developers to have a go at it, but they're overbooked for a long time ahead.

**Comment by gjb2048** [comment]
Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/39e18873862d13d1a2b8d29714c993354206b87c

**Comment by gjb2048** [comment]
Will back-port to M2.8 version at some point.

**Comment by cdipe** [comment]
Great, thanks!
