### ISSUE TITLE
Private Files: Still active when it is deactivated in the repository settings

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#551]
If private files are deactivated in moodle.url/admin/repository.php there is still an entry in the user menu.

![screenshot 2015-09-28 10 39 56](https://cloud.githubusercontent.com/assets/5286499/10131103/25d50a6c-65ce-11e5-9760-86dbe3fd7c18.png)

**Comment by gjb2048** [comment]
What are the steps to replicate please?

**Comment by relecand** [comment]
Hi Gareth,

1. Go to yourmoodle.url/admin/repository.php and deactivate "Private Files"

![screenshot 2015-09-28 11 27 43](https://cloud.githubusercontent.com/assets/5286499/10131926/009f774a-65d4-11e5-8926-2f87df337e7d.png)

2. Open the user menu and "Private files" entry is still there

![screenshot 2015-09-28 11 28 28](https://cloud.githubusercontent.com/assets/5286499/10131957/170806b4-65d4-11e5-936f-9364cb86cb7d.png)

**Comment by gjb2048** [comment]
Thanks.  Currently ill, will fix when can.

**Comment by relecand** [comment]
Get well soon!

**Comment by gjb2048** [comment]
Looking at this, there is no warning when manually accessing 'user/files.php' anyway, which is a core fault.

**Comment by gjb2048** [comment]
![2015-09-29 13_04_20-dashboard - internet explorer](https://cloud.githubusercontent.com/assets/1058419/10163481/26887d26-66ab-11e5-9667-ce4437d84bdf.png)
![2015-09-29 13_07_05-private files - internet explorer](https://cloud.githubusercontent.com/assets/1058419/10163483/26a6c33a-66ab-11e5-909f-94822042879d.png)
![2015-09-29 13_06_38-dashboard - internet explorer](https://cloud.githubusercontent.com/assets/1058419/10163482/268ca360-66ab-11e5-83b2-5c1b56115c74.png)

**Comment by gjb2048** [comment]
Oh no.... its more complicated than that: https://docs.moodle.org/29/en/Private_files#Preventing_access_to_Private_files - ref: MDL-47467

**Comment by relecand** [comment]
One way to check the capability moodle/user:manageownfiles

**Comment by gjb2048** [comment]
Already do: https://github.com/gjb2048/moodle-theme_essential/blob/master/classes/core_renderer.php#L747 - so why is this not working for you?

**Comment by gjb2048** [comment]
Humm, ok, might need:

```
$usercontext = context_user::instance($user->id);
```

instead.

**Comment by relecand** [comment]
deactivating the capability moodle/user:manageownfiles works for me.

**Comment by gjb2048** [comment]
Without changing the code?

**Comment by relecand** [comment]
Yes, I changed the permission moodle/user:manageownfiles for the role "Authenticated user" - here: moodle.url/admin/roles/manage.php

This works, but I thought just deactivating the private files repository would be enough. This changed in the last Moodle releases. I think, we can close this issue.

**Comment by gjb2048** [comment]
Can replicate as stated on: https://docs.moodle.org/29/en/Capabilities/moodle/user:manageownfiles - code is correct.
