### ISSUE TITLE
Section highlighter in topic course format

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#553]
**Click here (in topic course format)**
-------------

![screenshot 2015-09-30 20 26 28](https://cloud.githubusercontent.com/assets/5286499/10202588/e1aa0b7c-67b1-11e5-861b-7be0baa15fd8.png)

**In standard color scheme: it's too close to the text**
-------------

![screenshot 2015-09-30 20 22 18](https://cloud.githubusercontent.com/assets/5286499/10202609/011d4686-67b2-11e5-8133-0089b5e26852.png)

**In the alternative color schemes: the outer box looks fine - but the inner box is still there**
-------------

alternative color theme 2:

![screenshot 2015-09-30 20 22 46](https://cloud.githubusercontent.com/assets/5286499/10202667/44d410ee-67b2-11e5-8070-d644a485508f.png)

alternative color theme 3:

![screenshot 2015-09-30 20 22 38](https://cloud.githubusercontent.com/assets/5286499/10205351/0434be12-67c1-11e5-9f0c-a61157635fdc.png)

**Comment by gjb2048** [comment]
Oh poop is there no end to the bugs in this theme :(

**Comment by relecand** [comment]
I think I have seen this bug a year ago, but didn't report.  Now the theme becomes better and better.

**Comment by gjb2048** [comment]
Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/87b02df07a9b41d17d231a82bfc779a633aff746
