### ISSUE TITLE
Slide interval: settings are ignored

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#554]
Hi Gareth,

thanks for the last fix. Here comes the next issue - sorry ...

The slider intervall settings are ignored. The slides always switching with the same speed.

![screenshot 2015-10-01 19 21 35](https://cloud.githubusercontent.com/assets/5286499/10228275/03667ac8-6872-11e5-8a3e-3f53380d80f1.png)

**Comment by gjb2048** [comment]
That was working the last time I tested it.

**Comment by relecand** [comment]
Tested in FF and Chrome

**Comment by gjb2048** [comment]
Essential is tooooo complex.  Definitely need another person as a 'pair programmer' in the 'extreme programming' sense.

**Comment by gjb2048** [comment]
Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/99a29c8cae12f335b15ec67a354a975db0c6b1fd
