### ISSUE TITLE
User Image not Appearing

### ISSUE THREAD

**Issue by martinvivek** [gjb2048/moodle-theme_essential#555]
User image is not appearing in the profile page. in the Essential theme 2.9.1 but in the clean theme it is appearing.

**Comment by martinvivek** [comment]
It is Moodle 2.9.2+ and essential 2.9.1

**Comment by gjb2048** [comment]
Screen shot evidence please so I know exactly where to look.

**Comment by gjb2048** [comment]
If you mean this:

![2015-10-02 11_15_23-admin user_ public profile](https://cloud.githubusercontent.com/assets/1058419/10244415/0040c8fa-68f7-11e5-8f75-4fb70fbe64f3.png)

Then it is not a bug, but a design decision.  I've decided not to implement the quite frankly 'horrible' page context header code.  Just because it does not look like Clean does not mean its a bug.

**Comment by martinvivek** [comment]
Yeah i was pointing this issue, but if the image is not visible then where can the user able see their/others profile picture?

**Comment by martinvivek** [comment]
Yeah i was pointing this issue, but if the image is not visible then where can the user able see their/others profile picture?

**Comment by martinvivek** [comment]
Yeah i was pointing this issue, but if the image is not visible then where can the user able see their/others profile picture?

**Comment by gjb2048** [comment]
Well...

When editing their profile.
In the user menu on the navbar on the right in LTR.  Which is on almost all pages!
In forums.
When messaging.
.....

Need I go on?

**Comment by martinvivek** [comment]
The user can seen their own Profile pictures/Name is not even necessary, How the Others can see, As a Teacher /Admin/Other roles they can't see, To see who he/she is the only way to seen in their messaging / by editing their profile. its wasting time also. Its up to you to include. and i agree with you the page will be not be that much good. at least an patch you can provide / any workaround for the profile picture / Full Name to appear in the body not in the header. Hope you can understand

**Comment by gjb2048** [comment]
I do, what specific code changes do you suggest?  Do you have a patch for this?

**Comment by gjb2048** [comment]
Ok, looked into this further.... and as a student on a course, they can see the user picture all over the place!  Easily!.....

![2015-10-04 12_25_32-cd_ participants](https://cloud.githubusercontent.com/assets/1058419/10267643/c28e414c-6a93-11e5-82a5-b0cb6081f9a6.png)
![2015-10-04 12_28_21-code_ personal profile_ admin user](https://cloud.githubusercontent.com/assets/1058419/10267644/c2904848-6a93-11e5-8e7e-62eda2646c4d.png)
![2015-10-04 12_27_25-news forum](https://cloud.githubusercontent.com/assets/1058419/10267645/c29152e2-6a93-11e5-8f74-de12cd9142ac.png)

Thus your argument that they cannot see the user image on the profile of another user is invalid.  Other roles as clearly shown, CAN SEE!!!!

For the record, its NOT up to me to 'include' the code is GPLv3, I have no obligation to include.

It seems to me that the page in question is only for the current user, thus they can already see themselves in the places already mentioned, especially the user menu.
