### ISSUE TITLE
Course management: course (sub-)categories are not indented

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#556]
In Essential theme:

![screenshot 2015-10-05 16 41 26](https://cloud.githubusercontent.com/assets/5286499/10283555/5b66981e-6b80-11e5-8ec5-1c585b594e30.png)

In Clean theme:

![screenshot 2015-10-05 16 42 10](https://cloud.githubusercontent.com/assets/5286499/10283664/ea0dbd18-6b80-11e5-9036-b7b3e6f9e838.png)

How to reproduce:
1. Create some categories und sub-categories in moodle.url/course/management.php
2. You will see that the sub-categories are not in the correct level

**Comment by gjb2048** [comment]
Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/53a3ddd5b98edbc0221da98002b016053d2fe9fb
