### ISSUE TITLE
Mobile layout with Android smartphones: Page jumps upwards

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#562]
The page jumps to the top of the site (frontpage), if you want to scroll down.

**Comment by gjb2048** [comment]
I don't have an Android device, so no way of replicating.

**Comment by jojoob** [comment]
This is also reproducible with the emulation function of the Chrome Developer Tools.

![screen shot 2015-10-19 at 16 12 19](https://cloud.githubusercontent.com/assets/4180675/10580101/356f68b4-767c-11e5-9d65-923cf12f639c.png)

**Comment by mkpelletier** [comment]
I am on Android 5.1 Lolipop with Latest Chrome browser, using Moodle 2.8.6+ and Essential 2.8.1.8 (Build: 2015061902).  I do not experience this behaviour.  Please ensure you always reference your Moodle version, Essential version, and in the case of Android, your OS and browser.  It is difficult in the extreme to pin down these things with out specifics such as these.

**Comment by relecand** [comment]
Moodle 2.9.2+, Essential 2.9.1.2

**Comment by relecand** [comment]
Short intro for the Chrome Developer Tools: https://developer.chrome.com/devtools/docs/device-mode#enable-device-mode

You can also toggle device mode on and off using the keyboard shortcut:
Ctrl+Shift+M (or Cmd+Shift+M on Mac).

**Comment by gjb2048** [comment]
Ok, with respect I know how to use Chrome Developer Tools, however: please explain in much more detail on how to replicate.

**Comment by relecand** [comment]
1. Update to the latest Chrome version on your computer
2. Go to your moodle site
3. Open Chrome Developer Tools
4. Enable device mode: Ctrl+Shift+M (or Cmd+Shift+M on Mac)
5. Select a Andoid device (like Google Nexus 5 or Samsung Galaxy S4)
6. Scroll down

Short video: https://youtu.be/F39GWuzY1Ms

**Comment by gjb2048** [comment]
Thanks, currently busy with work ATM and will look at some point.

**Comment by relecand** [comment]
Ok, thank you, Gareth. Will also investigate.

**Comment by relecand** [comment]
I was not able to reproduce the bug on the test system and on another productive system. After a git pull the bug disappeared. The fix was in a commit after 5th October (don't know which one). Now it works.
