### ISSUE TITLE
Alternative colors: Section highligther in week course format

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#565]
![screenshot 2015-10-22 12 56 37](https://cloud.githubusercontent.com/assets/5286499/10687701/52db8c48-796f-11e5-80f4-51c360f6ea6b.png)

**Comment by relecand** [comment]
Similar to: https://github.com/gjb2048/moodle-theme_essential/issues/553

**Comment by gjb2048** [comment]
Fixed in https://github.com/gjb2048/moodle-theme_essential/commit/6f15ae55aa4186306e4a0735d918c4f321bb0def
