### ISSUE TITLE
Tidy up Marketing spot mark-up and CSS.

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_essential#566]
Ref: https://moodle.org/mod/forum/discuss.php?d=322307

Mark-up is spread across two rows and uses big padding and negative margin to make it look like a block, well ugly.

**Comment by gjb2048** [comment]
Started here: https://github.com/gjb2048/moodle-theme_essential/blob/d946b14b22cb02b9d7a615a46417db04c002b2c2/layout/includes/marketingspots.php

**Comment by lazydaisy** [comment]
Who added the extra button?
What is this Toolbox?

**Comment by gjb2048** [comment]
1. David.
2. An auto loaded class (https://docs.moodle.org/dev/Automatic_class_loading) with static methods as a collection of helpers to the theme.
