### ISSUE TITLE
Wrong icon appearing in RTL in collapsed tree items in sideblocks

### ISSUE THREAD

**Issue by nzn-openapp** [gjb2048/moodle-theme_essential#567]
When in RTL, tree items in sideblocks show caret when collapsed instead of folder icon.
Solution: remove the rule:
```
.collapsed .tree_item.branch:before{font-family:FontAwesome;content:"\f053";margin-left:5px}
```
which only appears in essential-rtl.css

**Comment by gjb2048** [comment]
Thanks for the report.  What version of Essential please?  The CSS is generated from the LESS, so what LESS file is it please?

**Comment by nzn-openapp** [comment]
Looks like it's here:
less/essential/blocks.less line 94
```
.collapsed .tree_item.branch:before {
  font-family: FontAwesome;
  /*@replace: "\f053"*/content: "\f07b";
  margin-right: 5px;
}
```
I.e. f07b appears normally, but f053 appears in RTL which it shouldn't.

**Comment by gjb2048** [comment]
Thanks.  What version of Essential please?

**Comment by nzn-openapp** [comment]
2.9.1.1 (Build: 2015062411)

**Comment by gjb2048** [comment]
Fixed in https://github.com/gjb2048/moodle-theme_essential/commit/b7fc7df7e7b359bf61b1557933acbdf07589d774
