### ISSUE TITLE
Missing AJAX animation when opening Site administration in the ADMINISTRATION side-block

### ISSUE THREAD

**Issue by nzn-openapp** [gjb2048/moodle-theme_essential#568]
Version 2.9.1.1 (Build: 2015062411)
In the ADMINISTRATION block, when in the home page and clicking "Site administration", there is no indication that the menu is loading, i.e. the gif that shows in the default moodle theme is hidden. This is because - rightly so - all non-font icons have been made hidden. This, though causes confusion that the menu is not loading.
Here is a nice hourglass animation I have put together in CSS that might solve this. I guess it should go in less/essential/blocks.less maybe right after line 98:
```
.jsenabled .block_settings .block_tree .tree_item.branch.loadingbranch:before {
    font-family: FontAwesome;
	content: "\f250";
	-moz-animation: spin 1s infinite ease-in-out;
	-webkit-animation: spin 1s infinite ease-in-out;
	-o-animation: spin 1s infinite ease-in-out;
	animation: spin 1s infinite ease-in-out;
}

@-moz-keyframes spin {
    0% {-moz-transform: rotate(0deg);}
    100% {-moz-transform: rotate(180deg);}
}

@-webkit-keyframes spin {
    0% {-webkit-transform: rotate(0deg);}
    100% {-webkit-transform: rotate(180deg);}
}

@-o-keyframes spin {
    0% {-webkit-transform: rotate(0deg);}
    100% {-webkit-transform: rotate(180deg);}
}

@keyframes spin {
    0% {-webkit-transform: rotate(0deg);}
    100% {-webkit-transform: rotate(180deg);}
}
```
Otherwise thanks and well done for a great theme!

**Comment by gjb2048** [comment]
Fixed in https://github.com/gjb2048/moodle-theme_essential/commit/e586e0031fd68dbf7d4b4d382c5fe3566ec38401 - always more involved than you think.

**Comment by gjb2048** [comment]
Note: No spinning in IE9 because it does not support 'keyframes'.
