### ISSUE TITLE
Inactive category icon look all dimmed

### ISSUE THREAD

**Issue by nzn-openapp** [gjb2048/moodle-theme_essential#569]
In 2.9.1.1 (Build: 2015062411)
In category view, the category being inactive is not immediately obvious (only the writing is different).
In less/essential/categories.less maybe change:
```
    .category.dimmed_category {
      border-color: #AAAAAA;
    }
```
to:
```
    .category.dimmed_category {
      border-color: #AAAAAA;
      .opacity(50);
    }
```

**Comment by gjb2048** [comment]
How does the difference differ to the Clean theme?

**Comment by nzn-openapp** [comment]
It's like this: in the clean theme there is one, ominpresent element in the category div - the text. When it's disabled, it's gray and it's status is obvious. But in Essential the omnipresent element is the folder, and that is always equal to [\[setting:themeiconcolor]] (as per less/essential/settings/theme-admin.less) whether disabled or not, while the text color difference is not so striking.
If we wanted to emulate the obviousness that "clean" presents a bit more closely maybe we would make the folder also be gray instead of transparent by doing
```
body .dimmed_category  i {color: #AAA}
```
but I just suggested something that I think might look at bit more stylish.
Come to think of it maybe we would implement my original suggestion as
```
body .dimmed_category  i {.opacity(50)}
```
Your call.

**Comment by gjb2048** [comment]
Transpires that the category icon is wrong colour for dimmed, so bug.

**Comment by gjb2048** [comment]
Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/fe0e256d69c384cfaebc2e3667f7cdb87a7b7af2
