### ISSUE TITLE
Wrong icon color in navbar (login icon)

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#573]
Hi Gareth,

![screenshot 2015-11-06 19 21 29](https://cloud.githubusercontent.com/assets/5286499/11005084/21e8eac4-84bc-11e5-9f11-cb17471eab0c.png)

```
body i.fa {
    color: #000;
}
```

![screenshot 2015-11-06 19 21 36](https://cloud.githubusercontent.com/assets/5286499/11005100/3cd3b620-84bc-11e5-90b7-96aa223210d2.png)

```
body i.fa {
    color: inherit;
}
```

**Comment by gjb2048** [comment]
Standard colour scheme is wrong.

**Comment by gjb2048** [comment]
Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/681b6a47e816b6955d5135ee51559b2194b8c618
