### ISSUE TITLE
Color for icons on header not set properly

### ISSUE THREAD

**Issue by jojoob** [gjb2048/moodle-theme_essential#577]
The color of the icons on the right header side is the same as the background color (if not hovering).
<img width="328" alt="screen shot 2015-12-07 at 11 51 00" src="https://cloud.githubusercontent.com/assets/4180675/11625145/e3d6e350-9cd8-11e5-8fb8-8d7ad03ed73f.png">
<img width="234" alt="screen shot 2015-12-07 at 11 50 27" src="https://cloud.githubusercontent.com/assets/4180675/11625146/e5bed77c-9cd8-11e5-884b-60d86ba44b81.png">

There is a less/CSS rule that applies for the icons on the left side (`.navbar .navbar-inner .nav>li.dropdown>a i.fa`) but not for the right side (because they lack the 'dropdown' class).

Maybe it's a good idea to set the color for all icons on the navbar: `.navbar .navbar-inner .nav i.fa`.

**Comment by jojoob** [comment]
theme_essential version: 2.9.1.4 (Build: 2015062414) 86bedad201657128e11a4a044e53c92421324c7f

Moodle version: 2.9.3 (Build: 20151109)

**Comment by gjb2048** [comment]
Pending for a short while #576 to be resolved.
