### ISSUE TITLE
Message preview shows <br />

### ISSUE THREAD

**Issue by emanuelis** [gjb2048/moodle-theme_essential#579]
![image](https://cloud.githubusercontent.com/assets/329596/11700277/8f064b22-9ed1-11e5-9b40-3851d03efc60.png)

**Comment by whymiss** [comment]
We have the same thing. I thought it was related to Issue #538 which is closed and fixed but now I know its not just us. I'm not great at understanding all the code and conversations around it ....was 538 about just stopping the code from executing only and leaving the actual code displaying?
Regards,
Yvonne

**Comment by whymiss** [comment]
Forgot to say....We are using Moodle 2.9,3+ and Essential 2.9.1.3

**Comment by gjb2048** [comment]
That is probably because the user is sending markup.

**Comment by whymiss** [comment]
If I create a new message and use the enter key to drop to the next line it displays properly in the actual messages page but the same message in the notifications menu has the <br> displayed. Is that what you are expecting? Never used to do that in our older version (we skipped a few versions)

**Comment by gjb2048** [comment]
Thanks for the information.  It never happened in the older version because of improvements to make things better.

**Comment by gjb2048** [comment]
#538 related.
