### ISSUE TITLE
navigation block and activities

### ISSUE THREAD

**Issue by halbo5** [gjb2048/moodle-theme_essential#580]
Hi,

With some activities (for example assignments), the navigation menu and the admin menu are shown at the bottom of the page and not in the left column.
Is it wanted or is it a bug ?
I prefer having the blocks always at the same place.
![screenshot](https://cloud.githubusercontent.com/assets/674826/11742888/8201fa1a-a003-11e5-8c2e-221461c6fd3c.png)
 
Best,

Alain

**Comment by gjb2048** [comment]
This is intentional for screen space reasons.
