### ISSUE TITLE
Possible theme interference with Feedback module 'codingerror'

### ISSUE THREAD

**Issue by ghrich** [gjb2048/moodle-theme_essential#581]
Hi Gareth,

Have upgraded to 2.9.1.4 today and have an issue with the Feedback module... When users attempt to navigate to a course that is defined as a Feedback course I get the following exception:

Error: codingerror

The debug information is as follows:

Debug info: Argument 1 passed to theme_essential\output\core_renderer::render_tabtree() must be an instance of theme_essential\output\tabtree, instance of tabtree given, called in [dirroot]\lib\outputrenderers.php on line 188 and defined 
Error code: codingerror

Stack trace: •line 411 of \lib\setuplib.php: coding_exception thrown
•line 1001 of \theme\essential\classes\output\core_renderer.php: call to default_error_handler()
•line 188 of \lib\outputrenderers.php: call to theme_essential\output\core_renderer->render_tabtree()
•line 3605 of \lib\outputrenderers.php: call to renderer_base->render()
•line 2852 of \lib\weblib.php: call to core_renderer->tabtree()
•line 90 of \mod\feedback\tabs.php: call to print_tabs()
•line 152 of \mod\feedback\view.php: call to require()

Is this theme related? I've been assured the course was working on Friday last week and the only upgrade I have carried out is the step upgrade from 2.9.1.3 of Essential this morning.

Thanks,

Richard

**Comment by gjb2048** [comment]
Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/cb8164cff88914c987d17287dae4b81ee7a1d6db this morning.  Please read: https://moodle.org/mod/forum/discuss.php?d=324677#p1304385

**Comment by ghrich** [comment]
Excellent! Thank you as always!
