### ISSUE TITLE
Moodle Slide Show background color INOP

### ISSUE THREAD

**Issue by amwalding** [gjb2048/moodle-theme_essential#582]
The slide show background color is set as shown on the first attached file.

![screen shot 2015-12-14 at 10 21 53 am](https://cloud.githubusercontent.com/assets/9512659/11786510/a1e17cd4-a24c-11e5-98bd-6e10ba096d82.png)

However, the background does now show up on the actual front page: second attached file

![screen shot 2015-12-14 at 10 23 52 am](https://cloud.githubusercontent.com/assets/9512659/11786542/d0026506-a24c-11e5-9c72-eaf0032d58ae.png)

**Comment by gjb2048** [comment]
Hi Andy,

If you look at the information for that setting, it states "What colour the slide caption background should be. Does not apply to 'Beside' slide caption option." and you are using the 'Beside' option for placement of the caption.

Gareth

**Comment by amwalding** [comment]
OK - but wait...here is a screen shot from 2.8: it shows a light background
behind the slide show...where did that go?[image: Inline image 1]

On Mon, Dec 14, 2015 at 10:31 AM, Gareth J Barnard <notifications@github.com
> wrote:

> Closed #582 <https://github.com/gjb2048/moodle-theme_essential/issues/582>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gjb2048/moodle-theme_essential/issues/582#event-491174849>
> .
>



-- 
*Andrew M. Walding*
CellStream, Inc.
Tel & Fax: 866-659-1014   Cell: 214-405-3708
Skype ID: awalding   Twitter: @awalding
http://www.cellstream.com
http://www.netscionline.com

**Comment by gjb2048** [comment]
That's still working: 
![2015-12-14 16_47_54-moodle 29 - with a really long name for the purpose of testing really long names](https://cloud.githubusercontent.com/assets/1058419/11787230/8fb4a99c-a282-11e5-9eed-e5c17dd41995.png)

**Comment by gjb2048** [comment]
And still is as it always was with that option:
![2015-12-14 16_50_12-on-line school of network sciences](https://cloud.githubusercontent.com/assets/1058419/11787324/f50cfb6e-a282-11e5-8300-3cb311aa2c15.png)

**Comment by amwalding** [comment]
Ok.  They look very different to me....I must have something else wrong
elsewhere.

On Mon, Dec 14, 2015 at 10:49 AM, Gareth J Barnard <notifications@github.com
> wrote:

> That's still working:
> [image: 2015-12-14 16_47_54-moodle 29 - with a really long name for the
> purpose of testing really long names]
> <https://cloud.githubusercontent.com/assets/1058419/11787230/8fb4a99c-a282-11e5-9eed-e5c17dd41995.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gjb2048/moodle-theme_essential/issues/582#issuecomment-164491448>
> .
>



-- 
*Andrew M. Walding*
CellStream, Inc.
Tel & Fax: 866-659-1014   Cell: 214-405-3708
Skype ID: awalding   Twitter: @awalding
http://www.cellstream.com
http://www.netscionline.com

**Comment by gjb2048** [comment]
With "OK - but wait...here is a screen shot from 2.8: it shows a light background
behind the slide show...where did that go?[image: Inline image 1]" no image attached.

**Comment by amwalding** [comment]
Its OK - I found another way to eliminate the issue.  I simply changed the
image file.

On Mon, Dec 14, 2015 at 10:52 AM, Gareth J Barnard <notifications@github.com
> wrote:

> With "OK - but wait...here is a screen shot from 2.8: it shows a light
> background
> behind the slide show...where did that go?[image: Inline image 1]" no
> image attached.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gjb2048/moodle-theme_essential/issues/582#issuecomment-164492532>
> .
>



-- 
*Andrew M. Walding*
CellStream, Inc.
Tel & Fax: 866-659-1014   Cell: 214-405-3708
Skype ID: awalding   Twitter: @awalding
http://www.cellstream.com
http://www.netscionline.com

**Comment by 3-bits** [comment]
Gareth, I see the issue is already fixed but i still see this line of code marked as an error by FF:

<li data-target="#essentialCarousel" data-slide-to="0"class="active">

Probably is only a syntactic error and the browser can render the correct code. There are a no space between the "0" and class:

<li data-target="#essentialCarousel" data-slide-to="0" class="active">

The rest of tags that were not closed now are marked as closed.

**Comment by gjb2048** [comment]
Ok....

What line of code?
What tags that were not closed now are marked as closed?

**Comment by 3-bits** [comment]
It is located in the slide itself:

![selection_005](https://cloud.githubusercontent.com/assets/3742783/11791195/35908a12-a2a0-11e5-8be5-1d3fd96b0d3c.png)

**Comment by gjb2048** [comment]
Arrrrrrrrrrgggggghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh!!!!!!!!!!!!!!!!!!!!!

This has been in existence since 21st November 2014: https://github.com/gjb2048/moodle-theme_essential/blame/MOODLE_29/layout/includes/slideshow.php#L57 - it will be wiped out by the JS after the first transition.  This is a separate issue to this.

**Comment by gjb2048** [comment]
Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/39a61e852ff2ba4f17151db76710fb148c5d42b6
