### ISSUE TITLE
Fatal error on maintenance page

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#586]
with Essential theme 2.9.1.5 (from github)

Reproduce:
1. Install a new version of a plugin (mod, theme, course format etc) on the moodle server
2. visit moodle.url/admin

Following error appears:

Warning: require_once(/moodle/moodle/theme/essential/layout/includes/additionaljs.php): failed to open stream: No such file or directory in /moodle/moodle/theme/essential/layout/maintenance.php on line 37

Fatal error: require_once(): Failed opening required '/moodle/moodle/theme/essential/layout/includes/additionaljs.php' (include_path='/moodle/moodle/lib/zend:/moodle/moodle/lib/pear:.:/usr/share/php:/usr/share/pear') in /moodle/moodle/theme/essential/layout/maintenance.php on line 37

When I switch to clean theme with moodle.url/?theme=clean and moodle.url/admin then it works.

**Comment by gjb2048** [comment]
Thanks for the report.  Any version that is not tagged is a 'development' version that I am working on and may contain issues / incomplete development work.  In this case I intend to implement http://php.net/manual/en/language.oop5.traits.php.

**Comment by relecand** [comment]
Thank you for the quick answer, Gareth!

**Comment by gjb2048** [comment]
And a quick plug! -> http://www.moodlegarage.com/
