### ISSUE TITLE
Essential buid 2.9.1.4.1 (201506415): message outlining incoming 

### ISSUE THREAD

**Issue by gemguardian** [gjb2048/moodle-theme_essential#590]
Hi Gareth, 

It's a small issue and I could easily fix it within custom CSS but thought I would make a ticket for it. 
See enclosed screenshot for a visual view on the issue. 

Essential setting: General - set page width - Fixed Width - wide. 

When users send messages the incoming message doesn't seem to wrap the text properly to cause it "fall" outside the boxed area. (see screenshot). 

I had to change the width of the box + use word-wrap to get it with in the box. 
.message .messagearea .messagehistory .right{width:65%!important;word-wrap:break-word!important}

Goodluck with your work on 3.0 version! 

Gem 

![essential_2 9_receiving_mssg_wrap](https://cloud.githubusercontent.com/assets/16559999/12118545/6e91bc36-b3c7-11e5-8980-ddce2148418c.png)

**Comment by gjb2048** [comment]
Thanks Gem, I'll look at it when I can.

**Comment by gjb2048** [comment]
Cannot reproduce in M3.0.

**Comment by gjb2048** [comment]
Test code where URL underlaps:

````
http://moodle30.chloe/message/test/test/test/test/test/test/test/index.php?user1=2&user2=3&history=1 http://moodle30.chloe/message/index.php?user1=2&user2=3&history=1Testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing, testing....
````

**Comment by gjb2048** [comment]
Ok, but I can see how it can happen.

**Comment by gjb2048** [comment]
Fixed in both M3.0 and M2.9 versions.  M2.9 version needs double checking.
