### ISSUE TITLE
TinyMCE HTML editor Setting page format needs checking

### ISSUE THREAD

**Issue by zahrah-** [gjb2048/moodle-theme_essential#591]
Hello,
Hope all's well on your end.
Started having a look at the Release 3 Alpha candidate:

Moodle 3.0.1+ (Build: 20160107)
Essential 3.0.0.1 (Build: 2016010200)

I noticed that on the TinyMCE HTML editor Setting page the rows extend beyond the main section.

![ess3-plugins1](https://cloud.githubusercontent.com/assets/8460383/12215757/87a58b72-b6a0-11e5-8723-98e02e5c96c4.png)

(Note that this also occurs on 2.9 [2.9.1.5.2 (Build: 2015062418) and a little before as well - first noticed it there but was very busy to report it at the time]

I also noticed whilst on that page, that the colours need checking for the breadcrumb items without links, when one hovers on them:
![ess3-breadcrumb1](https://cloud.githubusercontent.com/assets/8460383/12215768/1e1e2762-b6a1-11e5-9dae-bd87ee3cdadf.png)
![ess3-breadcrumb2](https://cloud.githubusercontent.com/assets/8460383/12215769/2016996e-b6a1-11e5-951a-8792d19191e0.png)

Will continue testing and report any findings.

Thanks a lot for your continued support of the theme.

Regards,
sali

**Comment by gjb2048** [comment]
Hi Sali,

Thanks for the report, but I've already noticed the breadcrumb issue.  To save me lots of admin faff, please restrain from testing / reporting issues until I have released the theme at beta as stipulated in the CHANGES.txt file: https://github.com/gjb2048/moodle-theme_essential/blob/master/CHANGES.txt#L3-L4

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Breadcrumb fixed.  Cannot replicate first issue.

**Comment by zahrah-** [comment]
Hello,

I apologize. I must have misunderstood the statement from the email I received yesterday...

...do feel free to try the theme out by either forking the code or using the 'Download ZIP' button here: https://github.com/gjb2048/moodle-theme_essential/tree/master.  If you find anything, then do please eMail me or raise an issue in the tracker (https://github.com/gjb2048/moodle-theme_essential/issues ...

I'll await the beta version to continue testing.

Regards,
sali

**Comment by gjb2048** [comment]
Hi Sali,

No apology required.  The eMail is correct.  My mistake, I looked and did not match the id here with my eMail list where are listed as 'Anonymous'.  Please do continue testing.  I'll update GitHub soon with the breadcrumb fix.

Thank you for sponsoring.

Kind regards,

Gareth
