### ISSUE TITLE
InCourse page content should be on the right and blocks on the left, in RTL mode

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#593]
Assuming we follow "Content first" UX policy (which I think is great)
When viewing any module's first page (just after you click it on the course front page), the content area (region-main) should be on the right side of the page and the blocks (aside) should be on the left side.

Here is a quick fix for it:
.dir-rtl aside#block-region-side-pre {
    float: left;
}
.dir-rtl section#region-main {
    float: right;
}

**Comment by gjb2048** [comment]
Hi Nadav,

There is a setting: https://github.com/gjb2048/moodle-theme_essential/blob/master/settings.php#L88-L95 whereby it can be content first or side-pre first - left in LTR and right in RTL.

Therefore not an issue unless this is not working as previously designed.

G

**Comment by nadavkav** [comment]
I know that setting and i am using it on several systems too, but was under the impression it is meant for the course front page view/layout only. am I wrong? I though it was meant for switching between current course front page view (with two blocks areas on the left and one content area on the right) to the "common" view ( blocks, content, blocks), and not for activity's incourse page layout, which this issue is all about. It would be great if it works fine on both. 

With the layout setting checked, everything looks fine on both LTR and RTL.

But, I am referring to the state where "layout" setting is not checked and the user is clicking any kind of an activity on the course's front page, and view it. now, switch from LTR to RTL. the page layout is not inverted. That should be fixed. What do you think?

I agree "It is not simply a matter of floats as there is a side-post to consider too. "
The above suggestion is a gross visual outcome of how it should look.
I am obviously counting on your professional skills to come up with a proper solution :-)

**Comment by gjb2048** [comment]
Hi Nadav,

That setting has been in for ages.  It does apply to all pages.

It does appear to be wrong in RTL with the blocks first on the right where the content should be when the setting is unticked.

G

**Comment by nadavkav** [comment]
Thank you for confirming that.
I was just checking all (3) systems I use essential with and they all have the layout setting checked.
So If it is not something trivial and tiny to fix... I think it should get low priority.

**Comment by gjb2048** [comment]
Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/b27d09263e352dadd2f696987ab4135a89f5e9f2

**Comment by nadavkav** [comment]
That was quick! :-)

**Comment by gjb2048** [comment]
I'm better than good.

**Comment by nadavkav** [comment]
Funny, after all... you made a spelling mistake.. like a human, and used double o instead of one ;-)

**Comment by gjb2048** [comment]
That's because I'm double 'o' 7 and a half ;)

**Comment by gjb2048** [comment]
Where's the double 'o'?

**Comment by nadavkav** [comment]
good
