### ISSUE TITLE
Assignment main page has wrong (report) layout

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#594]
All activities seems to have normal (content+blocks on the side) incourse layout pages, except assignment, which looks like a report layout (content + blocks under). Is this intentional? or a bug.

btw, It seems very useful for a teacher to have a report layout when she/he clicks the "View/grade all submissions" link.

**Comment by gjb2048** [comment]
Intentional for space and usability reasons: https://github.com/gjb2048/moodle-theme_essential/blob/master/layout/tiles/pagesettings.php#L157

**Comment by nadavkav** [comment]
Interesting... (thanks for the info)

**Comment by gjb2048** [comment]
RE: "It seems very useful for a teacher to have a report layout when she/he clicks the "View/grade all submissions" link." - the theme does that already.

**Comment by nadavkav** [comment]
Yes. but in this issue I was referring to the assignment main page and not the inner "View/grade all submissions" page. which has a very useful report layout.

We discussed it, and It looks like we prefer to revert to the original layout with side blocks. as it is very helpful for the teachers. (I am referring to the assignment's main page)

btw, we hacked a piece of code that adds the current viewing user role to the page's body class.
we use it to display different customizations on top of the layouts for different roles.
And we are thinking of hiding the blocks from the students on that page. as some think it is redundant for them. we'll see...

**Comment by gjb2048** [comment]
Tricky as both of the pages have the same id and classes.

**Comment by gjb2048** [comment]
I'll see what I can do.

**Comment by gjb2048** [comment]
Implemented in: https://github.com/gjb2048/moodle-theme_essential/commit/1ed091ceea4f948a17978377fe5684375ad08ff8

**Comment by nadavkav** [comment]
Sweet. I wonder what other people think of this too?

**Comment by gjb2048** [comment]
Either:

They like it.
They don't like it.
They like it and say something.
They don't like it and say something.
They like it, say something and ask for something else.
They don't like it, say something and ask for something else.

**Comment by nadavkav** [comment]
It's good I use safety belts when I set to code, otherwise... I would be on the floor rolling in laughter.
Now I am only seating strapped, laughing and can not stop :-)

**Comment by nadavkav** [comment]
Hope mighty Google is not indexing this ;-)
