### ISSUE TITLE
Navbar turn editing on / off button does not always work.

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_essential#595]
Ref: https://moodle.org/mod/forum/discuss.php?d=325937#p1310608

Not working on Frontpage / Admin pages so far.  Looks like Moodle is inconsistent on how the URL / button for this functionality is generated.

Need to investigate options.

**Comment by gjb2048** [comment]
user/edit.php has no button or entry in administration block.

**Comment by gjb2048** [comment]
Starting from page_heading_button in $OUTPUT.

**Comment by gjb2048** [comment]
Ok, snag.  Pagelib has 'set_button' which takes the HTML for the button.  Need to see what calls it and what I can do.

**Comment by gjb2048** [comment]
But this is only called by WIKI, so meh!  Magic call in place.

**Comment by gjb2048** [comment]
Ok, looks like things are calling 'single_button' and 'edit_button' to generate the HTML then calling 'set_button' with the output, so no clean way of reverse engineering things cleanly as 'up in the air' as to what code is generated, so buttons / a tags / forms!

**Comment by gjb2048** [comment]
Probably going to have to code individual circumstances where possible against the page id / layout sort of thing.

**Comment by gjb2048** [comment]
Or just use the code itself and cope with styling issues.

**Comment by jojoob** [comment]
Admin pages using "adminedit" instead of "edit" parameter. And frontpage seems to require "id=1" when toggling edit.
To fix the button on admin pages a quick&dirty solution might be to use both parameters "adminedit" and "edit" regardless of the page type (worked for me in a short test, but don't know if this rises any new problems). 
For the frontpage we need an indicator that we are on the frontpage to append "id=1".

**Comment by gjb2048** [comment]
I've been working on it for a few days and it appears to be even more complex than that with a few pages not implementing the functionality at all.  Moodle is so consistent - not.

**Comment by gjb2048** [comment]
I've done as much as possible at the moment.  Wait for feedback.

**Comment by jojoob** [comment]
The navbar editing switch does not correctly work at the mod_forum manage subscribers page.
Turning edit off does not work with the navbar button (under Moodle 3.1.4+ (Build: 20170119)).

Just for completeness and for further testing: here is a list with places where the area for the editing button is used (just searched for "->set_button(" within the code of current Moodle 3.1.4+ (Build: 20170119)):
* /moodle/admin/category.php
* /moodle/admin/settings.php
* /moodle/calendar/export.php
* /moodle/calendar/managesubscriptions.php
* /moodle/calendar/view.php
* /moodle/course/renderer.php
* /moodle/course/search.php
* /moodle/course/view.php
* /moodle/grade/lib.php
* /moodle/lib/adminlib.php
* /moodle/lib/pagelib.php
* /moodle/mod/book/lib.php
* /moodle/mod/data/view.php
* /moodle/mod/forum/discuss.php
* /moodle/mod/forum/index.php
* /moodle/mod/forum/search.php
* /moodle/mod/forum/subscribers.php
* /moodle/mod/forum/view.php
* /moodle/mod/lesson/locallib.php
* /moodle/mod/quiz/index.php
* /moodle/mod/resource/locallib.php
* /moodle/mod/scorm/player.php
* /moodle/mod/wiki/pagelib.php
* /moodle/my/index.php
* /moodle/my/indexsys.php
* /moodle/tag/index.php
* /moodle/tag/search.php
* /moodle/theme/essential/classes/output/core_renderer.php
* /moodle/user/profile.php
* /moodle/user/profilesys.php
