### ISSUE TITLE
.gitattributes: extend for binary files

### ISSUE THREAD

**Issue by jpahullo** [gjb2048/moodle-theme_essential#597]
Hi all!

I've added your excellent theme in my Moodle, and I found myself in a trouble about CRLF and LF.

I solved this problem by extend your .gitattributes file with this content:

```
+*.otf binary 
+*.eot binary 
+*.svg binary 
+*.ttf binary 
+*.woff binary
```

Otherwise, I had no problem when committing, but on any checkout on any other place, the operation always left a ttf file with line endings modified.

Thanks for your effort!

PS: I found the content to extend for the .gitattributes from the FontAwesome repository.

**Comment by gjb2048** [comment]
Umm, thanks, but 'svg' files are text!

**Comment by gjb2048** [comment]
Rectified with addition of woff2 in https://github.com/gjb2048/moodle-theme_essential/commit/ce8672739a841178604a18578cf653585ec019ef.

**Comment by jpahullo** [comment]
Perfect!!! Thank you so much! You're right, svg is text file. I took that from https://github.com/FortAwesome/Font-Awesome/issues/4321. Your solution is even better :+1:
