### ISSUE TITLE
down arrow of scroll bar color of text box

### ISSUE THREAD

**Issue by lastimam** [gjb2048/moodle-theme_essential#598]
The down arrow background color separates from the scroll bar when the text box is expanded
![2016-01-27 11_30_48-sas virtual reality_ administration_ appearance_ themes_ essential_ general](https://cloud.githubusercontent.com/assets/1902058/12606875/5ba88152-c4ea-11e5-8024-babe47876733.png)

**Comment by gjb2048** [comment]
Hi,

What version of Essential and what are the steps to replicate please?

G

**Comment by gjb2048** [comment]
And what browser and version please?

**Comment by lastimam** [comment]
http://sasvr.rafed.co/theme/essential/README.txt
Chrome Version 48.0.2564.82 m
Firefox seems does not support colored scroll bar.

**Comment by gjb2048** [comment]
Thanks.  How do I replicate the problem please?

**Comment by gjb2048** [comment]
Yes I can replicate, but there is nothing I can do about it.  Must be a browser fault.  The theme is using the correct CSS to set that colour.
