### ISSUE TITLE
Colour per category

### ISSUE THREAD

**Issue by jpahullo** [gjb2048/moodle-theme_essential#601]
Hi!

We will use this theme for our next Moodle version 3.0. For our particular needs, we need to provide a way to show courses only relying under certain categories applying different colour schemes. 
### Colour per category

Administrators could define a color scheme related to each of the available categories from the "My categories" list. The effect should be that when changing to any context under a given category, and that category have an explicitly defined color scheme, the output would be using that scheme. Otherwise, the default theme colours will be applied.

We will not need that, but you may consider subcategories with different colour schemes. For instance:

category1 > category2 > .... > categoryN

Administrators could choose a certain colour scheme per category1, another scheme for category2 and another scheme for categoryN.

So, in those cases, the colour to be applied have to the that with the longest context path.
### Proposal
1. Build additional theme settings to select:
2. When set (i.e., checkbox to enable colour per category), any context under the longest category path will be applied with the corresponding colour scheme. Otherwise, the colour scheme will be the theme defaults.

In more detail:
1. Add a new settings page called **Colour per category**. The content of the page will be:
1.1. A checkbox to enable/disable the color per category feature. This will make easy to check wherever from the theme code if this feature has to be considered. If the checkbox is ticked/enabled, then the page will include also:
1.2. The list with all the alternative scheme colours with a checkbox beside.
1.3. The category list with multiple selection.

Once the categories are selected from 1.3 and settings saved, then there will appear as many settings as categories selected in 1.3. Each of these settings will have a selector with the list of enabled colour schemes from 1.2. If at some time, a color scheme is unticked/unchecked, the categories selected for that colour scheme will be shown applying the default theme scheme.

**Mock-up of the proposal design**

![mockup](https://cloud.githubusercontent.com/assets/2048296/13747497/c886e43e-e9f8-11e5-999f-1c23c37f58da.png)

**Advantages of this design**
1. Simplicity to check if colour per category feature is enabled, by checking setting from 1.1.
2. Making explicit which of the alternative colour schemes will be available for this feature.
3. No human errors when selecting a colour per category.
### Tasks
1. Define settings page to pick colour schemes for any selected category.
2. At the very beginning of any page loading, detect if:
   1. The settings for colour per category is enabled, and then
   2. The current context is under any selected category with an explicit colour scheme, and then
   3. Apply that colour scheme instead of the theme defaults.
### Questions and answers

**Precedence.** I think it is better the category to take more precedence than user one. Even better, we could disable (hide) user selector when this precedence is active (or with an additional checkbox to disable the user selector for colour schemes).

**Alternatives** The colour alternatives are the same list for both users and categories.

**When user alternatives should be presented?** As I suggested in the first point, I think it is better to disable user alternatives when category alternatives are set. In our case, we will disable user alternatives when setting category alternatives. But, for you and your theme, you can add an extra checkbox for explicitly disable user alternatives when desired for administrators.

**When to apply category alternative?** As it is said in the description, the colour for that category will be applied to **any context** under the given category with customized colour alternative. That includes courses, activities, resources, blocks, etc.

**Sub-categories with a different colour alternative.** In that case I will follow the Moodle standards, that makes applicable the nearest setting to the given context. In other words, the colour to apply will be for the matching category with the longest context path. For instance, in a hierarchy of categories Cat1 > Cat2 >... > CatN, where all Cat1, Cat2 and CatN have explicitly colour alternatives, anything under the context of CatN will take that colour alternative. Any context under Cat2 excluding CatN category tree will take its own colour alternative. Any context under Cat1 excluding Cat2 context tree will take its own colour alternative. So, when showing any Moodle page, the idea is to take always the **longest/deepest context path** for the current context whenever the colour per category setting is enabled and a match is found.

**Which colour to apply when no match?** If the context for the current page does not match any category with an explicit colour alternative, we will apply the default site settings.

**Comment by gjb2048** [comment]
Yes I'm interested.  How much does the job pay / budget?  Is there a contradiction between default category and categories user enrolled in requirements?  What are the types of reordering needed?

**Comment by jpahullo** [comment]
Hi!

* Budget: I will be our contribution. We need it. We'll share it to the community. Afterwards, it will be maintained by all of us.
* Contradiction? Nope. Default category should be one of the listed categories. This is necessary to choose one category if none was selected previously. In our case, we would use it for courses by academic years, so that default category would show the courses from the current academic year.
* Reordering: I think that by default users may reorder list of enrolled in courses (before the dashboard, it was done in the "My moodle" page in a standard way when editing on that page). I assume it will rely now under the dashboard page (not checket yet). 

Maybe this last point needs some other modifications (don't checked yet) apart from the theme.

**Comment by gjb2048** [comment]
I need to think about this as ultimately it will take me time to review, independently test and maintain the changes.  Pragmatically all the bugs after release are fixed by me.

There is still an issue with the default category as I don't think you need it down to the fact that you are generating a list of categories that the user is enrolled in.  If none then no menu.

**Comment by gjb2048** [comment]
Hi Jordi,

Ok, this is what I will agree to....

I need to have more information to make an informed decision.  For that I need to look at the code.  For that I want to create a branch for the pull request.  That branch needs to be based off of master.  I need to bump the version before I do that.  In addition I have enabled TravisCI checking on pull requests so it will automatically check the code against lots of things.

If this is ok, then please let me know then I will inform you of when the pull branch is ready at my end.

Kind regards,

Gareth

**Comment by jpahullo** [comment]
Hi Gareth!

Default category is to set it up to the user by the system when the user firstly log in with this settings enabled. It is something like saying "the institution hosting this moodle decides this category to be the default for all users loging in".

Our use case is as follows: given that we have categories per academic year, only one category will be the current academic year, and so it will be the "default category". Other categories are related mainly to old academic years, which are read-only, and so, less used. 

Above all, this "default category" setting helps to answer the question "which category we are going to show for this user if the user has no already selected category, and this user has courses to show in all categories in the list?".

Regarding the pull branch, it is ok for me. Give me some time, since we are deciding how to focus this requirement from our side. When all things were agreed upon what we were talking before, we will start working on this and you will be able to build that branch. Therefore, put this issue as "waiting for the developer" :stuck_out_tongue_winking_eye: ASAP I have confirmation for this, I'll be back and we'll make the wheel run.

It's awesome to have such an active feedback. I'll put this as a personal TODO, since I'm also a Moodle plugin maintainer, and I'm not always so active nor giving feedback in such a short time. Good for you!

Regards,

Jordi

**Comment by gjb2048** [comment]
Thanks Jordi.

Deferred label represents 'waiting for developer'.

**Comment by jpahullo** [comment]
Perfect!

**Comment by gjb2048** [comment]
I'm not saying that I will 'definitely' agree to the code, just that I will consider it when I see how things work.

However all features 'must' be able to be turned off as clearly the functionality is for a specific scenario.

**Comment by jpahullo** [comment]
I always assume these settings have to be optional, so they can be enabled and disabled. When disabled, the theme should behave just right now the theme does, and when enabled, they will be considered into account. Obviously.

If we go ahead with this solution, we will be happy to be contributed to be shared, and so used and improved by others. If sadly you finally does not include these changes, we would have those local changes applied in our repository :cry: 

However, thank you so much for making this explicit and clear beforehand. In the end, we agree on all items. :smile:

**Comment by gjb2048** [comment]
Hi Jordi,

You would not have to discard the changes.  There are two options if I consider to reject the code.

1. Maintain a separate branch where the changes are one commit which you then rebase when upgrading.
2. Put the features into a child theme.

Cheers,

Gareth

**Comment by jpahullo** [comment]
Yes! Absolutely! I usually apply for the first option you mentioned about.

Thanks!

**Comment by fontinixxl** [comment]
Hi all!

I work with @jpahullo. We are going to add the **Color per category** feature.

To do so, this is our proposal:
1. Add a new settings page called *Color per category*. The content of the page will be:
1.1. A checkbox to enable/disable the color per category feature. This will make easy to check wherever from the theme code if this feature has to be considered. If the checkbox is ticked/enabled, then the page will include also:
1.2. The list with all the alternative scheme colours with a checkbox beside.
1.3. The category list with multiple selection.

Once the categories are selected from 1.3 and settings saved, then there will appear as many settings as categories selected in 1.3. Each of these settings will have a selector with the list of enabled color schemes from 1.2. If at some time, a color scheme is unticked/unchecked, the categories selected for that color scheme will be shown applying the default theme scheme.

### Mock-up of the proposal design
![theme_essential_colours_cat](https://cloud.githubusercontent.com/assets/5080665/13668933/52a546f6-e6c0-11e5-8dcc-fdbc5457d7dd.png)

### Advantages of this design

1. Simplicity to check if color per category feature is enabled, by checking setting from 1.1.
2. Making explicit which of the alternative color schemes will be available for this feature.
3. No human errors when selecting a color per category.

We need to start working on it. Please, could you give us feedback about this design? Would you accept this design in the end?

Thanks in advance!

Gerard

**Comment by gjb2048** [comment]
Hi Gerard,

Ok, a few points:

1. The user interface is overly complex.
2. 'Color' should be 'Colour' as all Moodle is in Australian English - 'en'.  The spelling of that word is defined in US English - 'en_us'.
3. This is all becoming work for me.

Therefore with '3', I will make enhancements for the following reasons:

1. To improve my technical knowledge.
or to:
2. To make money.

So, even though you are writing the code, my time is involved.  As a result of the enhancement I do not see me improving my technical knowledge as I could easily make this enhancement myself.  As the code will be given away to the community for free, I will not make money.  Therefore there is a 'cost' factor in this and it will need funding of my time to review / comment / maintain after release (because there are always bugs).

Gareth

**Comment by gjb2048** [comment]
A lot to take in, going to take a while to figure out the cost.

**Comment by gjb2048** [comment]
A lot more than 'Color per category' to figure out the cost for.

**Comment by gjb2048** [comment]
Questions for 'Category list':

1. How can the administrator set categories when this will be different to the list the user is currently enrolled in?  With MyCourses the list is automatically generated from the user.  The admin has no input.
2. With the 'default' are you saying that it should appear if the user does not already have that category?
3. I don't understand what you mean by "Once a user change to another option from "My categories", the user would only see the courses under that category (including sub-categories).", as once a user clicks on a category menu item I assume it will go to that item?

**Comment by gjb2048** [comment]
Questions for 'Course reordering':

1. I do not understand what you mean by "In the user dashboard, whether the user would like to reorder courses, that reordering should consider only the courses under the given selected category."? - please elaborate further.  An annotated screen shot would help.
2. The user dashboard just has the 'Course overview' block.  There are no categories until a certain number of courses is reached.  So are you saying that courses should be reordered within category when this happens?
3. What happens when no categories are shown and just courses from different / one category?
4. What reordering do you want?  Ascending? etc.

**Comment by jpahullo** [comment]
Hi!

We'll give the details about the questions you're making:

Answers about "Category List":

**Overall description**

Administrator knows that courses any user can be enrolled in appears in certain categories. Why do so? For instance, administrators know it due to syncronization scripts, organizational category structure for all active/deactivated courses, etc.

Therefore, administrators can always set categories in the list of categories where all enrolled courses will be shown. Somehow, administrator will be sure that showing this list of categories, users will see and be able to access to any useful/active course they are enrolled in.

Just in case there are courses that fall into categories not in the above list, they will not be listed, but anyway they can be searched for.  We use this feature to simplify user's course overview, since we "hide" passed/not active/old user courses.

**Category list operation overview**

* Whenever user selects a category from the list, the user will see the list of courses under that category (or any of its sub-categories if exist). In addition, the list of courses will be updated to see only the courses from the selected category.
* In any case, whenever a user wants to change to a different course, the user may:
 1. Select a course from the list of courses, if it appears there. Otherwise,
 1. Select a different category from the list, as preview step to change to the expected course. 
This partition of courses per category in the "MyCourses" list is very useful in cases where users have a lot of courses (such as >100 courses in total). Students may not have such amount of courses, but other roles such as teachers or some other kind of custom roles (reviewers/managers/coordinators) may have such amount of courses.
* The list of available categories per user must be the whole list of categories, except those that the user has no courses enrolled in. The default category will always be shown. If the user has no courses in the default category, we can just show a descripting message (like "No courses available yet").

Answers to questions for "Category list":
1. The list of MyCourses will show the courses under the current selected category. 
2. The default category is shown always, even though the current user has no courses enrolled in yet.
3. Once a user change to another different category option from the list, two actions occur:
 1. The list of "MyCourses" is updated with only the courses under that category, and
 1. The user is brought to the site page, with only the courses under the selected category.

**Comment by jpahullo** [comment]
Sorry for the inconvenience, @gjb2048, we are refactoring the issue detail to match exactly what can be done via theme.

When detailing the issue, we realized that we asked more than could be done only via theme. Therefore, we will simplify the requirements to only the colour per category.

Sorry again @gjb2048. Forget what we wrote before.

Wait a minute and it will be done.

**Comment by gjb2048** [comment]
@jpahullo you do realise that a theme can override any render in '/course' don't you?

**Comment by jpahullo** [comment]
Mmm.... I didn't know that one could override rendering for selected URLs, sincerely.

But the main problem detected on our initial proposal was that it would have required modifying the course_overview block too (for listing corresponding courses), and that is not the task of a theme :disappointed:

**Comment by jpahullo** [comment]
Thank you so much for you time. Now we have updated the issue description accordingly. Do you have any question?

Thanks!

**Comment by gjb2048** [comment]
The course overview block has a render, so bits of it could be overridden in a theme.

And I'm not talking about overriding URL's, I'm taking about the files in the path '/course'.

Questions: Where are things now?  What is the budget for this?  What specifically are you now asking me to quote for?

**Comment by jpahullo** [comment]
Sorry for going back and forward. It was all about confusion in our minds.

The specific tasks required for this issue appear in the descripcion of the issue (as the final and updated definition of the requirement). Could you have a look at that now and then comment on any further doubt?

Thanks in advance.

**Comment by gjb2048** [comment]
Hi @jpahullo 

Not now, but when I next get a chance.  But I'm confused, things have changed so many times.  Thus the specification is what it was before, but with the modifications of today?  But not the retraction.  Plus there is no point in spending my time quoting if the budget for this is below my rates, therefore, what is the budget for this please?

Kind regards,

Gareth

**Comment by jpahullo** [comment]
Hi @gjb2048,

No more changes. Things will not change now on. The whole specification is on the description. I included the comment @fontinixxl did some day ago too.

About the budget: you can count on this issue the time already spent till now (including that time related to all the stuff we retracted), plus the time of developing and testing all this new part. 

We are looking forward to hearing from you.

Kind regards,

Jordi

**Comment by gjb2048** [comment]
Hi @jpahullo,

No, I mean 'your' budget?  On the premise that you were going to do this and now you have asked me to quote for it.  Therefore there might be "no point in spending my time quoting if the budget for this is below my rates".

Kind regards,

Gareth

**Comment by jpahullo** [comment]
Hi!

I think I missed a word about the budget. We realized that is better for you and for the theme you to develop the whole job (developing and testing this feature).

As you quoted for #606, how many hours do you need to have this feature working?

Hopefully, now we have all points clear :smile: 

Thanks in advance!

Jordi

**Comment by gjb2048** [comment]
Hi @jpahullo,

Ok, with #606, that was small and I could easily work that out.  With this it will take much longer, and as it has transpired, you were going to develop it yourselves before asking me.  Thus, you would have already established a budget for the work.

So, what is YOUR budget for the work?  With that figure I will know if it is worth me expending time on this complex quote.

I hope I am making myself clear.

Kind regards,

Gareth

**Comment by jpahullo** [comment]
Ok, @gjb2048,

Our initial expectation was like this, without knowing exactly and perfectly your theme as you do:

* 5-6 hours by developing the new theme page.
* an uncertain number of hours to find where to detect whether we have to use a colour scheme or the default theme settings. We do not know where "all begins" in a theme to detect the currect context, and from there, set an alternative colour scheme as the default when applicable. In the worst case, this single point can be several ones. I think you will know about this in your theme for sure.
* 1-2 hours to develop the piece of code to change colour settings according to current context.
* Plust testing, maybe 3-4 more hours.

So, we could say 12 hours + the second point as minimum.

Now it's your time :smile: 

Thanks in advance,

Jordi

**Comment by gjb2048** [comment]
Hi @jpahullo,

Thank you.  That is just the 'time'.  I am being asked for both time and money.  Therefore what 'money' is there for the twelve hours please?  How much is 'twelve' hours in money?  Therefore what is your 'budget' please?

Kind regards,

Gareth

**Comment by gjb2048** [comment]
i.e. What is your maximum spend in money for this project?

**Comment by jpahullo** [comment]
Well, IMHO, I think that you know the time, so you now can say how much it is. We do not know how are you getting paid per hour.

In Spain, IT freelance and enterprises get paid 20€ + VAT (21%) per hour. We would need an invoince with VAT, identification number and so, since we would pay you via the University.

Kind regards,

Jordi

**Comment by gjb2048** [comment]
Hi Jordi,

Ok, my current rates are as follows:

50 GBP for the first hour and then 40 GBP for every hour after that or
132.50 GBP for a 3.5 hour day or
220 GBP for a 7 hour day or
negotiated fixed price contract.

Payable by PayPal or negotiated bank transfer within 15 days to avoid 10 GBP late payment penalty cumulative every 15 days late up to 3 months.

In the UK I a self-employed sole trader.  Thus I am working for myself and am not registered as a company, therefore I do not have a VAT identification number.

Are my rates and terms of business acceptable?

Kind regards,

Gareth

**Comment by jpahullo** [comment]
I can see several options.

Please, put a price for it as a whole, to get all job done and integrated in the master branch for all we to use. How much is it? Then, I could pass this information (your price) to my bosses in order to accept it. And lastly I will be back with more information for you.

Thanks in advance,

Jordi

**Comment by gjb2048** [comment]
Questions:

When the user sets a colour preference, which takes precedence?  Category or user?
Are the category alternatives one and the same thing as the user alternatives?
When the category colour has been set, should the user alternatives be presented?
When a category colour has been set, that applies to all courses and activities / resources (category, course and incourse layouts)?
When a sub-category has a different colour alternative to the parent then that takes priority?
When the scheme for a category has not been set, then it inherits from the category above / site?

**Comment by jpahullo** [comment]
Hi!

Nice to hear from you.

Here are the answers:

**Precedence.** I think it is better the category to take more precedence than user one. Even better, we could disable (hide) user selector when this precedence is active (or with an additional checkbox to disable the user selector for colour schemes).

**Alternatives** The colour alternatives are the same list for both users and categories.

**When user alternatives should be presented?** As I suggested in the first point, I think it is better to disable user alternatives when category alternatives are set. In our case, we will disable user alternatives when setting category alternatives. But, for you and your theme, you can add an extra checkbox for explicitly disable user alternatives when desired for administrators.

**When to apply category alternative?** As it is said in the description, the colour for that category will be applied to **any context** under the given category with customized colour alternative. That includes courses, activities, resources, blocks, etc.

**Sub-categories with a different colour alternative.** In that case I will follow the Moodle standards, that makes applicable the nearest setting to the given context. In other words, the colour to apply will be for the matching category with the longest context path. For instance, in a hierarchy of categories Cat1 > Cat2 >... > CatN, where all Cat1, Cat2 and CatN have explicitly colour alternatives, anything under the context of CatN will take that colour alternative. Any context under Cat2 excluding CatN category tree will take its own colour alternative. Any context under Cat1 excluding Cat2 context tree will take its own colour alternative. So, when showing any Moodle page, the idea is to take always the **longest/deepest context path** for the current context whenever the colour per category setting is enabled and a match is found.

**Which colour to apply when no match?** If the context for the current page does not match any category with an explicit colour alternative, we will apply the default site settings.

I'll append this to the description to the issue, for more information.

Thanks for your time,

Jordi

**Comment by gjb2048** [comment]
Hi @jpahullo,

I'm preparing the quote at the moment.  Where can I PM it to you please?

Kind regards,

Gareth

**Comment by gjb2048** [comment]
With "I think it is better the category to take more precedence than user one. Even better, we could disable (hide) user selector when this precedence is active (or with an additional checkbox to disable the user selector for colour schemes)." - what happens if the tick box is not ticked?  And both are active, what happens?

**Comment by jpahullo** [comment]
With the last question, category alternative will have more precedence than user one. You can read that as a site setting being more important than a user preference. 

Similarly, Moodle has a tick box to enable/disable the theme being selected by the user. In our case, in our Moodle, for example, we have disabled that, so there is only a theme being available.

Thanks!

**Comment by gjb2048** [comment]
Thanks Jordi,

I have finished the quotation.  Where can I PM it to you please?

Kind regards,

Gareth
