### ISSUE TITLE
<audio> elements can overflow to the right on small, older phones

### ISSUE THREAD

**Issue by sympo** [gjb2048/moodle-theme_essential#602]
This is an issue that also happens in clean theme, particularly on older phones with small screen resolutions so I understand if you decide not to make any changes to the code. 

Anyway, I have noticed that adding
 
```
audio {
max-width:100%;
}
```

fixes the issue without any adverse effects.

**Comment by gjb2048** [comment]
How can I replicate this so that I know the fix works please?

**Comment by sympo** [comment]
We got a error notification from a student, so I'm not sure exactly what device he and browser has but we were able to replicate this by shrinking the Firefox window enough for the contents of <audio> to overflow.

This screen https://imgur.com/RRbI1Gg shows the difference with and without the style mentioned above. We got a confirmation that the issue has been resolved ever since we added the fix to custom css.It also shows that the seekbar on the player is scaled properly, so we don't end up with audio still on when it seemingly should have ended.

**Comment by gjb2048** [comment]
Thanks - I will double check and confirm.

**Comment by gjb2048** [comment]
![rrbi1gg - imgur](https://cloud.githubusercontent.com/assets/1058419/12645245/9e93b47e-c5c0-11e5-8410-46b207192c75.png)

**Comment by gjb2048** [comment]
How can I replicate this please?  How did you create the 'audio' tag.  I have a test course with a file but the core media plugin makes it a flash thing.

**Comment by sympo** [comment]
We don't have flash at school so we have opted for manually adding audio elements by using the source view in the editor instead of the default moodle option. It's also more mobile friendly that way. To do so we add:

`<audio src="/[path_to_file]/[filename].mp3"  preload="auto" controls></audio>`

in the source. That way it is played in the default player of each browser.

**Comment by gjb2048** [comment]
Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/fe5d6c07fba363b1a2e72c395dcf7b21e6ff6a12
