### ISSUE TITLE
Front page setting "theme_essential | frontpagemiddleblocks" set to "show..." makes the three Home regions visible to any "editing role" in a course

### ISSUE THREAD

**Issue by andreumarti** [gjb2048/moodle-theme_essential#605]
Hi Gareth,

When the Front page setting of the theme "theme_essential | frontpagemiddleblocks" is set to any value different than "Never show" any user with editing capabilities (ie: a teacher) sees the three regions when editing any of the course blocks in a course, these are "Home (left)", "Home (middle)" and "Home (right)". You can see this in the attached screenshot:

![image](https://cloud.githubusercontent.com/assets/6594883/12712690/71eea0fc-c8ca-11e5-8ab2-3f909fd335f7.png)

Although there are no apparent changes when a course teacher select any of the three "Home values" of the Region setting of a Block in a course, it would be much "cleaner" when these three locations could be hidden for the roles different from the "admin"

Is there a way of hidding these three regions for all users except for the admins?

Thanks for your time!
Andreu.-

**Comment by gjb2048** [comment]
Hi Andreu,

Ok, when editing is on that page then any person who has the capability to edit that page will see that block region.  Therefore the logic applied and explained in this comment applies: https://github.com/gjb2048/moodle-theme_essential/issues/603#issuecomment-176321041

As the content is not controlled by the theme's settings and thus for admins only then the core capabilities come into play.  If you don't want the teacher to edit the page then use the standard capability settings to prevent them.

There is another backstory to this, but information costs.

Cheers,

Gareth
