### ISSUE TITLE
Allowing blocks placed at the top of the content column

### ISSUE THREAD

**Issue by jpahullo** [gjb2048/moodle-theme_essential#606]
Hi!

We are looking at the possibility to add a new block region to be placed just at the top of the (middle) content column. 

This will allow putting into the central column content not only in the front page, but also in the courses.

Are you interested in this kind of feature for blocks?

Thanks for your time!

Jordi

**Comment by cdipe** [comment]
Sounds like a great idea. We would like to be able to make global announcements that show up in all courses, and that sticks until the user has actively marked it as "Read". I'm not sure if that is what you are considering?

**Comment by jpahullo** [comment]
Nope @cdipe.

Blocks in Moodle can be placed in the left or right column, but not in top of the middle/content/main column. 

My proposal is to enable a default "middle" column that will show  any blocks placed in that region. Obviously, inheriting editing privileges: admins will be able to place blocks in that place in front page, and professors in course context.

@cdipe , you're talking like the three messages that this theme also allows you to enable, also in different colours.

Regards,

Jordi

**Comment by cdipe** [comment]
Ah, ok. 
I have seen the three messages on the start page, but I would like to have them appear in the courses, and to be closed once the user have marked them "Read". Mostly to use for big, global news and information on changes.

**Comment by gjb2048** [comment]
Hi Jordi,

When you say 'content' column I assume you mean on courses?

Ok, pragmatically Essential already has lots of features and I don't want to overload it much more.  Also given the triviality of the solution, for me it would be faster to implement the code than review somebody else's.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Also with the front page, there is already 'front page middle' blocks in the theme.

**Comment by jpahullo** [comment]
Hi Gareth!

Yes, there is an upper area with 3 columns that admins can make visible before and/or after login. However, what we are focusing on is placing those blocks just in top of the content area, starting at the same heigh than the columns blocks.

It is simple, yes, but this is something that we always needed from every theme we have been using.

Thanks for all Gareth!

Nice to hear from you.

Jordi

**Comment by jpahullo** [comment]
I close this issue for being discarded.

**Comment by gjb2048** [comment]
Reopened as still a possibility.  Why did you close it Jordi?

**Comment by jpahullo** [comment]
Hi Gareth!

I assumed/understood you were not interested in this enhancement.

Sorry, I don't want to interfere in your decisions. I misunderstood the situation :stuck_out_tongue_closed_eyes: 

Thanks!

**Comment by gjb2048** [comment]
No worries Jordi, I just said I thought I could do a better job ;)

**Comment by gjb2048** [comment]
Time cost: 1 hour development + 1 hour to test and confirm D&D CSS is fine etc.

**Comment by jpahullo** [comment]
Please, put a price for it too, together with the #601 as a pack, since we are interested in both features.

Thanks in advance,

Jordi

**Comment by jpahullo** [comment]
You can send me a private message if you want to.

**Comment by gjb2048** [comment]
Hi Jordi,

I'm starting to look at this and currently the 'middle blocks' on the front page are three separate regions.  This is a bit 'naff' as Shoehorn etc. (my other themes) have a dynamic single horizontal block region that can be set to have between 1 and 4 blocks per row.  I think this would be a good solution here.  The disadvantage would be that 'home-left', 'home-middle' and 'home-right' regions would be removed.

Gareth

**Comment by jpahullo** [comment]
Hi Gareth!

In the end! :smile: 

I know about the horizontal block with up to 3 or 4 columns.  However, in our configuration of Essential theme, we only show this horizontal block before being logged in. Once logged in, we need to hide the information placed in this horizontal block to make wider the use of the page for the site and course information. In addition, another advantage, is that the block is "integrated" in the area of the main, central content of Moodle. 

For an example, just visit our current Moodle (http://moodle.urv.cat/moodle/) and imagine you are logged in and you see those blocks placed in the middle (like "Informació general" or "Apps oficials per a Moodle") and the rest of the page the other information of the main Moodle site page.

We need this. Maybe its a bit naff, but it has so powerful functionality for us. In our context, we need that.

Lookinf forward of hearing from you.

Jordi

**Comment by jpahullo** [comment]
Hi again!

There is problem we found in our configuration and that horizontal block is the following:

* If we have only a single block in the midde of that horizontal block, there is a total reservation of the area, pushing down the content of the actual course (either in the main Moodle site or any course).

Sincerely, we "played" quite long with the possitibilies from your Essential theme, and we need this functionality.

Jordi

**Comment by gjb2048** [comment]
Hi Jordi,

Ok, I envisage that the front-page before / after login would stay the same, however I would remove the  'home-left', 'home-middle' and 'home-right' regions in favour of the 1-4 column functionality in Shoehorn etc.  That actually is intelligent and counts the number of blocks, and makes the block bigger when there are say 3 blocks on one row and only 1 on the next.  Or even just one block when the settings say up to 3 etc.

Therefore both the front-page and the other pages would get the functionality with the front-page keeping the before / after login etc.

G

**Comment by jpahullo** [comment]
Hi Gareth!

Could you please give me an example via an image/screenshot of the result you are talking about using the horizontal block?

```
------------------------------------------------------------------------
| header                                                               |
------------------------------------------------------------------------
|                  | horizontal block          |                       |
|                  | with tree columns         |                       |
|                  | but only a central block  |                       |
|                  | with content              |                       |
|                  -----------------------------                       |
| -------------------- start of content at site or course -------------|
| left column   |       central column / main content   | right column |
| ....          |     ....                              | ....         |
------------------------------------------------------------------------
```

The trials we made with that horizontal block, always produced the above result.

Thanks!

Jordi

**Comment by jpahullo** [comment]
Hi!

Ah! Another thing: in our case, the content of the horizontal block is going to be different from before logged in and after logged in.

Jordi

**Comment by gjb2048** [comment]
Hi Jordi,

Umm, that's a 'lot' more work!  You only stated "We are looking at the possibility to add a new block region to be placed just at the top of the (middle) content column.", therefore I quoted for adding a new block region in the middle of the other pages besides the front-page.

Currently even with the regions as they stand you can either show them or not.  Having a way where you could have both before and after login regions and be able to edit them is a whole new ball game.

G

**Comment by gjb2048** [comment]
Therefore as you are 'changing' the requirement after the work has been agreed, then I could:

Add in the middle region as agreed.
Quote the before / after (if its even possible) as a separate task after this has been completed.

**Comment by jpahullo** [comment]
wait wait wait

**Comment by jpahullo** [comment]
I was confused with your words on the possibilities on the horizontal block.

We what really need is to "add a new block region to be placed just at the top of the (middle) content column."

No other things. Please, I was only evaluating the alternatives you were talking about. If I ask you to quote something else, I will make it explicitly. Sorry for the confusion and the inconvenience.

Jordi

**Comment by jpahullo** [comment]
I ask you to a private chat if possible.

**Comment by gjb2048** [comment]
Hi Jordi,

Ok, but you did state "Ah! Another thing: in our case, the content of the horizontal block is going to be different from before logged in and after logged in."

G

**Comment by gjb2048** [comment]
Very quickly please.

**Comment by jpahullo** [comment]
I ask you via Hangout. I see "invite sent".

**Comment by jpahullo** [comment]
Sorry again for my words giving you to this confusion.

I think it is somehow difficult to be sufficiently explicit here, only by text.

Jordi

**Comment by gjb2048** [comment]
I think you need Hangouts installed.

**Comment by jpahullo** [comment]
Calling you from my mobile.

**Comment by gjb2048** [comment]
![2016-07-21 18_44_02-start](https://cloud.githubusercontent.com/assets/1058419/17033084/51ea7fca-4f74-11e6-8dd3-3b40c13974d8.png)
![2016-07-21 18_44_25-start](https://cloud.githubusercontent.com/assets/1058419/17033085/51ee2a12-4f74-11e6-9ff6-2b03a998811f.png)

**Comment by gjb2048** [comment]
NTS: home-left etc. removed and replaced by 'page-top'.
