### ISSUE TITLE
warning in footer into a course for non found version

### ISSUE THREAD

**Issue by jpahullo** [gjb2048/moodle-theme_essential#607]
### Context

In any Moodle course.

### Problem

With enabled debug one can see at the footer:

```
Notice: Undefined property: stdClass::$version in /var/www/gcuello/next/moodle/theme/essential/classes/output/core_renderer.php on line 135
Call Stack
#   Time    Memory  Function    Location
1   0.0007  325184  {main}( )   ../view.php:0
2   2.2963  47538928    theme_essential\output\core_renderer->footer( ) ../view.php:293
```

### Proposal

Use current theme API, instead of property, passing from `$this->page->theme->settings->version` to `\theme_essential\toolbox::get_setting('version')`

Will be PR soon.

**Comment by gjb2048** [comment]
DO NOT SUBMIT A PR!!!!

The version setting exists in ALL plugins.  There must be a fault on your system as I do not get the notice when debugging.

**Comment by gjb2048** [comment]
I reviewed that line of code when moving to get_setting and it is intentionally unconverted.

**Comment by jpahullo** [comment]
Wow... I cannot figure out how we have disabled such settings. The element `$this->page->theme->settings` appears to be a stdClass with no attribute at all. Any idea/help for this?

Thanks in advance!

**Comment by gjb2048** [comment]
No

**Comment by jpahullo** [comment]
Thank you anyway.
