### ISSUE TITLE
Add setting to set/unset link underline

### ISSUE THREAD

**Issue by julenpardo** [gjb2048/moodle-theme_essential#610]
Hi,

In my faculty, they've asked for underlining the links (only contents' ones, labels, pages, etc., not all) because they are a bit camouflaged, but they don't want to change links' color. So, I've added the CSS for underlining these.

If you find it a suitable feature, I could make a pull request.

Julen

**Comment by gjb2048** [comment]
Just CSS is not a setting.  A setting in settings.php with the conversion of the tag in lib.php etc. is a setting.

All enhancements now need to be funded unless I decide to do them for the technical challenge.

**Comment by julenpardo** [comment]
Yes, sorry for the misunderstanding, I didn't want to refer only to the CSS but to its proper setting in settings.php, etc.

**Comment by gjb2048** [comment]
Time cost: 30 mins coding + probably 1 hour to test that only the places required are actually affected.  Need more information on what should actually be underlined.

**Comment by gjb2048** [comment]
Is this still wanted?

**Comment by gjb2048** [comment]
No reply, closing.
