### ISSUE TITLE
Section names on 'Return to section X'

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_essential#613]
Ref: https://moodle.org/mod/forum/discuss.php?d=327372#p1317815

"display the actual name of the section in a future version (truncated to button-size-convenient length, with the full section name as a hover tooltip)?"

**Comment by gjb2048** [comment]
Estimate at 1.5 hours work with testing.  Given that need to determine when the section name has been set, then its length, then truncate, then tooltip, then update language strings....

**Comment by mifantrax** [comment]
Hi Gareth, how much would that be ? Please PM me.

**Comment by gjb2048** [comment]
Thanks @mifantrax but I can find no way of PM'ing you.

**Comment by gjb2048** [comment]
Implemented in: https://github.com/gjb2048/moodle-theme_essential/commit/d158ee57cf6000cc352a36ecb3cf0fb55da18c0a and https://github.com/gjb2048/moodle-theme_essential/commit/6df2d279955fa3d0ce1465050df3e2c7cfa429d3
