### ISSUE TITLE
Block login on frontpage

### ISSUE THREAD

**Issue by gemguardian** [gjb2048/moodle-theme_essential#615]
Hi Gareth, 
Since awhile now I noticed that the block Login is not padding correct on the frontpage when you have all 3 options open (login, forgotten password and making new account). Setting is fix width-normal. 

I fixed it with custom css: 
.block_login .content.block_login .content {padding: 30px 0px!important} but maybe you want to look into it (when you have the time)

Thank Gemma 

**Screenshots**

![essential_2 9_block_login](https://cloud.githubusercontent.com/assets/16559999/12889403/045fd456-ce7f-11e5-9778-48d3134a7941.png)
![login_block_front_page_essential_fixwidth-normal](https://cloud.githubusercontent.com/assets/16559999/12889406/05ddba8c-ce7f-11e5-8ecb-a0328d95a192.png)

**Comment by gjb2048** [comment]
Hi Gemma,

Does it happen only on M2.9?

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Scenario with new accounts not normally tested:

![2016-02-08 16_10_02-moodle30](https://cloud.githubusercontent.com/assets/1058419/12891132/88ec8bac-ce7e-11e5-9440-a1eaf66aa201.png)

**Comment by gjb2048** [comment]
Can replicate in M3.0: 
![2016-02-08 16_17_36-moodle30](https://cloud.githubusercontent.com/assets/1058419/12891363/91ffa386-ce7f-11e5-95d3-6b355f33c38b.png)

**Comment by gjb2048** [comment]
Fixed in M3.0 will back port to M2.9 before next release.

**Comment by gjb2048** [comment]
Now back-ported to M2.9 version.

**Comment by gemguardian** [comment]
You are way to fast to respond too..:) thanks
