### ISSUE TITLE
Gradebook links are displayed when reports cannot be viewed

### ISSUE THREAD

**Issue by tonyjbutler** [gjb2048/moodle-theme_essential#618]
In the course settings ('Appearance' section) the teacher can choose not to show the gradebook to students. However this is not taken into account by the logic that decides whether or not to display them in the 'activity stream' and 'user' custom menus, so the students can still click the links and are taken to a page with an error message.

**Comment by gjb2048** [comment]
What version of Essential and Moodle please.

Screen shots of how to replicate and error please.

**Comment by tonyjbutler** [comment]
It affects the latest master. I've just pushed a patch, so you can expect a pull request imminently. :-)

**Comment by gjb2048** [comment]
Thanks Tony, I'll look at it when I get a moment.  Please could you supply 'Screen shots of how to replicate the error' so I may confirm that the patch works please.

**Comment by tonyjbutler** [comment]
No problem. You just need to go to a course, edit its settings (Administration->Edit settings->Appearance) and choose not to display the gradebook, then log in as a student and click one of the custom menu grade report links while within the same course.

**Comment by gjb2048** [comment]
Thanks Tony, I'll look at this when I'm free.

**Comment by gjb2048** [comment]
Patch is #619.

**Comment by gjb2048** [comment]
All integrated and tested now, thanks Tony :)
