### ISSUE TITLE
'alternativethemedefaultbuttonbackgroundhovercolourX' setting name too long for 'name' attribute in 'config_plugins' table.

### ISSUE THREAD

**Issue by gemguardian** [gjb2048/moodle-theme_essential#620]
hi Gareth, 
My hosting party who installes plugins on the Moodle enviroments contacted me Friday noting there was a "bug" after the installation. 

After each installation Moodle seems to keep requesting on the new color settings. 
The page http://xxx/admin/upgradesettings.php keeps asking to set the colors, they can only overrule it by http://xxx/?redirect=0 

If you need more information please let me know. 

Gemma

**Comment by gjb2048** [comment]
Hi Gemma,

May I ask a silly question?  Are they clicking on the button to save the settings?

It seems to me like the normal course of events to have a new setting value saved.  But that value is not being stored in the database (standard core functionality) or the database is being reset.

Gareth

**Comment by gemguardian** [comment]
HI Gareth,

I redirected your question and asked them to reply to you. 


Gem

 

Van: Gareth J Barnard [mailto:notifications@github.com] 
Verzonden: maandag 15 februari 2016 11:38
Aan: gjb2048/moodle-theme_essential <moodle-theme_essential@noreply.github.com>
CC: gemguardian <gemma@ltnc.nl>
Onderwerp: Re: [moodle-theme_essential] Moodle 2.9.4| Essential 2.9.1.8 (Build: 2015062421) (2015062421) (#620)

 

Hi Gemma,

May I ask a silly question? Are they clicking on the button to save the settings?

It seems to me like the normal course of events to have a new setting value saved. But that value is not being stored in the database (standard core functionality) or the database is being reset.

Gareth

**Comment by gemguardian** [comment]
Hi Gareth, 
just spoke with them. 

They are clicking on the button to save the setting. 

I asked abit further: 

What they do is, they go to a site http://xxx/admin to see which need to be upgraded. 
When they go to this they keep seeing the screenshot below. 
If they press the button to save they cannot get pass it. 
To overrule it they use: http://xxx/?redirect=0

The weird part is that I did place color settings in the Theme Essential. 
And these don't match if I use the url tp://xxx/admin

Which seems weired. 

What I did is asked them to check on the database, regarding your comment on "it's a normal course of events to have a new setting value saved, but not being stored in the database or the database is being reset" 

I don't have this issue at all on local 3.0. Have you seen it on 2.9? 





![2016-02-15_1352](https://cloud.githubusercontent.com/assets/16559999/13049197/907f26f0-d3eb-11e5-8c56-46919a3e8c33.png)

**Comment by gjb2048** [comment]
Hi Gemma,

Odd that they cannot get past it.  Please could you turn on 'developer level debugging' or get them to look for errors in the PHP log file.

I have never seen this issue.

As a test I'm in the process of updating my test M2.9 remote site to see if I can replicated it.

G

**Comment by gemguardian** [comment]
Hi Gareth, 

Requested them to check with Developer level debuggin on, and checking the PHP files. But my "feeling" says it's on their end - as in a conflict with the database. 

Gem

**Comment by gjb2048** [comment]
Hi Gemma,

I've just replicated the issue on my remote server and now have an idea that the setting value name might be too long.  Thus a theme issue.  Will investigate and get back to you.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Ok, running an SQL query on the database like:

````
SELECT * FROM `vletest`.`mdl_config_plugins` where plugin like 'theme_essential'
````

shows that the setting value for `alternativethemedefaultbuttonbackgroundhovercolour1` etc. is not making it, but locally it is.

**Comment by gjb2048** [comment]
Ok....

Database structure for config_plugins 'name' has a VARCHAR of 100.  With the database charset of UTF-8.  So, therefore 16 instead of 8 bits per character.  The following setting strings are 50+ characters:

alternativethemedefaultbuttonbackgroundhovercolour1
alternativethemedefaultbuttonbackgroundhvrcolour1

but this is 46:

alternativethemedefbuttonbackgroundhvrcolour1

which works, so can only deduce that the character length is an issue.  Might be an MySQL bug, not sure as would have thought VARCHAR(100) would give 100 UTF-8 characters.

**Comment by gjb2048** [comment]
Fix will have to be changing the name of the setting.  Will be slightly annoying but no choice.

**Comment by gjb2048** [comment]
Gemma,

When updating Moodle, did you ever see anything like this: https://moodle.org/mod/forum/discuss.php?d=312136 ?

G

**Comment by gjb2048** [comment]
Note: Moodle 2.9.4| Essential 2.9.1.8 (Build: 2015062421) (2015062421)

**Comment by gemguardian** [comment]
Thanks Gareth - again for your prompt - responds on these things. 

I will ask my hostingparty if they have seen what you have linked. I will get back to you shortly.
