### ISSUE TITLE
Request for an unknown renderer

### ISSUE THREAD

**Issue by kordan** [gjb2048/moodle-theme_essential#627]
Install Essential.
Choose it as current theme.
Change the current theme to the core theme "More".
Change again the current theme to Essential.
This is what I get.

 Coding error detected, it must be fixed by a programmer: Request for an unknown renderer theme_more, core, general
Debug info:
Error code: codingerror
Stack trace:

    line 445 of /lib/outputfactories.php: coding_exception thrown
    line 1833 of /lib/outputlib.php: call to theme_overridden_renderer_factory->get_renderer()
    line 812 of /lib/pagelib.php: call to theme_config->get_renderer()
    line 176 of /theme/essential/classes/toolbox.php: call to moodle_page->get_renderer()
    line 203 of /theme/essential/classes/toolbox.php: call to theme_essential\toolbox::check_corerenderer()
    line 27 of /theme/essential/layout/admin.php: call to theme_essential\toolbox::get_tile_file()
    line 1016 of /lib/outputrenderers.php: call to include()
    line 946 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 69 of /theme/index.php: call to core_renderer->header()

I am not sure if this is a problem of Essential or related to More.

**Comment by kordan** [comment]
I just installed last release for moodle 3.

**Comment by gjb2048** [comment]
Last release being 3.0.1?

**Comment by gjb2048** [comment]
Cannot be as line numbers in toolbox.php do not match the ones in 3.0.1 for those calls.

**Comment by kordan** [comment]
Yes it is 3.0.1!
I added the patch to resize the slide show that you don't like.
Using a clean copy of the theme the error is:
Debug info:
Error code: codingerror
Stack trace:

    line 445 of /lib/outputfactories.php: coding_exception thrown
    line 1833 of /lib/outputlib.php: call to theme_overridden_renderer_factory->get_renderer()
    line 812 of /lib/pagelib.php: call to theme_config->get_renderer()
    line 159 of /theme/essential/classes/toolbox.php: call to moodle_page->get_renderer()
    line 186 of /theme/essential/classes/toolbox.php: call to theme_essential\toolbox::check_corerenderer()
    line 27 of /theme/essential/layout/admin.php: call to theme_essential\toolbox::get_tile_file()
    line 1016 of /lib/outputrenderers.php: call to include()
    line 946 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 69 of /theme/index.php: call to core_renderer->header()

**Comment by gjb2048** [comment]
Thanks for the information.

Its not that I don't 'like' the resize idea, its just I've been having a 'lot' of bad experiences with other peoples code.  I integrate it then after releasing, find bugs then more bugs then more bugs.  As the logic is found to be incomplete.  This takes me time, lots of it.  Its not so bad when I rectify my mistakes.  Therefore if I agree to a bit of code going in then I have to be sure its correct and that any mistakes I then have to correct I know its because I did not check it enough.
