### ISSUE TITLE
Increase performance of administration settings pages

### ISSUE THREAD

**Issue by Dagefoerde** [gjb2048/moodle-theme_essential#633]
Thanks for developing and maintaining such a great Moodle theme! We are running a customized version of it and we are very happy that we could base our work on it.

Ever since the theme is installed on our servers, I noticed that the performance of some workflows has become worse, i.e. that loading times have increased. I have set out to find the underlying problems and I'd like to share my findings and possible solutions. Please correct me if my findings are wrong, though. :)

I am starting with this issue, since it possibly has the largest impact on performance:  
The theme's `settings.php` file is included **at every page load within Moodle's administration area**, since Moodle assembles the settings / administration menu by including the `settings.php` files of active plugins. For example, for themes, this happens in `admin/settings/appearance.php` using `include($settings_path);`. Each time it is included, **all settings are added and all their values are loaded**. However, usually Moodle is only interested in the pages that should be added to the menu.

Most themes start their `settings.php` by testing for `if ($ADMIN->fulltree) {` (cf. https://docs.moodle.org/dev/Creating_a_theme_settings_page#Creating_the_settings_page or https://github.com/moodle/moodle/blob/a2161d57a4a07c2f34956b6733fea3bd068c39f0/theme/clean/settings.php#L33 for an actual theme). `$fulltree` is only `true` if all settings are required. Otherwise, i.e. if `settings.php` should only add pages to the menu, `$fulltree` is false (cf. https://github.com/moodle/moodle/blob/a2161d57a4a07c2f34956b6733fea3bd068c39f0/lib/adminlib.php#L1127). Therefore, if it is `false`, the individual settings should just be omitted.

However, Essential never checks `$ADMIN->fulltree`. Therefore, every single setting is processed whenever `settings.php` is included, i.e. at every page load. This includes loading all setting values and even formatting some of them, which is both CPU intensive and memory intensive.

Of course we cannot simply replace Essential's `if (is_siteadmin())` (https://github.com/gjb2048/moodle-theme_essential/blob/338d79a/settings.php#L30) with this, because then none of Essential's setting pages were available to the user. However, for each page, `$ADMIN->fulltree` should be checked before adding the values.

I will submit a pull request later that illustrates my point.

**Comment by Dagefoerde** [comment]
Here is the output of two profiling runs for a page that includes Essential's settings.php but does not require any setting values:

![profiling_settings](https://cloud.githubusercontent.com/assets/432117/13674965/d5be85d8-e6df-11e5-84f5-29c4986e3f71.png)

First line: Memory & CPU requirements without checking `$ADMIN->fulltree`, second line: with **added checks for** `$ADMIN->fulltree`.

You can see that – in my particular example, which is probably not representative – _CPU time_ for the page has nearly halved and _Memory used_ is reduced by 6 MB.

**Comment by gjb2048** [comment]
So to cut a long story short, you want:

````
if ($ADMIN->fulltree) {
....
}
````

added.

**Comment by Dagefoerde** [comment]
Basically, yes. But since you still need to declare the pages in that file, I believe that is not sufficient. Right now, you would need to add this line 11 times, i.e. once per page. My suggestion will follow :)

**Comment by gjb2048** [comment]
Needs refactoring.

**Comment by gjb2048** [comment]
Refactored in: https://github.com/gjb2048/moodle-theme_essential/commit/a45f2b5b6b2501ab7d3068cb98ba11651d032a4d
