### ISSUE TITLE
Increase performance of icon rendering functions

### ISSUE THREAD

**Issue by Dagefoerde** [gjb2048/moodle-theme_essential#634]
The `core_renderer` class contains two functions that deal with rendering and replacing Moodle icons for the Essential theme: `render_pix_icon(pix_icon $icon)`  and `replace_moodle_icon($icon, $alt = false)`.

Both methods need improvement:
1. `render_pix_icon` calls `replace_moodle_icon` twice. The result of the first call is basically thrown away if successful, since the `alt` text was not passed into it (otherwise we could already use the output). In the second call, only the `alt` text is added. This _should_ be reduced to one call that already contains the `alt` text.
2. `replace_moodle_icon` probably is expensive. It starts by defining a local array `$icons` containing the mapping from Moodle icons to Essential/FontAwesome icons. This array is constant – it is never altered later on. Consequently, at each call to this method PHP always allocates space for the entire array, writes the values and discards everything shortly after. This array _should_ be initialised _exactly once_ and stay available to the method.

The double-call described in (1) gains importance considering how expensive `replace_moodle_icon` is. _However,_ it is possible that PHP detects and optimizes the problem of (2) automatically, but I would not rely on that.

I will submit a pull request later that illustrates my ideas to solve this.   
(That's it for now; if I discover more things I will report them as well. Thanks @gjb2048 and other developers, keep up the good work!)

**Comment by gjb2048** [comment]
In other words, you want the result of the call to 'replace_moodle_icon' stored so that is only called once.

P.S.  There are no other developers, only me now.

**Comment by Dagefoerde** [comment]
Not exactly: Yes, I would like to call it only once instead of twice. There is no need for caching however, it is just that the second call can be avoided (see my first commit `e778d2e`).

Second, I would prefer if the replacements array were not initialised at every single call to `replace_moodle_icon`: I am guessing that this repeatedly causes memory allocation and deallocation. (This is fixed by my second commit `662e7c2`).

Thanks for reviewing :)

**Comment by gjb2048** [comment]
https://github.com/gjb2048/moodle-theme_essential/commit/38e07bd75d3002897aff9dee5628885c999cf46d far better solution than #637 and overridable if needed.
