### ISSUE TITLE
Edit profile style not set properly

### ISSUE THREAD

**Issue by martinvivek** [gjb2048/moodle-theme_essential#640]
There is a small bug in the user menu (Edit profile) as shown in the image
![untitled](https://cloud.githubusercontent.com/assets/7712010/13810351/6997c0da-eb95-11e5-94fd-df4e32ae1785.png)

I think there is a issue in the line 
https://github.com/gjb2048/moodle-theme_essential/blob/master/classes/output/core_renderer.php#L1174

where it has to be 
$branchlabel = '<em>'.$this->getfontawesomemarkup('info-circle').get_string('editmyprofile').'</em>';

Sorry if i am wrong. and Thanks for the great theme.

**Comment by gjb2048** [comment]
Thanks Martin, I must have missed that!  There was another one which I spotted and fixed, then checked them all.  Odd!
