### ISSUE TITLE
Navigation bar in course: without course category links

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#647]
Hi Gareth,

this is a feature request: when a moodle installation has a lot of categories, there are too much information in the navigation bar.

![screenshot-2016-04-04-09-26-53](https://cloud.githubusercontent.com/assets/5286499/14240785/d81295b0-fa47-11e5-9d45-2ddafa35d535.jpg)

Is it possible to add a setting to the essential theme, e.g. "Short navigation bar", that does not display the course category links in the navi bar (just in the course)?

If yes: how long would it take, what would it cost? You can send me also a private message to: christian.niemczik@gmail.com

Thank you and all the best,

Christian

**Comment by gjb2048** [comment]
Implemented in: https://github.com/gjb2048/moodle-theme_essential/commit/9447ba9177e9240f234077ef0242af46964f8394

Note to self, in next commit, change 'FIX' to 'NEW'.

**Comment by relecand** [comment]
Hi Gareth,

thank you for this quick implementation!

Just one issue: 
- the nav bar without categories works an the course main page
- when I open an activity or ressource (forum, test etc) the nav bar still contains the categories

Testet with 2.9 

All the best,

Christian

**Comment by gjb2048** [comment]
Hi Christian,

Oh!  I took your words literally.  I need to modify the code for the 'incourse' layout.  I'll do that ASAP.

Gareth

**Comment by gjb2048** [comment]
Hi Christian,

This: https://github.com/gjb2048/moodle-theme_essential/commit/3c2ad2ddfaa7743666a533fa5c6f73b4e7160d22 should do the trick.  Tested in M2.9.

Gareth

**Comment by relecand** [comment]
Hi Gareth,

yes, I think I didn't described it clear enough. Your patch did the trick!

Thank you!
