### ISSUE TITLE
Checkbox in the forms are not lined up

### ISSUE THREAD

**Issue by martinvivek** [gjb2048/moodle-theme_essential#648]
The checkbox in the forms are not lined up properly, refer the below screenshot. it may be a small css issue.
Moodle 3.0.2
Essential - 3.0.1.2

![checkbox](https://cloud.githubusercontent.com/assets/7712010/14306414/8665ab64-fbe4-11e5-9ee4-880911ad7fc7.jpg)

**Comment by gjb2048** [comment]
That does not look like a core form.  Does it happen in a core form?  If so, which one and how do I get to it?

**Comment by martinvivek** [comment]
For a example if we include a checklist for the user profile field it occurs, and what i shown in the screen shot is belongs to facetoface plugin.  see the edit profile screen with the custom profile field check box.

![checkbox](https://cloud.githubusercontent.com/assets/7712010/14312916/29e32fba-fc0c-11e5-820d-779dbe4576db.jpg)

**Comment by martinvivek** [comment]
In forum settings

![checkbox](https://cloud.githubusercontent.com/assets/7712010/14313003/b647f62a-fc0c-11e5-881c-66c91ab97036.jpg)

**Comment by gjb2048** [comment]
Cannot replicate:

![2016-04-06 12_04_10-editing forum](https://cloud.githubusercontent.com/assets/1058419/14314550/c9d334d8-fbef-11e5-86e9-1b7303d0a8ad.png)

**Comment by martinvivek** [comment]
Sorry to trouble you, It was the problem with the mod_booking Plugin. In adaptable theme it is working fine so u thought it was the theme issue.  thanks for the support.
