### ISSUE TITLE
Style Sheet could not be loaded

### ISSUE THREAD

**Issue by verzog** [gjb2048/moodle-theme_essential#650]
HI Gareth,
Getting the (Non critical) error Style Sheet could not be loaded: https:/ .../theme/styles.php/essential/xxxxxx/all

It seems to be related to the amount of CSS in the "Custom CSS" area. Is there a limit to the amount one can add here?

Cheers,
Vernon

**Comment by gjb2048** [comment]
Probably iffy CSS that is causing the core minifier to fail.  Core / your CSS issue / probably is a limit.  Not an Essential issue!
