### ISSUE TITLE
Bug on change password menu link

### ISSUE THREAD

**Issue by lionphilips** [gjb2048/moodle-theme_essential#651]
When I try to change my password using the top menu, the link is broken.
I got the message "You are trying to use a ID of invalid course".

My fix was remove the ID from URL, because the ID is on session and is not required.

Info:
File:  theme/essential/renderers/core_renderer.php (Line 759)

Changes:
- Before
$branchurl = new moodle_url('/login/change_password.php', array('id' => $USER->id));
- After
$branchurl = new moodle_url('/login/change_password.php');

**Comment by gjb2048** [comment]
What version of Essential please?

**Comment by gjb2048** [comment]
Looking at the code this issue only happened in the M2.5 version.  M2.6+ do not have the issue.  Therefore out of date version that I no longer maintain.

**Comment by lionphilips** [comment]
Yes, it happened in 2.5 version.
Thanks!
