### ISSUE TITLE
Header logo and background refinements.

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_essential#652]
In: https://github.com/gjb2048/moodle-theme_essential/commit/f21d340dbdfc2c4da05ba931a54ca9c2736a3188 a width was added so that the header would be better suited and adaptable when the social networks and mobile apps icons were added rather than the 'guess' of 'ecol7' class on the wrapping 'div'.

This resulted in better functionality here but at the detriment of a responsive logo.

**Comment by gjb2048** [comment]
Humm, spent a while, width I think is really needed and the report that sparked the issue was down to a really wide logo.  Perhaps in that circumstance the 'headerbackground' setting would be better and the logo should be a small fixed entity.

**Comment by gjb2048** [comment]
Need to think if its a bug or in reality the user should have used the 'headerbackground' setting for their purpose instead of the 'logo' setting.

**Comment by gjb2048** [comment]
Also looking at things the outer floats are not needed for LTR / RTL switching.

**Comment by gjb2048** [comment]
However, if the 'headerbackground' is used then potentially need an option not to show the logo and the title icon at all.

**Comment by gjb2048** [comment]
background-repeat: no-repeat;
background-position: center;
background-size: contain;

and use background-image

**Comment by gjb2048** [comment]
But when a new setting that indicates if the image should be repeated or not.  Thus if so then as currently is but if not then the no-repeat and others like position etc. need to discover best solution.

**Comment by gjb2048** [comment]
Also take 'titlearea' into account!

**Comment by gjb2048** [comment]
Humm, floats are needed when using an icon, best leave as is.

**Comment by gjb2048** [comment]
Really an enhancement.

**Comment by gjb2048** [comment]
Humm, bug with the backgroundheader.

**Comment by dschwa** [comment]
Upgraded my sandbox from 2.8.5 to 2.9+ and Essential 2015062425 	2.9.1.12 (Build: 2015062425)
Sandbox site is not public accessible 

No links work in header. Scroll down and what should be the header links (my courses, profile, social) are actually the links from items that are behind the header after scroll.
Live site on 2.8 for reference minerva.osteopathic.org

My logo is 430 x 55 (Logo with Organization text) 
I'm trying moving the logo to a header background but that wants to be centered. Used custom css to move it left. It would be fine if I was using variable width, but we used a fixed-width wide. The logo goes to the left of the theme. I'll play with css some more but this really is odd that changing the logo size should mess things up so much when it was perfect in 2.8

Let me know if you want me to record the behaviors.

First image is how it should look. But no header links work. Scroll down a bit and hover a header link and it is actually serving the link from the slide show
![essential_header_logo](https://cloud.githubusercontent.com/assets/7027431/14858345/c49d89da-0c6d-11e6-8e55-a6843dd68812.jpg)

Second image is logo as header background position left. All header links work
![essential_header_bac_left](https://cloud.githubusercontent.com/assets/7027431/14858355/cf967f5e-0c6d-11e6-9432-8fcd256225f4.jpg)

**Comment by gjb2048** [comment]
Hi @dschwa,

This issue is 'closed' if you have evidence of specific issues then please raise another one.  Please remove any Custom CSS you have to address the issues as the code could be wrong and invalidate any evidence.  I assume that you have set all of the appropriate logo width and height settings.  Also you could make use of the page heading background with its new features rather than using an image that combines both concepts.

Additionally, if I am unable to view your sandbox site then I'm guessing in the dark and then cannot investigate to determine if indeed it is an Essential issue or site specific.   If the latter then there would be a fee for any support information I would then provide.

Kind regards,

Gareth
