### ISSUE TITLE
Quiz question preview: does not uses the selected color scheme

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#653]
Hi Gareth,

a small issue in essential theme 2.9.1.5.2:

1. Select an alternative color scheme
2. Create a quiz
3. Create a question in this quiz
4. Click on question preview

You will see, that selected color scheme is not used (instead the standard scheme).

![screenshot-2016-04-22-11-10-52](https://cloud.githubusercontent.com/assets/5286499/14737443/54a401f8-087c-11e6-86e1-35e83baba529.jpg)

**Comment by gjb2048** [comment]
Hi relecand,

That is a really out of date version and a lot has happened since then, especially with alternative colours.  The current version is 2.9.1.11.  I will not investigate issues in past versions unless paid to do so.

Cheers,

Gareth

**Comment by relecand** [comment]
Hi Gareth, 

thank you for your answer. My mistake - I was using 2.9.1.11 - now 2.9.1.12. The issue remains.

All the best,

Christian

**Comment by gjb2048** [comment]
Hi Christian,

The M2.9 and M3.0 versions are functionally identical so will try and replicate there first.

Gareth

**Comment by gjb2048** [comment]
Bug in M3.0 too... investigating why.

**Comment by gjb2048** [comment]
Body class missing 'essential-colours-alternative3' class etc.

**Comment by gjb2048** [comment]
Hi Christian,

Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/fb06ec123630ed9d9329cca1363e590b4b2fc12d on M3.0.  I will back-port to M2.9 before the next official release for M2.9.  If you want to patch your code now, then the changes should work.

Kind regards,

Gareth

**Comment by relecand** [comment]
Wow - that was fast! Thank you!!
