### ISSUE TITLE
Adding a quiz question menu does not use the selected colour scheme

### ISSUE THREAD

**Issue by relecand** [gjb2048/moodle-theme_essential#654]
Hi Gareth,

maybe related to #653 

1. Select an alternative color scheme
2. Turn editing on
3. Configure a block

![screenshot-2016-04-22-15-11-21](https://cloud.githubusercontent.com/assets/5286499/14742755/0b58d088-089e-11e6-81f3-82425558108e.jpg)

1. Select an alternative color scheme
2. Create a quiz
3. Add a new question to the quiz

![screenshot-2016-04-22-15-14-16 1](https://cloud.githubusercontent.com/assets/5286499/14742772/2dd9bca8-089e-11e6-800f-a80d01821417.jpg)

![screenshot-2016-04-22-15-14-28](https://cloud.githubusercontent.com/assets/5286499/14742776/3393e3f8-089e-11e6-8dc8-1d90ca603e9c.jpg)

Thank you and all the best,

Christian

**Comment by gjb2048** [comment]
This is two issues!

**Comment by gjb2048** [comment]
Cannot replicate first, but can replicate second in quiz.

**Comment by gjb2048** [comment]
Hi Christian,

Fixed in: https://github.com/gjb2048/moodle-theme_essential/commit/53744583d80b98adeaf9d5798c79338d12703595 on M3.0.  Will back-port to M2.9 in due course.

Kind regards,

Gareth

**Comment by relecand** [comment]
Hi Gareth,

thank you very much!

All the best,

Christian
