### ISSUE TITLE
Moodle with SSL and Essential

### ISSUE THREAD

**Issue by rosimittermeier** [gjb2048/moodle-theme_essential#656]
hi, when trying to make my moodle platform working with ssl all the icons, colours and css of the essential theme is lost. in general the platform works theoretically, but is looks confuse since the essential theme is not realized. is it a bug or a problem of the theme -- or is an error on my side more probable?

**Comment by sympo** [comment]
Have you changed `wwwroot` in config.php to `https://`? I vaguely remember my installation looking like this before I finished with all config changes.

**Comment by rosimittermeier** [comment]
yes i have

**Comment by gjb2048** [comment]
I run my test environment on HTTPS so not an issue with the theme.  What version are you using?

**Comment by rosimittermeier** [comment]
i work with 3.0.4 -- i will try to find the error. i just wanted to exculde problems of the theme. THANKS!!!

**Comment by gjb2048** [comment]
And what version of Essential?

**Comment by rosimittermeier** [comment]
everything is up to date: 3.0.1.2

**Comment by gjb2048** [comment]
So is this really a bug with the theme?

**Comment by rosimittermeier** [comment]
i dont know.
