### ISSUE TITLE
Links with anchors don't work with the "flexsections" course format.

### ISSUE THREAD

**Issue by jk3us** [gjb2048/moodle-theme_essential#659]
In v3.0.1.2, if you are using the flexsections course format (https://github.com/marinaglancy/moodle-format_flexsections) with collapsed sections, there is a bit of javascript that breaks the links that take you from a section page back to the course.  The section page (at `.../course/view.php?id=71&sectionid=1084`) has a link that looks like `.../course/view.php?id=71&section=0#section-2`, but clicking the link scrolls the page so that this link is at the top instead of taking you back to the course page.  I think this happens at https://github.com/gjb2048/moodle-theme_essential/blob/V3.0.1.2/amd/src/course_navigation.js#L30, but I can't make it stop by commenting it out, so I could be wrong.  

More generally, it's probably the case that any link to another page with an #anchor is going to be broken by that click handler.

**Comment by gjb2048** [comment]
So if the line https://github.com/gjb2048/moodle-theme_essential/blob/V3.0.1.2/amd/src/course_navigation.js#L30 is commented out and the resulting minified version is recreated, what happens to the functionality?  Umm, it does not work!  And then 'course_navigation.js' has no purpose but to waste CPU cycles.  Thus you are correct that you are wrong.  So, what is the solution in your opinion please?

Pragmatically with all of the possible combinations of contributed plugins, it is impossible to test them all.  Of all the course formats, flexsections is the one I dislike the most.

**Comment by gjb2048** [comment]
Additionally, any other page with an anchor will not be affected because of: https://github.com/gjb2048/moodle-theme_essential/blob/master/layout/tiles/additionaljs.php#L35-L37 - thus please give me some credit.  I am not stupid.

**Comment by jk3us** [comment]
Ah, so commenting out that click handler and running `grunt amd` does make the problem go away, sorry about that.  The section pages still run that code, so apparently the section pages still have pagelayout == 'course'.  

I reproduced this without flexsections by just putting a link to a section in _another_ course in the description of a section.  Clicking the link scrolls to that section _of the current course_ instead of going to the proper page.

A quick solution I found was to check if the "base" of the href (without the hash part) was different from location.href, and if so return from the function before preventDefault(), allowing the normal link behavior to work.  This won't do the smooth scroll for some relative links that point to the current page and probably some other cases I haven't thought of yet, but could be the start of a fix:

```
                     $(this).click(function(e) {
-                        e.preventDefault();
                         var url = $(this).attr('href');
+                        if (url.substring(0,url.indexOf('#')) != location.href.substring(0,url.indexOf('#'))) {
+                            return;
+                        }
+                        e.preventDefault();
                         log.debug('Essential Course Navigation AMD navigation element url: ' + url);
```

Hope this helps.

**Comment by gjb2048** [comment]
Ok, I think this covers all the bases: https://github.com/gjb2048/moodle-theme_essential/commit/99f3b06687e721a5e3e31443896eb2837ade6111.

**Comment by relecand** [comment]
Hi Gareth, is it possible that you merge this commit with the Moodle 2.9 branch? All the best, Christian

**Comment by gjb2048** [comment]
Yes.  I keep the two in sync and will happen in due course.
