### ISSUE TITLE
Moodle 3.1 Version

### ISSUE THREAD

**Issue by dschwa** [gjb2048/moodle-theme_essential#661]
I'm sandboxing a site on 3.1 and would love to use Essential. I can wait a few days but just wondering when the 3.1 version is expected.

If it's a few weeks out I may just tweak the version in order to build out the design

thanks

**Comment by gjb2048** [comment]
Hi,

The M3.1 version will take several days to create.  The M3.0 version was funded.  Would you be so kind as to fund my time for the M3.1 version?

Thanks,

Gareth

**Comment by dschwa** [comment]
Gareth, I'd rather just help you out with a general donation. I was just thinking of kicking in a small amount since I'm an indi consultant much like you.

I use the theme on 1 client so far and hope to be using it for 2 more within the next month.

ds

**Comment by gjb2048** [comment]
Hi DS,

Thank you for your reply and offer of a donation.  I'm planning (although not even started yet as iMoot and paid work before that) with running a crowd funding campaign like last time: http://www.moodlegarage.com/ - will be less as I made some improvements to make the process easier.  Perhaps you would be so kind as to be one of the funders when that happens?

Cheers,

Gareth

**Comment by marcocevoli** [comment]
Do you have an ETA for the new release and can you state how much money is needed?

Thanks in advance
Marco

**Comment by gjb2048** [comment]
Hi Marco,

1. No ETA yet, see 2.
2. Not worked out how much work is needed yet in order to determine how much money is needed.

I'll do this probably some time next week after iMoot 2016 and other contracts finish.

Cheers,

Gareth

**Comment by rjones578** [comment]
Hi Gareth,

Do you know if the current Essential 3.0 is compatible with Moodle 3.1?
Please do let us know about costs for the 3.1 update, we would be interested in helping out as Essential has been very helpful to us over the last year or so :-)

**Comment by gjb2048** [comment]
Hi rjones,

It may work but there will be issues with it.  There is already an
outstanding bug with the version.  I know there is also new M3.1 core
functionality to add.

Thank you for your offer of help.  At the moment I'm looking at
crowdfunding the update, please see:
https://moodle.org/mod/forum/discuss.php?d=334052.  Currently my estimate
of the time cost is between 450 and 500 GBP.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Crowdfunding now live: http://www.moodlegarage.com/

**Comment by gjb2048** [comment]
Note: Development in https://github.com/gjb2048/moodle-theme_essential/tree/master_bsb branch.
