### ISSUE TITLE
Site pages indent

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_essential#662]
Ref: https://moodle.org/mod/forum/discuss.php?d=333557

Site pages on navigation block are incorrectly indented.

**Comment by gjb2048** [comment]
Reopened as a reminder to back-port.

**Comment by nadavkav** [comment]
I just saw this on latest Moodle 3.1 + Essential 3.0.1.2 (in RTL mode too)
![image](https://cloud.githubusercontent.com/assets/231168/15607979/72acbf6e-241f-11e6-8ccd-a379c112ad90.png)
I have marked the CSS that need to be fixed.

**Comment by gjb2048** [comment]
Hi Nadav,

The patch should fix RTL too.

G

**Comment by nadavkav** [comment]
I have upgraded the theme to 3.0.1.3 (Build: 2016010206) , but it did not fix the issue.
I have also noticed the FA icons are missing. 
See attached screen capture of block administration (settings):
![image](https://cloud.githubusercontent.com/assets/231168/15614759/2a21826a-2443-11e6-90dc-7b17e35d9350.png)

**Comment by nadavkav** [comment]
Here is a fix:
```
.block_settings .block_tree [aria-hidden="true"] {
    display: inline-block;
}
.block_settings .block_tree p.hasicon {
    text-indent: 0;
}
```
![image](https://cloud.githubusercontent.com/assets/231168/15614941/233e2362-2444-11e6-9de4-ce6d9bb96ac9.png)

**Comment by nadavkav** [comment]
Fixes RTL too

**Comment by gjb2048** [comment]
Hi Nadav,

Thanks, but the screen-shots do not relate to the actual problem.

Cheers,

Gareth

**Comment by nadavkav** [comment]
You are right. I got carried away. (the missing icons is a different issue)

**Comment by gjb2048** [comment]
Hi Nadav,

Cannot replicate Administration block issue.

G

**Comment by gjb2048** [comment]
Block needs tidying up though.
