### ISSUE TITLE
Broken Alt-text in blocks

### ISSUE THREAD

**Issue by cdipe** [gjb2048/moodle-theme_essential#664]
Using Moodle 3.04+ and Essential 3.0.1.2

The title text shown when hovering over the docking controls Dock and Undock is broken. I think this is in the theme, since they look OK when switching to Clean theme.

![essential 3](https://cloud.githubusercontent.com/assets/14754240/15668358/2963ec52-271b-11e6-957c-3252f9567c30.png)

![essential 2](https://cloud.githubusercontent.com/assets/14754240/15668360/29910ea8-271b-11e6-93d0-816a9304f18d.png)

![essential 1](https://cloud.githubusercontent.com/assets/14754240/15668359/2990de7e-271b-11e6-921a-46cead771c45.png)

**Comment by gjb2048** [comment]
M2.9 too.

**Comment by gjb2048** [comment]
Need to back-port to M2.9 - still close as will happen.

**Comment by gjb2048** [comment]
Backports are open!
