### ISSUE TITLE
Course page header missing enrolled user info

### ISSUE THREAD

**Issue by lazydaisy** [gjb2048/moodle-theme_essential#668]
Looks like the <?php echo $OUTPUT->full_header(); ?> is not being used in Essential.
There is a renderer for this in ourputrenderers.php
See discussion in Themes Forum
https://moodle.org/mod/forum/post.php?reply=1346354#mformforum

**Comment by gjb2048** [comment]
Link is a post reply, better one: https://moodle.org/mod/forum/discuss.php?d=334191

**Comment by lazydaisy** [comment]
Ooops sorry I thought I had linked to the actual post!

**Comment by gjb2048** [comment]
No worries, trickier to solve than I thought.
