### ISSUE TITLE
Course is blank after a brand new installation of moodle and the theme - 2016010208

### ISSUE THREAD

**Issue by demontech** [gjb2048/moodle-theme_essential#670]
I have a brand new installation of moodle 3.0. I installed the theme, and I create a course. The course is blank. I have purge all the caches but not success. This is happening with 3 different browsers.
Other themes are displaying the courses fine.

![image](https://cloud.githubusercontent.com/assets/8148238/15983364/0f17f18a-2f5a-11e6-9ee9-5a814594a4ff.png)

**Comment by gjb2048** [comment]
What exact version of Moodle and Essential?  Please give full details of the environment and other contributed plugins.  Plus details of any errors in the php.log file before I investigate.

**Comment by gjb2048** [comment]
I see that you are using a custom font too.  What is it and how do I configure it?

Additionally, I've replied within two hours at a weekend and after seven there is no reply.

**Comment by demontech** [comment]
Hi Gareth,
Thank you for your response. The moodle version is 3.0.4+ and the theme Essential is 2016010208.

This is brand new installation and not extra plugins were installed. The font is Raleway from Google web fonts, as a matter of fact, the previous version of theme was working perfectly fine. When I click on "Turn editing on" page is displayed.

**Comment by gjb2048** [comment]
Thank you for replying, do you happen to know the previous version of the theme please?

**Comment by gjb2048** [comment]
Are there any errors in the php.log file?

**Comment by gjb2048** [comment]
Ref: Moodle 3.0.4+ (Build: 20160603) - Essential 3.0.1.3 (Build: 2016010206) - install from scratch at the same time.

**Comment by gjb2048** [comment]
Ok,

Clean install (versions as above).  Installed Essential from downloaded ZIP from plugins DB.  Set Essential as the theme.  Changed to Google fonts and set 'Raleway' as both the heading and text fonts.  Created a course in Misc... category called Test with the Weeks format.  Did not enrol any users and proceeded to course content.  Course displayed correctly.

No bug or fault to rectify given the scenario reported.

Will close and only reopen if new evidence comes to light.

**Comment by demontech** [comment]
OK,

Here's what happened, since the new version has "category course title images" and enable by default. If this disable the course page is fine or if this is enable a picture has to be in the correspondent course.

**Comment by gjb2048** [comment]
Ok,

In my test version as "category course title images" is enabled by default on a clean install and I 'cannot' replicate.  You now say "If this disable the course page is fine or if this is enable a picture has to be in the correspondent course, otherwise, the course shows blank." but earlier you stated that it was the state of 'editing' that caused the problem.  I'm starting to disbelieve what you say.

For the third time of asking: Are there any ERRORS IN THE PHP.LOG FILE?

**Comment by gjb2048** [comment]
What are you not telling me?  Are you typing anything in the course summary?  If so, what!

**Comment by demontech** [comment]
No errors on the php.log file - Course Summary is empty

**Comment by gjb2048** [comment]
Ok, please do a 'view source' on the problem page and post the code here.

**Comment by gjb2048** [comment]
What version of PHP are you running on what OS please?

**Comment by demontech** [comment]
5.6 on Linux

**Comment by gjb2048** [comment]
Now the markup please.

**Comment by demontech** [comment]
<!DOCTYPE html>
<html  dir="ltr" lang="en-us" xml:lang="en-us" class="no-js">
<head>
    <title>Course: Class Locations and Schedules</title>
    <link rel="shortcut icon" href="//bhmt.alamom.com/pluginfile.php/1/theme_essential/favicon/1465680227/favicon.ico"/>
    <link rel="stylesheet" href="//bhmt.alamom.com/pluginfile.php/1/theme_essential/style/1465680227/essential.css"><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="moodle, Course: Class Locations and Schedules" />
<link rel="stylesheet" type="text/css" href="http://bhmt.alamom.com/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.css" /><script id="firstthemesheet" type="text/css">/** Required in order to fix style inclusion problems in IE with YUI **/</script><link rel="stylesheet" type="text/css" href="http://bhmt.alamom.com/theme/styles.php/essential/1465680227/all" />
<script type="text/javascript">
//<![CDATA[
var M = {}; M.yui = {};
M.pageloadstarttime = new Date();
M.cfg = {"wwwroot":"http:\/\/bhmt.alamom.com","sesskey":"uEFj5NdG2R","loadingicon":"http:\/\/bhmt.alamom.com\/theme\/image.php\/essential\/core\/1465680227\/i\/loading_small","themerev":"1465680227","slasharguments":1,"theme":"essential","jsrev":"1465622294","admin":"admin","svgicons":true};var yui1ConfigFn = function(me) {if(/-skin|reset|fonts|grids|base/.test(me.name)){me.type='css';me.path=me.path.replace(/\.js/,'.css');me.path=me.path.replace(/\/yui2-skin/,'/assets/skins/sam/yui2-skin')}};
var yui2ConfigFn = function(me) {var parts=me.name.replace(/^moodle-/,'').split('-'),component=parts.shift(),module=parts[0],min='-min';if(/-(skin|core)$/.test(me.name)){parts.pop();me.type='css';min=''};if(module){var filename=parts.join('-');me.path=component+'/'+module+'/'+filename+min+'.'+me.type}else me.path=component+'/'+component+'.'+me.type};
YUI_config = {"debug":false,"base":"http:\/\/bhmt.alamom.com\/lib\/yuilib\/3.17.2\/","comboBase":"http:\/\/bhmt.alamom.com\/theme\/yui_combo.php?","combine":true,"filter":null,"insertBefore":"firstthemesheet","groups":{"yui2":{"base":"http:\/\/bhmt.alamom.com\/lib\/yuilib\/2in3\/2.9.0\/build\/","comboBase":"http:\/\/bhmt.alamom.com\/theme\/yui_combo.php?","combine":true,"ext":false,"root":"2in3\/2.9.0\/build\/","patterns":{"yui2-":{"group":"yui2","configFn":yui1ConfigFn}}},"moodle":{"name":"moodle","base":"http:\/\/bhmt.alamom.com\/theme\/yui_combo.php?m\/1465622294\/","combine":true,"comboBase":"http:\/\/bhmt.alamom.com\/theme\/yui_combo.php?","ext":false,"root":"m\/1465622294\/","patterns":{"moodle-":{"group":"moodle","configFn":yui2ConfigFn}},"filter":null,"modules":{"moodle-core-blocks":{"requires":["base","node","io","dom","dd","dd-scroll","moodle-core-dragdrop","moodle-core-notification"]},"moodle-core-tooltip":{"requires":["base","node","io-base","moodle-core-notification-dialogue","json-parse","widget-position","widget-position-align","event-outside","cache-base"]},"moodle-core-formchangechecker":{"requires":["base","event-focus"]},"moodle-core-handlebars":{"condition":{"trigger":"handlebars","when":"after"}},"moodle-core-notification":{"requires":["moodle-core-notification-dialogue","moodle-core-notification-alert","moodle-core-notification-confirm","moodle-core-notification-exception","moodle-core-notification-ajaxexception"]},"moodle-core-notification-dialogue":{"requires":["base","node","panel","escape","event-key","dd-plugin","moodle-core-widget-focusafterclose","moodle-core-lockscroll"]},"moodle-core-notification-alert":{"requires":["moodle-core-notification-dialogue"]},"moodle-core-notification-confirm":{"requires":["moodle-core-notification-dialogue"]},"moodle-core-notification-exception":{"requires":["moodle-core-notification-dialogue"]},"moodle-core-notification-ajaxexception":{"requires":["moodle-core-notification-dialogue"]},"moodle-core-languninstallconfirm":{"requires":["base","node","moodle-core-notification-confirm","moodle-core-notification-alert"]},"moodle-core-checknet":{"requires":["base-base","moodle-core-notification-alert","io-base"]},"moodle-core-formautosubmit":{"requires":["base","event-key"]},"moodle-core-event":{"requires":["event-custom"]},"moodle-core-maintenancemodetimer":{"requires":["base","node"]},"moodle-core-popuphelp":{"requires":["moodle-core-tooltip"]},"moodle-core-dragdrop":{"requires":["base","node","io","dom","dd","event-key","event-focus","moodle-core-notification"]},"moodle-core-actionmenu":{"requires":["base","event","node-event-simulate"]},"moodle-core-chooserdialogue":{"requires":["base","panel","moodle-core-notification"]},"moodle-core-lockscroll":{"requires":["plugin","base-build"]},"moodle-core-dock":{"requires":["base","node","event-custom","event-mouseenter","event-resize","escape","moodle-core-dock-loader"]},"moodle-core-dock-loader":{"requires":["escape"]},"moodle-core_availability-form":{"requires":["base","node","event","panel","moodle-core-notification-dialogue","json"]},"moodle-backup-backupselectall":{"requires":["node","event","node-event-simulate","anim"]},"moodle-backup-confirmcancel":{"requires":["node","node-event-simulate","moodle-core-notification-confirm"]},"moodle-calendar-info":{"requires":["base","node","event-mouseenter","event-key","overlay","moodle-calendar-info-skin"]},"moodle-course-modchooser":{"requires":["moodle-core-chooserdialogue","moodle-course-coursebase"]},"moodle-course-management":{"requires":["base","node","io-base","moodle-core-notification-exception","json-parse","dd-constrain","dd-proxy","dd-drop","dd-delegate","node-event-delegate"]},"moodle-course-formatchooser":{"requires":["base","node","node-event-simulate"]},"moodle-course-toolboxes":{"requires":["node","base","event-key","node","io","moodle-course-coursebase","moodle-course-util"]},"moodle-course-dragdrop":{"requires":["base","node","io","dom","dd","dd-scroll","moodle-core-dragdrop","moodle-core-notification","moodle-course-coursebase","moodle-course-util"]},"moodle-course-categoryexpander":{"requires":["node","event-key"]},"moodle-course-util":{"requires":["node"],"use":["moodle-course-util-base"],"submodules":{"moodle-course-util-base":{},"moodle-course-util-section":{"requires":["node","moodle-course-util-base"]},"moodle-course-util-cm":{"requires":["node","moodle-course-util-base"]}}},"moodle-form-showadvanced":{"requires":["node","base","selector-css3"]},"moodle-form-dateselector":{"requires":["base","node","overlay","calendar"]},"moodle-form-passwordunmask":{"requires":["node","base"]},"moodle-form-shortforms":{"requires":["node","base","selector-css3","moodle-core-event"]},"moodle-core_message-messenger":{"requires":["escape","handlebars","io-base","moodle-core-notification-ajaxexception","moodle-core-notification-alert","moodle-core-notification-dialogue","moodle-core-notification-exception"]},"moodle-core_message-deletemessage":{"requires":["node","event"]},"moodle-question-qbankmanager":{"requires":["node","selector-css3"]},"moodle-question-chooser":{"requires":["moodle-core-chooserdialogue"]},"moodle-question-searchform":{"requires":["base","node"]},"moodle-question-preview":{"requires":["base","dom","event-delegate","event-key","core_question_engine"]},"moodle-availability_completion-form":{"requires":["base","node","event","moodle-core_availability-form"]},"moodle-availability_date-form":{"requires":["base","node","event","io","moodle-core_availability-form"]},"moodle-availability_grade-form":{"requires":["base","node","event","moodle-core_availability-form"]},"moodle-availability_group-form":{"requires":["base","node","event","moodle-core_availability-form"]},"moodle-availability_grouping-form":{"requires":["base","node","event","moodle-core_availability-form"]},"moodle-availability_profile-form":{"requires":["base","node","event","moodle-core_availability-form"]},"moodle-qtype_ddimageortext-dd":{"requires":["node","dd","dd-drop","dd-constrain"]},"moodle-qtype_ddimageortext-form":{"requires":["moodle-qtype_ddimageortext-dd","form_filepicker"]},"moodle-qtype_ddmarker-form":{"requires":["moodle-qtype_ddmarker-dd","form_filepicker","graphics","escape"]},"moodle-qtype_ddmarker-dd":{"requires":["node","event-resize","dd","dd-drop","dd-constrain","graphics"]},"moodle-qtype_ddwtos-dd":{"requires":["node","dd","dd-drop","dd-constrain"]},"moodle-mod_assign-history":{"requires":["node","transition"]},"moodle-mod_forum-subscriptiontoggle":{"requires":["base-base","io-base"]},"moodle-mod_quiz-autosave":{"requires":["base","node","event","event-valuechange","node-event-delegate","io-form"]},"moodle-mod_quiz-repaginate":{"requires":["base","event","node","io","moodle-core-notification-dialogue"]},"moodle-mod_quiz-quizquestionbank":{"requires":["base","event","node","io","io-form","yui-later","moodle-question-qbankmanager","moodle-core-notification-dialogue"]},"moodle-mod_quiz-toolboxes":{"requires":["base","node","event","event-key","io","moodle-mod_quiz-quizbase","moodle-mod_quiz-util-slot","moodle-core-notification-ajaxexception"]},"moodle-mod_quiz-questionchooser":{"requires":["moodle-core-chooserdialogue","moodle-mod_quiz-util","querystring-parse"]},"moodle-mod_quiz-dragdrop":{"requires":["base","node","io","dom","dd","dd-scroll","moodle-core-dragdrop","moodle-core-notification","moodle-mod_quiz-quizbase","moodle-mod_quiz-util-base","moodle-mod_quiz-util-page","moodle-mod_quiz-util-slot","moodle-course-util"]},"moodle-mod_quiz-quizbase":{"requires":["base","node"]},"moodle-mod_quiz-util":{"requires":["node"],"use":["moodle-mod_quiz-util-base"],"submodules":{"moodle-mod_quiz-util-base":{},"moodle-mod_quiz-util-slot":{"requires":["node","moodle-mod_quiz-util-base"]},"moodle-mod_quiz-util-page":{"requires":["node","moodle-mod_quiz-util-base"]}}},"moodle-mod_quiz-modform":{"requires":["base","node","event"]},"moodle-mod_quiz-randomquestion":{"requires":["base","event","node","io","moodle-core-notification-dialogue"]},"moodle-message_airnotifier-toolboxes":{"requires":["base","node","io"]},"moodle-block_navigation-navigation":{"requires":["base","io-base","node","event-synthetic","event-delegate","json-parse"]},"moodle-filter_glossary-autolinker":{"requires":["base","node","io-base","json-parse","event-delegate","overlay","moodle-core-event","moodle-core-notification-alert","moodle-core-notification-exception","moodle-core-notification-ajaxexception"]},"moodle-filter_mathjaxloader-loader":{"requires":["moodle-core-event"]},"moodle-editor_atto-rangy":{"requires":[]},"moodle-editor_atto-editor":{"requires":["node","transition","io","overlay","escape","event","event-simulate","event-custom","node-event-html5","yui-throttle","moodle-core-notification-dialogue","moodle-core-notification-confirm","moodle-editor_atto-rangy","handlebars","timers","querystring-stringify"]},"moodle-editor_atto-plugin":{"requires":["node","base","escape","event","event-outside","handlebars","event-custom","timers","moodle-editor_atto-menu"]},"moodle-editor_atto-menu":{"requires":["moodle-core-notification-dialogue","node","event","event-custom"]},"moodle-report_eventlist-eventfilter":{"requires":["base","event","node","node-event-delegate","datatable","autocomplete","autocomplete-filters"]},"moodle-report_loglive-fetchlogs":{"requires":["base","event","node","io","node-event-delegate"]},"moodle-gradereport_grader-gradereporttable":{"requires":["base","node","event","handlebars","overlay","event-hover"]},"moodle-gradereport_history-userselector":{"requires":["escape","event-delegate","event-key","handlebars","io-base","json-parse","moodle-core-notification-dialogue"]},"moodle-tool_capability-search":{"requires":["base","node"]},"moodle-tool_monitor-dropdown":{"requires":["base","event","node"]},"moodle-assignfeedback_editpdf-editor":{"requires":["base","event","node","io","graphics","json","event-move","event-resize","querystring-stringify-simple","moodle-core-notification-dialog","moodle-core-notification-exception","moodle-core-notification-ajaxexception"]},"moodle-atto_accessibilitychecker-button":{"requires":["color-base","moodle-editor_atto-plugin"]},"moodle-atto_accessibilityhelper-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_align-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_bold-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_charmap-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_clear-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_collapse-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_emoticon-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_equation-button":{"requires":["moodle-editor_atto-plugin","moodle-core-event","io","event-valuechange","tabview","array-extras"]},"moodle-atto_html-button":{"requires":["moodle-editor_atto-plugin","event-valuechange"]},"moodle-atto_image-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_indent-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_italic-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_link-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_managefiles-usedfiles":{"requires":["node","escape"]},"moodle-atto_managefiles-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_media-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_noautolink-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_orderedlist-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_rtl-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_strike-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_subscript-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_superscript-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_table-button":{"requires":["moodle-editor_atto-plugin","moodle-editor_atto-menu","event","event-valuechange"]},"moodle-atto_title-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_underline-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_undo-button":{"requires":["moodle-editor_atto-plugin"]},"moodle-atto_unorderedlist-button":{"requires":["moodle-editor_atto-plugin"]}}},"gallery":{"name":"gallery","base":"http:\/\/bhmt.alamom.com\/lib\/yuilib\/gallery\/","combine":true,"comboBase":"http:\/\/bhmt.alamom.com\/theme\/yui_combo.php?","ext":false,"root":"gallery\/1465622294\/","patterns":{"gallery-":{"group":"gallery"}}}},"modules":{"core_filepicker":{"name":"core_filepicker","fullpath":"http:\/\/bhmt.alamom.com\/lib\/javascript.php\/1465622294\/repository\/filepicker.js","requires":["base","node","node-event-simulate","json","async-queue","io-base","io-upload-iframe","io-form","yui2-treeview","panel","cookie","datatable","datatable-sort","resize-plugin","dd-plugin","escape","moodle-core_filepicker"]}}};
M.yui.loader = {modules: {}};

//]]>
</script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
        <link href='//fonts.googleapis.com/css?family=Raleway|Raleway&subset=latin' rel='stylesheet' type='text/css'>
    
    
<link rel="apple-touch-icon-precomposed" sizes="57x57" href="http://bhmt.alamom.com/theme/image.php/essential/theme/1465680227/homeicon/iphone"/>
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="http://bhmt.alamom.com/theme/image.php/essential/theme/1465680227/homeicon/ipad"/>
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="http://bhmt.alamom.com/theme/image.php/essential/theme/1465680227/homeicon/iphone_retina"/>
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="http://bhmt.alamom.com/theme/image.php/essential/theme/1465680227/homeicon/ipad_retina"/>    
        
</head>

<body  id="page-course-view-topics" class="format-topics  path-course path-course-view safari dir-ltr lang-en_us yui-skin-sam yui3-skin-sam bhmt-alamom-com pagelayout-course course-2 context-35062 category-1 loggedin desktopdevice pagewidthwide modeditingmenu hasboringlayout has-region-side-pre used-region-side-pre has-region-side-post used-region-side-post has-region-footer-left empty-region-footer-left has-region-footer-middle empty-region-footer-middle has-region-footer-right empty-region-footer-right">

<div class="skiplinks"><a class="skip" href="#maincontent">Skip to main content</a></div>
<script type="text/javascript" src="http://bhmt.alamom.com/theme/yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js&amp;rollup/1465622294/mcore-min.js"></script><script type="text/javascript" src="http://bhmt.alamom.com/lib/javascript.php/1465622294/lib/javascript-static.js"></script>
<script type="text/javascript">
//<![CDATA[
document.body.className += ' jsenabled';
//]]>
</script>


<header role="banner">
    <nav id="essentialnavbar" role="navigation" class="moodle-has-zindex logo">
        <div class="navbar">
            <div class="container-fluid navbar-inner">
                <div class="row-fluid">
                    <div class="custommenus pull-left">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target="#essentialmenus">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                        <a class="brand" href="//bhmt.alamom.com">BHMT Course Portal</a>                    <div class="pull-right">
                        <div class="usermenu">
                            <ul class="nav"><li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><img src="http://bhmt.alamom.com/theme/image.php/essential/core/1465680227/u/f2" alt="Picture of Admin BHMT" title="Picture of Admin BHMT" class="userpicture defaultuserpic" width="35" height="35" />Admin<span aria-hidden="true" class="fa fa-caret-right"></span></a><ul class="dropdown-menu pull-right"><li><a href="http://bhmt.alamom.com/user/profile.php?id=2"><em><span aria-hidden="true" class="fa fa-user"></span>Admin BHMT</em></a></li><li class="dropdown-submenu preferences"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><em><span aria-hidden="true" class="fa fa-cog"></span>Preferences</em></a><ul class="dropdown-menu"><li><a href="http://bhmt.alamom.com/user/preferences.php?userid=2"><em><span aria-hidden="true" class="fa fa-user"></span>User</em></a></li><li><a href="http://bhmt.alamom.com/user/edit.php?id=2"><em><span aria-hidden="true" class="fa fa-info-circle"></span>Edit profile</em></a></li><li><a href="http://bhmt.alamom.com/login/change_password.php"><em><span aria-hidden="true" class="fa fa-key"></span>Change password</em></a></li><li><a href="http://bhmt.alamom.com/message/edit.php?id=2"><em><span aria-hidden="true" class="fa fa-comments"></span>Message</em></a></li></ul></li><hr class="sep" /><li><a href="http://bhmt.alamom.com/calendar/view.php"><em><span aria-hidden="true" class="fa fa-calendar"></span>Calendar</em></a></li><li><a href="http://bhmt.alamom.com/message/index.php"><em><span aria-hidden="true" class="fa fa-envelope"></span>Messages</em></a></li><li><a href="http://bhmt.alamom.com/user/files.php"><em><span aria-hidden="true" class="fa fa-file"></span>Private files</em></a></li><li><a href="http://bhmt.alamom.com/mod/forum/user.php?id=2"><em><span aria-hidden="true" class="fa fa-list-alt"></span>Forum posts</em></a></li><li><a href="http://bhmt.alamom.com/mod/forum/user.php?id=2&amp;mode=discussions"><em><span aria-hidden="true" class="fa fa-list"></span>Discussions</em></a></li><hr class="sep" /><li><a href="http://bhmt.alamom.com/grade/report/overview/index.php?userid=2"><em><span aria-hidden="true" class="fa fa-list-alt"></span>My grades</em></a></li><hr class="sep" /><li><a href="http://bhmt.alamom.com/login/logout.php?sesskey=uEFj5NdG2R"><em><span aria-hidden="true" class="fa fa-sign-out"></span>Log out</em></a></li><li><a target="" href="//bhmt.alamom.com/admin/settings.php?section=theme_essential_header"><em><span aria-hidden="true" class="red fa fa-exclamation-triangle"></span>Invalid email address</em></a></li></ul></li></ul>                        </div>
                        <div class="messagemenu">
                            <ul class="nav"><li><a title="No messages were found" href="http://bhmt.alamom.com/message/index.php?viewing=recentconversations"><span><i class="fa fa-envelope-o"></i></span></a></li></ul>                        </div>
                        <div class="gotobottommenu">
                            <ul class="nav"><li><a title="Go to the bottom of the page" href="#region-main"><i class="fa fa-arrow-circle-o-down"></i></a></li></ul>                        </div>
                        <div id="custom_menu_editing" class="editingmenu">
                                                    </div>
                    </div>
                        <div id='essentialmenus' class="nav-collapse collapse pull-left">
                            <div id="custom_menu_language">
                                <ul class="nav"></ul>                            </div>
                            <div id="custom_menu_courses">
                                <ul class="nav"></ul>                            </div>
                                                        <div id="custom_menu">
                                <ul class="nav"></ul>                            </div>
                            <div id="custom_menu_activitystream">
                                <ul class="nav"><li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" title="This course"><span aria-hidden="true" class="fa fa-book"></span>This course<span aria-hidden="true" class="fa fa-caret-right"></span></a><ul class="dropdown-menu"><li><a title="People" href="http://bhmt.alamom.com/user/index.php?id=2"><span aria-hidden="true" class="fa fa-users"></span>People</a></li><li><a title="Grades" href="http://bhmt.alamom.com/grade/report/index.php?id=2"><span aria-hidden="true" class="icon fa fa-list-alt"></span>Grades</a></li></ul></ul>                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <div id="page-header" class="clearfix logo">
        <div class="container-fluid">
            <div class="row-fluid">
                
                <div class="pull-left">
<a class="logo" href="//bhmt.alamom.com" title="Home"></a>                </div>
                            </div>
        </div>
    </div>
</header>

<div id="page" class="container-fluid">
    <div id="page-navbar" class="clearfix row-fluid"><div class="breadcrumb-nav span9"><span class="accesshide" id="navbar-label">Page path</span><nav aria-labelledby="navbar-label"><ul class="breadcrumb style1"><li><a href="http://bhmt.alamom.com/">Home</a></li><li><a title="Class Locations and Schedules" href="http://bhmt.alamom.com/course/view.php?id=2">Class Locations and Schedules</a></li></ul></nav></div><nav class="breadcrumb-button span3"><a href="http://bhmt.alamom.com/course/view.php?id=2&amp;sesskey=uEFj5NdG2R&amp;edit=on" class="btn btn-success" title="Turn editing on"><i class="fa-edit fa fa-fw"></i>Turn editing on</a></nav></div>    <section role="main-content">
        
        <div id="page-content" class="row-fluid">
            <div id="region-bs-main-and-pre" class="span9">
                <div class="row-fluid">
<section id="region-main" class="span8 pull-right">

**Comment by gjb2048** [comment]
Ok, that's failed.  Please put in a text file and upload that.

**Comment by demontech** [comment]
[source_course_blank.txt](https://github.com/gjb2048/moodle-theme_essential/files/310510/source_course_blank.txt)

**Comment by gjb2048** [comment]
Ok, thanks.  Does not make sense as does not even get near new course title code.

Additionally, what other settings are changed from default as the last bit in the markup being 'section id="region-main" class="span8 pull-right"' cannot happen unless the 'layout' setting is set and its not set by default.

**Comment by gjb2048** [comment]
Ok, please turn on developer level debugging and reload the page and see if there are any errors.

**Comment by gjb2048** [comment]
Ok, off to bed now.  Will look again when I get time.

**Comment by gjb2048** [comment]
Ok....

Fired up a virtual "3.13.0-86-generic #130-Ubuntu" running the Bitnami LAMP stack with PHP 5.6.21 on Moodle 3.0.4 build 20160509, installed Essential and set the Google Font to 'Raleway', and set 'layout' on and still could not replicate.  That elminates any PHP / OS difference in generating the output with the method $OUTPUT->course_title().
