### ISSUE TITLE
Moodle 3.1 evolutions

### ISSUE THREAD

**Issue by GuiGuiSoft** [gjb2048/moodle-theme_essential#671]
Hello,

I'm not sure if it is the right place, but I realized some tests with Moodle 3.1 and I saw 2 problem with Essential theme.
It is logical because it is clearly announced that it is not the right version theme for this Moodle version, but I just want to help an tell you :)

The navigation menu is "strange" (see menu.png)
![menu](https://cloud.githubusercontent.com/assets/8069239/16004776/049a6f6a-3164-11e6-8e46-1700e541e655.png)

When we try to launch a timing-base test : we can not see the start/cancel buttons (buttons are in a fieldset class="hidden")
![timing](https://cloud.githubusercontent.com/assets/8069239/16004781/0952a7e8-3164-11e6-9429-c88bcc455538.png)

Thank you for this great theme.
Regards.

**Comment by gjb2048** [comment]
Hi,

Thanks for the report.  However the M3.0 version of the theme is not designed to work on M3.1, hence the information in the readme and the warning that comes up on all the admin screens.  I will be starting on a M3.1 version soon, as stated by: https://github.com/gjb2048/moodle-theme_essential/issues/661 and https://moodle.org/mod/forum/discuss.php?d=334052.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Also there are two issues here, please keep one problem per issue.  The latter has already been reported in: https://github.com/gjb2048/moodle-theme_essential/issues/663

**Comment by GuiGuiSoft** [comment]
Oops, excuse-me, I will be attentive in te futur :)

**Comment by gjb2048** [comment]
M3.1 beta does not have the issue.
