### ISSUE TITLE
Advanced Forum Issue With Essentials Theme (responsive issue?)

### ISSUE THREAD

**Issue by jeevesgreen** [gjb2048/moodle-theme_essential#672]
Greetings,
We are experiencing an issue with the way Advanced Forums and the Essentials Theme interact with eachother. Whenever we add a new Advanced Forum it will display it to the far right of the screen and seeing it is responsive, the larger the web-browser window the more of a gap is between the Navigation box and the Advanced Forum.( See http://adweb.clarkson.edu/~sgreen/moodle_advanced_forum_issue.png). I know that the Essentials theme is considered "responsive" so I am wondering if that is causing this issue to happen. This only seems to be happening with "Advanced Forums" and not the standard forum, page, assignment... We would like to have the forum be in the center of the page and not adjust when the size of the browser changes.

Any suggestions/help is greatly appreciated.

Thank you!

**Comment by gjb2048** [comment]
Ok,

What version of Moodle and Essential?

What is "Advanced Forums", where can I get it, what version and how can I replicate the problem?

**Comment by gjb2048** [comment]
Hi,

Please could you respond!  If I don't get the information requested, how can I help you?

Gareth

**Comment by malinz** [comment]
Hi GarethI am on the other side of the world :) when you are responding, I am sleeping. I received this at 5:34am our time.Regards,Malcolm

Date: Mon, 20 Jun 2016 10:46:35 -0700

**Comment by gjb2048** [comment]
Hi Malcolm,

Fair enough, but the issue was raised five days ago and I responded within a few hours and then nothing.

Cheers,

Gareth

**Comment by jeevesgreen** [comment]
Hi Gareth,

Sorry about the extremely late reply. I was out of the office due to surgery and being sick. (Feeling much better now).

Hopefully you can still help.

Moodle Version: 3.0.2+ (Build: 20160304)
Essentials: 3.0.1 (Build: 2016010205)

The "Advanced Forum" is a moodle plugin and can be downloaded here ( https://moodle.org/plugins/mod_hsuforum ).

Side-note: This issue also existed in our old environment (Moodle 2.8+).


Seeing I am back to work now I will respond back to any questions as quickly as I can.


Thank you,
               Jeeves

**Comment by gjb2048** [comment]
Hi Jeeves,

Get well soon.

Gareth

**Comment by gjb2048** [comment]
Firstly, looking at: https://moodle.org/plugins/pluginversions.php?plugin=mod_hsuforum its only designed for M2.9- and not M3.0+

**Comment by gjb2048** [comment]
![moodle_advanced_forum_issue](https://cloud.githubusercontent.com/assets/1058419/16277073/2be1d012-38a9-11e6-8b52-af6c590a876d.png)

**Comment by gjb2048** [comment]
Hi Jeeves,

Yes I can replicate and there is a problem.  However, it is with the advanced forum and not with the theme.  Therefore there is nothing for me to do Essential wise.

Pragmatically as it has taken me time to look at this and in my terms of business I charge for support, there will be a fee involved for me to report on what the problem is with the module.

Kind regards,

Gareth

**Comment by jeevesgreen** [comment]
Gareth,

Thank you for the help on this. No need to look into the issue of the module. I will contact the developers of the "Advanced Forum"... If they don't reply I will probably dig into their code and see whats going on.

Once again, thank you for your help!

Regards,
            Jeeves
