### ISSUE TITLE
Moodle 3.1+ (Build: 20160609) with Elegance 3.0.1.4 (Build: 2016010209)

### ISSUE THREAD

**Issue by celsoishida** [gjb2048/moodle-theme_essential#673]
I create a course in a Moodle 3.1+ (Build: 20160609) with Elegance 3.0.1.4 (Build: 2016010209):

Course configuration:
1) Course format / Format / Single activity format 
2) Type of activity / Forum

And I can't see the course as student. I have to force to another theme to see the course
You can see the video: https://youtu.be/RyQFu_1_zTA

Celso

**Comment by gjb2048** [comment]
A. This is the Essential theme.
B. The M3.0 version does not work on M3.1 as it states in the Readme, the admin pages, numerous times on the Moodle themes forum and other issues here.
C. The M3.1 version is under development as stated on the Moodle themes forum and here (issues).

Therefore I will not spend any time on this.

**Comment by celsoishida** [comment]
Sorry. It's Essential, not Elegance.
I was just trying to help.

**Comment by gjb2048** [comment]
I know, but this is Software Engineering and you must be accurate.

**Comment by gjb2048** [comment]
See: https://moodle.org/mod/forum/discuss.php?d=334859#p1349360
