### ISSUE TITLE
M31 beta: Breadcrumbs should be right aligned and flipped in RTL mode

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#674]
![snapshot61](https://cloud.githubusercontent.com/assets/231168/16177155/dd1e482a-362d-11e6-8674-34987b55169a.png)

Link to a Moodle 3.1 RTL testing system:
http://themes.moodlemagic.info/
(Where the following patch was applied)
If you open an account, I will give you admin privileges, so you can play around

Fix:
/* RTL breadcrumbs */
.dir-rtl .breadcrumb-nav ul.breadcrumb.style1 {
    float: right;
    margin-left: -4px;
}
.dir-rtl .breadcrumb-nav ul.breadcrumb.style1 li {
    padding: 0 15px 0 5px;
    float: right;
}
.dir-rtl .breadcrumb-nav ul.breadcrumb.style1 li:before {
    right: 100%;
    border-right-width: 14px;
    border-right-style: solid;
    margin-right: 1px;
    border-left-width: 0;
    border-left-style: none;
}
.dir-rtl .breadcrumb-nav ul.breadcrumb.style1 li:after {
    right: 100%;
    border-right-width: 14px;
    border-right-style: solid;
    border-left-width: 0;
    border-left-style: none;
}
.dir-rtl .breadcrumb-button .singlebutton, .breadcrumb-button a {
    float: left;
}
.dir-rtl .row-fluid .breadcrumb-nav {
float:right;
}
.dir-rtl .breadcrumb-nav ul.breadcrumb.style1 li:first-of-type a {
    margin-right: -25px;
   margin-left: 0;
}

**Comment by gjb2048** [comment]
For some reason in the branch merge, the breadcrumb.less lost all of the .dir-rtl styles.

**Comment by gjb2048** [comment]
https://github.com/gjb2048/moodle-theme_essential/blob/master_bsb/less/essential/breadcrumb.less

**Comment by nadavkav** [comment]
Weird

**Comment by gjb2048** [comment]
Fixing a hover bug too in the alternative LESS.
