### ISSUE TITLE
M31b: Tree nodes on Navigation block have redundant 21px right padding, in RTL mode.

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#677]
![image](https://cloud.githubusercontent.com/assets/231168/16179322/98281a1a-366a-11e6-951f-e8a666b61fcc.png)

**Comment by gjb2048** [comment]
Core mess this up stupidly.  One bit has text indent of -21px and another with 21px padding.  Stupid.
