### ISSUE TITLE
M31b: Gradebook sticky headers broken, in RTL mode.

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#678]
Scrolling the page, the gradebook header disappears. (Maybe intentional?)
![image](https://cloud.githubusercontent.com/assets/231168/16179340/39a9adc2-366b-11e6-89d7-680824660b85.png)

Also, in RTL mode, there is no bottom browser scrollbars (Maybe, a separate issue?)

**Comment by nadavkav** [comment]
Ok. just saw it was like this on earlier versions of Essential

**Comment by gjb2048** [comment]
The grade-book is a pain in the xxxx.

**Comment by nadavkav** [comment]
I know

**Comment by nadavkav** [comment]
I was probably mixed it with core Clean/More theme.

There is already a sticky Essential main header. so I am not sure how easy it will be to stick the gradebook (and probably Assignments grades, and other table headers) under that.

What's your opinion about this?

**Comment by gjb2048** [comment]
My opinion would use words not fit for public display.

**Comment by nadavkav** [comment]
:smile:

**Comment by nadavkav** [comment]
About the bottom scrollbars, in RTL mode...
I am using "Fixed with - Normal", but also tested it on all other widths, and it seems persistent. (no scroll bar)

**Comment by gjb2048** [comment]
Navbar on top or below?

**Comment by gjb2048** [comment]
I remember fixing this ages ago.

**Comment by gjb2048** [comment]
Scrolling headers not really an issue, need to prove with lots more rows.  Scrollbar is an issue.

**Comment by nadavkav** [comment]
Browser's bottom horizontal scrollbar (To show course activities)
I have a RTL course with lots of students here:
http://themes.moodlemagic.info/grade/report/grader/index.php?id=11
(Create a user, and I will give you proper permissions to see this)

**Comment by gjb2048** [comment]
Thanks.  I can replicate the scrollbar issue.  Header will be for another time.

**Comment by nadavkav** [comment]
Great.
(The Header issue is just me, nobody complaint)

**Comment by gjb2048** [comment]
Fix is not ideal as loose 10px on the margin, but it works.

**Comment by nadavkav** [comment]
Confirmed :-)
