### ISSUE TITLE
Guest user menu show missing support email error

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#679]
![image](https://cloud.githubusercontent.com/assets/231168/16179407/82ce6824-366d-11e6-956c-130e0d23ed06.png)

I think we better hide this from unauthenticated users.

**Comment by gjb2048** [comment]
Why?

**Comment by gjb2048** [comment]
Oh poop.

**Comment by gjb2048** [comment]
Umm, going to leave for a mo as a M3.1- issue too.

**Comment by nadavkav** [comment]
Ok [label:minor]

**Comment by gjb2048** [comment]
Note: Not M3.1 specific - will be a back-port.

**Comment by gjb2048** [comment]
Ok, not a bug as the email address is the 'support' email address not the user, therefore would be a valid thing to be wrong and would be something if correct would be appropriate for help for a guest user.

See: https://github.com/gjb2048/moodle-theme_essential/blob/master/classes/output/core_renderer.php#L1314-L1364

**Comment by nadavkav** [comment]
But I do not think the Guest user should see this error/notice/warning.
The admin should. and probably fill in the missing support email, if she/he care for it.
Don't you think?

**Comment by gjb2048** [comment]
Oh poop.

**Comment by gjb2048** [comment]
In fact, only admin should see the error.

**Comment by gjb2048** [comment]
Who wrote this anyway!

**Comment by gjb2048** [comment]
Need to back-port this.

**Comment by nadavkav** [comment]
Probably innocent looking white rabbits
![image](https://cloud.githubusercontent.com/assets/231168/16180202/44a6812a-3687-11e6-94d6-95c9f8ca71ff.png)
They are all over the internet, close all the doors :smiley:

**Comment by gjb2048** [comment]
Umm, ok, been drinking have we? ;)

**Comment by gjb2048** [comment]
Back ported!

**Comment by nadavkav** [comment]
​​
Confirmed :-)
