### ISSUE TITLE
problem with 3.1.0.4?? (no automatic scaling of images)

### ISSUE THREAD

**Issue by rosimittermeier** [gjb2048/moodle-theme_essential#683]
hi, 
   maybe there is a problem with images in moodle-courses. as you can see in the screenshot. before the release cadidate the images had been scaled automatically. now there is the scroll bar.

best wishes, hans
![clipboard01](https://cloud.githubusercontent.com/assets/13799805/16541563/b8d3c0a4-4086-11e6-82d7-1927fed85843.jpg)

**Comment by gjb2048** [comment]
Hi Hans,

So this problem was not in the beta?

G

**Comment by rosimittermeier** [comment]
hmmm ... to be honest, I don't know. sorry for my negligence in observing the knew version and describing the problem!hans  02.07.2016, 18:58, "Gareth J Barnard" <notifications@github.com>:Hi Hans,  So this problem was not in the beta?  G—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by gjb2048** [comment]
Hi Hans,

Its just that you said "before the release cadidate the images had been scaled automatically" therefore you were aware of the version that was ok.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Apart from the 'margin' added by ATTO, cannot reproduce:

![2016-07-02 19_28_43-course_ topics](https://cloud.githubusercontent.com/assets/1058419/16541923/81f1d0da-408b-11e6-8d49-e2641d5f232b.png)

**Comment by rosimittermeier** [comment]
... maybe this helps. i don't have your analysis-tool of the code.it may depend on the image properties. i used "image-rounded". it does not work (my reported error or problem appears). i changed to "image-polaroid". it does not work (in the same way). i changed to "image-responsive". it works (as you can see in the attachement).maybe this helps!thanksav 02.07.2016, 20:31, "Gareth J Barnard" <notifications@github.com>:Apart from the 'margin' added by ATTO, cannot reproduce:—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by gjb2048** [comment]
Hi Hans,

Not really as I don't know why you removed the img-responsive class in the first place?  Also you do have the tool, just press F12.

G

**Comment by rosimittermeier** [comment]
hi gareth,      i dont know why, too. maybe it's just because i like rounded squares. but now i dont like them any more and so everything is ok. thanks for your responses!!!! besthans    03.07.2016, 08:56, "Gareth J Barnard" <notifications@github.com>:Hi Hans,  Not really as I don't know why you removed the img-responsive class in the first place? Also you do have the tool, just press F12.  G—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by rosimittermeier** [comment]
everything is ok. i made the observation that before 3.1.0.xyz with 3.0 of the essential theme my observation was different from now. i do not have any probelm which any more.thanks 03.07.2016, 15:42, "Gareth J Barnard" <notifications@github.com>:Hi Hans,  You can have more than one class in a tag class list. Therefore possible to have responsive and the effects classes you want.  So, is there actually a problem you want me to fix?  G—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
