### ISSUE TITLE
Blocks should be right aligned under content in admin page layout, on RTL mode

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#685]
Following screen capture is from https://moodle-site/admin/plugins.php?updatesonly=0&contribonly=1&lang=he
(Site administration >> Plugins >> Plugins overview)
![image](https://cloud.githubusercontent.com/assets/231168/16545550/d456283e-4136-11e6-9b30-928a63d4667c.png)
A fix should probably be:
```
.dir-rtl .row-fluid [class*=span] {
    float: right;
}
```
But we should make sure if it not raising new issues elsewhere...

**Comment by gjb2048** [comment]
Fix is easy, just target the footer blocks.

**Comment by nadavkav** [comment]
You are right. Thanks.
I did not notice these are footer blocks. just thought it's a #block-region-side-pre .
(better read more carefully the page layout, next time)
