### ISSUE TITLE
Folder state in blocks and icons

### ISSUE THREAD

**Issue by izendegi** [gjb2048/moodle-theme_essential#694]
I've seen several things with colours in the blocks in Moodle 3.1 with Essential 3.1.0.5, I put them all in one issue as it seems to me they can be related:

![moodle30_homeadminblock](https://cloud.githubusercontent.com/assets/5556433/16793927/e7825d9c-48d4-11e6-94fc-8e39980ce22f.png)
This is who Essential shows the admin block in the Moodle 3.0 home
![moodle31_homeadminblock](https://cloud.githubusercontent.com/assets/5556433/16793932/ee4c1424-48d4-11e6-8d32-7d92ecb4a4bb.png)
This is who Essential shows the admin block in the Moodle 3.1 home

**Block Hide & Dock icon and (some) menu item colours**
In previous versions of Moodle the hide and block icons all blocks have in their upper right corner were grey (#999999) both in Essential and Clean themes, but in Moodle 3.1 these icons seems to be coloured by Essential (#30add1) but there is no way (or I haven't found the option) to set that colour. 
A similar thing happens sometimes to some icons of the menu (I haven't been able to detect the pattern).

**Open/Close Folder icons**
In Moodle 3.1 some folder icons are opened, even if they are actually closed

**Comment by gjb2048** [comment]
Ok, thanks for the report, there is a long story to answer later.  But 'which' folder icons are closed when they should be open?  I need specifics please so I can replicate.  Without replication I cannot fix.

**Comment by izendegi** [comment]
Hi Gareth,

Maybe I didn't explain it properly: the folders "Users", "Reports" and "Question Bank" in "Front page settings" are actually closed but have the open-folder icon (view the image above).

**Comment by gjb2048** [comment]
Ok, ta.

**Comment by gjb2048** [comment]
Ok, bar the open folder issue, please look at point '2' here for the rest: https://moodle.org/mod/forum/discuss.php?d=334985#p1355540

**Comment by gjb2048** [comment]
Ok, can replicate.  M3.1 only.  Issue is that core are no longer using 'collapsed' class but rather relying on 'aria-expanded'.

**Comment by izendegi** [comment]
Thanks Gareth, I've installed the latest release and realized the folder issue is fixed.

And I've been also able to recolour the icons using grunt svg --svgcolour. 

> Until this morning have I worked out a possible test that does not use a contributed theme that may justify a core tracker issue with the Clean theme as a bug to get this sorted.  However, things in core that are issues for contributed plugins don't tend to get accepted.

I think it deserves to open a issue in the tracker and try to get it done (I think many Essential theme and other plugin admins would vote for it)

**Comment by gjb2048** [comment]
It would, I just need to find the time to write it such that the scenario where somebody adjusts the Clean theme to use their own icon using pix_url does not see it.  Need to look at the JS to find the specific place and use that.  Lots to do.  Unless you can create the tracker with a Clean scenario with test instructions?
