### ISSUE TITLE
Accessibility: role=main-content ("Role must be one of the valid ARIA roles")

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#698]
Axe (chrome accessibility extension tool) report all instances of:
`<section role="main-content">` (In all layout pages)
, as "Role must be one of the valid ARIA roles" (Critical).

Looking at https://www.w3.org/TR/wai-aria/rdf_model.png, it seems that a simple role=main could be appropriate. What do you think?

**Comment by gjb2048** [comment]
I think I need to go to sleep and work on this another day.

**Comment by gjb2048** [comment]
I also think, how the XXXX did that get there?

**Comment by gjb2048** [comment]
And yes, I agree its wrong.

**Comment by gjb2048** [comment]
'main' would be the solution.

**Comment by nadavkav** [comment]
Great.
(It's too late over this side of the internet too :smile: , let's call it a day. tomorrow...)

**Comment by gjb2048** [comment]
Ok, 'role="main"' already output by '$OUTPUT->main_content();' therefore cannot be twice.

**Comment by gjb2048** [comment]
Currently looking at things, that 'section' is pointless.

**Comment by nadavkav** [comment]
You are right. it make sense.

**Comment by gjb2048** [comment]
I'm always correct, except when I'm incorrect.

**Comment by nadavkav** [comment]
:smile:
