### ISSUE TITLE
Header height

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_essential#700]
A tad wrong in M3.1:

![2016_07_26_18_12_44_start](https://cloud.githubusercontent.com/assets/1058419/17148136/b20f8232-535d-11e6-8b70-64148b8b67ae.jpg)

**Comment by gjb2048** [comment]
M3.0 too?

![2016-07-27 13_27_49-start](https://cloud.githubusercontent.com/assets/1058419/17175216/237ec8ec-53fe-11e6-8fa7-20c38669186c.png)

**Comment by fvendrell** [comment]
Vertical space between the header title and header subtitle is to small (hrer it chose header title = fill name and summary
![capture-header-essential](https://cloud.githubusercontent.com/assets/1890966/17275452/b3a73438-5708-11e6-91f4-ce75009b8522.PNG)

**Comment by gjb2048** [comment]
That's a separate problem to this problem, if indeed it is a problem at all or simply the choice of font.

**Comment by fvendrell** [comment]
Shall I create a new issue for this ?

With Verdana font, the result is similar:
![capture1](https://cloud.githubusercontent.com/assets/1890966/17277558/f9d0e7be-5745-11e6-8412-b5e3b4d876e3.PNG)

**Comment by gjb2048** [comment]
Yes please.
