### ISSUE TITLE
Header title - Fullname and summary option - language span tags

### ISSUE THREAD

**Issue by tswilson** [gjb2048/moodle-theme_essential#702]
In Site Administration / Front Page Settings - content within multilanguage span tags renders appropriately in a Course / Site Summary block on the front page.

When selecting 'Full name and Summary' for Header Title in Themes / Essential / Header, the language tags are not being respected, and both the languages appear side-by-side.

IE:  With the site in English the Summary block reads: English... likewise with the site in French it reads: French.

In the spot below my site name with the above option enabled, it reads: EnglishFrench.

Regards,

Trevor

**Comment by gjb2048** [comment]
Thanks for the report Trevor,

What version of Essential please?
What do you think the solution is?

**Comment by gjb2048** [comment]
P.s. can you give me some sample code to test with please.

**Comment by tswilson** [comment]
Hi, Gareth

Assuming you have English and French languages on your Moodle installation, if you put the following in as the Site Summary you’ll get one or the other based on which language you’re in.

<span class="multilang" lang="en">English</span><span class="multilang" lang="fr">French</span>

I’d bet the text for the Site Summary block is getting pushed through format_text($your_text_here, FORMAT_HTML); to activate the Multilanguage Filter, and not when it gets pulled into the Header.

Hope this helps!

Trevor

**Comment by tswilson** [comment]
Ooops, realized I forgot to tell you what version I was on.

[cid:image001.png@01D1E815.5EACDF80]

Regards,

Trevor

**Comment by gjb2048** [comment]
Thanks Trevor.
