### ISSUE TITLE
Group images are not well displayed

### ISSUE THREAD

**Issue by fvendrell** [gjb2048/moodle-theme_essential#703]
Hello, 

As you can see from the images provided, the group images are not all shown in the message.
First image: Clean theme
Second image: Essential theme

![capture-message-posted-clean](https://cloud.githubusercontent.com/assets/1890966/17275339/a4a01ecc-5704-11e6-80e2-4b4a52335324.PNG)
![capture-message-posted-essential](https://cloud.githubusercontent.com/assets/1890966/17275340/a8d92baa-5704-11e6-9f1a-ff5e893601f3.PNG)

**Comment by gjb2048** [comment]
What are group images please?  Is this a forum?  What versions of Moodle and Essential?

**Comment by fvendrell** [comment]
****  Message automatique du répondeur ****

Bonjour,

Je vous remercie pour votre message et de prendre note de ma nouvelle adresse de courriel

francis@reiki.center

vers laquelle votre message a été transféré automatiquement.

Francis Vendrell

Centre d'Etudes et de Formation en Reiki

**Comment by fvendrell** [comment]
Moodle 3.1.1+ (Build: 20160721)
Essential 3.1.0.5 (Build: 2016061703)

Yes, I am talking about the group images on the left side of the messages posted in a forum.

![capture-message-posted-essential-1](https://cloud.githubusercontent.com/assets/1890966/17277510/ed3e1d74-5744-11e6-919e-d75b65d6a68d.PNG)

**Comment by gjb2048** [comment]
Do you have the link to the Moodle docs for this as I've not heard of group images before?

**Comment by fvendrell** [comment]
See section "Creating a group" on the page https://docs.moodle.org/31/en/Groups

**Comment by gjb2048** [comment]
That's odd as DE, EN and FR are language codes.  And yet the documentation for groups could have anything of any length for the group title, so are you sure that those icons are 'groups' and if so, how do I replicate that in a forum as there is nothing on https://docs.moodle.org/31/en/Groups or https://docs.moodle.org/31/en/Category:Groups about forums themselves.

**Comment by fvendrell** [comment]
I have created manually those groups ! Sorry this is confusing. I am just working on a project where users are grouped according to the languages they know….

 

To replicated the issue:

1.       Create a course with “group mode” = visible or separated groups.

2.       Create at least 4 groups within this course, with any picture and any names.

3.       Create a forum  (any group mode will do) within this course.

4.       Add a topic to the forum and published it.

5.       Look at the result (i.e. the message). The first two group pictures are well displayed, the third one is cut and the fourth is not visible.

6.       Check that all the four group pictures are visible with the “Clean” theme.

 

For convenience you will find enclosed the pictures I have created.

 

cid:image001.png@01D1EBA2.4F7FCD20

 

de.pngen.pngfr.pngit.png

**Comment by fvendrell** [comment]
Erratum. I missed on step.
To replicated the issue: 
1. Create a course with “group mode” = visible or separated groups. 
2. Create at least 4 groups within this course, with any picture and any names. 
**3. Enrol yourself in all these groups.**
4. Create a forum (any group mode will do) within this course. 
5. Add a topic to the forum and published it. 
6. Look at the result (i.e. the message). The first two group pictures are well displayed, the third one is cutted and the fourth is not visible. 
7. Check that all the four group pictures are visible with the “Clean” theme.
