### ISSUE TITLE
Vertical space between the header title and header subtitle is to small

### ISSUE THREAD

**Issue by fvendrell** [gjb2048/moodle-theme_essential#704]
Vertical space between the header title and header subtitle is to small (with header title = full name and summary - maybe others as well).

With Montserrat Google font:
![capture-header-essential](https://cloud.githubusercontent.com/assets/1890966/17277672/e3cda0a8-5748-11e6-9a3a-4e3b3b6f62a9.PNG)

With Verdana font:
![capture1](https://cloud.githubusercontent.com/assets/1890966/17277674/edccd204-5748-11e6-985f-68d011881a49.PNG)

**Comment by ghrich** [comment]
Hi Gareth,

Is this still an issue? I've just upgraded my dev site and it seems to be doing something very similar:

Dev Site (running 3.0.1.8)

![dev](https://cloud.githubusercontent.com/assets/8349855/17897899/c0f11e7c-694d-11e6-86e2-9e86bdde7ba0.PNG)

Sorry, I wont be able to give you access to my dev site as its on an internal server not accessible to the Internet... But if there is more info I can give you then please ask.

Thanks,

Richard

**Comment by gjb2048** [comment]
Not an issue that I've noticed.
