### ISSUE TITLE
Header h tags mixed up

### ISSUE THREAD

**Issue by fvendrell** [gjb2048/moodle-theme_essential#705]
Hello,

There seem to be a mixed up in the h tags in the header from what I observed in the generate code 

< h1 id="smalltitle">European Reiki Group</ h2>
< h2 id="subtitle">Forum of Reiki association representatives</h3></div>

It should be:

< h1 id="smalltitle">European Reiki Group**< /h1>**
< h2 id="subtitle">Forum of Reiki association representatives**< /h2>**</div>

 (with header title = full name and summary). See the generate code of my site www.reiki.group

**Comment by gjb2048** [comment]
Tested locally and no-bug.  Also looked at http://www.reiki.group/ and markup is correct.
