### ISSUE TITLE
Wrong profile image used.

### ISSUE THREAD

**Issue by cdipe** [gjb2048/moodle-theme_essential#710]
Using Moodle 3.0.5 and Essential 3.0.1.6 (Build: 2016010211)

When using the Forum Search while in a forum, the wrong (smaller) profile image is shown in the search result.
Also, the block "Activities and resources" is shown empty.

When browsing forums otherwise, all is normal.

Also, the profile image in Site News is using the smaller image.

**Comment by gjb2048** [comment]
Ok, several issues here which need to be separated, but before that post screen shots to demonstrate an actual issue rather than subjective personal preference of how things should be.  Thus how they are in Clean etc. pertains to that rather than the Essential way.

Also what is the "Activities and resources" block?  There is a link to such when editing but no actual block that I know of.

Also update to 3.0.1.7 and retest to confirm that no improvements have actually inadvertently already rectified the issue.

**Comment by gjb2048** [comment]
Cannot replicate, in fact, Clean uses smaller images....

![2016-08-17 18_11_18-start](https://cloud.githubusercontent.com/assets/1058419/17746097/7ed4fb9a-64a6-11e6-9e3e-42ca736c361c.png)
![2016-08-17 18_11_50-start](https://cloud.githubusercontent.com/assets/1058419/17746098/7ed967fc-64a6-11e6-9869-fd7490980450.png)
![2016-08-17 18_12_07-new notification](https://cloud.githubusercontent.com/assets/1058419/17746100/7ee0835c-64a6-11e6-9378-5ece5e9a2282.png)
![2016-08-17 18_12_52-start](https://cloud.githubusercontent.com/assets/1058419/17746101/7ee188f6-64a6-11e6-80fe-709c6b80ab26.png)
![2016-08-17 18_13_18-start](https://cloud.githubusercontent.com/assets/1058419/17746099/7ede9cd6-64a6-11e6-94ca-bfad10d9d97d.png)

**Comment by gjb2048** [comment]
RE: Also, the block "Activities and resources" is shown empty. - After looking, really no idea what you're talking about / does not make sense.

**Comment by cdipe** [comment]
Yes, you are right. Clean also uses the smaller version of the image. But clean always has a small image presentation in the forums, while Essential is showing a big image. This is an actual problem only on the Start page, I think,  and I'm not sure if this is a moodle core problem or a Essential problem, though - should I report this elsewhere?
I have made a short video showing the problem: https://play.lnu.se/media/t/0_9sidf0qr

The other problem, with the Activities block being empty in the serach ruslt page, I have to look further into.

**Comment by gjb2048** [comment]
Ok, I see Peter, I'll look at it again.

**Comment by gjb2048** [comment]
Ok, disparity with this Essential CSS:

````
body .forumpost .picture img {
    border-radius: 250px;
    width: 72px;
    height: 72px;
}
````

Which applies to the site news list, search result list and viewing a post.  The forum renderer for the first two uses the 35px version of the image and for the latter the 100px version.  However Essentual's CSS applies to all three, hence the issue.

**Comment by gjb2048** [comment]
Ok.... User picture output code is in forum's lib.php so cannot be overridden by the theme.  Code assumes you would not want to alter the size of things.  But... user_picture in the output renderer can be and so can render_user_picture - humm.

**Comment by gjb2048** [comment]
Fixed in M3.1, needs backporting.
