### ISSUE TITLE
Grading page has no navigation

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_essential#713]
Ref: https://moodle.org/mod/forum/discuss.php?d=334985&parent=1363059

I wonder what the Clean theme does?

**Comment by gjb2048** [comment]
Clean theme does the same.  For some reason the 'embedded' layout is used.  However there is navigation:

![2016-08-18 12_58_19-start](https://cloud.githubusercontent.com/assets/1058419/17772964/9f4a8316-6543-11e6-91cb-e715aa45cc90.png)

**Comment by nadavkav** [comment]
Just adding a rent, nothing useful I am afraid... 
I am sure Moodle HQ meant well, but... it seems like this new assignment page layout & navigation is too much confusing to experienced Moodle teachers that are used to the current block navigation layouts.
I am getting this from several Moodle installs, and we are considering hiding/disabling it, but still would like to see this fixed ;-)

**Comment by gjb2048** [comment]
Hi Nadav,

This page is a 'nightmare' from a dev point of view.  Took me ages to figure out what was going on.  No grid etc.  All 'absolutes' within default 'static' - trying to use standard 'relative' positioning as a container breaks it - yuck!!!

G

**Comment by gjb2048** [comment]
But... there are templates which can be overridden, so hope is not all lost!

**Comment by nadavkav** [comment]
Next time I am in the UK, we'll get some beers and hope it will de-solve this issue ;-)

**Comment by gjb2048** [comment]
Is a core issue, however discovered a way of overriding the template and adding the breadcrumb: https://moodle.org/mod/forum/discuss.php?d=338784

**Comment by gjb2048** [comment]
Then #722.

**Comment by gjb2048** [comment]
![2016-08-26 18_29_30-start](https://cloud.githubusercontent.com/assets/1058419/18014667/e2cc07c6-6bbb-11e6-8e12-ed02d50ad03b.png)

**Comment by nadavkav** [comment]
Looks great on RTL too :smile:

**Comment by gjb2048** [comment]
:)
