### ISSUE TITLE
Assignment grading page lacking styling

### ISSUE THREAD

**Issue by tonyyeb** [gjb2048/moodle-theme_essential#722]
http://vle.wilberforce.ac.uk/mod/assign/view.php lacks any form of styling (see below). Font face does not match the rest of the theme for example. Tested with latest 3.1.0.7.

![image](https://cloud.githubusercontent.com/assets/872800/17851375/933c0e50-6859-11e6-9237-a8fa024bd39b.png)

**Comment by gjb2048** [comment]
What are your theme font settings please?

Visiting the URL provided gives:

````
Default exception handler: A required parameter (id) was missing Debug: 
Error code: missingparam
* line 495 of \lib\setuplib.php: moodle_exception thrown
* line 552 of \lib\moodlelib.php: call to print_error()
* line 28 of \mod\assign\view.php: call to required_param()
````

**Comment by gjb2048** [comment]
Please prove that the font is set and is working elsewhere too.

I cannot replicate currently with 'User fonts'.

**Comment by gjb2048** [comment]
What version of Moodle are you running?

**Comment by gjb2048** [comment]
Cannot replicate with 'Custom fonts'.

**Comment by gjb2048** [comment]
Can replicate with 'Google web fonts' - change in status pending reply.

**Comment by tonyyeb** [comment]
Moodle version: Moodle 3.1.1+ (Build: 20160804)
Fonts: Google Web Fonts

**Comment by gjb2048** [comment]
NTS: embedded.php missing fonts tile file (and some others) in 'head'.

**Comment by gjb2048** [comment]
Will fix in the fullness of time.

**Comment by gjb2048** [comment]
Note: No idea why 'embedded' was chosen for this functionality!
