### ISSUE TITLE
Header not displaying correctly in 3.0.1.8

### ISSUE THREAD

**Issue by ghrich** [gjb2048/moodle-theme_essential#723]
Hi Gareth,

Is this still an issue? #704 

I've just upgraded my dev site and it seems to be doing something very similar:

Dev Site (running 3.0.1.8)
![dev](https://cloud.githubusercontent.com/assets/8349855/17898250/f62e36b4-694e-11e6-8b5a-23c8ad167158.PNG)

Production Site (running 3.0.1.6)
![prod](https://cloud.githubusercontent.com/assets/8349855/17898260/007d2a44-694f-11e6-9775-2cb3d1e23b7e.PNG)

Sorry, I wont be able to give you access to my dev site as its on an internal server not accessible to the Internet... But if there is more info I can give you then please ask.

Thanks,

Richard

**Comment by gjb2048** [comment]
Humm:

![2016-08-23 16_42_10-start](https://cloud.githubusercontent.com/assets/1058419/17898700/a6a96d1e-6950-11e6-95f1-8aae45c1fb98.png)

Not adjacent but social icons are close.  What are your font settings please?

**Comment by gjb2048** [comment]
Clearly you have replaced the string for 'Social networks' with 'Links', what other changes are there?

**Comment by gjb2048** [comment]
Looks like #700 needs careful backporting to M2.9 and M3.0.

**Comment by ghrich** [comment]
Hi Gareth,

Do you need anymore information?

In regards to changes, all I have done is made some lang changes as noticed and I always change core_renderer.php to display the users username instead of firstname (v3.0.1.6 line 1262)

``$usermenu .= html_writer::link($userurl, $userpic.$USER->username.$caret, $userclass);

Header font: Candara
Test font: Calibri

Custom css:

``#page-site-index #region-main {
 display: none !important;
 }

#page-site-index.editing #region-main {
display: block !important;
}

.navbar .navbar-inner .nav > li.dropdown ul.dropdown-menu > li > a {
color: #333;
}

.navbar .navbar-inner .nav-collapse .nav > li.dropdown ul.dropdown-menu > li > a {
color: #333;
}

#page-header #headerlogo {
    color: #026187;
}

Thats it. If I can be of anymore help please don't hesitate to ask. Thanks.

**Comment by gjb2048** [comment]
Will be fixed by #700 backport.
