### ISSUE TITLE
Missing Google Analytics code

### ISSUE THREAD

**Issue by ffeytout** [gjb2048/moodle-theme_essential#725]
Hi,
I'm using version 2.7.9.5.2 on a  2.7.15 Moodle and it seems to me there is a bug with Google Universal Analytics integration. 
I have enabled GUA with my site ID and it doesn't integrate the code on the web pages. There is no code between "" and ""

I would gladly take a quick fix for it.
Thanks

**Comment by gjb2048** [comment]
Hi,

I no longer support any versions less than Moodle 2.9 without being paid for my time.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Is this still an issue?

**Comment by ffeytout** [comment]
Hi, 
No, and it wasn't even one in the first place : I disabled admin reporting in Analytics and forgot about it. 
Thank you for your time and work.
