### ISSUE TITLE
New "page top" block region is not properly margined in RTL mode

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#726]
Just added a new block to the new (and super cool) "top page" block region, in RTL mode.
And when edit mode is turned off, the block slightly pushed to the right.
(something to do with margins not handled in RTL mode, I guess)
Here is how it looks:
![image](https://cloud.githubusercontent.com/assets/231168/18013949/4b33e240-6bc9-11e6-8105-df7a2595474e.png)
Adding the following code seems to solve it, but I am not sure if it is the right solution:
```
.dir-rtl aside.rowblock-blocks div.row-fluid div.block:first-of-type {
    margin-left: 0; /* Added this line */
    margin-right: 0; /* Kept this line, for luck ;-) */
}
```

**Comment by gjb2048** [comment]
Nadav,

I've tidied a few things up, so have you tested master on GitHub?

G

**Comment by nadavkav** [comment]
Just updated master two hours ago

**Comment by nadavkav** [comment]
And now, again, git saying "Already up-to-date."

**Comment by nadavkav** [comment]
Link to the course: http://themes.moodlemagic.info/course/view.php?id=11

**Comment by gjb2048** [comment]
Ok, I believe you, currently working on #713.

**Comment by gjb2048** [comment]
Then #722.

**Comment by nadavkav** [comment]
You know, fixing #713, will automatically get you a "brave" badge ;-)

**Comment by gjb2048** [comment]
LOL - you'd better go to makebadg.es then! ;)

**Comment by nadavkav** [comment]
![bravemoodler_makebadges-1472233530](https://cloud.githubusercontent.com/assets/231168/18014952/0c1d00b4-6bce-11e6-99b2-7b2daac1c9af.png)

**Comment by gjb2048** [comment]
:)
