### ISSUE TITLE
Drag modules icons when in course Edit mode, are partly misplaced.

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#728]
![image](https://cloud.githubusercontent.com/assets/231168/18033218/e9eb483a-6d25-11e6-87c6-31a281832b00.png)

**Comment by gjb2048** [comment]
Related to: https://moodle.org/mod/forum/discuss.php?d=337924

**Comment by nadavkav** [comment]
Exactly

**Comment by gjb2048** [comment]
But cannot reproduce.  What are the settings for layout etc?

**Comment by gjb2048** [comment]
Course format?

More info please Nadav.

**Comment by nadavkav** [comment]
Oups, sorry. 
Regular "topics"

**Comment by nadavkav** [comment]
http://themes.moodlemagic.info/course/view.php?id=2

**Comment by gjb2048** [comment]
Thanks for the link, however, guest access and cannot turn editing on!

**Comment by gjb2048** [comment]
Still cannot replicate locally.

**Comment by nadavkav** [comment]
You got email with admin privileges, enjoy :smile:

**Comment by gjb2048** [comment]
Thanks.

I've found some CSS on your site that does not exist in the theme:

````
.section .activity .editing_move {
    position: absolute;
    left: 0;
    top: 0;
}
````

Where can I send the bill for my time! ;)

**Comment by gjb2048** [comment]
Turned on TDM but could not find it.  TDM now off.  Not in Custom CSS.

**Comment by gjb2048** [comment]
But in Bootstrapbase course.less there is:

````
        .editing_move {
            /* Move the move icon to the start of the line */
            position: absolute;
            left: 0;
            top: 0;
        }
````

Humm!

**Comment by gjb2048** [comment]
Ok... that's in local... humm.

**Comment by gjb2048** [comment]
So why is your left indent less than mine?

**Comment by gjb2048** [comment]
Ok.... Bug in the Board course format which has:

````
.section .activity .mod-indent-outer {
    padding: 0 !important;
}
````
Therefore not a problem with the theme, but with the Board format which should have CSS specific to it like I do in Grid and Collapsed Topics etc.

**Comment by gjb2048** [comment]
Grrrr.

**Comment by nadavkav** [comment]
Found it. It's Moodle's bootstrapbase 
https://github.com/moodle/moodle/blob/master/theme/bootstrapbase/less/moodle/course.less#L69

**Comment by nadavkav** [comment]
Ok. now I see you also found it (a few comment before me)

**Comment by nadavkav** [comment]
I do not have Board course format installed.

**Comment by gjb2048** [comment]
TDM on.... Yes you do!  Explain this then! ->

![2016-08-30 18_14_33-start](https://cloud.githubusercontent.com/assets/1058419/18099353/05a024ec-6ede-11e6-83f1-b624388a5611.png)

**Comment by nadavkav** [comment]
Mmmm... 
It is probably something else, checking...

**Comment by nadavkav** [comment]
I think I found it. it is actually...
```
.path-course-view li.activity>div, .path-site li.activity>div {
    position: relative;
    padding: 0 16px 0 0;
}
```
Where it should be:
```
.path-course-view li.activity>div, .path-site li.activity>div {
    position: relative;
    padding: 0 0 0 16px;
}
```

**Comment by gjb2048** [comment]
No Nadav, Sorry you are wrong.

**Comment by gjb2048** [comment]
Ok, save time, agree with me!  Right, in Chrome if I disable that 'iffy' CSS in the Board format then everything becomes as it should:

![2016-08-30 18_27_41-new notification](https://cloud.githubusercontent.com/assets/1058419/18099725/d4f41b4e-6edf-11e6-9fd8-40a27e6624ad.png)

**Comment by gjb2048** [comment]
Therefore a problem with the Board course format!!!!!!!!!

**Comment by nadavkav** [comment]
I would LOVE to agree but I do not have Board course format installed. (still looking for that code on the entire Moodle install)
And also added the following code:
```
.editing.path-course-view li.activity>div, 
.editing.path-site li.activity>div {
    position: relative;
    padding: 0 0 0 16px;
}
```
Which looks much better now. (but might not be the right/correct solution)

**Comment by gjb2048** [comment]
Ok,

So why does this URL - http://themes.moodlemagic.info/course/format/board/styles.css - give a style sheet then?

**Comment by gjb2048** [comment]
You have the board course format installed:

![2016-08-30 18_36_57-start](https://cloud.githubusercontent.com/assets/1058419/18099970/e93d8f3a-6ee0-11e6-9f3a-c6e07b4282e9.png)

**Comment by gjb2048** [comment]
I'm not sure I can put it any other way!!!!!!!!

**Comment by nadavkav** [comment]
Me BAD! My phpStorm IDE was not synced with the installed plugins on the server.

**Comment by gjb2048** [comment]
At last!!!!

**Comment by nadavkav** [comment]
:-( so sorry

**Comment by nadavkav** [comment]
Ok. just send you a 50USD "donation" through http://www.moodlegarage.com/ or else I cound not live with myself

**Comment by gjb2048** [comment]
Thank you Nadav.
