### ISSUE TITLE
New "page top" block region looks weird, when adding a new module

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#729]
To add a new module I have to turn editing ON, and click the "Add resource or activity" link.
After choosing a module, I get redirected to the module's settings page, and it looks like this:
![image](https://cloud.githubusercontent.com/assets/231168/18033233/65d5d97e-6d26-11e6-8bee-dd99a934dfe5.png)

I find it a little bit confusing for teachers, seeing all the dashed borders of the blocks regions.
What do you think?

I am not entirely sure what would be a good solution to this, do you have any ideas?

**Comment by nadavkav** [comment]
Thinking about this a little bit more, maybe...
* "If no blocks in the region" make it about 1cm height? (so it is seen, but it take not so much space)
* Use a theme renderer to override the sections display on the course front page, and add an "Add resource or activity" icon at the end of the section's title? in normal mode, not in edit mode. and, of course, only for teachers. (which could be a cool feature too, regardless)

**Comment by gjb2048** [comment]
If no blocks in region then will leave as is as height is fine elsewhere and matches collapsed blocks when dragging as a suitably barn door sized target.

**Comment by nadavkav** [comment]
Great. as I only ment incourse page layouts.

**Comment by gjb2048** [comment]
Turns out to be the 'admin' layout.

**Comment by gjb2048** [comment]
Ok, I've made a decision that the page top block region is silly on admin pages.
