### ISSUE TITLE
Group symbols not switching when editing activities/resources on course page

### ISSUE THREAD

**Issue by cdipe** [gjb2048/moodle-theme_essential#730]
I'm not sure if this is a theme problem, but I suspect so: When using the group symbols to change group settings on course front page, the symbols does not change until page is reloaded. The settings does, though, as well as the hover text information. I have made a video showing the problem: [https://play.lnu.se/media/t/0_yq3dooel](https://play.lnu.se/media/t/0_yq3dooel)

Using Moodle 3.0.5
Essential 3.0.1.8 (Build: 2016010213)

**Comment by gjb2048** [comment]
Was a theme problem, then fixed, should be working.

**Comment by gjb2048** [comment]
First raised in #320 and fixed in #535.

**Comment by gjb2048** [comment]
Ah, #320 closed by mistake, still an issue and no solution as core thing.

**Comment by cdipe** [comment]
Sorry, I don't understand, has this been fixed? It's not working for me, maybe there something I should do? 
I'm already using the latest release, Essential 3.0.1.8 (Build: 2016010213)

**Comment by gjb2048** [comment]
Ok, I thought it was fixed by some changes I remember a few years ago.  Not fixed and thought impossible to fix, now after some research on recent changes it looks like it can be fixed in #320 but I've not fixed it yet.
