### ISSUE TITLE
Unable to disable the new "page top" block region

### ISSUE THREAD

**Issue by izendegi** [gjb2048/moodle-theme_essential#734]
Hi,

I'm not sure if this is an issue or not, but I'm trying to disable the new page top block region with no success.

I think this should be done setting "Never show" in _theme_essential | fppagetopblocks_ option (_Enable additional front page 'Page top' blocks_), but I've done that (and purged all caches) and that region remains enabled.

I'm using Moodle 3.1.1 (Build: 20160711) with Essential 3.1.0.7 (Build: 2016061706)

TIA.

**Comment by cdipe** [comment]
Hi! This worked for me (Moodle 3.0.5):
/* Hide Top page block*/
aside#block-region-page-top {
display: none; 
}

**Comment by izendegi** [comment]
Hi,

Thanks @cdipe , that trick works in 3.1 too, but shouldn't that theme_essential | fppagetopblocks setting do that?

**Comment by cdipe** [comment]
As I understand it, that only controls the front page top block.

**Comment by izendegi** [comment]
You may be right, but it doesn't disable it in the front page either...

Anyway, if you are right it would be great to have an option to disable that function in a site level.

**Comment by gjb2048** [comment]
Ok, on the frontpage there is the option as the 'page-top' replaced 'home-left' etc. as it made sense to do this given possible confusion - this was costed and implemented in #606.  In that issue there was not the requirement to have 'before' / 'after' login etc. as that would not make sense on the other pages.  It was not a requirement to have a 'no-show' for this.

Therefore to add such a setting and backport is one hour of my time.

**Comment by lazydaisy** [comment]
To disable this in CSS you need the body classes which are:
.has-region-page-top 
.used-region-page-top
.empty-region-page-top
So depending on the conditions imposed you can add the body classes to target those conditions.
For example:
https://github.com/lazydaisy/moodle/blob/master/theme/bootstrapbase/less/moodle/core.less#L12-L40

**Comment by bfriesenvcc** [comment]
Thanks, @cdipe! As far as I can tell, your custom CSS works on all course pages, which is all I really care about.  I don't want our instructors to see this.  An option in the theme settings would be great.  Perhaps Gareth will consider adding it when he does the next major upgrade to 3.2.
