### ISSUE TITLE
Problem when nothing in the right column ?

### ISSUE THREAD

**Issue by GuiGuiSoft** [gjb2048/moodle-theme_essential#735]
Hello,

With the last Realease Candidate, when there is no block in the right colum, left colum and central area are smaller than they should (the content does not "fill" all the width like before).

You can see an example below.
![1](https://cloud.githubusercontent.com/assets/8069239/18094423/b1b8afc0-6ed3-11e6-9fb6-889b82305145.png)
![3](https://cloud.githubusercontent.com/assets/8069239/18094424/b1bff0c8-6ed3-11e6-853c-96e6e26338ab.png)

Regards

**Comment by gjb2048** [comment]
Fixed in #724.
