### ISSUE TITLE
Stripes on grade-report even rows use incorrect color for links

### ISSUE THREAD

**Issue by danmarsden** [gjb2048/moodle-theme_essential#736]
on the grader report on even rows the text colour of links (names, magnifying glass etc) uses the textcolor instead of the correct link colours.

looks like it's related to the color: inherit line here:
https://github.com/gjb2048/moodle-theme_essential/blame/master/style/essential-settings.css#L1059

removing the line color: inherit makes the links use the correct color.

hopefully that makes sense - let me know if you need a screnshot and I'll send one through.

**Comment by gjb2048** [comment]
Hi Dan,

That is currently intentional as to be consistent with the striped rows (odd) ones as there is no 'stripeurlcolour' setting.  Therefore to be balanced there would have to be one.  So this is actually an enhancement.

Such a setting would be around 30 mins to an hour to complete.

Cheers,

Gareth

**Comment by danmarsden** [comment]
yep - makes a lot of sense for this to be a setting, thanks Gareth! :-)

**Comment by gjb2048** [comment]
No worries Dan, but don't thank me yet, I've added the label 'Funding required'.

**Comment by danmarsden** [comment]
yep - saw that - made sense to me! - I know how hard it is to balance maintenance vs improvements as a plugin maintainer!

**Comment by danmarsden** [comment]
pull request coming your way... not sure how the essential-alternative.css file is generated though... will try to work that out and submit a pull request you can use.

**Comment by danmarsden** [comment]
scrap that - I see the less files now....
