### ISSUE TITLE
Rubric pop-out on assignment grading page doesn't use full height.

### ISSUE THREAD

**Issue by danmarsden** [gjb2048/moodle-theme_essential#737]
on the assignment grading page if you get the rubric to pop-out it doesn't use the full height of the available pop-up
![rubric grade page](https://cloud.githubusercontent.com/assets/362798/18150661/c1803dd2-703c-11e6-9e94-74cb9150b73b.png)

**Comment by gjb2048** [comment]
Hi Dan,

I tried to replicate, however even though my test assignments are set to 'Rubric' I cannot find the button to open up the pop-up and be in a position to replicate the problem.  Please could you provide the test steps I need in order to do so.

Thanks,

Gareth

**Comment by danmarsden** [comment]
sure - create an assignment with "grading method" set to "rubric" - Save and display.

Define new rubric (should appear after save and display)
add 5 or more criteria to the rubric so that you have a decent list
save rubric and make it ready
hit grade button to start grading
brings up the new grading form with the rubric embedded on the right hand side.
click the expand arrows at the top right of the embedded rubric to make it pop-out.

hopefully that's enough? - let me know if you get stuck - thanks!

**Comment by gjb2048** [comment]
Thanks for the information Dan, I'll attempt to replicate when I get a moment.

**Comment by gjb2048** [comment]
Can replicate thanks and also noticed this:

![2016-09-02 17_47_06-start](https://cloud.githubusercontent.com/assets/1058419/18211443/76644cd6-7135-11e6-9c9e-ad0fa722d7ae.jpg)

Too many grains of sand to style.

**Comment by gjb2048** [comment]
http://stackoverflow.com/questions/17904088/disable-less-css-overwriting-calc

**Comment by danmarsden** [comment]
great - thanks Gareth!
