### ISSUE TITLE
FontAwesome icons on incorrect side for RTL in Firefox.

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_essential#739]
Ref: https://moodle.org/mod/forum/discuss.php?d=339178

**Comment by nadavkav** [comment]
Hi @gjb2048,
I am checking out a new development funding framework: bountysource.com
And added a "bounty" on this issue. see:
https://www.bountysource.com/issues/37525473-fontawesome-icons-on-incorrect-side-for-rtl-in-firefox 
It feels like it is missing some link automation between your account the and bountysource service, so with your permission... How do I link it back to this issue, properly?

**Comment by gjb2048** [comment]
Hi Nadav,

Thanks for the idea, I've looked at BountySource in the past, but please don't use them because of the payments: https://github.com/bountysource/core/wiki/Frequently-Asked-Questions#do-i-have-to-pay-taxes-on-bounties-i-collect - if I were to earn more than $600 then I'd have to fill in a whole load of US forms (could mean a trip to the US embassy in London etc. - and that would be expensive).  I have no desire to fill in anymore paper work than I do already locally.

In any event I only charge for enhancements and not bugs.

Kind regards,

Gareth

**Comment by nadavkav** [comment]
Thanks for the insights, I was not aware of the complexity they impose.
Anyways, it was just a test. and I will revert it.

I know your policy about bugs and features (requests), which is great by me.
but I was only using this issue as a test because it has "rtl" in the title, to check out the service and did not gave much thought about it's type (bug/feature)

Do you have a service that you prefer? (bitcoins, may be ;-))

**Comment by gjb2048** [comment]
MoodleGarage!

**Comment by nadavkav** [comment]
You're right. it's the best.
I was too quick on the trigger. should have asked you first.

**Comment by nadavkav** [comment]
btw, I am running your latest theme version on M31 and I am not experiencing this issue

**Comment by gjb2048** [comment]
Umm, that's because its a M3.0 and M2.9 bug only, hence the labels! :)

**Comment by nadavkav** [comment]
I know, just to made sure you do not fix this on my account, as I was just using this issue for testing.
