### ISSUE TITLE
'My Courses' scrollbar no longer appears in dropdown menu

### ISSUE THREAD

**Issue by ghrich** [gjb2048/moodle-theme_essential#741]
Hi Gareth,

I've just upgraded to 3.0.1.9 and thank you for fixing the issue relating to #700.

I now seem to have a different issue in that the scrollbar on the 'My Courses' dropdown menu no longer appears.

When the menu opens up it drops down as long as the screen but you can't scroll on the menu to get to the courses at the bottom.

I'm not 100% sure on the function of this menu in the past as my account has limited courses assigned to it so I didn't notice this but staff are informing me that on their menus are acting differently (some of them are assigned to 50+ courses).

If you need any more info please let me know!

Thanks,

Richard

**Comment by ghrich** [comment]
![menu](https://cloud.githubusercontent.com/assets/8349855/18267431/fd2e954e-7416-11e6-8368-da1127e49002.png)

**Comment by ghrich** [comment]
Just uploaded this screenshot as an example of what the menu now does in 3.0.1.9.

Thanks,

Richard

**Comment by gjb2048** [comment]
Hi Richard,

This is intentional.  The original CSS used to restrict the list caused the top arrow to disappear.  Now that there is the 'mycoursesmax' setting, it restricts the number of courses on the menu.  Please use that instead.

Kind regards,

Gareth

**Comment by ghrich** [comment]
Ok, thanks for the update. I've had a look and made some changes to these settings, however, the vast majority of my users are assigned to far more than 20 courses and they use this menu heavily. Are you planning on incorporating the scrollbars in the future? And/or some other solution at all?

Thanks,

Richard

**Comment by gjb2048** [comment]
Hi Richard,

I'm not planning anything at all.  Technically things work as they stand.  Any other solution would probably be an enhancement.

Cheers,

Gareth
