### ISSUE TITLE
Custom HTML block is showing in signup.php

### ISSUE THREAD

**Issue by Al6325** [gjb2048/moodle-theme_essential#742]
When you create a custom html block at home page and the block has setting "Display throughout  the entire site", then it will showed in signup.php page in the middle column. 

How it may be fixed?

This bug can be viewed on the website etp2014.ru - block named "ГЛАВНОЕ МЕНЮ"

**Comment by gjb2048** [comment]
Ok, if "Display throughout the entire site" then well!!! It will appear on the WHOLE site!!!!!!   So in what way is this a theme issue?

**Comment by Al6325** [comment]
Ok, but it must be shown in left side and not in footer in middle column...

See also: https://drive.google.com/folderview?id=0ByMcD7HJRyo1emVMT2VJUkowazg&usp=sharing

**Comment by gjb2048** [comment]
Ok, fair enough, but that is your preference.

**Comment by Al6325** [comment]
I not want your support, I think it's bug. It's only information for you.

**Comment by Al6325** [comment]
So, this block shown by standard procedure in signup.php -> echo $OUTPUT->footer(); 

Do you mean what block defined in left side realy must be displaed in footer?

**Comment by gjb2048** [comment]
Ok, as the signup page is one column and looks ok as such, then not a bug.

With respect as its not a bug to fix, then I'm not going to answer questions.
