### ISSUE TITLE
Suggested improvement: Better tuning of "Course content search"

### ISSUE THREAD

**Issue by cdipe** [gjb2048/moodle-theme_essential#745]
My users find the "Course content search" to be very confusing, since it searches courses, activities, resources and course sections and produces so many results. For now we've turned it off, but with more granular configuration settings it would be useful. 
I would probably set it to search course titles only, and that would be great for our many users with a lot of courses.

Also, the shown results could use som space between them, it's a very compact list now.

Using Moodle 3.0.5 and Essential 3.0.1.9 (Build: 2016010214)

**Comment by gjb2048** [comment]
Interesting, need to think.  If 15 mins setting then may do, otherwise funded enhancement.

**Comment by gjb2048** [comment]
Hi Peter,

Would it be ok for it to just not list the activities / resources but still the course sections?  As course names themselves are not linked?

G

**Comment by cdipe** [comment]
I do think that it should be only courses, if they can be made clickable, since so many people have a lot of courses and so many courses have a lot of sections that is called the same in each and every course. Or, may that should be a filter option?
(With the global search, there's already a way to find specific resources - or maybe I'm wrong, we have still not implemented global search.)

**Comment by gjb2048** [comment]
Ok, currently course sections and course activities / resources are linked.  Therefore course only would be an addition as well as the setting for removing the former.

**Comment by gjb2048** [comment]
Hi Peter,

Is this still an issue?

Kind regards,

Gareth

**Comment by cdipe** [comment]
Hi Gareth, I think a filter to choose weather to search only course names or all content would be great! As always, the problem when having a lot of courses... 
The "My Latest Courses" menu is **very** much appreciated with us, but the possibility to find your old courses would add to the usability.
![sok kurs](https://user-images.githubusercontent.com/14754240/27783827-0d05ffea-5fd8-11e7-862b-93eacf2103eb.png)

**Comment by gjb2048** [comment]
Thank you for your reply Peter.

I think that "The "My Latest Courses" menu is very much appreciated with us, but the possibility to find your old courses would add to the usability." is a separate issue - or do you mean within this course search?

**Comment by cdipe** [comment]
Absolutely, I think "My latest courses" should be left as it is. 

I would just like to add a filter to the course search, to search only for corse names/titles and exclude the course content, making it quicker to find a specific course. 
(Not sure what option is more pedagogical to the users: "Include course content in search" or "Exclude course content from search" or "Search course titles only", but it's the functionality I'm looking for.)

Another suggestion from one of my teachers, having a lot of courses: When searching for specific content, an operator option would be nice, like "course" AND/OR "content". 
I not as sure on the usability, though.

**Comment by gjb2048** [comment]
Implemented in https://github.com/gjb2048/moodle-theme_essential/commit/86776b6472a0b95c96d873e084e800820cd4993c
