### ISSUE TITLE
"Page Top" blocks area, in edit mode, display blocks one under the other, in RTL mode

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#748]
![image](https://cloud.githubusercontent.com/assets/231168/18484919/3580d72c-79f3-11e6-843a-841a7d98f1db.png)

Fix, change:
```
aside.rowblock-edit div.block:nth-of-type(1) {
    margin-left: 0;
}
```
To:
```
.dir-rtl aside.rowblock-edit div.block:nth-of-type(1) {
    margin-right: 0;
}
```

**Comment by gjb2048** [comment]
Odd as LESS mixin already has that:

````
// Support multiple rows when editing otherwise above works, see: http://www.w3schools.com/cssref/sel_nth-of-type.asp
.rowblock-nth(@index) {
    aside.rowblock-edit div.block:nth-of-type(@{index}) {
        margin-left: 0;
    }
    .dir-rtl aside.footer-edit div.block:nth-of-type(@{index}) {
        margin-right: 0;
    }
}
````

**Comment by gjb2048** [comment]
Oh :poop: selector is wrong.

**Comment by gjb2048** [comment]
Note: Before I do this I have work to do, then https://tracker.moodle.org/browse/MDL-55913, then something on another theme I've been meaning to do in ages, then review the pull request on Essential, then the other issues.  Might be a while and if more work comes in.....

**Comment by nadavkav** [comment]
It's minor. backlog it.

MDL-55913, is much more interesting, philosophically. as I keep asking myself, over the years, what is best. looking forward for your answer on that MDL.

**Comment by nadavkav** [comment]
10xs
