### ISSUE TITLE
Custom icon colour doesn't seem to apply correctly to icons in drop-downs

### ISSUE THREAD

**Issue by danmarsden** [gjb2048/moodle-theme_essential#757]
Here's what happens in 3.1 site when you set a custom icon colour - see the drop down on the top right

![31-essentialicons](https://cloud.githubusercontent.com/assets/362798/18620981/d21c225e-7e70-11e6-9d25-f66a6a7652dd.png)

Here's what happens in a 3.0 site with an older version of the 3.0 theme:
![30-essentialicons](https://cloud.githubusercontent.com/assets/362798/18620979/cc7146c2-7e70-11e6-8fbe-2204f6e48dac.png)

**Comment by danmarsden** [comment]
we have a handful of clients using the essential theme on their sites - a couple of them have just started testing 3.1 upgrades - (these issues have been reported to us from our clients) in the past they have probably been using slightly older Moodle releases where the community has already given you a lot of feedback. Typically we try to provide patches upstream to 3rd party plugin developers but some of the reported issues the clients are happy to live with as-is for now - but I figure it's helpful to document them by creating an issue here for you. Thanks heaps!

**Comment by gjb2048** [comment]
Hi Dan,

Thank you for your reply.  Can I be cheeky and ask if any of them wish to sponsor the theme to support its maintenance?  They get a mention in the readme file and I do respond to sponsors faster.

Kind regards,

Gareth

**Comment by danmarsden** [comment]
That's not cheeky at all! - I've been thinking about ways we can encourage this sort of thing anyway - for some clients it might be easier to manage than others but I'll do what I can. :-)

Can you please email me the details on your sponsorship processes via e-mail so I have them on file for future reference?

**Comment by gjb2048** [comment]
Thanks Dan, what's your eMail so I can eMail you please?

**Comment by danmarsden** [comment]
try my firstname at http://danmarsden.com
