### ISSUE TITLE
Changes not saving

### ISSUE THREAD

**Issue by carlboyd** [gjb2048/moodle-theme_essential#758]
I am running Essentials 3.0.1.8 (Build: 2016010213) on Moodle 3.0.3 (Build: 20160314).

The site has been live since August, I have loved using the theme and have received excellent feedback from the users. 

I don't normally buy the "It just stopped working" game, however this morning I was making changes to the Custom CSS. I successfully made one change to hide the header of a block on the front page:

/*Hides the header for the bullying block on front page*/
#page-site-index .block_tc_stop_bullying  .header {
display:none; 
}

However now I can't make any changes to any of the settings within the theme. This includes changing the Custom CSS, Changing a colour or even putting the site in maintenance mode.

I thought the changes were saving however I only worked it out when I tried to install a block and got stuck on the upgradesettings.php page as I can no longer write changes to the DB.

Kind regards,

Carl

**Comment by gjb2048** [comment]
Hi Carl,

In the Custom CSS did you have the comment above the CSS too?  As its missing the '*', so probably broke it.

G

**Comment by carlboyd** [comment]
Hi Gareth, that was quick!

It looks like the editor stripped it out on GIT. It is in my custom CSS though.

**Comment by gjb2048** [comment]
Hi Carl,

I added:

````
/* Hides the header for the bullying block on front page */
#page-site-index .block_tc_stop_bullying .header {
display:none; 
}
````

to the Custom CSS box and my site is working fine.  Therefore not a theme problem.  If you'd like my support then I offer competitive rates.  Terms of business available on request.

Kind regards,

Gareth
