### ISSUE TITLE
Message button disappears when viewing user's profil under Site administration

### ISSUE THREAD

**Issue by PatLemaire** [gjb2048/moodle-theme_essential#759]
Hi,
I no longer see the "Message" button when I'm on a specific user's profil under "List of users" in Site administration. This button is visible only when I'm on a course context. The function's name of this button is "core_message-messenger::sendmessage"
"page-context-header" seems totally missing in user profil in system context which includes avatar, name and "Message" button.
Thanks
Best regards,
Patrick

**Comment by PatLemaire** [comment]
I think it's link to this other issue #747 !

**Comment by gjb2048** [comment]
It is.
