### ISSUE TITLE
Impossible to drag a block into an empty left column

### ISSUE THREAD

**Issue by PatLemaire** [gjb2048/moodle-theme_essential#760]
Hi,
I try to drag a block into an empty left column and I think there is no area for this if the column is empty. It works for a left column which already contains almost a block.
Regards,
Patrick

**Comment by gjb2048** [comment]
I know this works.  Ok, what version of Essential?  Screen shot of issue please.

**Comment by PatLemaire** [comment]
Essential version : 3.1.0.8 (Build: 2016061707)
![2016-09-21_16-35-56](https://cloud.githubusercontent.com/assets/8931218/18715450/98c6d7ba-8019-11e6-8e33-a3b22ff9399e.png)

**Comment by PatLemaire** [comment]
Notice that the "Add a new block" is on the right column for me.
No problem with Clean theme... Moodle version : Moodle 3.1.1+ (Build: 20160825)

**Comment by gjb2048** [comment]
So you are using the old style layout?

**Comment by PatLemaire** [comment]
Yes...

**Comment by gjb2048** [comment]
Not dragging far enough:

![2016-09-21 16_10_19-start](https://cloud.githubusercontent.com/assets/1058419/18716849/1fce74c4-8016-11e6-8323-c11fba0deb47.jpg)

Upon inspection of the D&D drop area, there is nothing wrong.

**Comment by PatLemaire** [comment]
OK. Sorry for the inconvenience.
