### ISSUE TITLE
Course fullname repeated above and below breadcrumbs

### ISSUE THREAD

**Issue by danmarsden** [gjb2048/moodle-theme_essential#762]
looks like pagetopheader.php calls context_header and adds it before the breadcrumbs, then context_header is called again in essential core_renderer.php course_title() - is this correct behaviour?

![essentialheadercoursenameduplicate](https://cloud.githubusercontent.com/assets/362798/18771653/a648879a-8194-11e6-823a-ad5652dfb161.png)

**Comment by danmarsden** [comment]
looks like it was caused by #747

**Comment by gjb2048** [comment]
It is.  What a mess.  I thought it was too easy.  Snag is with core they write methods that do too much in the context of their themes.

**Comment by danmarsden** [comment]
yep - I'm glad I don't maintain any themes! - maintaining Essential is a much bigger challenge than any of the other plugins I look after these days.... except maybe SCORM when I first started working on it! - these days it's pretty stable.

**Comment by gjb2048** [comment]
Essential is a beast that was brought into this world overnight at 30,000 feet in a moment of jet lagged inspiration.  At the moment I seem to be the only one brave enough to tame it.

**Comment by danmarsden** [comment]
classic!
