### ISSUE TITLE
Custom EOT files don't work

### ISSUE THREAD

**Issue by leonstr** [gjb2048/moodle-theme_essential#763]
I'm troubleshooting an issue for a client at the moment where lots of 404 Not Founds are being logged for fonts.

Custom fonts are enabled for this site and font files have been uploaded.

It looks like the path name being used for the pathname hash on storing EOT files is different for the one being used to retrieve them. Consequently the EOT file isn't retrieved from mdl_files and the 404 is returned.

What I think is happening is that in theme/essential/settings.php, the filearea for EOT files is set to fontfileweotheading and fontfileweotbody, but theme/essential/classes/toolbox.php sends a style sheet with fontfileeotheading and fontfileeotbody prefix (no 'w').

When the browser tries to get the resources matching these prefix, they don't match, thus 404.

**Comment by gjb2048** [comment]
Ok, before I spend any time, what version of Essential and Moodle please?

**Comment by leonstr** [comment]
Reproduced with Moodle 3.1.1 (20160721) and theme_essential 3.1.0.9 (Build: 2016061708).

**Comment by gjb2048** [comment]
Ta.

**Comment by gjb2048** [comment]
Are you using 3.1.0.9 in production with your clients?

**Comment by leonstr** [comment]
No, theirs is 3.1.0.6 (Build: 2016061705). I tested with the latest to check the issue I'm reported hadn't been resolved (assuming my report and proposed resolution are correct).

**Comment by gjb2048** [comment]
Ta.  Ok, I hope you don't mind, but I'm going to fix in one commit locally with words in Changes.txt rather than merge the pull request.  That is because I'd then have double the number of commits to cherry-pick for backporting (the merge and the update to CHANGES.txt).

**Comment by gjb2048** [comment]
Broken for years and nobody spotted it!
