### ISSUE TITLE
Login page background image.

### ISSUE THREAD

**Issue by gemguardian** [gjb2048/moodle-theme_essential#766]
Hi Gareth, 

I would like to see the option in Essential where I can upload a background-image that is only available on the  /login/index.php page, with an option to choice to fill the back ground or just show on the div class loginpanel. 

Can you give me a cost / time indication for this? 

Thank you 

Gemma

**Comment by gjb2048** [comment]
Hi Gemma,

Ok, would you like to gave many images like the "Login page background image changer" settings in the Shoehorn theme?

Or for what you want exactly with testing where the image is stretched to fit the available space, then one and a half hours at the most.  As always if less, then I charge less.  Cost is per my current rates with admin fee - do you have a copy of them?  Also when in the 'login-panel' container should there be some 'opacity' such that the white background is faded like a 'haze' on top of the image and thus better for contrast and readability.

Kind regards,

Gareth

**Comment by gemguardian** [comment]
Hi Gareth, 

I am kind of doubting on that part. 



But looking to the user case I am on right now – see http://leeromgeving.iokai.nl/login/index.php-  I am seeking a solution where I can upload an image that stretches to fit the available space of the box. 
Something that “breaks” the full white background. 


But I do like the Shoehorn solution as well :( 

 

I have copy of your fees :) 

And you suggestion on the “opacity” sounds fine to me. 

 





 

Van: Gareth J Barnard [mailto:notifications@github.com] 
Verzonden: woensdag 28 september 2016 17:57
Aan: gjb2048/moodle-theme_essential <moodle-theme_essential@noreply.github.com>
CC: gemguardian <gemma@ltnc.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [gjb2048/moodle-theme_essential] Essential Moodle 3.0 - 3.1 new feature request (#766)

 

Hi Gemma,

Ok, would you like to gave many images like the "Login page background image changer" settings in the Shoehorn theme?

Or for what you want exactly with testing where the image is stretched to fit the available space, then one and a half hours at the most. As always if less, then I charge less. Cost is per my current rates with admin fee - do you have a copy of them? Also when in the 'login-panel' container should there be some 'opacity' such that the white background is faded like a 'haze' on top of the image and thus better for contrast and readability.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Hi Gemma,

As sometimes there are instructions, then I suggest 'loginbox' instead of 'loginpanel'.  Would you like a prototype screen shot of what could be possible?

Kind regards,

Gareth

**Comment by gemguardian** [comment]
Yup please :) 


Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Gareth J Barnard <notifications@github.com> Datum: 28-09-16  19:46  (GMT+01:00) Aan: gjb2048/moodle-theme_essential <moodle-theme_essential@noreply.github.com> Cc: gemguardian <gemma@ltnc.nl>, Author <author@noreply.github.com> Onderwerp: Re: [gjb2048/moodle-theme_essential] Essential Moodle 3.0 - 3.1 new
  feature request (#766) 
Hi Gemma,

As sometimes there are instructions, then I suggest 'loginbox' instead of 'loginpanel'.  Would you like a prototype screen shot of what could be possible?

Kind regards,

Gareth

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gjb2048/moodle-theme_essential","title":"gjb2048/moodle-theme_essential","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/gjb2048/moodle-theme_essential"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gjb2048 in #766: Hi Gemma,\r\n\r\nAs sometimes there are instructions, then I suggest 'loginbox' instead of 'loginpanel'.  Would you like a prototype screen shot of what could be possible?\r\n\r\nKind regards,\r\n\r\nGareth"}],"action":{"name":"View Issue","url":"https://github.com/gjb2048/moodle-theme_essential/issues/766#issuecomment-250242975"}}}

**Comment by gjb2048** [comment]
![2016-09-28 19_11_53-start](https://cloud.githubusercontent.com/assets/1058419/18926567/3658286c-85b0-11e6-9e1b-e59252099a69.jpg)
![2016-09-28 19_12_21-start](https://cloud.githubusercontent.com/assets/1058419/18926566/3654873e-85b0-11e6-9e82-6ba52afa5606.jpg)
![2016-09-28 19_12_38-start](https://cloud.githubusercontent.com/assets/1058419/18926564/364352d4-85b0-11e6-8521-041dc49d1275.jpg)
![2016-09-28 19_15_09-start](https://cloud.githubusercontent.com/assets/1058419/18926568/3658fea4-85b0-11e6-9ef8-fe41771b39f7.jpg)
![2016-09-28 19_15_41-start](https://cloud.githubusercontent.com/assets/1058419/18926565/36448622-85b0-11e6-86fe-57eca629e281.jpg)

**Comment by gjb2048** [comment]
White bit is page header background image being: http://leeromgeving.iokai.nl/pluginfile.php/1/theme_essential/headerbackground/1475083145/banner_wit.png

**Comment by gemguardian** [comment]
Asked a second opinion :) going for the full picture as on the last 2.

Yeah I know about the header banner_wit issue when full page background. That is an easy fix for me.

**Comment by gjb2048** [comment]
Hi Gemma,

With the last two they have different background sizes, so one keeps the aspect ratio but means the image can be cropped, the other is used completely but the aspect ratio can be wrong.  Which would you like or a setting for a bit more time?  Plus additionally would you like an opacity setting for the login box!

G

**Comment by gemguardian** [comment]
Make it a setting + yes the opacity setting please :)

**Comment by gjb2048** [comment]
Hi Gemma,

Ok will do.  Is there a deadline?

Are you happy if I backport to M2.9 in my own time after the work is done for M3.1 and M3.0?  Then I can keep things in sync.

G

**Comment by gjb2048** [comment]
P.s. Thank you :)

**Comment by gemguardian** [comment]
Have a deadline but not one for you to stick on :) but if you can sort it in the next two weeks that would be nice. I will just tell that a change is coming to that part, I am sure they are happy if they just know it will be following. 

Yeah please backport to M2.9 :)

**Comment by gjb2048** [comment]
Ok, thanks Gemma, I'll keep you informed of progress.

**Comment by gjb2048** [comment]
Hi Gemma,

Please could you review the work in https://github.com/gjb2048/moodle-theme_essential/tree/master_766 for M3.1 and see if you're happy.  The settings are in the 'Features' setting area.  Would you like to be credited with funding the work in CHANGES.txt?

Please let me know if you'd like a zip of the theme to install with the changes.

Thanks,

Gareth

**Comment by gemguardian** [comment]
Hi Gareth, 

 

Just to be sure can you send me a .zip file of the theme with the changes. 

I have tried it locally (Bitnami) I can see the settings, but the uploaded image doesn’t seem to appear on the page. 


Maybe it’s just me being not very smart on this – but if you send me the proper zip file I will ask the technical staff to install it on a demo site. 

 

And yes please place credits for funding in changes.txt

 


Gem

 

Van: Gareth J Barnard [mailto:notifications@github.com] 
Verzonden: donderdag 29 september 2016 20:13
Aan: gjb2048/moodle-theme_essential <moodle-theme_essential@noreply.github.com>
CC: gemguardian <gemma@ltnc.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [gjb2048/moodle-theme_essential] Login page background image. (#766)

 

Hi Gemma,

Please could you review the work in https://github.com/gjb2048/moodle-theme_essential/tree/master_766 for M3.1 and see if you're happy. The settings are in the 'Features' setting area. Would you like to be credited with funding the work in CHANGES.txt?

Please let me know if you'd like a zip of the theme to install with the changes.

Thanks,

Gareth

**Comment by gjb2048** [comment]
Hi Gemma,

Ok, I tested and was working, but tested with a pagebackground too to see if that was overridden.  When I remove it, then does not appear to work.  Investigating.

G

**Comment by gemguardian** [comment]
Hi Gareth,

 

Ok great. Thought it was just me :) 

 

Van: Gareth J Barnard [mailto:notifications@github.com] 
Verzonden: vrijdag 30 september 2016 10:29
Aan: gjb2048/moodle-theme_essential <moodle-theme_essential@noreply.github.com>
CC: gemguardian <gemma@ltnc.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [gjb2048/moodle-theme_essential] Login page background image. (#766)

 

Hi Gemma,

Ok, I tested and was working, but tested with a pagebackground too to see if that was overridden. When I remove it, then does not appear to work. Investigating.

G

**Comment by gjb2048** [comment]
Is a bug, fixing....

**Comment by gjb2048** [comment]
Hi Gemma,

Fixed in branch, just sent you an eMail with ZIP.

G

**Comment by gemguardian** [comment]
Yes it works as intended thank you very much. 

 

Van: Gareth J Barnard [mailto:notifications@github.com] 
Verzonden: vrijdag 30 september 2016 10:56
Aan: gjb2048/moodle-theme_essential <moodle-theme_essential@noreply.github.com>
CC: gemguardian <gemma@ltnc.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [gjb2048/moodle-theme_essential] Login page background image. (#766)

 

Hi Gemma,

Fixed in branch, just sent you an eMail with ZIP.

G

**Comment by gjb2048** [comment]
Thanks Gemma,

G

**Comment by relecand** [comment]
Hey, this looks great. Thank you, both!
