### ISSUE TITLE
Display right arrow in dropdown-submenu

### ISSUE THREAD

**Issue by nbutet** [gjb2048/moodle-theme_essential#768]
Hello,

I would add a right arrow when a dropdown-submenu exists. In the 3.0 version, it worked but in the 3.1 version I checked the source code but It doesn't display anything, do you have a solution or an idea please ?

Thank you for your answer,

Regards.

**Comment by gjb2048** [comment]
So, you're saying that there is a bug where there is no right arrow on the sub-menu in the M3.1 version when there is in M3.0?

**Comment by gjb2048** [comment]
Reading this as a bug.

**Comment by nbutet** [comment]
Yes, and I found where to modify the source code to make appear the right arrow un a submenu in 3.1 version.
here it is 
.dir-ltr .dropdown-submenu > a::after {
    border-width: 5px;
}
Thank you for your answers.
