### ISSUE TITLE
Create 'top-block' region with optionality setting.

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#770]
I found that it is less scary for teachers to see a smaller empty "Page top" block region when they switch to edit mode on main course view and inside modules (just after finish adding a new module)

I have changed min-height to 20px
```
.editing.empty-region-footer-left #block-region-footer-left, .editing.empty-region-footer-middle #block-region-footer-middle, .editing.empty-region-footer-right #block-region-footer-right, .editing.empty-region-hidden-dock #block-region-hidden-dock, .editing.empty-region-home #block-region-home, .editing.empty-region-page-top #block-region-page-top, .editing.empty-region-side-post #block-region-side-post, .editing.empty-region-side-pre #block-region-side-pre, .editing.used-region-footer-left #block-region-footer-left, .editing.used-region-footer-middle #block-region-footer-middle, .editing.used-region-footer-right #block-region-footer-right, .editing.used-region-hidden-dock #block-region-hidden-dock, .editing.used-region-home #block-region-home, .editing.used-region-page-top #block-region-page-top, .editing.used-region-side-post #block-region-side-post, .editing.used-region-side-pre #block-region-side-pre {
    min-height: 20px;
```
How about it?

**Comment by gjb2048** [comment]
Working on a different idea Nadav, thanks anyway.

**Comment by nadavkav** [comment]
Cool

Just letting you know that everyone that sees those new/extra blocks areas is very excited! and most commonly ask for another wider block area  (above all content and other blocks regions) so they can drag special blocks that can display images (image galleries), various navigation blocks and other unique course information blocks. so you know :smile:

**Comment by gjb2048** [comment]
Working on fixing: https://github.com/gjb2048/moodle-theme_essential/issues/751.

I get mixed reactions about page top block region.

If you'd like another 'top-block' region then only two hours work.

**Comment by nadavkav** [comment]
I would love to fund this new/extra "header" block region. And just to make it more clear, to what I am aiming for, here is a mockup:
![image](https://cloud.githubusercontent.com/assets/231168/19190114/4ee636f8-8ca4-11e6-9b26-1e76e33884c5.png)

btw, If users do not like those new/extra regions... maybe you can enable/disable them with a settings?
(As far as I am concerned... there's no going back :wink: )

**Comment by gjb2048** [comment]
Ok, call it 'top-block'.  All pages?  A setting would make it 2.5 hours because of the testing.  Would you like me to send you my terms of business please Nadav?

Also other settings for such have been asked for: https://github.com/gjb2048/moodle-theme_essential/issues/734

**Comment by gjb2048** [comment]
Or would you prefer 'header-block'?  But, possibly that might be confusing with the header itself.  Ok, it is technically possible to put it in the header, but that may cause grief.

**Comment by gjb2048** [comment]
And happy if backported to M3.0 / M2.9?

**Comment by nadavkav** [comment]
Yes. to all your above comments.
Except... do not put it in the real HEADER just above id="page-content".
Or maybe you think it is better above id="page-top-header" ? (Hard for me to decide)

**Comment by nadavkav** [comment]
Do you think we should move these last comments into a new issue?

**Comment by gjb2048** [comment]
I think the region should be just below 'page-top-header' then would be underneath the breadcrumb.

I'm going to change the nature of the issue to be the enhancement it has turned out to be.

**Comment by nadavkav** [comment]
Great. Thanks.

**Comment by gjb2048** [comment]
Hi Nadav,

I think its there bar the back-porting and integration into master.....

![2016-10-11 20_11_26-start](https://cloud.githubusercontent.com/assets/1058419/19285273/4e2da2be-8ff1-11e6-83f8-bd7d7422cf48.jpg)
![2016-10-11 20_19_20-new notification](https://cloud.githubusercontent.com/assets/1058419/19285266/4e119786-8ff1-11e6-9ebe-b29e17ba7723.jpg)
![2016-10-07 18_06_08-start](https://cloud.githubusercontent.com/assets/1058419/19285267/4e13d30c-8ff1-11e6-938f-3e434c5d76f7.jpg)
![2016-10-11 20_10_23-start](https://cloud.githubusercontent.com/assets/1058419/19285268/4e167ae4-8ff1-11e6-8dbd-ad1b07809bb1.jpg)
![2016-10-11 20_16_16-start](https://cloud.githubusercontent.com/assets/1058419/19285269/4e1683f4-8ff1-11e6-9b22-a628d67fab78.jpg)
![2016-10-11 20_13_12-start](https://cloud.githubusercontent.com/assets/1058419/19285270/4e1746ae-8ff1-11e6-9005-c8ce672082c9.jpg)
![2016-10-11 20_10_58-start](https://cloud.githubusercontent.com/assets/1058419/19285271/4e25fc12-8ff1-11e6-9254-0c0741f46b71.jpg)
![2016-10-11 20_16_38-start](https://cloud.githubusercontent.com/assets/1058419/19285272/4e2c1336-8ff1-11e6-9b9e-ed55beb6d90a.jpg)
![2016-10-11 20_14_36-start](https://cloud.githubusercontent.com/assets/1058419/19285274/4e2ee688-8ff1-11e6-8e17-6366fe582f9f.jpg)
![2016-10-04 17_15_20-start_sm](https://cloud.githubusercontent.com/assets/1058419/19285275/4e30fca2-8ff1-11e6-89cc-9045a4a9441d.jpg)
![2016-10-11 20_15_37-start](https://cloud.githubusercontent.com/assets/1058419/19285276/4e3428a0-8ff1-11e6-8e96-4eef40719bdd.jpg)

Please test the branch when you like: https://github.com/gjb2048/moodle-theme_essential/compare/master_%23770.

Kind regards,

Gareth

**Comment by nadavkav** [comment]
Looks great! Testing...
(As our "Yom Kippur - no talking to anyone and only doing meditation" holiday has officially over :smile: )

**Comment by gjb2048** [comment]
Thanks Nadav,

Please let me know how it goes :).

& :).

Cheers,

Gareth

**Comment by nadavkav** [comment]
Again, looks great.
Found two tiny issues:
![image](https://cloud.githubusercontent.com/assets/231168/19320084/89d12cd8-90b8-11e6-8dd8-ad9602bdc18f.png)

**Comment by gjb2048** [comment]
Hi Nadav,

The no dashed borders are intentional after complaints.  They appear as soon as you start to drag and drop or they have blocks in them.

With the labels, this is a separate issue to address on its own.

Cheers,

Gareth

**Comment by nadavkav** [comment]
I see. Indeed, originally, they are very high/large and confusing especially if they are empty. but I already shorten them (locally) to 20px and everyone seems happy now.
Anyway, I think I will add them locally. as our teachers need to see them to get inspired by the option to move blocks around. (maybe... in 10 years I will hide them again ;-)

BTW, so why not hide the "right" and "left" block regions too? (until drag starts)

The label issue is minor, as it get "fixed" after switching off the edit mode.

So as far as I am concerned, we are done :smile: !
Super cool and thank you for this feature.
Nadav

**Comment by gjb2048** [comment]
Hi Nadav,

Thank you.  Just need to merge and back-port to complete the job.

RE: BTW, so why not hide the "right" and "left" block regions too? (until drag starts) - good idea, so note to self: yui3-dd-drop-active-valid for another issue.

I'll document the other issues tomorrow.

Cheers,

Gareth
