### ISSUE TITLE
"Skip to main content" link is hidden by main fixed navbar

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#771]
Double clicking the TAB key, immediately after page loads, activate the "skip to main content" link, but it is hidden under the top/main navbar.

**Comment by nadavkav** [comment]
Maybe...
```
.skiplinks a.skip:focus {
    position: relative;
    top: 40px;
}
```
Which seems to fix it, is a good solution?

**Comment by gjb2048** [comment]
No.  Because the position of the navbar can change relative to the values of more than one setting.

**Comment by nadavkav** [comment]
I had a feeling I am not seeing the big picture with this one.
(btw, I am using the navbar setting that stick it at the top)
