### ISSUE TITLE
Scroll in the drop down menus

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_essential#773]
Ref: https://moodle.org/mod/forum/discuss.php?d=339018.

Need a solution whereby the arrow shows:

![untitled](https://cloud.githubusercontent.com/assets/1058419/19280160/7ce6d400-8fdc-11e6-9062-daf6b86d2f9d.png)

But still can scroll with a large list of items.  Currently thinking that wrap a 'div' and have that as 'dropdown-menu' then 'overflow-x: auto' etc. on the 'ul' and to achieve, remove selected '>' on the specific parts of the CSS selector.

**Comment by ghrich** [comment]
Big thumbs up for sorting this @gjb2048! (#741) I'm so glad the menu scrollbars are back! Was causing so much grief not having them!

Thanks again!

Richard

**Comment by gjb2048** [comment]
Hi Richard,

No worries.  As with all things though its never completely straightforward, so the fix in #777 will be released soon.

G
