### ISSUE TITLE
Add a button to the front page to add alert settings 

### ISSUE THREAD

**Issue by rhysfroggatt** [gjb2048/moodle-theme_essential#778]
Please could it be costed to add a button to the front page (when in edit mode) to turn on and set the front page alerts from a single button on the front page (similar to that of the slideshow) without having to rummage deep within the System Admin menu.

Thanks

Rhys

**Comment by gjb2048** [comment]
Hi Rhys,

I'll do that as soon as I can.

Kind regards,

Gareth

**Comment by rhysfroggatt** [comment]
That would be excellent.


Thanks


Rhys

________________________________

**Comment by gjb2048** [comment]
Hi Rhys,

With testing this will take twenty minutes of my time.  For that I'll add a button with the word 'Edit alerts' and refactor the code to support such a change.

Unless you want to edit the alerts on the frontpage itself and not go to the actual settings page?

Kind regards,

Gareth
