### ISSUE TITLE
Certain grades not appearing in gradebook

### ISSUE THREAD

**Issue by mpenguin** [gjb2048/moodle-theme_essential#780]
Currently using the most recent Moodle 3.1 and the most recent Essential theme (default colors; no changes).

I've found that some items in the gradebook don't appear; their CSS appears to make them transparent. It is only when highlighting with the mouse that I can see them (the default orange highlighting by the Essential theme does not reveal them). I've included two screenshots - one without mouse highlighting and one with mouse highlighting to show you that every other max grade is not visible in the gradebook setup.

![no highlighting](https://cloud.githubusercontent.com/assets/6459925/19502569/696d8f2c-95e0-11e6-8fc1-519971e0592b.PNG)

![highlighting](https://cloud.githubusercontent.com/assets/6459925/19502568/696d094e-95e0-11e6-9e97-da065eef83cf.PNG)

Since I'm running the Essential theme with the default colors, this appears to be a bug in the theme. Anything that I can change in order to make these max grades appear again?

**Comment by gjb2048** [comment]
Ok, what 'specific' version of the theme please?  I need to make sure just in case it's something silly.

**Comment by mpenguin** [comment]
Moodle 3.1.2 (Build: 20160912)
Essential 3.1.1.2 (Build: 2016061711)

**Comment by gjb2048** [comment]
Took longer to find as 'Grade: Setup: Gradebook setup'.

**Comment by gjb2048** [comment]
Down to '.leveleven' class.  Almost certainly need to fix 2.9 -> 3.1.

**Comment by gjb2048** [comment]
No easy solution to this.  Need to think.

**Comment by lazydaisy** [comment]
I think this is the same problem.
https://moodle.org/mod/forum/discuss.php?d=341865
Looks to be load of HOVER specific CSS being generated in Essential for the gradebook.

**Comment by gjb2048** [comment]
It is.

**Comment by gjb2048** [comment]
But rather that the gradebook is styling things at a very specific level.  This is why Moodle needs a design, a set of re-usable styles that are used everywhere for the same sort of thing.  Then any theme could change them once and be happy that they were changed everywhere.  Thus, tables styled by one set of selectors, rather than the mess we have now with every single grain of sand being styled.

**Comment by gjb2048** [comment]
Oh no, levels!  This contradicts the striping.  Muppets!

**Comment by lazydaisy** [comment]
Indeed!

**Comment by gjb2048** [comment]
Grrr, still an issue.

**Comment by gjb2048** [comment]
M3.1 only issue still.

**Comment by mpenguin** [comment]
I purged all caches; Running in the latest Moodle 3.1.3 and latest Essential 3.1.13 (see pics below).

It appears that the "hidden" numbers are now white, which makes them barely stand out, but still not easily visible. Any other information I could provide to help?

![2016-11-16 20_12_00-twu dafl moodle_ administration_ notifications](https://cloud.githubusercontent.com/assets/6459925/20346922/a896d112-ac39-11e6-8d60-0fabdff6b85c.jpg)
![2016-11-16 20_12_48-twu dafl moodle_ administration_ plugins_ plugins overview](https://cloud.githubusercontent.com/assets/6459925/20346919/a88e15ae-ac39-11e6-9922-5a12d5993e2f.jpg)
![2016-11-16 20_10_31-grades_ setup](https://cloud.githubusercontent.com/assets/6459925/20346921/a8924aca-ac39-11e6-93b7-dbcbe193411a.jpg)
![2016-11-16 20_10_56-grades_ setup](https://cloud.githubusercontent.com/assets/6459925/20346920/a88f7e12-ac39-11e6-8a55-d9f346060e41.jpg)

**Comment by gjb2048** [comment]
Thanks @mpenguin - so complicated!  All to do with specific styling in the grade CSS that I have to undo / redo because of the Essential hover / table styling and attempts by me to be generic.

**Comment by gjb2048** [comment]
I do have a plan!

**Comment by gjb2048** [comment]
Still can't work out why the changes I made by adding 'grade.less' for the settings: https://github.com/gjb2048/moodle-theme_essential/commit/14ac6d8cfa8c3a9c89940237984956cdd42c1977 worked and now don't work.

**Comment by gjb2048** [comment]
Ok, two things going on here, fixed 'Grade: View: User report' but not '
Grade: Setup: Gradebook setup'.

**Comment by gjb2048** [comment]
@mpenguin - Please could you test: https://github.com/gjb2048/moodle-theme_essential/commit/cc92b6b4db833e58a39c2bd8f826893b3788b627.

**Comment by mpenguin** [comment]
@gjb2048 Yes, that is working! Looks great!
Thanks for your hard work in fixing this issue!

**Comment by gjb2048** [comment]
Thank you @mpenguin - I'm going to release 3.1.1.4 shortly.

**Comment by gjb2048** [comment]
Fixed.
