### ISSUE TITLE
Hide Global search for unauthenticated users

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#781]
Enabling Global search display "Search" icon for unauthenticated on the frontpage (maybe other pages too) 
![image](https://cloud.githubusercontent.com/assets/231168/19553992/389ecc50-96bf-11e6-8aa3-c151e0ba0467.png)
Should probably be restricted to loggedin users. although no real search can be initiated by the unauthenticated user.

Maybe:

```
if (!isloggedin() || empty($CFG->enableglobalsearch) || !has_capability('moodle/search:query', \context_system::instance())) {
            return '';
        }
```

**Comment by gjb2048** [comment]
Essential bar the icon is identical to core:

https://github.com/gjb2048/moodle-theme_essential/blob/master/classes/output/core_renderer.php#L100-L137

and

https://github.com/moodle/moodle/blob/MOODLE_31_STABLE/lib/outputrenderers.php#L3221-L3258

Therefore will change when core does.

**Comment by nadavkav** [comment]
I open a tracker issue about it. and also was digging more into this and found it to be (maybe) some sort of privacy issue. (waiting for Moodle HQ response on this)
https://tracker.moodle.org/browse/MDL-56526

**Comment by gjb2048** [comment]
Hi Nadav,

Cannot find https://tracker.moodle.org/browse/MDL-56526!

Still an issue?

G

**Comment by nadavkav** [comment]
You'll need a security clearance to see it, but anyways... we fixed it on 13/Mar/17 and it was applied to Moodle 3.2.1+ versions.

**Comment by nadavkav** [comment]
Closing
