### ISSUE TITLE
Tags page looks messy

### ISSUE THREAD

**Issue by emanuelis** [gjb2048/moodle-theme_essential#786]
Hello,
on the page domain.tld/moodle/tag/index.php?tc=1&tag=something&from=2

The names and avatars looks messy:
![taguserdisplay](https://cloud.githubusercontent.com/assets/329596/19679902/5b06d666-9aac-11e6-91a4-d645cd14aa92.jpg)

Is there a way to make the look more consistent? So, that short names doesn't go to the same line as avatars.

**Comment by gjb2048** [comment]
What version of Moodle and Essential please?
How can I replicate this (full instructions) please?

**Comment by emanuelis** [comment]
"Moodle" 3.1.2+ (Build: 20161020)
Essential theme 3.1.1.2 (Build: 2016061711)

Replication:
- Create some users with different name lengths
- Add the same interest to some users
- Go to that interest/tag page

**Comment by gjb2048** [comment]
Ok, I'll look at this when I can, probably in a few weeks time.

**Comment by gjb2048** [comment]
Cannot replicate:

![2016-11-08 17_34_55-start](https://cloud.githubusercontent.com/assets/1058419/20109895/f99cf2a0-a5d9-11e6-976a-0d173ac6b2dc.jpg)
