### ISSUE TITLE
Disabling Sticky Navbar

### ISSUE THREAD

**Issue by ajlee** [gjb2048/moodle-theme_essential#787]
I have been digging around in the theme files but I have so far been unable to disable the sticky navbar, is there a way to get rid of this functionality? I am using 3.1.1.2

**Comment by gjb2048** [comment]
Hi Alex,

Possibly if you pay for my time to find out for you.

Kind regards,

Gareth

**Comment by ajlee** [comment]
I think I was overcomplicating it! The lines below fixed it

#essentialnavbar {  position:absolute !important; }
#essentialnavbar .navbar {
    position: static !important;
}

**Comment by gjb2048** [comment]
That may or not work everywhere.
