### ISSUE TITLE
Have a setting for default block positions in courses in regions specific to Essential

### ISSUE THREAD

**Issue by Leminkainen** [gjb2048/moodle-theme_essential#791]
First, I would like to say hello and a thank you for the great theme!

I am new to Moodle and I have found Moodle block positioning to be a very complex subject.

What I am struggling with right now is to have a specific block placed in the Top region of every main course page. The default moodle left & right sidebar positions can be achieved thru modifying the config.php, but how to place a block in a custom theme position to be available for all future courses escapes me.

Any help will be greatly appreciated. Even if this functionality does not exist atm or is not planned, please just give me a hint or a short snippet as to what theme php file must be edited and what is the php code for inserting a block in the specified region (Top or Head).

Thank you very much!

**Comment by gjb2048** [comment]
Hi,

Welcome to Moodle.

Please read: https://docs.moodle.org/31/en/Blocks and referenced by.  If that does not help then I can, however I would need to be remunerated for my time.

Good luck,

Gareth

**Comment by Leminkainen** [comment]
Thanks Gareth,

I have found the solution somewhere, whereby you add a block to the front page for it to be seen only on the course page. Moodle elegance at its best. Sigh.
