### ISSUE TITLE
Role permissions for editing front page regions

### ISSUE THREAD

**Issue by Leminkainen** [gjb2048/moodle-theme_essential#793]
As a superadmin, I can see buttons for editing Essential regions (Alerts, Header, etc) on the frontpage, but users with the Manager role cannot see them. Which permission should be changed to grant managers this capability?

**Comment by gjb2048** [comment]
Hi Leminkainen,

The Essential theme comes with NO support (https://github.com/gjb2048/moodle-theme_essential/blob/master/README.txt#L62-L66).  I'd be happy to answer the question for a fee.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Hi Leminkainen,

Is this still an issue?

Kind regards,

Gareth

**Comment by gjb2048** [comment]
No response after nearly a year, closing.
