### ISSUE TITLE
Hidden grade items in user report not clear as such.

### ISSUE THREAD

**Issue by bjodau** [gjb2048/moodle-theme_essential#794]
I'm using Moodle 3.1.2 (Build: 20160912) and Essential 3.1.1.4 (Build: 2016061713).

In user report the hidden grade items are not shaded/dimmed as the even rows in the list are overridden with another color. This is causing some confusion for our teachers.

![course_view](https://cloud.githubusercontent.com/assets/7644276/20920460/55ead186-bba0-11e6-88c0-c752ec5bbca5.png)
The course view

![user_report](https://cloud.githubusercontent.com/assets/7644276/20920473/5e66ad8a-bba0-11e6-83be-4d628d2c2a90.png)
User report view where not all hidden items are dimmed/shaded

**Comment by gjb2048** [comment]
This area is a nightmare to style, so they are italic instead.

**Comment by gjb2048** [comment]
Additional.  If I work out a different colour from the settings then that sometimes works, however then can lead to potential ARIA contrast issues.  Or I could have a dimmed colour setting times five for the alternative colour schemes.  But that is quite a bit of work.  Would you find it please?

**Comment by gjb2048** [comment]
And I'd have to work out the effect of the dimmed colour in relation to the striped colour in other tables that is not applied to the grade book because its a nightmare to style and was better to keep lack of striping in its case.  Hence the complexity of the problem.  So to work all of this out would probably take 3.5 to 7 hours to get it correct and tested.

**Comment by bjodau** [comment]
Thank you for your fast respons, much appreciated!

I reliease I'm probably not the first with this thought/question, but I didn't find any information about it. I wanted to know whether this is something to stay or if you plan on future versions to have the hidden grade items dimmed/shaded as the odd rows so it's coherent?

**Comment by gjb2048** [comment]
As I said above I'm going with the 'italic' solution.

**Comment by bjodau** [comment]
Ok, thank you for your time!

//B

**Comment by gjb2048** [comment]
As per #805 will go with 'strike-through' too.

**Comment by gjb2048** [comment]
Changed to 'Bug' for strike-through.  If shading required then will be an enhancement - raise separate issue please.

**Comment by ActionJONA** [comment]
I know this is closed but just thought I'd throw in our solution to this problem...

We simply use the closed eye font-awesome icon (and dim and italicise):
![screen shot 2017-02-15 at 10 38 28](https://cloud.githubusercontent.com/assets/10047439/22970719/0b28008a-f36b-11e6-9ffe-6d4f4c36a0d4.png)
We use this for hidden courses (in my courses dropdown), items, everything. It keeps things consistent and easily identifiable.

**Comment by gjb2048** [comment]
Hi Jona,

Interesting solution.  But.... it looks annoying to me with the icons out of alignment.  If they were at the end then possibly, but then it would be confused with the editing option.  Perhaps better to have a totally different icon.

Kind regards,

Gareth
