### ISSUE TITLE
File Upload and Rename Plugin

### ISSUE THREAD

**Issue by moe255** [gjb2048/moodle-theme_essential#800]
Hi, im not really sure how to achieve this, but if someone can give me a hand I would really appreciate it, I'm kind of new to Moodle development. What I'm trying to do is to "clone" the file upload plugin and make a new one that does exactly the same but also rename the file. The purpose for this is that teachers need to upload the course roadmap, but some of them just doesn't do it; so the person that manages all the courses needs to be able to check in the DB what teacher upload it and what teacher didn't. The idea is to have a dedicated button called "course roadmap" for example, and have the teacher upload it through this button, and since not all teachers name the file the same, i would like to rename the file to, for example, "roadmap_design", "roadmap_law", "roadmap_architecture", and so on, being the word "roadmap_" placed at the begining of every file.

Hope this is possible and that someone can help me. Thanks!

**Comment by gjb2048** [comment]
This has absolutely nothing to do with the Essential theme!
