### ISSUE TITLE
Add Custom JS

### ISSUE THREAD

**Issue by avatautadeo** [gjb2048/moodle-theme_essential#801]
Hi, i'm trying to add some custom JS to load specific CSS on different courses, specially to add different color backgrounds to the header depending on what course i'm in (for example "/index.php?categoryid=2" i would like to add a custom header background color, and for the different "?categoryid=" i would like to have different header background colors). I found where to add custom CSS but I can't figure out where to add custom Javascript/Jquery in order for me to add specific id names to the different header depending on the URL. Any help will be appreciated.

Thanks

**Comment by gjb2048** [comment]
Hi,

Where are you located?

G

**Comment by avatautadeo** [comment]
Hi, thanks for your quick reply! You mean where in the world? I'm located in Bogotá, Colombia.

**Comment by gjb2048** [comment]
Hi,

I'm sorry I can't help you, please try the themes forum: https://moodle.org/mod/forum/view.php?id=46.

Kind regards,

G

**Comment by avatautadeo** [comment]
Ok, no problem. I'll ask in the forum. Thanks
