### ISSUE TITLE
Edit Profile - New Picture alignment

### ISSUE THREAD

**Issue by martinvivek** [gjb2048/moodle-theme_essential#806]
In Edit profile Upload user picture file upload area alignment is not correct. attached the screenshot.
Using Recent version as on date of moodle 3.1 and Essential Theme 

![image](https://cloud.githubusercontent.com/assets/7712010/22640177/7f1fe76e-ec77-11e6-88b9-70db033ceb9b.png)

**Comment by gjb2048** [comment]
Cannot replicate on 3.1.1.8 regardless of 'pagebackgroundstyle' setting.  As the picture description box is centred, which is odd, then I suspect you have some custom CSS or changes affecting the form = not my problem.  If you have evidence to the contrary then please provide it and I'll look at it again.

**Comment by martinvivek** [comment]
If the page width is less that 1200px it is looks fine. if it is more than that it is causing misalignment.
and no custom css or changes done in the theme

Moodle 3.1.4+ (Build: 20170202)
Essential version  3.1.1.8 (Build: 2016061717)

**Comment by gjb2048** [comment]
Ok, still cannot replicate at any resolution between 50 px and 1880px on Chrome.
