### ISSUE TITLE
Social Icon fa-globe hover color incorrect

### ISSUE THREAD

**Issue by dschwa** [gjb2048/moodle-theme_essential#811]
I'm using the latest Essential 3.2.0.1 (Build: 2017021000) and Moodle Moodle 3.2.1+ (Build: 20170216)

The website social icon is showing white on hover. All other social icons work correctly. I suspect this is due to the themecolor being set to white "#ffffff".

I've tried to figure out the custom css for it with no luck. 
Normal:
![social](https://cloud.githubusercontent.com/assets/7027431/23724032/5183e31e-0419-11e7-80f2-a77c9ffd7625.jpg)
Hover;
![social_hover](https://cloud.githubusercontent.com/assets/7027431/23724146/b1eb2514-0419-11e7-8d0d-97215cdddc94.jpg)

**Comment by gjb2048** [comment]
````
button.website:hover, button.website:focus {
    background-color: #fff;
}
````

**Comment by gjb2048** [comment]
Not incorrect as takes the website colour, so appropriate.

**Comment by dschwa** [comment]
Thank you
