### ISSUE TITLE
navbar alignment

### ISSUE THREAD

**Issue by martinvivek** [gjb2048/moodle-theme_essential#816]
Using moodle 3.2.2+
essential : 2017021002 (3.2.1.1)
Windows 2008/IIS and PHP 7.0
everything working normally in desktop or laptop.
when viewed from mobile (with social icons) initally no issues, when you click the  collapse button which is highlighted in red. the navbar comes down and again its not goining back. 

custom css we used  #page-header {background:none;}

![image](https://cloud.githubusercontent.com/assets/7712010/24445674/57c369f0-1488-11e7-9726-af3ec0c29a1e.png)

![image](https://cloud.githubusercontent.com/assets/7712010/24445709/84c3f1b8-1488-11e7-94fd-3c596d985779.png)

**Comment by gjb2048** [comment]
Cannot replicate.
