### ISSUE TITLE
Fix Apple touch icon

### ISSUE THREAD

**Issue by davmann** [gjb2048/moodle-theme_essential#818]
```
-------------------------- layout/tiles/iosicons.php --------------------------
index d57cfd2..2e14380 100755
@@ -51,4 +51,4 @@ if (\theme_essential\toolbox::get_setting('ipadretinaicon')) {
-<link rel="apple-touch-icon-precomposed" sizes="57x57" href="<?php echo $iphoneicon ?>"/>
-<link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo $ipadicon ?>"/>
-<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo $iphoneretinaicon ?>"/>
-<link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo $ipadretinaicon ?>"/>
\ No newline at end of file
+<link rel="apple-touch-icon" sizes="57x57" href="<?php echo $iphoneicon ?>"/>
+<link rel="apple-touch-icon" sizes="72x72" href="<?php echo $ipadicon ?>"/>
+<link rel="apple-touch-icon" sizes="114x114" href="<?php echo $iphoneretinaicon ?>"/>
+<link rel="apple-touch-icon" sizes="144x144" href="<?php echo $ipadretinaicon ?>"/>
```

**Comment by gjb2048** [comment]
Evidence please Davide of API change of 'apple-touch-icon-precomposed' to 'apple-touch-icon'.

**Comment by davmann** [comment]
Hi Gareth. It seems a W3C suggestion. And anyway, Apple used that declaration on iOS2 (but now no one is using so old system)
https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.onlinelifeschool.com%2F#l114c262

**Comment by gjb2048** [comment]
Ok, but where is the evidence that the replacement is correct please?

**Comment by davmann** [comment]
If you click on the link I gave you, you will see the W3C suggestion

**Comment by gjb2048** [comment]
But the site says "This tool is an ongoing experiment in better HTML checking, and its behavior remains subject to change" therefore could be a 'bug' and not a definitive definition of correctness for the value.

**Comment by davmann** [comment]
Yes, you're right, Gareth. 
I trust in W3C so I searched for more info. I found something interesting in Apple.
https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html
In that page is mentioned only:
`<link rel="apple-touch-icon" ...>`
and not:
apple-touch-icon-precomposed

**Comment by gjb2048** [comment]
Notes:

https://mathiasbynens.be/notes/touch-icons
https://github.com/h5bp/html5-boilerplate/issues/1615
https://github.com/h5bp/html5-boilerplate/pull/1622
https://developer.apple.com/support/app-store/
https://realfavicongenerator.net/blog/apple-touch-icon-the-good-the-bad-the-ugly/
