### ISSUE TITLE
Wrong URL format for Google Analytics

### ISSUE THREAD

**Issue by davmann** [gjb2048/moodle-theme_essential#820]
```
------------------------- layout/tiles/guniversal.php -------------------------
index 051cfad..6691338 100644
@@ -93 +93 @@ function insert_analytics_tracking() {
-            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
+            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
```
https://developers.google.com/analytics/devguides/collection/analyticsjs/

**Comment by davmann** [comment]
Hi Gareth,
if you have 2 minutes, could you please explain me why this is not a bug?
If you look at the source code (after the page is fully loaded) you will see the missing "https:" from the URL.
Thanks

**Comment by gjb2048** [comment]
Hi Davide,

Its not a two minute explanation.  Its just not a bug that needs fixing because its is not broken.

Kind regards,

Gareth

**Comment by davmann** [comment]
Hi Gareth,
maybe you're right and I'm missing something.
What I find unusual is in line 57:
`})(window,document,'script','//www.google-analytics.com/analytics.js','ga');`
website: https://www.onlinelifeschool.com/

**Comment by gjb2048** [comment]
Yes I know, and it would take more than two minutes to explain and it is not actually broken.

**Comment by davmann** [comment]
Perfect
I trust
:-)
