### ISSUE TITLE
Blank page is shown in Internet Explorer 11 with News items on Front Page

### ISSUE THREAD

**Issue by jgilevich** [gjb2048/moodle-theme_essential#822]
A blank page is shown in Internet Explorer 11 (Win 7) with Moodle 3.1.5+ and Essential 3.1.1.9 when posting new topic at News items at Moodle Front page.
Can not recreate the problem with other browsers (IE11 - Win10, Edge, FF, Chrome).
There is no problem when using other theme.

**Comment by gjb2048** [comment]
Screen shot evidence please.

IE12?  I cannot find evidence that it exists.

**Comment by jgilevich** [comment]
My mistake, IE11 on Win10.
![ff](https://cloud.githubusercontent.com/assets/24698574/25230110/7d3a5568-25db-11e7-99e1-d490208d9adc.PNG)
![ie11-win7](https://cloud.githubusercontent.com/assets/24698574/25230125/8c9f88c0-25db-11e7-835e-70cbf0968acc.PNG)

**Comment by gjb2048** [comment]
Ok, given the graphics that does not look like IE11 on Win 10 but rather a really old IE on something like Win 98.

**Comment by gjb2048** [comment]
Can you show the version via 'About Internet Explorer' from the tools menu please.

**Comment by jgilevich** [comment]
![ie11-ver](https://cloud.githubusercontent.com/assets/24698574/25230593/33a74634-25dd-11e7-8b66-a0b617e9d452.PNG)

**Comment by gjb2048** [comment]
Cannot replicate:

![e822](https://cloud.githubusercontent.com/assets/1058419/25231434/c3a4c076-25cf-11e7-9330-47dbea5eacb1.png)

**Comment by jgilevich** [comment]
Please try the same test on IE11 with Windows 7, Not 10.
It works in Windows 10, but not on Windows 7.

**Comment by gjb2048** [comment]
I no longer have a Windows 7 machine as upgraded to Win 10.
