### ISSUE TITLE
Social icons

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_essential#823]
Social icon LESS in header.less wrong with :focus - see:

body button {
    &.socialicon {

and not overridden correctly in alternative colours.  Fixed in M3.3 version so need to update M3.2 etc.

**Comment by rosimittermeier** [comment]
i am surprised, but: yes! with Moodle 3.2.2+ (Build: 20170421) and 3.2.1.1 (Build: 2017021002) the problem, too, exists.
