### ISSUE TITLE
Header area/slide show/bullet-menu "on top"

### ISSUE THREAD

**Issue by rosimittermeier** [gjb2048/moodle-theme_essential#824]
hi, I use moodle 3.3 and essential 3.3.0.1. I the header area I have a slide show. now, if i am logged in i see my name on the top in the usermenu which is a dropdown-menu. if i drop it down the menu-bullets of the slide show are on top!

**Comment by gjb2048** [comment]
Could you post a screen shot to explain the issue please?

**Comment by rosimittermeier** [comment]
yes. to clipboard. the first in state not dropped down, the second in state dropped down
![state_dropdown_notdropped](https://cloud.githubusercontent.com/assets/13799805/26173113/f9bffee2-3b4a-11e7-879d-a927af0710ad.png)
![state_dropdown_dropped](https://cloud.githubusercontent.com/assets/13799805/26173122/01eb87a8-3b4b-11e7-8d29-24e4abf16002.png)

**Comment by rosimittermeier** [comment]
"to clipboard." would like to mean: two clipboards ...

**Comment by gjb2048** [comment]
M3.2 issue too?
