### ISSUE TITLE
course-administration area is missing

### ISSUE THREAD

**Issue by rosimittermeier** [gjb2048/moodle-theme_essential#826]
perhaps i am puzzled, but: i cant see the course-administration area any more in the navigation. there is only the website-administration-area. if a change into the clean theme, everything is ok. i recognized the problem because i wanted to change settings of groups of a course.

**Comment by rosimittermeier** [comment]
i found the source in "theme_essential | flatnavigation" (yes, no). maybe the the flat navigation is too flat?!

**Comment by gjb2048** [comment]
What about the cog on the navbar?

**Comment by rosimittermeier** [comment]
yes, the cog opens a menue with some options of the course-administration menu. but i tried to change admission keys to groups of a course. and there is a difference:

[navbar, cog:][flat and unflat navigation]
turn editing on
edit settings 
filters
...

[sidemenu, course administration (just before Site administration) ][no flat navigation]
edit settings
turn editin on
######users#####
-----------enrolled users
-----------enrolment methods
-----------groups ** !!!!!!! **
...
################
filters
...

**Comment by gjb2048** [comment]
How does the Essential Cog menu compare with the Boost cog menu?

**Comment by rosimittermeier** [comment]
oh! its the same with both themes. it is moodle itself.

**Comment by gjb2048** [comment]
So not a theme issue then?

**Comment by rosimittermeier** [comment]
seems so! thanks
