### ISSUE TITLE
Flat navigation does not show if blocks were previously docked

### ISSUE THREAD

**Issue by mkpelletier** [gjb2048/moodle-theme_essential#827]
Moodle 3.3+
Essential 3.3.0.2 (Build: 2017040301)

It appears that the flat navigation is hidden if a user previously had his blocks docked.  This can be remedied by first turning off flat navigation, then undocking the blocks.  The flat navigation can be enabled.  However, I would assume this would have to be done for every user or via an update query.

**Comment by gjb2048** [comment]
Can replicate if a block in the same region as Flat Navigation is docked.  Cannot replicate scenario described yet.

**Comment by gjb2048** [comment]
empty-region-side-pre is added to body class.  Humm.

**Comment by gjb2048** [comment]
Note: Can override body css classes method but there is some JS changing it on load.

**Comment by gjb2048** [comment]
lib/yui/src/dock/js/dock.js resizeBlockSpace is being a pain.
