### ISSUE TITLE
div id# completionprogressid has z-index

### ISSUE THREAD

**Issue by mkpelletier** [gjb2048/moodle-theme_essential#828]
Moodle 3.3+
Essential: 3.3.0.2 build: 2017040301

The "Your Progress" item at the top of course-content has a z-index of 10.  I thought this was unusual as a default behaviour since it rides over the header and menus in places.  Must be a little bug?

**Comment by gjb2048** [comment]
Added here: https://github.com/gjb2048/moodle-theme_essential/commit/90545a67e29701df99d3d615d636f88acd2709b9#diff-367b115aee91a46c69ed747899ff471fR37 - no idea why!

**Comment by gjb2048** [comment]
Thanks for the report Mathieu :)

**Comment by gjb2048** [comment]
Needs backporting?
