### ISSUE TITLE
Problem in installing the theme

### ISSUE THREAD

**Issue by slddrns** [gjb2048/moodle-theme_essential#829]
Hi,
I have installed the latest version of moodle and the latest and the latest version of the essential theme. I also have installed the latest version of moodle-theme_essential-master. I still get the Plugins check page with Essential as plugins requiring attention. How do I proceed?
Thanks.

**Comment by gjb2048** [comment]
You proceed by telling me the exact versions.

**Comment by slddrns** [comment]
I have installed 
- moodle version 3.3.
- theme_essential_moodle33_2017040301 (3.3.0.2 Release date: Monday, June 5, 2017, 7:40 PM)
- moodle-theme_essential-master (downloaded from the site https://docs.moodle.org/29/en/Essential_theme by clicking on 'Download latest development version' link.
![pluginscheck](https://user-images.githubusercontent.com/20815605/26940553-b9bc28ac-4c98-11e7-86bc-6a5eb2c8caa5.png)
Thanks

**Comment by gjb2048** [comment]
It does not require attention, just click on 'Upgrade Moodle database now'.

**Comment by slddrns** [comment]
Ok, thank you. I was sceptical about doing anything to the database. But anyways I clicked on the button and it is working fine now.
Thanks.
