### ISSUE TITLE
Course page hides blocks in Flat Navigation and editing off

### ISSUE THREAD

**Issue by martinvivek** [gjb2048/moodle-theme_essential#830]
The blocks are hidden in the course pages and creates more gaps in pages. is some setting i have to enabled or I am doing anything wrong.

Moodle 3.3+ (build : 20170601)
Essentail 3.3.0.3 (Build: 2017040302) Downloaded from github

In Disabled Flat Navigation state

![image](https://user-images.githubusercontent.com/7712010/26978795-5b37246e-4d4a-11e7-9193-0a71e6aea2d0.png)

In Enabled Flat Navigation state

![image](https://user-images.githubusercontent.com/7712010/26978932-cc68d1b4-4d4a-11e7-8f95-dbf256911ea6.png)

Turned Editing ON

![image](https://user-images.githubusercontent.com/7712010/26978953-e07ae732-4d4a-11e7-87e6-7a84d98a61af.png)

**Comment by gjb2048** [comment]
Umm, this looks like a customised installation as there is no docking.

**Comment by martinvivek** [comment]
theme is not edited, just downloaded and installed, have custom css but it may not an issue i removed custom css (not related to theme) and saved purge caches through web and cli. then tried same issue.

When i open quiz it showing blocks
![image](https://user-images.githubusercontent.com/7712010/26980081-a972cf76-4d4e-11e7-903e-d7b5b78c12e0.png)

**Comment by martinvivek** [comment]
Sorry, what customization id refer to? Like theme editing or anything else.

**Comment by gjb2048** [comment]
Screen shots show no docking and yet should have = thus something going on.

**Comment by gjb2048** [comment]
What other contributed modules do you have installed?

**Comment by gjb2048** [comment]
Cannot replicate, please provide the 'Properties' file with the 'Export properties as a JSON string' button.

**Comment by martinvivek** [comment]
sorry for late reply...
[theme.txt](https://github.com/gjb2048/moodle-theme_essential/files/1132773/theme.txt)

**Comment by martinvivek** [comment]
In plugins ->blocks -> manage blocks-> Navigation block is disabled (core plugin)
Reason : as it showing lots of courses.

**Comment by gjb2048** [comment]
Do you mean 'Administration' and not 'Site Administration'?

**Comment by gjb2048** [comment]
Ok can replicate with 'layout' setting off and no blocks on the course page at all.  Flat navigation is on.

**Comment by gjb2048** [comment]
Body tag has 'used-region-side-pre' but is 'empty' when change to Clean on same course.

**Comment by gjb2048** [comment]
Ok, logic flaw between 'body_css_classes' and 'essential_blocks' in the overridden core_renderer.php.

**Comment by gjb2048** [comment]
M3.3 issue.

**Comment by martinvivek** [comment]
Issue has been resolved in the course page but in the quiz page still the space are there.
With block_navigation and Administration is Disabled

The screenshot with flat navigation enabled.
![image](https://user-images.githubusercontent.com/7712010/28021798-c1951b7a-65a6-11e7-86e6-5f2b82b1323d.png)
With flat navigation disabled
![image](https://user-images.githubusercontent.com/7712010/28021945-40e5fbf6-65a7-11e7-9651-dbe5e7aa2d08.png)

**Comment by gjb2048** [comment]
Ok, technically this is a new issue as this is 'Course page' - is the same true in the Clean theme?

**Comment by gjb2048** [comment]
Ok, cannot now replicate extra space on the right when editing is on (the 'Left' is showing) and 'layout' setting is true.
