### ISSUE TITLE
User tour with backdrop alignment off

### ISSUE THREAD

**Issue by mnods** [gjb2048/moodle-theme_essential#831]
essential 3.2.1.1
moodle 3.2.3 
user tour for /course/view.php%
one tour step points to ID custom_menu_courses
backdrop off - points to correct ID, with it on the tour step gets aligned to centre, highlighting the wrong element. 
![course__about_moodle4mac](https://user-images.githubusercontent.com/1924364/27269820-6f6b86b0-54ec-11e7-98c5-35699914825f.png)

I also have some weirdness happening in a different step, with or without backdrop - text in the step not displaying properly - looks like it needs a line height. 
![course__about_moodle4mac](https://user-images.githubusercontent.com/1924364/27269909-2454e396-54ed-11e7-8c47-7cfd3738974a.png)

neither issue appeared when using clean or boost.

**Comment by gjb2048** [comment]
Thanks for the report.

How do I replicate the problem please?  I've not used user tours before.

**Comment by mnods** [comment]
site admin > appearance > user tours
create a new tour
give it a name
in the Apply to URL match field  use /course/view.php% 
show with backdrop = YES
leave others default
save
head back to main user tours page - admin/tool/usertours/configure.php
click on the item you just created
add a new step
title "user menu"
css selector = .usermenu
title = User Menu
content = This is the user menu which displays on all of your pages. It contains links to your Dashboard, Messages, Profile, and your Preferences.

head to a course main page and the user tour should appear. you can reset to start again via the rest link in the footer.

**Comment by mnods** [comment]
... so you could add new steps to this tour for various other selectors
eg #custom_menu_courses and others
in main tour settings, alter backdrop setting to see difference in placement of the tour step on the course page.

**Comment by gjb2048** [comment]
Thanks, added to list of jobs, probably sometime in July.

**Comment by mnods** [comment]
nice on gareth, thanks.

**Comment by gjb2048** [comment]
Target type = Selector?

**Comment by gjb2048** [comment]
Caused by: 

````
.navbar .navbar-inner {
    line-height: 0;
}
````

**Comment by gjb2048** [comment]
Not in M3.3.

**Comment by gjb2048** [comment]
Testing instructions do not state how to replicate first issue.

**Comment by gjb2048** [comment]
Cannot replicate either issue in M3.1.

**Comment by gjb2048** [comment]
Can replicate first issue in M3.2.

**Comment by gjb2048** [comment]
In M3.3 the first issue is off but not by much.

**Comment by gjb2048** [comment]
Actually ditto for M3.2.

**Comment by gjb2048** [comment]
Ok I think that the first issue is down to user tours being confused about the navbar not being at the top but changing position.  Not sure I can solve that.

**Comment by gjb2048** [comment]
In M3.3 the #custom_menu_courses issue jumps around from when you've done 'Next step' to reloading with it showing.

**Comment by gjb2048** [comment]
Ok I can replicate the first issue with being 'off' in the Clean theme if the '.langmenu' is targeted on the navbar as it's within a '.collapse' -> core issue for that.   So far in M3.2.

**Comment by gjb2048** [comment]
Not actually sure why 'line-height: 0' is there, removing for now in M3.2 and M3.3.

**Comment by gjb2048** [comment]
Ok, up to you to raise MDL tracker issue.
