### ISSUE TITLE
Use Core Notification and Messages menus

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_essential#832]
Ref: https://moodle.org/mod/forum/discuss.php?d=354336

Possibly separate out notifications in M3.2+ with the 'Notification bell' icon on the navbar from the messages menu.

**Comment by mkpelletier** [comment]
Gareth,

Your amazing.  Were you exposed to plutonium or bit by a genetically altered coding spider when you were a kid or something?  How does one get these coding super-powers?  :-)

I have pulled ced968c and it works great.  Thanks again for all the hard work!
