### ISSUE TITLE
Help icons open a new tab

### ISSUE THREAD

**Issue by tonyjbutler** [gjb2048/moodle-theme_essential#833]
Just testing the latest version for 3.3 and clicking Moodle's context help icons opens a new tab rather than a modal dialogue.

**Comment by gjb2048** [comment]
Latest version?

**Comment by tonyjbutler** [comment]
Yes, 2017040302.

**Comment by gjb2048** [comment]
Can replicate, no idea why its not working though.

**Comment by gjb2048** [comment]
Note:  Running M3.2 version on M3.3 gets same issue, so nothing changed in the theme at the moment, so must be some sort of core API change as M3.2 version ok on M3.2.

**Comment by tonyjbutler** [comment]
This is the fella: https://github.com/moodle/moodle/commit/f745b81201735b5bc094a0a4fb17910a0c952660

**Comment by gjb2048** [comment]
Thank you Tony :)

**Comment by gemguardian** [comment]
Gareth, the issue is also in M3.1

**Comment by gjb2048** [comment]
Hi Gemma,

I can't reproduce on M3.1.

G

**Comment by gemguardian** [comment]
Sorry I had an issue with Help, thought it was the same. But it was "Help" in the user menu, if I place emailadress there.

**Comment by gjb2048** [comment]
Hi Gemma,

If I complete the 'helplink' theme setting with an eMail address then it correctly creates a 'mailto' link.  So not sure what the issue is?

G

**Comment by gjb2048** [comment]
M3.3 only.
