### ISSUE TITLE
Outlining in course "Edit" option

### ISSUE THREAD

**Issue by gemguardian** [gjb2048/moodle-theme_essential#834]
Hello Gareth,
At first I thought it was a courseformat issue but I tested it on Clean and it seems to outline okay in there. That's why I made this issue. 

Screenshot 1: Essential
The "edit" option behind the activities do not seem to outline properly
![essential_3 1](https://user-images.githubusercontent.com/16559999/27931518-c31915aa-629a-11e7-8464-8e5158320183.png)

Screenshot 2: Clean
Or it might be also a small hardly noticable jump in but with essential is more clear since the layout is more spread??? 
![clean_001](https://user-images.githubusercontent.com/16559999/27931519-c3195bb4-629a-11e7-808f-ddea8c847f73.png)

Gemma

**Comment by gjb2048** [comment]
Hi Gemma,

What version of Essential and what course format and version please?

G

**Comment by gemguardian** [comment]
Oh I forgot.. sorry.

Essential: 3.1.1.9 (Build: 2016061718) | 2016061718
Onetopic format: buenavista | 2016071402
Moodle 3.1.6 (Build: 20170508)

**Comment by gjb2048** [comment]
.commands .fa {
    margin-left: 3px;
    margin-right: 3px;
}

to

.commands .fa {
    padding: .3em;
}

and remove:

.actions a>.fa, .course-item-actions a>.fa, .menu a.menu-action>.fa {
    width: 15px;
}

**Comment by gjb2048** [comment]
Or at least .actions a>.fa part.

**Comment by gemguardian** [comment]
hi Gareth,

I tried it with custom CSS and ended up with: 

.commands .fa {margin-left:none!important;margin-right:none!important;padding: 1.8px!important;}
 .actions a>.fa part.{display:none!important}

I had some issues with the "Fa-icon" for grouping, it seemed it did not want to outline properly.

Gem

**Comment by gjb2048** [comment]
Hi Gem,

Patched 3.3 last night: https://github.com/gjb2048/moodle-theme_essential/commit/1a45a42bb21c4a30b8ccb08d3e57a4c69dac5aa7 - so I think this may solve this when I back-port and get things up to date.

G

**Comment by gjb2048** [comment]
Hi Gem,

Looks like a M3.1 issue only.  Please raise a new issue if you find a problem in M3.2 or 3.3.

G
