### ISSUE TITLE
Display fake blocks before Flat Navigation

### ISSUE THREAD

**Issue by martinvivek** [gjb2048/moodle-theme_essential#835]
In Quiz setting the show blocks during quiz attempts is set to "NO"

![image](https://user-images.githubusercontent.com/7712010/28022378-9eef417a-65a8-11e7-9efc-757114a408e5.png)

With navigation Enabled -> Quiz navigation goes below the Navigation
![image](https://user-images.githubusercontent.com/7712010/28022470-e9e98258-65a8-11e7-83f0-8c74fc225c34.png)

With Navigation Disabled
![image](https://user-images.githubusercontent.com/7712010/28022550-21a34044-65a9-11e7-8572-6d49daf19a99.png)

**Comment by martinvivek** [comment]
essential Version : 201704030
moodle version : Moodle 3.3+ (Build: 20170601)

**Comment by gjb2048** [comment]
So is this problem that the quiz navigation is below flat navigation?
