### ISSUE TITLE
Secure layout broken

### ISSUE THREAD

**Issue by martinvivek** [gjb2048/moodle-theme_essential#836]
In Manage Blocks i have disabled the Block_navigation and Administration but in Flat Navigation the blocks still showing. if flat navigation disabled its disappears. Is it intentionally kept? Yes means you can close this issue.

**Comment by martinvivek** [comment]
essential Version : 201704030
moodle version : Moodle 3.3+ (Build: 20170601)

**Comment by gjb2048** [comment]
I don't actually understand what you are saying?

**Comment by martinvivek** [comment]
If i disabled the blocks, it should not show in the pages right. I disabled the administration and navigation blocks. and it is not showing if the flat navigation is disabled. the below screenshot not shows the naviagation block.

![image](https://user-images.githubusercontent.com/7712010/28050788-63dcd762-661d-11e7-93ab-7e59ecc774f4.png)

if i enabled the flat navigation, navigation and Site administration menu is displaying in the pages even it is in disabled state

![image](https://user-images.githubusercontent.com/7712010/28050767-43da31e4-661d-11e7-8166-a2b6ed6acab8.png)

The screenshot shows the quiz page but is appearing in course page also.

**Comment by gjb2048** [comment]
On https://user-images.githubusercontent.com/7712010/28050767-43da31e4-661d-11e7-8166-a2b6ed6acab8.png the area with 'Silp assessment' is the 'Flat navigation' - so confused by what you are saying.

**Comment by gjb2048** [comment]
With "If i disabled the blocks, it should not show in the pages right" it should show "Next page" as that is a quiz thing and nothing to do with the navigation block.

**Comment by gjb2048** [comment]
Still confused about this!

**Comment by martinvivek** [comment]
**1. For other pages:**
The Flat Navigation Block should not appear on the pages when the navigation and administration is disabled in manage blocks. (as it wont show when the flat navigation is disabled)

**2. For quiz pages** 
The Flat Navigation Block Should not appear on the quiz page also because i selected do not show blocks in quiz settings. So only quiz navigation should display.

**To reproduce : 1**
Disable the Administration and navigation block in Plugin overview ->>Manage blocks
Disable Flat navigation and see the course pages no blocks will be there
Enable Flat navigation and see the navigation block is appeared with Site Administration Menu

**To reproduce : 2**
Create a quiz. in quiz setting -->appearance ->Show blocks during quiz attempts ->"NO"
Disable Flat navigation and see the quiz pages no blocks will be there except quiz navigation
Enable Flat navigation and see the navigation block is appeared and below that quiz navigation blocks appear

**Comment by gjb2048** [comment]
Ok,

For '1' you are wrong as when the navigation and settings blocks in Boost are disabled then the flat navigation is still shown.  In fact now in Essential this is 'broken' argh!

For '2' do not show blocks option seems to be broken in both Boost and Clean, so please raise with Moodle HQ via the tracker.

Therefore nothing on this for me to fix but rather fix something that was not broken.

**Comment by martinvivek** [comment]
![image](https://user-images.githubusercontent.com/7712010/29738344-2857ea70-8a3e-11e7-9ff3-230fc34162a7.png)

**Fresh Moodle installation with only essential theme Plugin. (no Custom CSS code)**

Created New Course
Added New Quiz
Added two questions - one with image one without Image
Quiz Settings
Attempt 1

Every thing is working fine as per your feedback.

But when i Enable Browser security Problem occurs.

![image](https://user-images.githubusercontent.com/7712010/29738377-ac13a9a8-8a3e-11e7-8b8d-137eeb184225.png)

Switch role to Student and attempt the quiz, you can see the gap on the right side and quiz navigation occurs in left.

In clean theme Everything is perfect
![image](https://user-images.githubusercontent.com/7712010/29738404-40eb7952-8a3f-11e7-9197-fe0d1b7b1f78.png)

Essential :3.3.1.1 (Build: 2017040305)
Moodle : 3.3.1+ (Build: 20170824)

**Comment by gjb2048** [comment]
Note to self, do not back-port solution but see if in M3.2- there is an issue and consider separate solution as all to do with layouts etc. and they have changed.

**Comment by gjb2048** [comment]
Still an issue?

**Comment by gjb2048** [comment]
No reply so assuming not.
