### ISSUE TITLE
Import boost messaging widget

### ISSUE THREAD

**Issue by mkpelletier** [gjb2048/moodle-theme_essential#837]
Hi Gareth,
As always Essential is looking amazing and working great.

With regard to messaging in the latest versions of Moodle, it seems many of the UI improvements are lost to those of us on essential.  Most importantly, the message read indicator gets stuck for some students and I am not really sure why.  I notice in the boost widget, there is an option to "mark all as read".

I realise we will need to get funding for this, but I thought it worth adding this to the list (if it is not already planned).  Wasn't there a funding page setup for the 3.3 branch of essential?  Is anything like this still in place for new items?

**Comment by gjb2048** [comment]
Hi Mathieu,

Boost seems to have added many things upon which I'm not sure if they pertain to Boost or Moodle itself.  Can you see the "mark all as read" in the Clean theme?  If so, please post a screen shot so I know exactly what it is.

Essential also does have an older but more original message icon before Moodle introduced theirs so hence different.

G

**Comment by mkpelletier** [comment]
Hi Gareth,

I hadn't realised that it is actually part of moodle and is not specific to boost.  It appears that the Clean theme also makes use of a floating widget.  It looks pretty much like the one in Boost.  Here is a screenshot:

![course__bhb1121_biblical_hebrew_1a_2016](https://user-images.githubusercontent.com/4638072/28064339-7c4cc5ca-6634-11e7-8329-2a968d4eeb03.jpg)

I see the class .popover-region-container in which the div element appears in Clean and Boost is already in Essential, but it is not being used for the messages menu in Essential.

**Comment by gjb2048** [comment]
With the funding, that is now complete, hence the beta and me now working towards a stable with bug fixes.  So no scope for new features unless separately funded.

**Comment by mkpelletier** [comment]
I figured as much, Gareth.  Perhaps, if there is interest elsewhere, this might make it into the next funded project? Thanks for all the amazing work, as always.

**Comment by gjb2048** [comment]
The next funded project is likely to be Essential for Moodle 3.4 some time in November 2017.

**Comment by mkpelletier** [comment]
Hi Gareth,
I have a bit more clarity on this issue after several of my users reported problems.  As I understand it the issue relates specifically to system notices; less concerning messages.

Apparently, the counter in essential on the messages icon persists for notifications and can never be cleared by going to the message.  For example see the following screenshot:

![alerts in essential](https://user-images.githubusercontent.com/4638072/28106336-d0c3e35e-66e3-11e7-92be-1207895a25ad.jpg)

In clean, system notifications are separate from system messages and there is an option to "Mark all as read" in both:
![clean theme - mark all as read](https://user-images.githubusercontent.com/4638072/28106403-03225bf0-66e4-11e7-8e78-3d91a3ebe679.jpg)
![clear counter in clean](https://user-images.githubusercontent.com/4638072/28106404-0323daa2-66e4-11e7-9b58-5d57c7b664ad.jpg)

The absence of the "mark all as read" option seems to be the source of the problem.

Should I resubmit this as a bug?

**Comment by mkpelletier** [comment]
Sorry Gareth, I forgot to mention:
Moodle 3.3 (Build: 20170710) Version 2017051501
Essential 3.3.0.2 (Build: 2017040301)

**Comment by gjb2048** [comment]
Hi Mathieu,

I'll look into it.

G

**Comment by gjb2048** [comment]
Just realised that is a duplicate in effect of https://github.com/gjb2048/moodle-theme_essential/issues/832.
