### ISSUE TITLE
Lesson Menu overlaps Administration menu in Moodle 3.2

### ISSUE THREAD

**Issue by martinvivek** [gjb2048/moodle-theme_essential#839]
![image](https://user-images.githubusercontent.com/7712010/28211067-5c2af394-68b8-11e7-8993-c206d91ea186.png)

When the lesson is viewed with the lesson menu, the menu overlapping the administration menu.
In clean theme the lesson menu is appeared in left and administration appeared in the right so no way to over lap.

Moodle 3.2.3+ (Build: 20170509) Version 2016120503.02
Essential 3.2 2017021000

**Comment by martinvivek** [comment]
I not updated the essential 3.2 after feb, as we planning to move to 3.3 and searched in issues but not seen any issue regarding overlapping menu. So icreated new issue.

 I will check with moodle 3.3 and essential 3.3 and revert back too.

**Comment by gjb2048** [comment]
RE: "In clean theme the lesson menu is appeared in left and administration appeared in the right so no way to over lap."

With the Clean theme for me both the lesson menu and other blocks are on the left, therefore you have a customised installation or custom CSS.
