### ISSUE TITLE
Would it be possible to change a private to a protected?

### ISSUE THREAD

**Issue by Tazoeur** [gjb2048/moodle-theme_essential#842]
Hi,
First of all, I'd like to thank you for the great work you do on this theme plugin.

I am currently overriding the function custom_menu_user() by extending your \theme_essential\output\core_renderer.

The problem I have is that the private function getfontawesomemarkup() is used in the custom_menu_user() function.

I can bypass the problem by copy/pasting the function getfontawesomemarkup() inside my renderer but If you could change the visibility of this function from private to protected, it will make things easier and IMHO improve the usability of this class.

Regards,
Guillaume

**Comment by Tazoeur** [comment]
Here is a patch :)
[change_visibility_core_renderer.patch.txt](https://github.com/gjb2048/moodle-theme_essential/files/1233655/change_visibility_core_renderer.patch.txt)

**Comment by gjb2048** [comment]
Hi Guillaume,

I see no problem with this.  What version of Essential are you running please?

G

**Comment by Tazoeur** [comment]
Hi G,

I currently use the version 2017040305 (release 3.3.1.1)
