### ISSUE TITLE
Add an activity or resource popup display

### ISSUE THREAD

**Issue by martinvivek** [gjb2048/moodle-theme_essential#843]
![image](https://user-images.githubusercontent.com/7712010/29738225-51af36ba-8a3b-11e7-8710-204b0417b25c.png)

The activity and resource name are all getting wrap.

Fresh Moodle installation with only essential theme Plugin. (no Custom CSS code)

Essential :3.3.1.1 (Build: 2017040305)
Moodle : 3.3.1+ (Build: 20170824)

**Comment by gjb2048** [comment]
oldnavbar: 0

**Comment by gjb2048** [comment]
Diff here: https://moodle.org/mod/forum/discuss.php?d=357647#p1442594 is font name - so that has an effect on the wrapping as all the other values are fixed.

**Comment by gjb2048** [comment]
Backport possibly.

**Comment by gjb2048** [comment]
Can replicate on M3.2....
