### ISSUE TITLE
While adding images with floating submit buttons

### ISSUE THREAD

**Issue by martinvivek** [gjb2048/moodle-theme_essential#844]
![image](https://user-images.githubusercontent.com/7712010/29738272-6d297206-8a3c-11e7-9b55-af8f65f09bdb.png)

current behaviour:
While adding questions, Click the image from the text editor and add the image to the question, the image popup have save button which is hiding behind the floating submit button. so by oversight we clicking the question save button

Expected behaviour:
The image popup save image button to be appear above the floating buttons.

Fresh Moodle installation with only essential theme Plugin. (no Custom CSS code)

Essential :3.3.1.1 (Build: 2017040305)
Moodle : 3.3.1+ (Build: 20170824)

**Comment by gjb2048** [comment]
Submit button z-index changed from 1 to 101 in #550.

**Comment by gjb2048** [comment]
You can move the dialog around!  Solving this by making the floating area smaller rather than messing with the z-index as the YUI dialog's z-index is calculated somehow.
