### ISSUE TITLE
categoryincoursebreadcrumbfeature doesn't work if navshowcategories is disabled

### ISSUE THREAD

**Issue by tonyjbutler** [gjb2048/moodle-theme_essential#845]
I'm guessing the category data just isn't available with navshowcategories disabled, but is there any way around this?

**Comment by tonyjbutler** [comment]
This is in Moodle 3.3.1 with Essential 3.3.1.0 (Build: 2017040304) by the way.

navshowcategories is a core config setting in /admin/settings.php?section=navigation

**Comment by gjb2048** [comment]
Any way around this = no bar Moodle tracker to change get_items() in /lib/navigationlib.php to accept a parameter that overrides $CFG->navshowcategories.  Or this global is changed by the theme when the setting 'categoryincoursebreadcrumbfeature' is used, but that then breaks the intent of 'navshowcategories'.
