### ISSUE TITLE
Use or deprecated API pix_url.

### ISSUE THREAD

**Issue by juacas** [gjb2048/moodle-theme_essential#847]
The theme uses a deprecated API for images and icons.
The warnings break the interface if debug is enabled.

`pix_url is deprecated. Use image_url for images and pix_icon for icons.
line 1696 of \lib\outputlib.php: call to debugging()
line 64 of \theme\essential\classes\output\core_renderer_toolbox.php: call to theme_config->pix_url()
line 971 of \theme\essential\classes\output\core_renderer.php: call to theme_essential\output\core_renderer->pix_url()
line 68 of \theme\essential\layout\tiles\navbar.php: call to theme_essential\output\core_renderer->custom_menu_activitystream()
line 58 of \theme\essential\layout\tiles\header.php: call to require_once()
line 30 of \theme\essential\layout\columns3.php: call to require_once()
line 1162 of \lib\outputrenderers.php: call to include()
line 1092 of \lib\outputrenderers.php: call to core_renderer->render_page_layout()
line 244 of \course\view.php: call to core_renderer->header()`

**Comment by gjb2048** [comment]
You must be using the wrong version on Moodle 3.3 -> https://github.com/gjb2048/moodle-theme_essential/blob/master/classes/output/core_renderer_toolbox.php#L64
