### ISSUE TITLE
The course administrator menu is missing

### ISSUE THREAD

**Issue by mileginy** [gjb2048/moodle-theme_essential#848]
I'm using Moodle 3.3.2. The course administrator menu is missing, hence i can't edit the course. Kindly please check.

**Comment by gjb2048** [comment]
Have you looked at the 'cog' on the navigation bar at the top?

**Comment by mileginy** [comment]
Hi, sorry for late reply. Ya, i manage to find the course administrator menu on the navigation bar at top. Thank you. 

Another question, how to dock the course menu to side? it seem no option now. 
![image](https://user-images.githubusercontent.com/25074507/34811162-803a0698-f6da-11e7-9042-6a77e68bb1af.png)

**Comment by gjb2048** [comment]
That's flat navigation and you can't dock it.  But you can turn it off with the 'flatnavigation' setting in the 'General' section of the theme settings.
