### ISSUE TITLE
Flip main content and blocks, RTL mode.

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#850]
Switching from LTR to RTL, should mirror the content area and the blocks areas (columns) in RTL mode, on all theme modes (Legacy blocks and the new "Nav drawer")

For theme settings: flatnavigation = off & layout = off
This is how it should be:
![image](https://user-images.githubusercontent.com/231168/32387848-60281738-c0ce-11e7-8bae-b6f928c94098.png)

For theme settings: flatnavigation = off & layout = on
This is how it should be:
![image](https://user-images.githubusercontent.com/231168/32388020-009cc0a6-c0cf-11e7-892b-36a5f44ca258.png)

For theme settings: flatnavigation = on & layout = on
This is how it should be:
![image](https://user-images.githubusercontent.com/231168/32388154-740a71b4-c0cf-11e7-8e2f-3be9c79661a2.png)

**Comment by nadavkav** [comment]
Suggested all-rtl CSS outcome fix for rtl mode:
.row-fluid [class*="span"] {
    float: left;
}
[class*="span"].pull-right, .row-fluid [class*="span"].pull-right {
    float: right;
}
But since Moodle 3.3 is auto flipping LTR css selectors, it should obviously be the exact opposite in the actual code.

**Comment by gjb2048** [comment]
So Nadav, is it the same core issue as https://tracker.moodle.org/browse/MDL-60250 where the auto-flip technology is changing the nature of a selector attribute when it should not?

**Comment by gjb2048** [comment]
Therefore a 'core' issue as 'pull-right' no longer means what it says.  As regardless of LTR or RTL, right is right and left is left, unless you're looking in a mirror!

**Comment by nadavkav** [comment]
Yep. unless there is a special /*rtl: ... */ comments in the CSS/SCSS code (https://docs.moodle.org/dev/CSS_Coding_Style#Right-to-left)

**Comment by gjb2048** [comment]
Therefore as a Bootstrap class in Bootstrapbase then core needs to change.

**Comment by gjb2048** [comment]
And I know about https://docs.moodle.org/dev/CSS_Coding_Style#Right-to-left as otherwise how could I have submitted the patch for MDL-60250? ;)

**Comment by gjb2048** [comment]
Hi Nadav,

As MDL-60250 is closed, is this still an issue?

G

**Comment by nadavkav** [comment]
Hi Gareth,
Unfortunately, it did not. as it was only related to popover.
Nadav

**Comment by nadavkav** [comment]
BTW, looking forward seeing you on the 2018 UK MoodleMOOT at Glasgow

**Comment by gjb2048** [comment]
Thinking this is an M3.3+ only issue.
