### ISSUE TITLE
Choice view: unreadable or hidden names when multiple columns

### ISSUE THREAD

**Issue by carreraj** [gjb2048/moodle-theme_essential#851]
Hi, I've noticed that when you have enough number of columns in a choice activity, students' names are displayed almost unreadable (or missing). 
 I have added this css to the extra css field in general options and now it has a better readability. 
.media-body {
    display: table-cell;
}
I attach two screenshots with examples. 

Cheers,
Juan Carrera

![choice_view_1](https://user-images.githubusercontent.com/1698605/32656544-88c442b8-c612-11e7-92b5-8d68f50cf9b1.png)
![choice_view_2](https://user-images.githubusercontent.com/1698605/32656546-8b74e2b0-c612-11e7-9b78-9a754fb3fc1b.png)

**Comment by gjb2048** [comment]
What version please?

**Comment by gjb2048** [comment]
What version of Moodle please?

**Comment by carreraj** [comment]
Sorry for that.
Essential 3.3.1.2 (Build: 2017040306)
Moodle 3.3.2+ (Build: 20171103)

**Comment by gjb2048** [comment]
Cannot replicate.
