### ISSUE TITLE
Site logo needs textual description for accessibility

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_essential#853]
Ref: https://github.com/gjb2048/moodle-theme_essential/pull/852

**Comment by gjb2048** [comment]
Solve with setting where the user can enter text.

**Comment by carreraj** [comment]
Hi Gareth, I realized of missing attribute because of http://wave.webaim.org/ report.
I agree with you that shortname is not descriptive. Probably "Site logo" fixed string is enough, and a specific setting is complete and definitive solution.
Thank you very much for your awesome work.

Juan

**Comment by gjb2048** [comment]
Ok started to do this, then read "The text should explain where the link goes if the image is inside an <a> element" on https://www.w3schools.com/tags/att_img_alt.asp - therefore!  The link already has the description.

**Comment by gjb2048** [comment]
Therefore just need:

````
alt="'.get_string('home').'"
````
instead of a setting!

**Comment by gjb2048** [comment]
Please advise.

**Comment by carreraj** [comment]
Thank you, Gareth.
