### ISSUE TITLE
administration block

### ISSUE THREAD

**Issue by abdallah84** [gjb2048/moodle-theme_essential#854]
When i click on Site administration on administration block it didn't expanded to show sub items,
this issue on all browsers.
theme ver 3.1.1.12
moodle ver 3.15

Thanks in advance.

**Comment by gjb2048** [comment]
Local issue with broken JavaScript.  Not a theme issue.

**Comment by abdallah84** [comment]
sorry,
now i check it is not from theme :)
do you face this issue before ?
