### ISSUE TITLE
Display glitch with docked blocks

### ISSUE THREAD

**Issue by gpillsbury** [gjb2048/moodle-theme_essential#857]
M3.3, latest version of Essential
When a block is docked, folder items in the block are indented in the list of links.  This is visually confusing, as it makes these root-level items appear as second-level items.
Here is what the Administration block looks like when docked:
<img width="473" alt="screen shot 2018-02-02 at 11 01 47 am" src="https://user-images.githubusercontent.com/1123665/35750050-836cfd04-0808-11e8-8173-2127b68270cf.png">

As you can see, the "Users", "Reports", "Badges", and "Question bank" items should all be left-aligned with the rest of the links.

Thanks!

**Comment by gjb2048** [comment]
Latest?  What exact version are you running please, i.e. the one on your computer!  Which might be different from the latest on Moodle.org.

**Comment by gpillsbury** [comment]
We have 3.3.1.2 installed.



On Wed, Feb 28, 2018 at 3:21 PM -0800, "Gareth J Barnard" <notifications@github.com<mailto:notifications@github.com>> wrote:


Latest? What exact version are you running please, i.e. the one on your computer! Which might be different from the latest on Moodle.org.
