### ISSUE TITLE
Class thumbnails broken

### ISSUE THREAD

**Issue by WINGsRealityEDU** [gjb2048/moodle-theme_essential#858]
Week old upgrade to Moodle 3.4.1 (Build: 20180115) PHP 7.0.0 and Essential 3.4.0.1 (Build: 2017102900). 

Now any use of the Class=”thumbnails” and the hole container falls apart. Here are some images one of Essential > Style guide
![essential class issue 1](https://user-images.githubusercontent.com/36108287/35768973-f560f4a0-08d1-11e8-9341-f48ff11877fe.jpg)
The other is in our sites library
![essential class issue 2](https://user-images.githubusercontent.com/36108287/35768975-faae42aa-08d1-11e8-9bfc-5efa9b2b7aa7.jpg)

**Comment by gjb2048** [comment]
Fine in M3.2.

**Comment by gjb2048** [comment]
Is broken, don't know why, leaving for a while.

**Comment by gjb2048** [comment]
Not an issue in Shoelace.

**Comment by WINGsRealityEDU** [comment]
How can I help you determine what is going on?  This is affecting 16 of our courses and some in use right now.   Moodle debugging shows no errors.

**Comment by gjb2048** [comment]
Ok, could you provide a course MBZ backup (without user data) that demonstrates the issue please?  Then I may have a chance of replicating locally and possibly finding a solution.  If the problem is a theme one then I'll try and fix it, if it is you then I'll say it is but not explain why.

**Comment by gjb2048** [comment]
What web browser are you using please?

**Comment by gjb2048** [comment]
Ok, cannot replicate what you have as.... the style guide issue is https://github.com/gjb2048/moodle-theme_essential/commit/f62e34a9af13d29410572100ca444a40bf1a6db8 which has fixes that pertain only to the style guide:

![screenshot-2018-2-16 moo34 administration appearance themes essential style guide](https://user-images.githubusercontent.com/1058419/36318612-42743bec-1338-11e8-8282-6ac0d5982595.png)

**Comment by gjb2048** [comment]
Therefore either a local issue with conflicting styles that is out of my control or is the theme that the course backup would demonstrate.  Or provide me with the markup you are using to create thumbnails on a course.

**Comment by WINGsRealityEDU** [comment]
I just finished a test on a new test server with Moodle 3.4.1+ (Build: 20180118) Version 2017111301.01 PHP 7.0 and there is no issue. 
![thumbtest1](https://user-images.githubusercontent.com/36108287/36320187-561c24ae-1313-11e8-8bea-d55b68cf83e8.jpg)

On our production server that just had the Moodle 3.4.1 (Build: 20180115) PHP 7.0.0 and Essential 3.4.0.1 (Build: 2017102900) upgrade this is the LMS with the issue. 
![thumbtest2](https://user-images.githubusercontent.com/36108287/36320194-5ba412b0-1313-11e8-97d9-20471abc6261.jpg)

I also have additional themes and the issue continues with them.  I am happy to give you a copy of a course MBZ backup is to large to attached here. I can send on chapter of a book that has the issue, 
[backup-moodle2-activity-538-book538-20180216-1212-nu.zip](https://github.com/gjb2048/moodle-theme_essential/files/1732151/backup-moodle2-activity-538-book538-20180216-1212-nu.zip)
see attachment.  It now seems like this it is conflicting style from here.  I will keep looking and thank you for you time. Regards,

**Comment by gjb2048** [comment]
Getting The selected file is not a valid Moodle backup file and can't be restored.

**Comment by gjb2048** [comment]
Ok, fine now.  Why did you put an mbz which is a zip file inside a zip file?

**Comment by gjb2048** [comment]
Not broken (please ignore navbar down the page - FireFox screen capture issue):

![screenshot-2018-2-16 module 1 - introduction to flight training purpose of flight training](https://user-images.githubusercontent.com/1058419/36322539-83b6deb8-1345-11e8-9347-251443a51907.png)

**Comment by WINGsRealityEDU** [comment]
Been out and just got back in. Yha I get the same result on my test server but still broken on my production server. I am going to uninstall the Adaptable theme 1.6.0.2 (2018011502) tonight after the usage quiets down. This was the other theme that got updated at the same time as the other upgrades. The one thing I do know is all this started after the upgrades.

I think it must be what you stated "Therefore either a local issue with conflicting styles that is out of my control or is the theme that the course backup would demonstrate." I will get back after I have done the theme uninstall.

Regards,

**Comment by WINGsRealityEDU** [comment]
Just wanted to report in on what I have found.  I removed the Adaptable theme and nothing change so I placed it back in and added the Enlight lite theme to see if a new theme is effected and the issue is on all themes.  The issue I am having may be higher up then the theme level.

**Comment by 3-bits** [comment]
.thumbnail class is part of the bootstrap styles core. Adaptable do not include or overwrite this class in any way. 
So the problem is located in bootstrapbase.css file.

**Comment by gjb2048** [comment]
Ok, not in bootstrapbase.css file (which actually does not exist) as.... I cannot replicate the issue and changing theme does not affect the issue locally.  Therefore the problem is with a custom plugin (not theme) or user entered CSS / bad markup.

**Comment by WINGsRealityEDU** [comment]
Just to give you and others an update on the cause of the broken thumbnail and thumbnails class.
I just replicated it and the cause was the BigBlueButton RecordingsBN v 1.3.2 (2016051906) plugin. Before I upgraded on my test server the two classes were functional and as soon as I upgraded both classes no longer worked. I will contact Blindside Networks so they may have a look. 

Regards,

**Comment by WINGsRealityEDU** [comment]
Update, issue resolved. 
Essential support thank you for all your help and thank you Blindside Networks support.

Regards,

**Comment by WINGsRealityEDU** [comment]
No the Essential theme is working perfect. It was a Big Blue Button plugin, thumbnail class that was overriding the Essential thumbnail class.  I have a temp fix until they release there next version sometime in the next week or so.  The help you gave, helped lead me down the road to find the issue.  Both your support and the Blindside Networks customer support are outstanding to work with.

 

Thank you,

 

Robert
