### ISSUE TITLE
Missing folder icon in courses list since commit 77abc460

### ISSUE THREAD

**Issue by Balecan** [gjb2048/moodle-theme_essential#862]
Hi,
Seems there is a problem with commit 77abc460. Some folder icons disapears 
git checkout 5b10cb02 (and purge cache) =>
![with-folder](https://user-images.githubusercontent.com/11347832/36312421-bad9f842-132e-11e8-8cec-89e796bfcbd2.png)
git checkout 77abc460 (and purge cache) =>
![without-icon--folder](https://user-images.githubusercontent.com/11347832/36312429-c304a666-132e-11e8-8866-8e0901d7a50f.png)

Best regards

**Comment by gjb2048** [comment]
I don't understand what https://github.com/gjb2048/moodle-theme_essential/commit/5b10cb0279ddffeb6facc446f6a5ee35a85ffb28 has to do with this.
