### ISSUE TITLE
Site Administration Block is missing in moodle 3.4 

### ISSUE THREAD

**Issue by chiioo** [gjb2048/moodle-theme_essential#863]
![24568492](https://user-images.githubusercontent.com/37575201/37644484-906bb65e-2c56-11e8-87c9-d05fa9b446f6.PNG)

**Comment by chiioo** [comment]
please help me.. im using essential theme in my moodle but its missing the admin block

**Comment by whymiss** [comment]
If you want to turn off the collapsed menu go to Siteadmin>Appearance>Themes>Essential>General. untick Enable flat navigation

**Comment by chiioo** [comment]
thank you so much.. its work, i got my block admin back
