### ISSUE TITLE
Text-shadow in explorer

### ISSUE THREAD

**Issue by rimacher** [gjb2048/moodle-theme_essential#866]
In moodle 3.4 rtl -when viewing items in a course the page won't scroll all the way to the top.
removing text-shadow:none from body seems to help?

**Comment by gjb2048** [comment]
Explorer?
text-shadow:none might be a solution, but please could you screen shot the problem with steps to replicate.

**Comment by rimacher** [comment]
![08-05-2018 08-46-29](https://user-images.githubusercontent.com/16016842/39739984-4971f558-529c-11e8-90b5-50d52a7770bb.png)

**Comment by gjb2048** [comment]
Ok, thanks, and the steps to reproduce please?  And...

- What web browser and version are you using?
- What specific version of Moodle are you using?
- What specific version of Essential are you using?

**Comment by gjb2048** [comment]
And what is 'Explorer' please?

**Comment by rimacher** [comment]
using rtl> any course> any activity. For example: forum, assignment, quiz.

Internet Explorer 11
moodle 3.4.2
Essential 3.4.1.2

**Comment by gjb2048** [comment]
Cannot replicate in M3.5 version.  Code is the same.
