### ISSUE TITLE
Front page "blocks per row" settings ignored

### ISSUE THREAD

**Issue by tim1mw** [gjb2048/moodle-theme_essential#871]
Using Moodle 3.5 and Essential V3.5.0.1

The "Home (was 'Middle') blocks per row" (frontpagehomeblocksperrow) and "Page top blocks per row" (fppagetopblocksperrow) front page settings don't seem to have any effect. Regardless of the value set I always get 2 blocks per row in the associated block locations. This doesn't seem to be related to screen size, I can expand my browser window to over 2000px wide and still only get 2 blocks per row. I'm testing using  HTML blocks with only a few words in each and a short title.

**Comment by gjb2048** [comment]
Is editing on?

**Comment by gjb2048** [comment]
Please supply requested information or I'll close the issue.

**Comment by tim1mw** [comment]
Sorry, I've had a lot of other tasks the past week, this slipped through the net. Yes, we discovered that the blocks only display correctly once editing is off. Which is really confusing (two of us failed to spot this), but less of a problem since most people will see the page as expected.
