### ISSUE TITLE
L/H Menu

### ISSUE THREAD

**Issue by johnpap21** [gjb2048/moodle-theme_essential#877]
Hello, since upgrading the theme and Moodle, the L/H page is populated by the Home/Dashboard menu and site Admin blocks appear all the time no matter the role, is there a way we can turn these off, or has this been an oversight with 3.5.2 and the latest version of the theme?

TIA
John

**Comment by gjb2048** [comment]
Ok....

What version of Moodle / Theme did you upgrade from?
Could you post a screen shot so I know exactly what you're talking about?

please.

**Comment by gjb2048** [comment]
And what version is 'latest'?  Your latest could not be my latest or the latest on moodle.org or could be the latest that is for another version of Moodle even though you think it is the latest, but in fact it is not the latest.  And could be the latest at the time you wrote your words but not the latest at the time they are read.

**Comment by gjb2048** [comment]
Turn off 'flatnavigation'.

**Comment by gjb2048** [comment]
Did turning off 'flatnavigation' work?

**Comment by johnpap21** [comment]
Yes thanks it dis




Get Outlook for Android







On Mon, Oct 15, 2018 at 10:57 AM +0100, "Gareth J Barnard" <notifications@github.com> wrote:












Did turning off 'flatnavigation' work?
