### ISSUE TITLE
Remove the left menu in Essential Theme

### ISSUE THREAD

**Issue by sfauset** [gjb2048/moodle-theme_essential#878]
Hi there,

I'm using the latest Essential theme and I want to remove the left menu.

I find it is block everything.

How do I do that?

Thanks

Sarah

**Comment by gjb2048** [comment]
Dear Sarah,

Please see: https://github.com/gjb2048/moodle-theme_essential/blob/master/README.md#support about support for the theme.

Good luck,

Gareth

**Comment by sfauset** [comment]
I'm very disappointed about the updates in this theme. I'm using that latest essential theme and it isn't half as good as the essential theme 3.0....that one was perfect...

**Comment by gjb2048** [comment]
Latest?

Since 3.0 all I've done is to remove the slider which had an iffy license, then make improvements on top of the existing functionality.  Essential is only a theme and you might be actually thinking of the underlying Moodle functionality that has changed for the better.

**Comment by sfauset** [comment]
The message nav bar is missing in the latest essential theme which makes it very confusing when you are trying to message someone.

**Comment by sfauset** [comment]
I don't really like the separate assignment notifications either...I liked to keep a track of where students were in the course by looking in the messages.

**Comment by gjb2048** [comment]
The messages nav bar is there:

![screenshot_2018-11-02 moo35](https://user-images.githubusercontent.com/1058419/47912361-463f2380-de90-11e8-8ed4-2ec39e3b6984.png)

And the separation of the messages and notifications is a core thing outside of the control of the theme.  All themes have this.

**Comment by sfauset** [comment]
Yes you are right...it turns out the separation of the notifications and messages is part of the system. I'm not sure why they had to do that as it worked perfectly before.

**Comment by sfauset** [comment]
This is the nav message menu that is missing...
![nav bar2](https://user-images.githubusercontent.com/34783579/47988483-52093080-e0b0-11e8-9817-46304269588f.jpg)

**Comment by gjb2048** [comment]
It's still there as buttons at the bottom:

![screenshot_2018-11-05 moo35 messages_essential](https://user-images.githubusercontent.com/1058419/47992049-ca3d1980-e0e3-11e8-8677-399134c2a3d4.png)

which is still the same as the Boost theme:

![screenshot_2018-11-05 moo35 messages_boost](https://user-images.githubusercontent.com/1058419/47992072-d45f1800-e0e3-11e8-9ff9-4b4b3ee25758.png)

and then indeed as others as this is core functionality.

**Comment by sfauset** [comment]
Also there were too many menus/boxes everywhere that I had to get removed...so I could actually see the course because it was making everything too small.

**Comment by gjb2048** [comment]
Ok... two things here, with the 'contacts' then that is a 'core change' so nothing much the theme can do about it bar attempt to put the old functionality back, but then as the underlying API has changed then that might not be possible.

What do you mean by 'Also there were too many menus/boxes everywhere that I had to get removed...so I could actually see the course because it was making everything too small.'?

Ok... so far with all the complaints I've not seen one thing that is specific to the Essential theme as 'everything' is to do so far with the underlying changes to Moodle core functionality between the versions.  Do you actually something that is Essential theme specific?

**Comment by sfauset** [comment]
You are probably right...I just changed from moodle 3.0 to moodle 3.5.2 and I think there are a lot of core changes. The theme issues that I'm talking about are....For example, the "left menu" was in the way...and it was making the course too small to see.

**Comment by gjb2048** [comment]
So an example is the "left menu", are there other things too?

Which 'left menu' as there are lots of things on the left.

**Comment by sfauset** [comment]
The "left menu" was at the top right corner of the page.

I didn't like the big word "restricted" when you have the restricted setting on...it is very distracting...had to get that removed.

**Comment by gjb2048** [comment]
Restricted???? I've no idea what you're talking about.

What "left menu" at the top right of the page?
