### ISSUE TITLE
Theme Removes Navigation Block from Wiki

### ISSUE THREAD

**Issue by Symbolicdeathwish** [gjb2048/moodle-theme_essential#885]
The theme unfortunately removes the navigation block form the Wiki.

This is a problem because in order to create new content, the navigation block is used. 

I have tried to jump into another theme to move this block around, to a different location, but no matter where i move this block, it remains hidden.

**Comment by gjb2048** [comment]
Screenshot please along with theme and Moodle version details.

**Comment by Symbolicdeathwish** [comment]
Moodle 3.5 

Screenshot below: (however, above is your theme, below that is another theme that shows the navigation block. 

![image](https://user-images.githubusercontent.com/30120017/49085914-78eff800-f253-11e8-9be5-f09d2beadf34.png)

Another Theme:
![image](https://user-images.githubusercontent.com/30120017/49086018-c0768400-f253-11e8-8427-183658b3d2e2.png)

**Comment by gjb2048** [comment]
Thanks Gemma :)

**Comment by gjb2048** [comment]
Functionality with both Essential and Boost is the same, including the missing FontAwesome icons.

**Comment by Symbolicdeathwish** [comment]
@gemguardian thank you for your reply, however i can't see the options there at all. Am i missing something really obvious? 

![image](https://user-images.githubusercontent.com/30120017/49142958-3a614880-f2fa-11e8-88e4-90ed1795d7fd.png)

**Comment by gjb2048** [comment]
Ok, it looks like with a comparison between the Clean and Boost themes that the Wiki options shown on the navigation block in Clean are missing for Boost in the flat navigation, therefore please raise a Moodle tracker for this.  Otherwise, in Essential, turn off the 'flatnavigation' setting.

**Comment by gjb2048** [comment]
FYI: https://moodle.org/mod/forum/discuss.php?d=379172

**Comment by gjb2048** [comment]
Ok, see 'Note' on https://docs.moodle.org/35/en/Using_Wiki#Navigating_page_to_page and https://tracker.moodle.org/browse/MDL-58965.
