### ISSUE TITLE
Extra whitespace added in navigation block when using AJAX

### ISSUE THREAD

**Issue by agrowe** [gjb2048/moodle-theme_essential#888]
When opening the site administration menu from the site home page where it is defaulted to closed, there is an extra bit of white space added beside the FontAwesome icons when they are rendered. This is when the admin branch is rendered with AJAX using getsiteadminbranch.php.

![capture](https://user-images.githubusercontent.com/1534918/50058918-a507f480-01d3-11e9-9c26-354804eb9b83.PNG)

When opening it from another page, such as settings, where it is already loaded, there are no pieces of extra white space added.

In the markup, it looks like there has been a new line/carriage return added, but I can't find where in the theme this rendering is taking place.

![capture1](https://user-images.githubusercontent.com/1534918/50058964-8eae6880-01d4-11e9-9de3-c9e7b1710c0a.PNG)

This is when flat navigation is turned off, and it does not occur in Clean as that theme is using IMG tags rather than FontAweome.

Moodle Version 3.5.3 (20181112)
Essential Version 3.5.1.2 (2018051903)

**Comment by gjb2048** [comment]
M3.3 version no longer being developed, closing.
