### ISSUE TITLE
Sidebar margin-left missing on iPad

### ISSUE THREAD

**Issue by daemonhunt** [gjb2048/moodle-theme_essential#890]
This issue relates somehow to this old post, but isn't exactly the same issue: https://moodle.org/mod/forum/discuss.php?d=341233

In a nutshell just issues with this side bar again on the iPad with the latest Essential version 2017102907, Moodle 3.4.x

Issue shown in this image (note margin-left missing from right-hand side menu on the iPad): https://nimb.ws/7mv6qY

**Comment by gjb2048** [comment]
Hi Daemon,

I see there is a non-theme 'Contact us' tab on the right hand side.  Therefore more than likely causing the issue.  So as this is a customised environment there are two choices:

1. Pay me for my time to help.
2. Buy me an iPad to replicate on.

Kind regards,

Gareth

**Comment by daemonhunt** [comment]
It is not that at all Gareth. It's a bug. I'm not that stupid. I have insepcted the code and nothing of mine is getting in the way, it's an issue somewhere in your code. Your customer service is getting worse and worse. I hate reaching out to you, and get anxious every time I do. Like the grumpy old troll under the bridge.
I work for an educational institute, we can't just give you money, unless you provide me a proper purchase order and an invoice? You will have to sign one of our 'new supplier' forms, and then I can send you something.
Why don't you just sell the blimmin' theme and stop extorting people for money? Or hand the development over to someone else who knows how to monetise the theme professionally? Then everyone would be happy.
I'll fix your bug myself.

**Comment by gjb2048** [comment]
Dear Daemon,

Ok.  Umm lost for words.  That is so unprofessional, insulting and abusive.  I have been nothing but polite to you.  I have never insulted you or called you stupid.  All I ask is for concrete evidence before I spend hours of my time on a wild goose chase or spend time fixing something specific to a given site which does not benefit all.

I do not 'extort people for money'.  I have put a substantial amount of time and effort into the theme and have fixed bugs and added some new functionality for no reward.  The theme is GPLv3 and is provided 'as is', if you want to copy the theme and give it a different name, then feel free to do so.

If you genuinely believe that it is an Essential issue, then please demonstrate this and even if you're not sure of a solution I will look at it.  But for the moment with one screen shot and a non-theme 'Contact us' tab then all the evidence points to faulty customisations at your end.

G

**Comment by gjb2048** [comment]
Ok, double checked and it is an issue with the theme.  I did not really feel like even publicising this fact but did not want to give you any reason to be even more abusive or insulting to me when you find the bug.  But to be moral and professional when it comes to admitting my mistakes and correcting them.

**Comment by daemonhunt** [comment]
I apologise for being insulting. It feels like 'extortion' when I can clearly see that it is a bug. I see a lot of questions come through to you from old threads I am subscribed to and I read your answers. "Polite" is not a word I associate with you. Perhaps "abrupt" is more befitting. I get that you are a rational, logical person, but customer service is not your strong suit. I might not know your theme as well as you do, but I know a bug when I see one. I have been using your theme for several years, and I have made many, many CSS tweaks to it, always respecting the core code, and always willing to admit if it is my customisation that is breaking it.

If you like, I'm willing to create a website with a basic pay wall for your theme so you can sell it. I would do this without expecting payment or thanks. This way, everyone wins. People love your theme. Only issue is that questions for assistance will go from a defensible position to one where you are obligated because you are suddenly selling the theme, and this may in fact be worse than the current situation where you have a rationale not to help. There are only so many hours in the day! Many of us in formal educational institutions can't just "pop you a few dollars" for your help, we have strict, annoyingly cumbersome financial policies we have to abide by... or I would!

I turned off the 'contact us' tab for this screenshot. That was a red herring, just some additonal JS in my HTML, completely unrelated.

![annotation 2019-03-01 093647](https://user-images.githubusercontent.com/4277521/53597464-1a963500-3c07-11e9-8478-52c1a824f307.jpg)

**Comment by daemonhunt** [comment]
Makes me reflect that I should be more proactive, learn your theme inside and out, and help you instead of being insulting. This would probably be far more productive than the current situation. Mary is amazing support. I haven't seen her around for some time, but then, I don't report issues often. Thanks for your time Gareth.

**Comment by gjb2048** [comment]
Ok.  Thank you for the offer of a site for selling the theme, but I politely refuse.  The theme is free, my time is not.  As it would be commercial suicide to force people to pay for a theme that once was free.

**Comment by gjb2048** [comment]
Now fixed in M3.6 version at least from a release perspective.  Closing.
