### ISSUE TITLE
Moodle upgrade 3.6.2 only pulling Essential 3.4.1.5 edit.. Not pulling update I should say

### ISSUE THREAD

**Issue by dschwa** [gjb2048/moodle-theme_essential#891]
Just upgraded a site to Moodle 3.6.2
Upgraded all plugins via UI, plugins overview
Does not show upgrade needed, see attached
Site notifications does throw a theme incompatible error

Version mismatch?

I cannot overwrite the theme via install from plugins repo and I’m fine installing by ftp but thought you’d like to see this issue

![c7350b33-b2fc-4fb1-81b2-52c695094c7e](https://user-images.githubusercontent.com/7027431/53598230-297ed800-3b72-11e9-9027-f2d8cdf555cb.jpeg)

**Comment by gjb2048** [comment]
Dear Don,

Nope as there are changes to make the theme cope.  Please backup your site, then read: https://github.com/gjb2048/moodle-theme_essential/blob/master/README.md#upgrading.

Gareth

**Comment by gjb2048** [comment]
P.S. Not sure why plugin's db not showing the need to update, core issue or I've done something wrong on the database entry.
