### ISSUE TITLE
Notification alert-marking missing

### ISSUE THREAD

**Issue by simpasam** [gjb2048/moodle-theme_essential#893]
We have Moodle 3.5 and we don't get alet when have new notifications. "New messages"-alert is working fine.
![moodle_notify](https://user-images.githubusercontent.com/49266260/55534863-23729e80-56be-11e9-9a2a-247c9b2f5235.png)

**Comment by gjb2048** [comment]
There are alerts showing, so from a theme perspective that is what should be happening.  So what do you exactly mean by not getting alerts when you have new notifications?  You don't get an eMail alert?

**Comment by simpasam** [comment]
eg. When you got message, there is red dot telling that there is 1 unread message.... That is what I want for this also

**Comment by gjb2048** [comment]
I don't understand?  Red dot?  Does this happen with the Clean or Boost themes?

**Comment by simpasam** [comment]
In older Moodle versions it did
![notify](https://user-images.githubusercontent.com/49266260/55542565-f9c27300-56cf-11e9-9c68-22f79b605054.JPG)

**Comment by gjb2048** [comment]
Older versions of Essential or Moodle?  Does it still happen when you change to the Clean or Boost themes?

**Comment by gjb2048** [comment]
Also the screen shot is showing the number of messages as that is the messages icon not the alerts icon.

**Comment by simpasam** [comment]
Actually no, so is it in core changes? list is coming like you have ordered, but no alert. I'll check bug listing in Moodle.org :)
