### ISSUE TITLE
Weird thing on login screen

### ISSUE THREAD

**Issue by ricpelo** [gjb2048/moodle-theme_essential#894]
On login screen, some elements are misplaced:

- The instructions panel is not centered.
- The footer isn't at the bottom of the webpage, and it's partially concealed due to the instructions panel.

You can live test on http://agora.iesdonana.org

![screenshot](https://user-images.githubusercontent.com/616169/56572319-2545c880-65bf-11e9-8b28-cd09ce4b1c1c.png)

**Comment by gjb2048** [comment]
This appears to be the Moove theme and not the Essential theme.  Therefore, not my problem.  Good luck with fixing it.

**Comment by ricpelo** [comment]
Oops, wrong repo! Very sorry and thank you.
