### ISSUE TITLE
Essential not compatible with Moodle 3.7

### ISSUE THREAD

**Issue by oursteve** [gjb2048/moodle-theme_essential#896]
Hi
I upgraded Moodle without checking the Essential version (my bad) and broke it, receiving a 500 error, oops. I have reverted to version 3.6.5 and now all is well. I have posted this just for information when considering an update or anyone else has the same error.

3.7 error:
Code:
Fatal error: Access level to theme_essential\output\core_renderer::build_action_menu_from_navigation() must be protected (as in class core_renderer) or weaker in /home/xxxxxxxx/public_html/theme/essential/classes/output/core_renderer.php on line 49

It seems that in:

/home/xxxxxx/public_html/theme/essential/classes/output/core_renderer.php

function was private but it should have been public, so on line 634 I changed:

private function build_action_menu_from_navigation(action_menu $menu, navigation_node $node, $indent = false,

to

public function build_action_menu_from_navigation(action_menu $menu, navigation_node $node, $indent = false,

and the website is now working, however it displays Essential theme not compatible.
I hope this assists anyone.
Steve

**Comment by gemguardian** [comment]
Hi Steve

You probably misser the forum message Gareth put up. But Essential will not be upgrades too 3.7 due too the theme changes that HQ.





Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: oursteve <notifications@github.com>
Datum: 28-07-19 20:43 (GMT+01:00)
Aan: gjb2048/moodle-theme_essential <moodle-theme_essential@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Onderwerp: [gjb2048/moodle-theme_essential] Essential not compatible with Moodle 3.7 (#896)


Hi
I upgraded Moodle without checking the Essential version (my bad) and broke it, receiving a 500 error, oops. I have reverted to version 3.6.5 and now all is well. I have posted this just for information when considering an update or anyone else has the same error.

Code:
Fatal error: Access level to theme_essential\output\core_renderer::build_action_menu_from_navigation() must be protected (as in class core_renderer) or weaker in /home/xxxxxxxx/public_html/theme/essential/classes/output/core_renderer.php on line 49

It seems that in:

/home/xxxxxx/public_html/theme/essential/classes/output/core_renderer.php

function was private but it should have been public, so on line 634 I changed:

private function build_action_menu_from_navigation(action_menu $menu, navigation_node $node, $indent = false,

to

public function build_action_menu_from_navigation(action_menu $menu, navigation_node $node, $indent = false,

and the website is now working, however it displays Essential theme not compatible.
I hope this assists anyone.
Steve

**Comment by gjb2048** [comment]
Hi Steve,

In addition to what @gemguardian has said, please read: https://moodle.org/mod/forum/discuss.php?d=385903.

Gareth

**Comment by oursteve** [comment]
Thank you Gareth, will do.

 

Regards

 

Steve
