### ISSUE TITLE
Iomad Dashboard icons missing

### ISSUE THREAD

**Issue by bagadeath** [gjb2048/moodle-theme_essential#897]
Hello,

I am sorry if this is the wrong place to post this, but I'm new to all this.

I have been using the Essential theme for Moodle for almost a year now, it's fantastic. My company has recently started to try out Iomad for the multi-tenancy, but when i use the Essential theme with Iomad, the Iomad dashboard icons don't appear! The cursor changes showing the link is still there, just no graphic/icon.

<img width="313" alt="Annotation 2019-08-09 140448" src="https://user-images.githubusercontent.com/53940497/62777903-2be54680-baaf-11e9-9711-9a4e76baea96.png">

I hope this image demostrates my issue. Other than this, the Essential theme is as brilliant as ever, so customisable. I really would like to continue using it, but this is, at the moment, a deal breaker.

I would seriously appreciate any help or guidance, and I apologise in advance if I'm doing something dumb.

Cheers,

Bagadeath

**Comment by gjb2048** [comment]
Hi Bagadeath,

Pragmatically Essential has only really been tested on Moodle itself and I've never tried it on Iomad and for me, Essential is now an old project, please see: https://moodle.org/mod/forum/discuss.php?d=385903.  So supporting it outside of the Moodle versions it's available is not high on my list.

You could use the browser development tools (F12) and see what you find out with them.

Kind regards,

Gareth

**Comment by bagadeath** [comment]
Many thanks for the swift answer!
Shame it's an old project, still great work. I'll have a dig about, see if I can do anything, but I don't hold out much hope.
Thanks again anyway for taking the time, appreciate it!

**Comment by gjb2048** [comment]
Solution: https://github.com/iomad/iomad/issues/1108 - ref: https://moodle.org/mod/forum/discuss.php?d=389991#p1572127.
